version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - python manage.py collectstatic --noinput --settings=sepromcbmepi.settings_aws_production
      - python manage.py migrate --noinput --settings=sepromcbmepi.settings_aws_production
  build:
    commands:
      - echo "Build completed successfully"
artifacts:
  files:
    - '**/*'
  base-directory: '.' 