version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - python manage.py collectstatic --noinput
      - python manage.py migrate --noinput
  build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - '**/*'
  base-directory: '.' 