version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando dependências..."
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Configurando ambiente..."
      - python manage.py collectstatic --noinput
      - python manage.py migrate --noinput
  build:
    commands:
      - echo "Build concluído com sucesso!"
artifacts:
  files:
    - '**/*'
  base-directory: '.' 