services:
  - type: web
    name: sepromcbmepi
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app --config gunicorn.conf.py
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sepromcbmepi.settings_render
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,.onrender.com,sysprom.onrender.com"
    healthCheckPath: /
    autoDeploy: true 