services:
  - type: web
    name: sepromcbmepi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sepromcbmepi.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sepromcbmepi.settings_production
      - key: PYTHON_VERSION
        value: 3.11.0 