"""
Django settings for sepromcbmepi project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-s9$g9l*0=97al&%+arft!#a1x7o&sob2l^5(yny07@2836-*@="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'testserver', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "militares",
    # 'django_ckeditor_5',
    'dal',
    'dal_select2',
    # 'captcha',  # Temporariamente comentado até instalação
]

# Configurações de Login
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/militares/'
LOGOUT_REDIRECT_URL = '/login/'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Adicionar WhiteNoise para servir arquivos estáticos
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "militares.middleware.FuncaoSelecaoMiddleware",
    "militares.middleware.ControleAcessoComissaoMiddleware",
    "militares.middleware.LoggingMiddleware",  # Middleware para registrar logs do sistema
]

ROOT_URLCONF = "sepromcbmepi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "militares.context_processors.sessao_alertas",
                "militares.context_processors.notificacoes_processor",
                "militares.context_processors.chat_processor",
                "militares.context_processors.funcao_atual_processor",
                "militares.context_processors.sessao_ativa_processor",
                "militares.context_processors.funcoes_usuario_processor",
                "militares.context_processors.menu_permissions_processor",
                "militares.permissoes_sistema.permissoes_context",
                "militares.context_processors_alertas.alertas_login_processor",
                "militares.context_processors.revisoes_proximas_processor",
                "militares.context_processors.alertas_frota_processor",
            ],
        },
    },
]

WSGI_APPLICATION = "sepromcbmepi.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "sepromcbmepi",
        "USER": "postgres",
        "PASSWORD": "11322361",
        "HOST": "localhost",
        "PORT": "5432",
        "OPTIONS": {
            "client_encoding": "UTF8",
            "connect_timeout": 10,
        },
        "CONN_MAX_AGE": 0,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Fortaleza"

USE_I18N = True

USE_TZ = True

# Configurações de codificação
DEFAULT_CHARSET = 'utf-8'
FILE_CHARSET = 'utf-8'

# Configurações específicas para caracteres especiais
import locale
import sys

# Garantir que o Python use UTF-8 (configuração compatível com Windows)
try:
    if sys.platform.startswith('win'):
        # Windows - usar configuração padrão ou específica do Windows
        try:
            locale.setlocale(locale.LC_ALL, 'Portuguese_Brazil.1252')
        except locale.Error:
            try:
                locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
            except locale.Error:
                # Fallback para configuração padrão
                pass
    else:
        # Unix/Linux
        if sys.version_info >= (3, 7):
            locale.setlocale(locale.LC_ALL, 'C.UTF-8')
        else:
            try:
                locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
            except locale.Error:
                locale.setlocale(locale.LC_ALL, 'C.UTF-8')
except locale.Error:
    # Se tudo falhar, usar configuração padrão
    pass

# Garantir que todos os outputs sejam UTF-8
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações de idioma
LANGUAGES = [
    ('pt-br', 'Português (Brasil)'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Configurações de formato de data
DATE_FORMAT = 'd/m/Y'
DATE_INPUT_FORMATS = ['%Y-%m-%d', '%d/%m/%Y', '%d-%m-%Y']
DATETIME_FORMAT = 'd/m/Y H:i'
DATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S', '%d/%m/%Y %H:%M', '%d-%m-%Y %H:%M']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuração do CKEditor 5
customColorPalette = [
    {"color": "hsl(4, 90%, 58%)", "label": "Red"},
    {"color": "hsl(340, 82%, 52%)", "label": "Pink"},
    {"color": "hsl(291, 64%, 42%)", "label": "Purple"},
    {"color": "hsl(262, 52%, 47%)", "label": "Deep Purple"},
    {"color": "hsl(231, 48%, 48%)", "label": "Indigo"},
    {"color": "hsl(207, 90%, 54%)", "label": "Blue"},
]

# Configurações do CKEditor 5
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
            'alignment', '|',
            'numberedList', 'bulletedList', '|',
            'indent', 'outdent', '|',
            'link', 'blockQuote', 'insertTable', 'mediaEmbed', '|',
            'undo', 'redo', '|',
            'sourceEditing'
        ],
        'height': 300,
        'language': 'pt-br',
    },
    'ata_config': {
        'heading': {
            'options': [
                {'class': 'ck-heading_paragraph', 'model': 'paragraph', 'title': 'Parágrafo'},
                {'class': 'ck-heading_heading1', 'model': 'heading1', 'title': 'Título 1', 'view': 'h1'},
                {'class': 'ck-heading_heading2', 'model': 'heading2', 'title': 'Título 2', 'view': 'h2'},
                {'class': 'ck-heading_heading3', 'model': 'heading3', 'title': 'Título 3', 'view': 'h3'},
                {'class': 'ck-heading_heading4', 'model': 'heading4', 'title': 'Título 4', 'view': 'h4'}
            ]
        },
        'height': 800,
        'language': 'pt-br',
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
            'alignment', '|',
            'numberedList', 'bulletedList', '|',
            'indent', 'outdent', '|',
            'link', 'blockQuote', 'insertTable', 'mediaEmbed', '|',
            'undo', 'redo', '|',
            'sourceEditing', '|',
            'removeFormat', 'subscript', 'superscript', 'highlight'
        ],
        'fontSize': {
            'options': [
                8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72
            ]
        },
        'fontFamily': {
            'options': [
                'default',
                'Arial, Helvetica, sans-serif',
                'Courier New, Courier, monospace',
                'Georgia, serif',
                'Lucida Sans Unicode, Lucida Grande, sans-serif',
                'Tahoma, Geneva, sans-serif',
                'Times New Roman, Times, serif',
                'Trebuchet MS, Helvetica, sans-serif',
                'Verdana, Geneva, sans-serif'
            ]
        },
        'alignment': {
            'options': ['left', 'center', 'right', 'justify']
        },
        'highlight': {
            'options': [
                { 'model': 'yellowMarker', 'class': 'marker-yellow', 'title': 'Marcador Amarelo' },
                { 'model': 'greenMarker', 'class': 'marker-green', 'title': 'Marcador Verde' },
                { 'model': 'pinkMarker', 'class': 'marker-pink', 'title': 'Marcador Rosa' },
                { 'model': 'blueMarker', 'class': 'marker-blue', 'title': 'Marcador Azul' },
                { 'model': 'redPen', 'class': 'pen-red', 'title': 'Caneta Vermelha' },
                { 'model': 'greenPen', 'class': 'pen-green', 'title': 'Caneta Verde' }
            ]
        },
        'table': {
            'contentToolbar': [
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableProperties',
                'tableCellProperties'
            ],
            'tableCellProperties': {
                'backgroundColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ],
                'borderColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ]
            },
            'tableProperties': {
                'backgroundColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ],
                'borderColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ]
            },
        },
        'link': {
            'decorators': {
                'addTargetToExternalLinks': True,
                'defaultProtocol': 'https://',
                'toggleDownloadable': {
                    'mode': 'manual',
                    'label': 'Downloadable',
                    'attributes': {
                        'download': 'download'
                    }
                }
            }
        },
        'mediaEmbed': {
            'previewsInData': True,
            'providers': [
                {
                    'name': 'youtube',
                    'url': [
                        '^(?:m?:)?(?:youtube\\.com|youtu\\.be)/watch\\?v=([\\w-]+)',
                        '^(?:m?:)?(?:youtube\\.com|youtu\\.be)/v/([\\w-]+)',
                        '^youtube\\.com/embed/([\\w-]+)',
                        '^youtu\\.be/([\\w-]+)'
                    ],
                    'html': '<iframe src="https://www.youtube.com/embed/{id}?wmode=transparent" width="480" height="270" frameborder="0" allowfullscreen></iframe>'
                },
                {
                    'name': 'vimeo',
                    'url': [
                        '^vimeo\\.com/([\\w-]+)',
                        '^vimeo\\.com/video/([\\w-]+)',
                        '^vimeo\\.com/groups/[\\w-]+/videos/([\\w-]+)',
                        '^vimeo\\.com/channels/[\\w-]+/([\\w-]+)'
                    ],
                    'html': '<iframe src="https://player.vimeo.com/video/{id}" width="480" height="270" frameborder="0" allowfullscreen></iframe>'
                }
            ]
        },
        'image': {
            'toolbar': [
                'imageTextAlternative',
                '|',
                'imageStyle:alignLeft',
                'imageStyle:alignRight',
                'imageStyle:alignCenter',
                'imageStyle:side',
                '|',
                'linkImage'
            ],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter'
            ],
            'resizeOptions': [
                {
                    'name': 'resizeImage:original',
                    'value': None,
                    'label': 'Original'
                },
                {
                    'name': 'resizeImage:50',
                    'value': '50',
                    'label': '50%'
                },
                {
                    'name': 'resizeImage:75',
                    'value': '75',
                    'label': '75%'
                }
            ],
            'resizeUnit': '%'
        },
        'simpleUpload': {
            'uploadUrl': '/ckeditor5/upload/',
            'headers': {
                'X-CSRF-TOKEN': 'CSRF_TOKEN'
            }
        },
        'ui': {
            'viewportOffset': {
                'top': 0,
                'right': 0,
                'bottom': 0,
                'left': 0
            }
        },
        'wordCount': {
            'container': [
                {
                    'type': 'character',
                    'label': 'Caracteres'
                },
                {
                    'type': 'word',
                    'label': 'Palavras'
                }
            ]
        }
    },
    'modelo_ata_config': {
        'heading': {
            'options': [
                {'class': 'ck-heading_paragraph', 'model': 'paragraph', 'title': 'Parágrafo'},
                {'class': 'ck-heading_heading1', 'model': 'heading1', 'title': 'Título 1', 'view': 'h1'},
                {'class': 'ck-heading_heading2', 'model': 'heading2', 'title': 'Título 2', 'view': 'h2'},
                {'class': 'ck-heading_heading3', 'model': 'heading3', 'title': 'Título 3', 'view': 'h3'}
            ]
        },
        'height': 500,
        'language': 'pt-br',
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
            'alignment', '|',
            'numberedList', 'bulletedList', '|',
            'indent', 'outdent', '|',
            'link', 'blockQuote', 'insertTable', 'mediaEmbed', '|',
            'undo', 'redo', '|',
            'sourceEditing'
        ],
        'table': {
            'contentToolbar': [
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableProperties',
                'tableCellProperties'
            ],
            'tableCellProperties': {
                'backgroundColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ],
                'borderColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ]
            },
            'tableProperties': {
                'backgroundColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ],
                'borderColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ]
            }
        }
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote'
        ],
        'toolbar': [
            'heading', '|',
            'outdent', 'indent', '|',
            'bold', 'italic', 'link', 'underline', 'strikethrough',
            'code', 'subscript', 'superscript', 'highlight', '|',
            'codeBlock', 'sourceEditing', 'blockQuote',
            'insertTable', 'mediaEmbed', 'undo', 'redo'
        ],
        'table': {
            'contentToolbar': [
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableProperties',
                'tableCellProperties'
            ],
            'tableCellProperties': {
                'backgroundColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ],
                'borderColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ]
            },
            'tableProperties': {
                'backgroundColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ],
                'borderColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ]
            }
        }
    },
    'voto_proferido_config': {
        'heading': {
            'options': [
                {'class': 'ck-heading_paragraph', 'model': 'paragraph', 'title': 'Parágrafo'},
                {'class': 'ck-heading_heading1', 'model': 'heading1', 'title': 'Título 1', 'view': 'h1'},
                {'class': 'ck-heading_heading2', 'model': 'heading2', 'title': 'Título 2', 'view': 'h2'},
                {'class': 'ck-heading_heading3', 'model': 'heading3', 'title': 'Título 3', 'view': 'h3'}
            ]
        },
        'height': 400,
        'language': 'pt-br',
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
            'alignment', '|',
            'numberedList', 'bulletedList', '|',
            'indent', 'outdent', '|',
            'link', 'blockQuote', 'insertTable', 'mediaEmbed', '|',
            'undo', 'redo', '|',
            'sourceEditing'
        ],
        'ui': {
            'viewportOffset': {
                'bottom': 0,
                'left': 0,
                'right': 0,
                'top': 0
            }
        },
        'table': {
            'contentToolbar': [
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableProperties',
                'tableCellProperties'
            ],
            'tableCellProperties': {
                'backgroundColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ],
                'borderColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ]
            },
            'tableProperties': {
                'backgroundColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ],
                'borderColors': [
                    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
                    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
                    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
                    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
                    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
                    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'}
                ]
            }
        }
    }
}

# Configuração de upload de arquivos para CKEditor 5
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
CKEDITOR_5_CUSTOM_CSS = """
    :root {
        --ck-color-focus-border: #ffc107;
    }
    .ck-editor__editable {
        min-height: 200px;
    }
"""

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Configurações de segurança para permitir acesso aos PDFs
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_BROWSER_XSS_FILTER = False

# Configurações do Captcha
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'
CAPTCHA_LENGTH = 4
CAPTCHA_TIMEOUT = 5
CAPTCHA_FONT_SIZE = 30
CAPTCHA_IMAGE_SIZE = (120, 40)
CAPTCHA_BACKGROUND_COLOR = '#ffffff'
CAPTCHA_FOREGROUND_COLOR = '#000000'
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_dots',)
CAPTCHA_CHARACTERS = 'ABCDEFGHIJKLMNPQRSTUVWXYZ123456789'

# Configurações de upload para formulários com muitos campos
# Aumentar limite de campos para formulários de permissões
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000  # Padrão: 1000 - Aumentado para formulários de permissões
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB (padrão: 2.5MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB (padrão: 2.5MB)
