# Generated by Django 4.2.7 on 2025-07-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0002_fichaconceito_cursos_civis_superior"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fichaconceito",
            options={
                "ordering": ["militar"],
                "verbose_name": "Ficha de Conceito",
                "verbose_name_plural": "Fichas de Conceito",
            },
        ),
        migrations.AlterUniqueTogether(
            name="fichaconceito",
            unique_together={("militar",)},
        ),
        migrations.AddField(
            model_name="fichaconceito",
            name="cursos_instrutor_csbm",
            field=models.PositiveIntegerField(
                default=0, verbose_name="CSBM (Instrutor)"
            ),
        ),
        migrations.RemoveField(
            model_name="fichaconceito",
            name="ano",
        ),
    ]
