# Generated by Django 5.2.3 on 2025-07-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0003_remove_ano_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichaconceito",
            name="medalha_cremepi",
        ),
        migrations.AddField(
            model_name="fichaconceito",
            name="pontos",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                verbose_name="Total de Pontos Calculado",
            ),
        ),
    ]
