# Generated by Django 5.2.3 on 2025-07-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0004_remove_fichaconceito_medalha_cremepi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="apto_inspecao_saude",
            field=models.BooleanField(
                default=True, verbose_name="Apto em Inspeção de Saúde"
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="curso_aperfeicoamento_oficial",
            field=models.BooleanField(
                default=False,
                verbose_name="Possui Curso de Aperfeiçoamento de Oficial Bombeiro Militar",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="curso_formacao_oficial",
            field=models.BooleanField(
                default=False,
                verbose_name="Possui Curso de Formação de Oficial Bombeiro Militar",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="data_inspecao_saude",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Inspeção de Saúde"
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="data_validade_inspecao_saude",
            field=models.DateField(
                blank=True, null=True, verbose_name="Validade da Inspeção de Saúde"
            ),
        ),
    ]
