# Generated by Django 5.2.3 on 2025-07-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0005_militar_apto_inspecao_saude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichaconceito",
            name="cursos_doutorado",
        ),
        migrations.RemoveField(
            model_name="fichaconceito",
            name="cursos_mestrado",
        ),
        migrations.RemoveField(
            model_name="fichaconceito",
            name="cursos_superior",
        ),
        migrations.RemoveField(
            model_name="fichaconceito",
            name="instrutor_cursos",
        ),
        migrations.AlterField(
            model_name="fichaconceito",
            name="cursos_cao",
            field=models.PositiveIntegerField(default=0, verbose_name="CÃO"),
        ),
        migrations.AlterField(
            model_name="fichaconceito",
            name="cursos_cas",
            field=models.PositiveIntegerField(default=0, verbose_name="CÃS"),
        ),
    ]
