# Generated by Django 5.2.3 on 2025-07-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0006_remove_fichaconceito_cursos_doutorado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="curso_superior",
            field=models.BooleanField(
                default=False, verbose_name="Possui Curso Superior"
            ),
        ),
    ]
