# Generated by Django 5.2.3 on 2025-07-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0007_militar_curso_superior"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="curso_csbm",
            field=models.BooleanField(
                default=False,
                verbose_name="Possui Curso Superior de Bombeiro Militar (CSBM)",
            ),
        ),
    ]
