# Generated by Django 5.2.3 on 2025-07-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0008_militar_curso_csbm"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="pos_graduacao",
            field=models.BooleanField(
                default=False, verbose_name="Possui Pós-Graduação"
            ),
        ),
    ]
