# Generated by Django 5.2.3 on 2025-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0011_alter_militar_curso_formacao_oficial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intersticio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posto",
                    models.CharField(
                        choices=[
                            ("CB", "Coronel"),
                            ("TC", "Tenente Coronel"),
                            ("MJ", "Major"),
                            ("CP", "Capitão"),
                            ("1T", "1º Tenente"),
                            ("2T", "2º Tenente"),
                            ("AS", "Aspirante a Oficial"),
                            ("AA", "Aluno de Adaptação"),
                            ("ST", "Subtenente"),
                            ("1S", "1º Sargento"),
                            ("2S", "2º Sargento"),
                            ("3S", "3º Sargento"),
                            ("CB", "Cabo"),
                            ("SD", "Soldado"),
                        ],
                        max_length=2,
                        verbose_name="Posto",
                    ),
                ),
                (
                    "quadro",
                    models.CharField(
                        choices=[
                            ("COMB", "Combatente"),
                            ("SAUDE", "Saúde"),
                            ("ENG", "Engenheiro"),
                            ("COMP", "Complementar"),
                        ],
                        max_length=10,
                        verbose_name="Quadro",
                    ),
                ),
                (
                    "tempo_minimo_anos",
                    models.PositiveIntegerField(verbose_name="Tempo Mínimo (anos)"),
                ),
                (
                    "tempo_minimo_meses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tempo Mínimo (meses)"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Interstício",
                "verbose_name_plural": "Interstícios",
                "ordering": ["quadro", "posto"],
                "unique_together": {("posto", "quadro")},
            },
        ),
    ]
