# Generated by Django 5.2.3 on 2025-07-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0012_intersticio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intersticio",
            name="quadro",
            field=models.CharField(
                choices=[
                    ("COMB", "Combatente"),
                    ("SAUDE", "Saúde"),
                    ("ENG", "Engenheiro"),
                    ("COMP", "Complementar"),
                    ("PRACAS", "Praças"),
                ],
                max_length=10,
                verbose_name="Quadro",
            ),
        ),
        migrations.AlterField(
            model_name="militar",
            name="quadro",
            field=models.CharField(
                choices=[
                    ("COMB", "Combatente"),
                    ("SAUDE", "Saúde"),
                    ("ENG", "Engenheiro"),
                    ("COMP", "Complementar"),
                    ("PRACAS", "Praças"),
                ],
                default="COMB",
                max_length=10,
                verbose_name="Quadro",
            ),
        ),
    ]
