# Generated by Django 5.2.3 on 2025-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0013_alter_intersticio_quadro_alter_militar_quadro"),
    ]

    operations = [
        migrations.AddField(
            model_name="quadroacesso",
            name="data_atualizacao",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AddField(
            model_name="quadroacesso",
            name="motivo_nao_elaboracao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SEM_VAGA", "Inexistência de vaga"),
                    (
                        "SEM_REQUISITOS",
                        "Não há militar que satisfaça os requisitos essenciais",
                    ),
                    ("SEM_EFETIVO", "Sem efetivo suficiente"),
                    ("OUTROS", "Outros motivos"),
                ],
                max_length=20,
                null=True,
                verbose_name="Motivo da Não Elaboração",
            ),
        ),
        migrations.AddField(
            model_name="quadroacesso",
            name="observacoes",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
        migrations.AddField(
            model_name="quadroacesso",
            name="status",
            field=models.CharField(
                choices=[
                    ("ELABORADO", "Elaborado"),
                    ("NAO_ELABORADO", "Não Elaborado"),
                    ("EM_ELABORACAO", "Em Elaboração"),
                ],
                default="EM_ELABORACAO",
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="quadroacesso",
            name="posto",
            field=models.CharField(
                choices=[
                    ("AS", "Aspirante a Oficial"),
                    ("2T", "2º Tenente"),
                    ("1T", "1º Tenente"),
                    ("CP", "Capitão"),
                    ("MJ", "Major"),
                    ("TC", "Tenente-Coronel"),
                    ("CB", "Coronel"),
                    ("ST", "Subtenente"),
                ],
                max_length=2,
                verbose_name="Posto",
            ),
        ),
    ]
