# Generated by Django 5.2.3 on 2025-07-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0014_quadroacesso_data_atualizacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="curso_cho",
            field=models.BooleanField(
                default=False,
                verbose_name="Possui Curso de Habilitação de Oficiais (CHO)",
            ),
        ),
    ]
