# Generated by Django 5.2.3 on 2025-07-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0015_militar_curso_cho"),
    ]

    operations = [
        migrations.AddField(
            model_name="quadroacesso",
            name="data_homologacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Homologação"
            ),
        ),
        migrations.AlterField(
            model_name="quadroacesso",
            name="status",
            field=models.CharField(
                choices=[
                    ("ELABORADO", "Elaborado"),
                    ("NAO_ELABORADO", "Não Elaborado"),
                    ("EM_ELABORACAO", "Em Elaboração"),
                    ("HOMOLOGADO", "Homologado"),
                ],
                default="EM_ELABORACAO",
                max_length=15,
                verbose_name="Status",
            ),
        ),
    ]
