# Generated by Django 4.2.7 on 2025-07-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0016_quadroacesso_data_homologacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="numeracao_antiguidade",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Numeração de Antiguidade"
            ),
        ),
    ]
