# Generated by Django 4.2.7 on 2025-07-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0017_add_numeracao_antiguidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="militar",
            name="numeracao_antiguidade",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Numeração de Antiguidade (Manual)"
            ),
        ),
    ]
