# Generated by Django 4.2.7 on 2025-07-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0020_alter_quadroacesso_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quadroacesso",
            name="is_manual",
            field=models.BooleanField(default=False, verbose_name="Quadro Manual"),
        ),
        migrations.AlterField(
            model_name="quadroacesso",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ANTIGUIDADE", "Quadro de Acesso por Antiguidade"),
                    ("MERECIMENTO", "Quadro de Acesso por Merecimento"),
                    ("MANUAL", "Quadro de Acesso Manual"),
                ],
                max_length=15,
                verbose_name="Tipo",
            ),
        ),
    ]
