# Generated by Django 4.2.7 on 2025-07-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0021_quadroacesso_is_manual_alter_quadroacesso_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="quadroacesso",
            name="criterio_ordenacao_manual",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Ordem Manual"),
                    ("ANTIGUIDADE", "Por Antiguidade"),
                    ("MERECIMENTO", "Por Merecimento"),
                ],
                default="MANUAL",
                max_length=20,
                verbose_name="Critério de Ordenação Manual",
            ),
        ),
    ]
