# Generated by Django 5.2.3 on 2025-07-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0022_quadroacesso_criterio_ordenacao_manual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intersticio",
            name="posto",
            field=models.CharField(
                choices=[
                    ("CB", "Coronel"),
                    ("TC", "Tenente Coronel"),
                    ("MJ", "Major"),
                    ("CP", "Capitão"),
                    ("1T", "1º Tenente"),
                    ("2T", "2º Tenente"),
                    ("AS", "Aspirante a Oficial"),
                    ("AA", "Aluno de Adaptação"),
                    ("ST", "Subtenente"),
                    ("1S", "1º Sargento"),
                    ("2S", "2º Sargento"),
                    ("3S", "3º Sargento"),
                    ("CAB", "Cabo"),
                    ("SD", "Soldado"),
                ],
                max_length=3,
                verbose_name="Posto",
            ),
        ),
        migrations.AlterField(
            model_name="militar",
            name="posto_graduacao",
            field=models.CharField(
                choices=[
                    ("CB", "Coronel"),
                    ("TC", "Tenente Coronel"),
                    ("MJ", "Major"),
                    ("CP", "Capitão"),
                    ("1T", "1º Tenente"),
                    ("2T", "2º Tenente"),
                    ("AS", "Aspirante a Oficial"),
                    ("AA", "Aluno de Adaptação"),
                    ("ST", "Subtenente"),
                    ("1S", "1º Sargento"),
                    ("2S", "2º Sargento"),
                    ("3S", "3º Sargento"),
                    ("CAB", "Cabo"),
                    ("SD", "Soldado"),
                ],
                max_length=3,
                verbose_name="Posto/Graduação",
            ),
        ),
        migrations.AlterField(
            model_name="promocao",
            name="posto_anterior",
            field=models.CharField(
                choices=[
                    ("CB", "Coronel"),
                    ("TC", "Tenente Coronel"),
                    ("MJ", "Major"),
                    ("CP", "Capitão"),
                    ("1T", "1º Tenente"),
                    ("2T", "2º Tenente"),
                    ("AS", "Aspirante a Oficial"),
                    ("AA", "Aluno de Adaptação"),
                    ("ST", "Subtenente"),
                    ("1S", "1º Sargento"),
                    ("2S", "2º Sargento"),
                    ("3S", "3º Sargento"),
                    ("CAB", "Cabo"),
                    ("SD", "Soldado"),
                ],
                max_length=3,
                verbose_name="Posto Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="promocao",
            name="posto_novo",
            field=models.CharField(
                choices=[
                    ("CB", "Coronel"),
                    ("TC", "Tenente Coronel"),
                    ("MJ", "Major"),
                    ("CP", "Capitão"),
                    ("1T", "1º Tenente"),
                    ("2T", "2º Tenente"),
                    ("AS", "Aspirante a Oficial"),
                    ("AA", "Aluno de Adaptação"),
                    ("ST", "Subtenente"),
                    ("1S", "1º Sargento"),
                    ("2S", "2º Sargento"),
                    ("3S", "3º Sargento"),
                    ("CAB", "Cabo"),
                    ("SD", "Soldado"),
                ],
                max_length=3,
                verbose_name="Novo Posto",
            ),
        ),
    ]
