# Generated by Django 5.2.3 on 2025-07-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0023_alter_intersticio_posto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrevisaoVaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posto",
                    models.CharField(
                        choices=[
                            ("CB", "Coronel"),
                            ("TC", "Tenente Coronel"),
                            ("MJ", "Major"),
                            ("CP", "Capitão"),
                            ("1T", "1º Tenente"),
                            ("2T", "2º Tenente"),
                            ("AS", "Aspirante a Oficial"),
                            ("AA", "Aluno de Adaptação"),
                            ("ST", "Subtenente"),
                            ("1S", "1º Sargento"),
                            ("2S", "2º Sargento"),
                            ("3S", "3º Sargento"),
                            ("CAB", "Cabo"),
                            ("SD", "Soldado"),
                        ],
                        max_length=3,
                        verbose_name="Posto",
                    ),
                ),
                (
                    "quadro",
                    models.CharField(
                        choices=[
                            ("COMB", "Combatente"),
                            ("SAUDE", "Saúde"),
                            ("ENG", "Engenheiro"),
                            ("COMP", "Complementar"),
                            ("PRACAS", "Praças"),
                        ],
                        max_length=10,
                        verbose_name="Quadro",
                    ),
                ),
                (
                    "efetivo_atual",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Efetivo Atual"
                    ),
                ),
                (
                    "efetivo_previsto",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Efetivo Previsto"
                    ),
                ),
                (
                    "vagas_disponiveis",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Vagas Disponíveis"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Previsão de Vaga",
                "verbose_name_plural": "Previsões de Vagas",
                "ordering": ["quadro", "posto"],
                "unique_together": {("posto", "quadro")},
            },
        ),
    ]
