# Generated by Django 5.2.3 on 2025-07-03 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0024_previsaovaga"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quadroacesso",
            name="homologado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quadros_homologados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Homologado por",
            ),
        ),
    ]
