# Generated by Django 5.2.3 on 2025-07-03 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0025_quadroacesso_homologado_por"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="assinado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_assinados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assinado por",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="data_assinatura",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Assinatura"
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="observacoes_assinatura",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações da Assinatura"
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente de Conferência"),
                    ("APROVADO", "Aprovado"),
                    ("REJEITADO", "Rejeitado"),
                    ("ARQUIVADO", "Arquivado"),
                    ("ASSINADO", "Assinado"),
                ],
                default="PENDENTE",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
