# Generated by Django 5.2.3 on 2025-07-03 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0026_documento_assinado_por_documento_data_assinatura_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quadroacesso",
            name="assinado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quadros_assinados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assinado por",
            ),
        ),
        migrations.AddField(
            model_name="quadroacesso",
            name="data_assinatura",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Assinatura"
            ),
        ),
        migrations.AddField(
            model_name="quadroacesso",
            name="observacoes_assinatura",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações da Assinatura"
            ),
        ),
        migrations.AlterField(
            model_name="quadroacesso",
            name="status",
            field=models.CharField(
                choices=[
                    ("ELABORADO", "Elaborado"),
                    ("NAO_ELABORADO", "Não Elaborado"),
                    ("EM_ELABORACAO", "Em Elaboração"),
                    ("HOMOLOGADO", "Homologado"),
                    ("ASSINADO", "Assinado"),
                ],
                default="EM_ELABORACAO",
                max_length=15,
                verbose_name="Status",
            ),
        ),
    ]
