# Generated by Django 5.2.3 on 2025-07-03 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0027_quadroacesso_assinado_por_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quadroacesso",
            name="assinado_por",
        ),
        migrations.RemoveField(
            model_name="quadroacesso",
            name="data_assinatura",
        ),
        migrations.RemoveField(
            model_name="quadroacesso",
            name="observacoes_assinatura",
        ),
        migrations.CreateModel(
            name="AssinaturaQuadroAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_assinatura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Assinatura"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações da Assinatura"
                    ),
                ),
                (
                    "tipo_assinatura",
                    models.CharField(
                        choices=[
                            ("ELABORACAO", "Elaboração"),
                            ("REVISAO", "Revisão"),
                            ("APROVACAO", "Aprovação"),
                            ("HOMOLOGACAO", "Homologação"),
                            ("OUTROS", "Outros"),
                        ],
                        default="APROVACAO",
                        max_length=20,
                        verbose_name="Tipo de Assinatura",
                    ),
                ),
                (
                    "assinado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assinado por",
                    ),
                ),
                (
                    "quadro_acesso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to="militares.quadroacesso",
                        verbose_name="Quadro de Acesso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura do Quadro de Acesso",
                "verbose_name_plural": "Assinaturas do Quadro de Acesso",
                "ordering": ["-data_assinatura"],
                "unique_together": {
                    ("quadro_acesso", "assinado_por", "tipo_assinatura")
                },
            },
        ),
    ]
