# Generated by Django 4.2.7 on 2025-07-04 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0028_remove_quadroacesso_assinado_por_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComissaoPromocaoOficiais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Comissão"),
                ),
                ("data_criacao", models.DateField(verbose_name="Data de Criação")),
                (
                    "data_termino",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Término"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVA", "Ativa"),
                            ("INATIVA", "Inativa"),
                            ("SUSPENSA", "Suspensa"),
                        ],
                        default="ATIVA",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Registro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comissão de Promoção de Oficiais",
                "verbose_name_plural": "Comissões de Promoção de Oficiais",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="MembroComissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PRESIDENTE", "Presidente (Comandante-Geral)"),
                            ("NATO", "Membro Nato"),
                            ("EFETIVO", "Membro Efetivo"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de Membro",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("COMANDANTE_GERAL", "Comandante-Geral"),
                            ("CHEFE_ESTADO_MAIOR", "Chefe do Estado Maior"),
                            ("DIRETOR_PESSOAL", "Diretor de Pessoal"),
                            ("BM1", "BM-1"),
                            ("OFICIAL_SUPERIOR", "Oficial Superior"),
                        ],
                        max_length=20,
                        verbose_name="Cargo/Função",
                    ),
                ),
                ("data_nomeacao", models.DateField(verbose_name="Data de Nomeação")),
                (
                    "data_termino",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Término"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Registro"
                    ),
                ),
                (
                    "comissao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros",
                        to="militares.comissaopromocaooficiais",
                        verbose_name="Comissão",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro da Comissão",
                "verbose_name_plural": "Membros da Comissão",
                "ordering": ["tipo", "militar__nome_completo"],
                "unique_together": {("comissao", "militar", "tipo")},
            },
        ),
        migrations.CreateModel(
            name="SessaoComissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(verbose_name="Número da Sessão"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ORDINARIA", "Ordinária"),
                            ("EXTRAORDINARIA", "Extraordinária"),
                            ("ESPECIAL", "Especial"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de Sessão",
                    ),
                ),
                ("data_sessao", models.DateField(verbose_name="Data da Sessão")),
                ("hora_inicio", models.TimeField(verbose_name="Hora de Início")),
                (
                    "hora_fim",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Término"
                    ),
                ),
                ("local", models.CharField(max_length=200, verbose_name="Local")),
                ("pauta", models.TextField(verbose_name="Pauta")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGENDADA", "Agendada"),
                            ("EM_ANDAMENTO", "Em Andamento"),
                            ("CONCLUIDA", "Concluída"),
                            ("CANCELADA", "Cancelada"),
                            ("SUSPENSA", "Suspensa"),
                        ],
                        default="AGENDADA",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Registro"
                    ),
                ),
                (
                    "comissao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessoes",
                        to="militares.comissaopromocaooficiais",
                        verbose_name="Comissão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão da Comissão",
                "verbose_name_plural": "Sessões da Comissão",
                "ordering": ["-data_sessao", "-numero"],
                "unique_together": {("comissao", "numero")},
            },
        ),
        migrations.CreateModel(
            name="DeliberacaoComissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(verbose_name="Número da Deliberação"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("APROVACAO", "Aprovação"),
                            ("REPROVACAO", "Reprovação"),
                            ("SUSPENSAO", "Suspensão"),
                            ("ENCAMINHAMENTO", "Encaminhamento"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de Deliberação",
                    ),
                ),
                ("assunto", models.CharField(max_length=200, verbose_name="Assunto")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("resultado", models.TextField(verbose_name="Resultado/Deliberação")),
                (
                    "votos_favor",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Votos Favoráveis"
                    ),
                ),
                (
                    "votos_contra",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Votos Contrários"
                    ),
                ),
                (
                    "votos_abstencao",
                    models.PositiveIntegerField(default=0, verbose_name="Abstenções"),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Registro"
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliberacoes",
                        to="militares.sessaocomissao",
                        verbose_name="Sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deliberação da Comissão",
                "verbose_name_plural": "Deliberações da Comissão",
                "ordering": ["sessao", "numero"],
                "unique_together": {("sessao", "numero")},
            },
        ),
        migrations.CreateModel(
            name="VotoDeliberacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voto",
                    models.CharField(
                        choices=[
                            ("FAVOR", "Favorável"),
                            ("CONTRA", "Contrário"),
                            ("ABSTENCAO", "Abstenção"),
                        ],
                        max_length=10,
                        verbose_name="Voto",
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(
                        blank=True, null=True, verbose_name="Justificativa"
                    ),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Registro"
                    ),
                ),
                (
                    "deliberacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos",
                        to="militares.deliberacaocomissao",
                        verbose_name="Deliberação",
                    ),
                ),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.membrocomissao",
                        verbose_name="Membro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto na Deliberação",
                "verbose_name_plural": "Votos na Deliberação",
                "ordering": ["deliberacao", "membro__militar__nome_completo"],
                "unique_together": {("deliberacao", "membro")},
            },
        ),
        migrations.CreateModel(
            name="PresencaSessao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "presente",
                    models.BooleanField(default=False, verbose_name="Presente"),
                ),
                (
                    "justificativa",
                    models.TextField(
                        blank=True, null=True, verbose_name="Justificativa da Ausência"
                    ),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Registro"
                    ),
                ),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.membrocomissao",
                        verbose_name="Membro",
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencas",
                        to="militares.sessaocomissao",
                        verbose_name="Sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presença na Sessão",
                "verbose_name_plural": "Presenças na Sessão",
                "ordering": ["sessao", "membro__militar__nome_completo"],
                "unique_together": {("sessao", "membro")},
            },
        ),
    ]
