# Generated by Django 4.2.7 on 2025-07-04 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("militares", "0029_comissaopromocaooficiais_membrocomissao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComissaoPromocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CPO", "Comissão de Promoção de Oficiais"),
                            ("CPP", "Comissão de Promoção de Praças"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de Comissão",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Comissão"),
                ),
                ("data_criacao", models.DateField(verbose_name="Data de Criação")),
                (
                    "data_termino",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Término"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVA", "Ativa"),
                            ("INATIVA", "Inativa"),
                            ("SUSPENSA", "Suspensa"),
                        ],
                        default="ATIVA",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Registro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comissão de Promoção",
                "verbose_name_plural": "Comissões de Promoção",
                "ordering": ["tipo", "-data_criacao"],
            },
        ),
        migrations.AddField(
            model_name="membrocomissao",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário do Sistema",
            ),
        ),
        migrations.AlterField(
            model_name="membrocomissao",
            name="comissao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membros",
                to="militares.comissaopromocao",
                verbose_name="Comissão",
            ),
        ),
        migrations.AlterField(
            model_name="sessaocomissao",
            name="comissao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessoes",
                to="militares.comissaopromocao",
                verbose_name="Comissão",
            ),
        ),
        migrations.DeleteModel(
            name="ComissaoPromocaoOficiais",
        ),
    ]
