# Generated by Django 4.2.7 on 2025-07-05 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import militares.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("militares", "0030_comissaopromocao_membrocomissao_usuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membrocomissao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PRESIDENTE", "Presidente da Comissão"),
                    ("EFETIVO", "Membro Efetivo"),
                    ("NATO", "Membro Nato"),
                    ("SECRETARIO", "Secretário"),
                ],
                max_length=15,
                verbose_name="Tipo de Membro",
            ),
        ),
        migrations.CreateModel(
            name="DocumentoSessao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PAUTA", "Pauta da Sessão"),
                            ("ATA", "Ata da Sessão"),
                            ("MEMORANDO", "Memorando"),
                            ("PORTARIA", "Portaria"),
                            ("DECRETO", "Decreto"),
                            ("RELATORIO", "Relatório"),
                            ("QUADRO_ACESSO", "Quadro de Acesso"),
                            ("FICHA_CONCEITO", "Ficha de Conceito"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=200, verbose_name="Título do Documento"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=militares.models.documento_sessao_upload_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Upload"
                    ),
                ),
                (
                    "deliberacao_gerada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.deliberacaocomissao",
                        verbose_name="Deliberação Gerada",
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="militares.sessaocomissao",
                        verbose_name="Sessão",
                    ),
                ),
                (
                    "upload_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Upload por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento da Sessão",
                "verbose_name_plural": "Documentos da Sessão",
                "ordering": ["-data_upload"],
            },
        ),
    ]
