# Generated by Django 4.2.7 on 2025-07-05 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("militares", "0031_alter_membrocomissao_tipo_documentosessao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentosessao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PAUTA", "Pauta da Sessão"),
                    ("ATA", "Ata da Sessão"),
                    ("MEMORANDO", "Memorando"),
                    ("OFICIO", "Ofício"),
                    ("REQUERIMENTO", "Requerimento"),
                    ("MANDADO_JUDICIAL", "Mandado Judicial"),
                    ("DESPACHO", "Despacho"),
                    ("PARECER", "Parecer"),
                    ("DECISAO", "Decisão"),
                    ("SENTENCA", "Sentença"),
                    ("NOTIFICACAO", "Notificação"),
                    ("INTIMACAO", "Intimação"),
                    ("CERTIDAO", "Certidão"),
                    ("PROCURACAO", "Procuração"),
                    ("CONTRATO", "Contrato"),
                    ("PORTARIA", "Portaria"),
                    ("DECRETO", "Decreto"),
                    ("RELATORIO", "Relatório"),
                    ("QUADRO_ACESSO", "Quadro de Acesso"),
                    ("FICHA_CONCEITO", "Ficha de Conceito"),
                    ("OUTROS", "Outros"),
                ],
                max_length=20,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.CreateModel(
            name="JustificativaEncerramento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("justificativa", models.TextField(verbose_name="Justificativa")),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Registro"
                    ),
                ),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.membrocomissao",
                        verbose_name="Membro",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="justificativas_encerramento",
                        to="militares.sessaocomissao",
                        verbose_name="Sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Justificativa de Encerramento",
                "verbose_name_plural": "Justificativas de Encerramento",
                "ordering": ["-data_registro"],
                "unique_together": {("sessao", "membro")},
            },
        ),
    ]
