# Generated by Django 4.2.7 on 2025-07-05 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("militares", "0032_alter_documentosessao_tipo_justificativaencerramento"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtaSessao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo", models.TextField(verbose_name="Conteúdo da Ata")),
                (
                    "data_edicao",
                    models.DateTimeField(auto_now=True, verbose_name="Data da Edição"),
                ),
                (
                    "versao",
                    models.PositiveIntegerField(default=1, verbose_name="Versão"),
                ),
                (
                    "editado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Editado por",
                    ),
                ),
                (
                    "sessao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ata_editada",
                        to="militares.sessaocomissao",
                        verbose_name="Sessão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ata da Sessão",
                "verbose_name_plural": "Atas das Sessões",
                "ordering": ["-data_edicao"],
            },
        ),
    ]
