# Generated by Django 4.2.7 on 2025-07-05 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("militares", "0033_atasessao"),
    ]

    operations = [
        migrations.AddField(
            model_name="atasessao",
            name="data_finalizacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Finalização"
            ),
        ),
        migrations.AddField(
            model_name="atasessao",
            name="status",
            field=models.CharField(
                choices=[
                    ("RASCUNHO", "Rascunho"),
                    ("PARA_ASSINATURA", "Para Assinatura"),
                    ("ASSINADA", "Assinada"),
                    ("FINALIZADA", "Finalizada"),
                ],
                default="RASCUNHO",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="AssinaturaAta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_assinatura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Assinatura"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "assinado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assinado por",
                    ),
                ),
                (
                    "ata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to="militares.atasessao",
                        verbose_name="Ata",
                    ),
                ),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.membrocomissao",
                        verbose_name="Membro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura da Ata",
                "verbose_name_plural": "Assinaturas da Ata",
                "ordering": ["data_assinatura"],
                "unique_together": {("ata", "membro")},
            },
        ),
    ]
