# Generated by Django 4.2.7 on 2025-07-05 04:19

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("militares", "0034_adicionar_assinatura_ata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atasessao",
            name="conteudo",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Conteúdo da Ata"
            ),
        ),
        migrations.CreateModel(
            name="ModeloAta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Modelo"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "tipo_comissao",
                    models.CharField(
                        choices=[
                            ("CPO", "Comissão de Promoção de Oficiais"),
                            ("CPP", "Comissão de Promoção de Praças"),
                            ("GERAL", "Geral (Ambos os tipos)"),
                        ],
                        default="GERAL",
                        max_length=10,
                        verbose_name="Tipo de Comissão",
                    ),
                ),
                (
                    "tipo_sessao",
                    models.CharField(
                        choices=[
                            ("ORDINARIA", "Ordinária"),
                            ("EXTRAORDINARIA", "Extraordinária"),
                            ("ESPECIAL", "Especial"),
                            ("GERAL", "Geral (Todos os tipos)"),
                        ],
                        default="GERAL",
                        max_length=15,
                        verbose_name="Tipo de Sessão",
                    ),
                ),
                (
                    "conteudo",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text="Use variáveis como {{sessao.numero}}, {{sessao.data_sessao}}, {{sessao.local}}, etc.",
                        verbose_name="Conteúdo do Modelo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "padrao",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, será usado como modelo padrão para novas atas",
                        verbose_name="Modelo Padrão",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Ata",
                "verbose_name_plural": "Modelos de Ata",
                "ordering": ["-padrao", "nome"],
            },
        ),
    ]
