# Generated by Django 4.2.7 on 2025-07-05 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("militares", "0035_alter_atasessao_conteudo_modeloata"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificacaoSessao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SESSAO_PENDENTE", "Sessão Pendente"),
                            ("VOTACAO_PENDENTE", "Votação Pendente"),
                            ("SESSAO_AGENDADA", "Sessão Agendada"),
                            ("SESSAO_HOJE", "Sessão Hoje"),
                            ("DELIBERACAO_PENDENTE", "Deliberação Pendente"),
                            ("ATA_PENDENTE", "Ata Pendente"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Notificação",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("BAIXA", "Baixa"),
                            ("MEDIA", "Média"),
                            ("ALTA", "Alta"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="MEDIA",
                        max_length=10,
                        verbose_name="Prioridade",
                    ),
                ),
                ("lida", models.BooleanField(default=False, verbose_name="Lida")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_leitura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Leitura"
                    ),
                ),
                (
                    "comissao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.comissaopromocao",
                        verbose_name="Comissão",
                    ),
                ),
                (
                    "deliberacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.deliberacaocomissao",
                        verbose_name="Deliberação",
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.sessaocomissao",
                        verbose_name="Sessão",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes_sessao",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação de Sessão",
                "verbose_name_plural": "Notificações de Sessão",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "lida"],
                        name="militares_n_usuario_e36380_idx",
                    ),
                    models.Index(
                        fields=["tipo", "data_criacao"],
                        name="militares_n_tipo_c39cec_idx",
                    ),
                ],
            },
        ),
    ]
