# Generated by Django 4.2.7 on 2025-07-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0036_notificacaosessao"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoComissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Cargo"),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único para identificação (ex: COMANDANTE_GERAL)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo da Comissão",
                "verbose_name_plural": "Cargos da Comissão",
                "ordering": ["ordem", "nome"],
            },
        ),
    ]
