# Generated by Django 4.2.7 on 2025-07-05 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0038_migrate_cargos_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membrocomissao",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="militares.cargocomissao",
                verbose_name="Cargo/Função",
            ),
        ),
    ]
