# Generated by Django 4.2.7 on 2025-07-05 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("militares", "0040_militar_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="VagaManual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posto",
                    models.CharField(
                        choices=[
                            ("2T", "2º Tenente"),
                            ("1T", "1º Tenente"),
                            ("CP", "Capitão"),
                            ("MJ", "Major"),
                            ("TC", "Tenente-Coronel"),
                            ("CB", "Coronel"),
                        ],
                        max_length=2,
                        verbose_name="Posto",
                    ),
                ),
                (
                    "quadro",
                    models.CharField(
                        choices=[
                            ("COMB", "Combatente"),
                            ("SAUDE", "Saúde"),
                            ("ENG", "Engenheiro"),
                            ("COMP", "Complementar"),
                        ],
                        max_length=5,
                        verbose_name="Quadro",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantidade de Vagas"
                    ),
                ),
                ("justificativa", models.TextField(verbose_name="Justificativa")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADA", "Aprovada"),
                            ("REJEITADA", "Rejeitada"),
                            ("IMPLEMENTADA", "Implementada"),
                        ],
                        default="PENDENTE",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_solicitacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Solicitação"
                    ),
                ),
                (
                    "data_aprovacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Aprovação"
                    ),
                ),
                (
                    "data_implementacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Implementação"
                    ),
                ),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaga Manual",
                "verbose_name_plural": "Vagas Manuais",
                "ordering": ["-data_solicitacao"],
            },
        ),
    ]
