# Generated by Django 4.2.7 on 2025-07-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0041_vagamanual"),
    ]

    operations = [
        migrations.AddField(
            model_name="previsaovaga",
            name="observacoes_vagas_fixadas",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações das Vagas Fixadas"
            ),
        ),
        migrations.AddField(
            model_name="previsaovaga",
            name="vagas_fixadas",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Vagas fixadas manualmente para este posto/quadro",
                verbose_name="Vagas Fixadas",
            ),
        ),
    ]
