# Generated by Django 4.2.7 on 2025-07-05 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("militares", "0042_add_vagas_fixadas"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuadroFixacaoVagas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título do Quadro"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("OFICIAIS", "Oficiais"), ("PRACAS", "Praças")],
                        default="OFICIAIS",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                ("data_promocao", models.DateField(verbose_name="Data da Promoção")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("EM_ELABORACAO", "Em Elaboração"),
                            ("FINALIZADO", "Finalizado"),
                            ("APROVADO", "Aprovado"),
                        ],
                        default="RASCUNHO",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações Gerais"
                    ),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Registro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quadro de Fixação de Vagas",
                "verbose_name_plural": "Quadros de Fixação de Vagas",
                "ordering": ["-data_promocao", "-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="ItemQuadroFixacaoVagas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vagas_fixadas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Vagas Fixadas"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Registro"
                    ),
                ),
                (
                    "previsao_vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.previsaovaga",
                        verbose_name="Previsão de Vaga",
                    ),
                ),
                (
                    "quadro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="militares.quadrofixacaovagas",
                        verbose_name="Quadro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Quadro de Fixação de Vagas",
                "verbose_name_plural": "Itens do Quadro de Fixação de Vagas",
                "ordering": ["previsao_vaga__quadro", "previsao_vaga__posto"],
                "unique_together": {("quadro", "previsao_vaga")},
            },
        ),
    ]
