# Generated by Django 4.2.7 on 2025-07-05 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("militares", "0043_quadrofixacaovagas_itemquadrofixacaovagas"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssinaturaQuadroFixacaoVagas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_assinatura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Assinatura"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações da Assinatura"
                    ),
                ),
                (
                    "tipo_assinatura",
                    models.CharField(
                        choices=[
                            ("APROVACAO", "Aprovação"),
                            ("HOMOLOGACAO", "Homologação"),
                            ("REVISAO", "Revisão"),
                            ("CONFERENCIA", "Conferência"),
                        ],
                        default="APROVACAO",
                        max_length=15,
                        verbose_name="Tipo de Assinatura",
                    ),
                ),
                (
                    "assinado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assinado por",
                    ),
                ),
                (
                    "quadro_fixacao_vagas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to="militares.quadrofixacaovagas",
                        verbose_name="Quadro de Fixação de Vagas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura do Quadro de Fixação de Vagas",
                "verbose_name_plural": "Assinaturas do Quadro de Fixação de Vagas",
                "ordering": ["-data_assinatura"],
                "unique_together": {
                    ("quadro_fixacao_vagas", "assinado_por", "tipo_assinatura")
                },
            },
        ),
    ]
