# Generated by Django 4.2.7 on 2025-07-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0044_assinaturaquadrofixacaovagas"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="curso_cas",
            field=models.BooleanField(
                default=False,
                verbose_name="Possui Curso de Aperfeiçoamento de Sargentos (CAS)",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="curso_cfsd",
            field=models.BooleanField(
                default=False,
                verbose_name="Possui Curso de Formação de Soldados (CFSD)",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="curso_chc",
            field=models.BooleanField(
                default=False,
                verbose_name="Possui Curso de Habilitação de Cabos (CHC) ou Adaptação a Cabos",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="curso_chsgt",
            field=models.BooleanField(
                default=False,
                verbose_name="Possui Curso de Habilitação de Sargentos (CHSGT) ou Adaptação a Sargentos",
            ),
        ),
    ]
