# Generated by Django 4.2.7 on 2025-07-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0045_militar_curso_cas_militar_curso_cfsd_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="militar",
            name="curso_chc",
            field=models.BooleanField(
                default=False,
                verbose_name="Possui Curso de Habilitação de Cabos (CHC) ou equivalente",
            ),
        ),
        migrations.AlterField(
            model_name="militar",
            name="curso_chsgt",
            field=models.BooleanField(
                default=False,
                verbose_name="Possui Curso de Habilitação de Sargentos (CHSGT) ou equivalente",
            ),
        ),
    ]
