# Generated by Django 4.2.7 on 2025-07-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0046_alter_militar_curso_chc_alter_militar_curso_chsgt"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="curso_formacao_pracas",
            field=models.BooleanField(
                default=False, verbose_name="Possui Curso de Formação de Praças"
            ),
        ),
    ]
