# Generated by Django 4.2.7 on 2025-07-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0047_militar_curso_formacao_pracas"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quadroacesso",
            unique_together={("tipo", "data_promocao", "is_manual")},
        ),
    ]
