# Generated by Django 4.2.7 on 2025-07-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0048_alter_quadroacesso_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quadroacesso",
            unique_together=set(),
        ),
    ]
