# Generated by Django 4.2.7 on 2025-07-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0049_alter_quadroacesso_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quadroacesso",
            name="criterio_ordenacao_manual",
            field=models.CharField(
                choices=[
                    ("ANTIGUIDADE", "Por Antiguidade"),
                    ("MERECIMENTO", "Por Merecimento"),
                ],
                default="ANTIGUIDADE",
                max_length=20,
                verbose_name="Critério de Ordenação Manual",
            ),
        ),
    ]
