# Generated by Django 4.2.7 on 2025-07-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0050_alter_quadroacesso_criterio_ordenacao_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="quadroacesso",
            name="categoria",
            field=models.CharField(
                choices=[("OFICIAIS", "Oficiais"), ("PRACAS", "Praças")],
                default="OFICIAIS",
                max_length=10,
                verbose_name="Categoria",
            ),
        ),
    ]
