# Generated by Django 5.2.3 on 2025-07-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0051_add_categoria_to_quadro_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadrofixacaovagas',
            name='numero',
            field=models.CharField(
                max_length=20,
                unique=True,
                verbose_name='Numeração do Quadro',
                help_text='Numeração automática e única, ex: 2025-07-001',
                null=True,
                blank=True
            ),
        ),
    ] 