# Generated by Django 4.2.7 on 2025-07-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0052_add_numero_to_quadrofixacaovagas"),
    ]

    operations = [
        migrations.AddField(
            model_name="quadroacesso",
            name="numero",
            field=models.CharField(
                blank=True,
                help_text="Numeração automática e única, ex: QAA-OF-2025/07/18 ou QAA-OF-2025/07/18 - A 01",
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Numeração do Quadro",
            ),
        ),
        migrations.AlterField(
            model_name="quadrofixacaovagas",
            name="numero",
            field=models.CharField(
                help_text="Numeração automática e única, ex: QFV-OF-2025/07/18 ou QFV-OF-2025/07/18 - A 01",
                max_length=30,
                unique=True,
                verbose_name="Numeração do Quadro",
            ),
        ),
    ]
