# Generated by Django 4.2.7 on 2025-07-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0053_quadroacesso_numero_alter_quadrofixacaovagas_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemquadroacesso",
            name="data_documento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Documento"
            ),
        ),
        migrations.AddField(
            model_name="itemquadroacesso",
            name="documento_referencia",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Documento de Referência",
            ),
        ),
        migrations.AddField(
            model_name="itemquadroacesso",
            name="inserido_manualmente",
            field=models.BooleanField(
                default=False, verbose_name="Inserido Manualmente"
            ),
        ),
        migrations.AddField(
            model_name="itemquadroacesso",
            name="motivo_insercao",
            field=models.CharField(
                choices=[
                    ("AUTOMATICO", "Inserção Automática"),
                    ("MANDADO_JUDICIAL", "Mandado Judicial"),
                    ("DECISAO_ADMINISTRATIVA", "Decisão Administrativa"),
                    ("RECURSO_ADMINISTRATIVO", "Recurso Administrativo"),
                    ("ACORDO_JUDICIAL", "Acordo Judicial"),
                    ("SENTENCA_JUDICIAL", "Sentença Judicial"),
                    ("OUTROS", "Outros Motivos"),
                ],
                default="AUTOMATICO",
                max_length=25,
                verbose_name="Motivo da Inserção",
            ),
        ),
        migrations.AddField(
            model_name="itemquadroacesso",
            name="observacoes_insercao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações da Inserção"
            ),
        ),
    ]
