# Generated by Django 4.2.7 on 2025-07-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0054_itemquadroacesso_data_documento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quadroacesso",
            name="criterio_ordenacao_manual",
        ),
        migrations.RemoveField(
            model_name="quadroacesso",
            name="is_manual",
        ),
        migrations.AlterField(
            model_name="quadroacesso",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ANTIGUIDADE", "Quadro de Acesso por Antiguidade"),
                    ("MERECIMENTO", "Quadro de Acesso por Merecimento"),
                ],
                max_length=15,
                verbose_name="Tipo",
            ),
        ),
    ]
