# Generated by Django 5.2.3 on 2025-07-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0055_remove_is_manual_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichaconceito",
            name="monitor_cas",
            field=models.PositiveIntegerField(default=0, verbose_name="Monitor CAS"),
        ),
        migrations.AddField(
            model_name="fichaconceito",
            name="monitor_cfsd",
            field=models.PositiveIntegerField(default=0, verbose_name="Monitor CFSD"),
        ),
        migrations.AddField(
            model_name="fichaconceito",
            name="monitor_chc",
            field=models.PositiveIntegerField(default=0, verbose_name="Monitor CHC/Cb"),
        ),
        migrations.AddField(
            model_name="fichaconceito",
            name="monitor_cho",
            field=models.PositiveIntegerField(default=0, verbose_name="Monitor CHO"),
        ),
        migrations.AddField(
            model_name="fichaconceito",
            name="monitor_chsgt",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Monitor CHSGT/Sgt"
            ),
        ),
    ]
