# Generated by Django 4.2.7 on 2025-07-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "militares",
            "0056_fichaconceito_monitor_cas_fichaconceito_monitor_cfsd_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichaconceito",
            name="monitor_cas",
        ),
        migrations.RemoveField(
            model_name="fichaconceito",
            name="monitor_cfsd",
        ),
        migrations.RemoveField(
            model_name="fichaconceito",
            name="monitor_chc",
        ),
        migrations.RemoveField(
            model_name="fichaconceito",
            name="monitor_cho",
        ),
        migrations.RemoveField(
            model_name="fichaconceito",
            name="monitor_chsgt",
        ),
        migrations.AddField(
            model_name="fichaconceito",
            name="monitor_csbm",
            field=models.PositiveIntegerField(default=0, verbose_name="Monitor CSBM"),
        ),
    ]
