# Generated by Django 4.2.7 on 2025-07-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0057_update_ficha_conceito_csbm_monitor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichaconceito",
            name="monitor_csbm",
        ),
    ]
