# Generated by Django 4.2.7 on 2025-07-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0058_remove_monitor_csbm"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichaconceito",
            name="categoria",
            field=models.CharField(
                choices=[("OFICIAIS", "Oficiais"), ("PRACAS", "Praças")],
                default="OFICIAIS",
                max_length=10,
                verbose_name="Categoria da Ficha",
            ),
        ),
    ]
