# Generated by Django 4.2.7 on 2025-07-10 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0059_add_categoria_ficha_conceito"),
    ]

    operations = [
        migrations.CreateModel(
            name="FichaConceitoOficiais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tempo_posto",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tempo no Posto (anos)"
                    ),
                ),
                (
                    "cursos_especializacao",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Especialização (militar)"
                    ),
                ),
                (
                    "cursos_csbm",
                    models.PositiveIntegerField(default=0, verbose_name="CSBM"),
                ),
                (
                    "cursos_cfsd",
                    models.PositiveIntegerField(default=0, verbose_name="CFSD"),
                ),
                (
                    "cursos_chc",
                    models.PositiveIntegerField(
                        default=0, verbose_name="CHC ou adaptação a Cb"
                    ),
                ),
                (
                    "cursos_chsgt",
                    models.PositiveIntegerField(
                        default=0, verbose_name="CHSGT ou adaptação a Sgt"
                    ),
                ),
                (
                    "cursos_cas",
                    models.PositiveIntegerField(default=0, verbose_name="CAS"),
                ),
                (
                    "cursos_cho",
                    models.PositiveIntegerField(default=0, verbose_name="CHO"),
                ),
                (
                    "cursos_cfo",
                    models.PositiveIntegerField(default=0, verbose_name="CFO"),
                ),
                (
                    "cursos_cao",
                    models.PositiveIntegerField(default=0, verbose_name="CÃO"),
                ),
                (
                    "cursos_instrutor_csbm",
                    models.PositiveIntegerField(
                        default=0, verbose_name="CSBM (Instrutor)"
                    ),
                ),
                (
                    "cursos_civis_superior",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Superior (civil)"
                    ),
                ),
                (
                    "cursos_civis_especializacao",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Especialização (civil)"
                    ),
                ),
                (
                    "cursos_civis_mestrado",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Mestrado (civil)"
                    ),
                ),
                (
                    "cursos_civis_doutorado",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Doutorado (civil)"
                    ),
                ),
                (
                    "medalha_federal",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Medalha Federal"
                    ),
                ),
                (
                    "medalha_estadual",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Medalha Estadual"
                    ),
                ),
                (
                    "medalha_cbmepi",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Medalha CBMEPI"
                    ),
                ),
                (
                    "elogio_individual",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Elogio Individual"
                    ),
                ),
                (
                    "elogio_coletivo",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Elogio Coletivo"
                    ),
                ),
                (
                    "punicao_repreensao",
                    models.PositiveIntegerField(default=0, verbose_name="Repreensão"),
                ),
                (
                    "punicao_detencao",
                    models.PositiveIntegerField(default=0, verbose_name="Detenção"),
                ),
                (
                    "punicao_prisao",
                    models.PositiveIntegerField(default=0, verbose_name="Prisão"),
                ),
                (
                    "falta_aproveitamento",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="Falta de Aproveitamento em Cursos Militares",
                    ),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Registro"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "pontos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Total de Pontos Calculado",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha de Conceito - Oficiais",
                "verbose_name_plural": "Fichas de Conceito - Oficiais",
                "ordering": ["militar"],
                "unique_together": {("militar",)},
            },
        ),
        migrations.CreateModel(
            name="FichaConceitoPracas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tempo_posto",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tempo no Posto (anos)"
                    ),
                ),
                (
                    "cursos_especializacao",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Especialização (militar)"
                    ),
                ),
                (
                    "cursos_csbm",
                    models.PositiveIntegerField(default=0, verbose_name="CSBM"),
                ),
                (
                    "cursos_cfsd",
                    models.PositiveIntegerField(default=0, verbose_name="CFSD"),
                ),
                (
                    "cursos_chc",
                    models.PositiveIntegerField(
                        default=0, verbose_name="CHC ou adaptação a Cb"
                    ),
                ),
                (
                    "cursos_chsgt",
                    models.PositiveIntegerField(
                        default=0, verbose_name="CHSGT ou adaptação a Sgt"
                    ),
                ),
                (
                    "cursos_cas",
                    models.PositiveIntegerField(default=0, verbose_name="CAS"),
                ),
                (
                    "cursos_civis_superior",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Superior (civil)"
                    ),
                ),
                (
                    "cursos_civis_especializacao",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Especialização (civil)"
                    ),
                ),
                (
                    "cursos_civis_mestrado",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Mestrado (civil)"
                    ),
                ),
                (
                    "cursos_civis_doutorado",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Doutorado (civil)"
                    ),
                ),
                (
                    "medalha_federal",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Medalha Federal"
                    ),
                ),
                (
                    "medalha_estadual",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Medalha Estadual"
                    ),
                ),
                (
                    "medalha_cbmepi",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Medalha CBMEPI"
                    ),
                ),
                (
                    "elogio_individual",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Elogio Individual"
                    ),
                ),
                (
                    "elogio_coletivo",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Elogio Coletivo"
                    ),
                ),
                (
                    "punicao_repreensao",
                    models.PositiveIntegerField(default=0, verbose_name="Repreensão"),
                ),
                (
                    "punicao_detencao",
                    models.PositiveIntegerField(default=0, verbose_name="Detenção"),
                ),
                (
                    "punicao_prisao",
                    models.PositiveIntegerField(default=0, verbose_name="Prisão"),
                ),
                (
                    "falta_aproveitamento",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="Falta de Aproveitamento em Cursos Militares",
                    ),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Registro"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "pontos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Total de Pontos Calculado",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha de Conceito - Praças",
                "verbose_name_plural": "Fichas de Conceito - Praças",
                "ordering": ["militar"],
                "unique_together": {("militar",)},
            },
        ),
        migrations.RemoveField(
            model_name="documento",
            name="ficha_conceito",
        ),
        migrations.DeleteModel(
            name="FichaConceito",
        ),
        migrations.AddField(
            model_name="documento",
            name="ficha_conceito_oficiais",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="militares.fichaconceitooficiais",
                verbose_name="Ficha de Conceito - Oficiais",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="ficha_conceito_pracas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="militares.fichaconceitopracas",
                verbose_name="Ficha de Conceito - Praças",
            ),
        ),
    ]
