# Generated by Django 4.2.7 on 2025-07-10 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0061_add_cursos_civis_tecnico"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichaconceitopracas",
            name="cursos_csbm",
        ),
    ]
