# Generated by Django 4.2.7 on 2025-07-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0062_remove_fichaconceitopracas_cursos_csbm"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichaconceitopracas",
            name="cursos_cho",
            field=models.PositiveIntegerField(default=0, verbose_name="CHO"),
        ),
    ]
