# Generated by Django 5.2.3 on 2025-07-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0063_add_cursos_cho_to_fichaconceitopracas"),
    ]

    operations = [
        migrations.AddField(
            model_name="votodeliberacao",
            name="voto_proferido",
            field=models.TextField(
                blank=True,
                help_text="Texto do voto proferido pelo membro",
                null=True,
                verbose_name="Voto Proferido",
            ),
        ),
    ]
