# Generated by Django 5.2.3 on 2025-07-11 14:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0064_add_voto_proferido_to_votodeliberacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atasessao",
            name="conteudo",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Conteúdo da Ata"
            ),
        ),
        migrations.AlterField(
            model_name="modeloata",
            name="conteudo",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Use variáveis como {{sessao.numero}}, {{sessao.data_sessao}}, {{sessao.local}}, etc.",
                verbose_name="Conteúdo do Modelo",
            ),
        ),
    ]
