# Generated by Django 4.2.7 on 2025-07-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0065_alter_atasessao_conteudo_alter_modeloata_conteudo"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="numeracao_antiguidade_anterior",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numeração de antiguidade que o militar tinha antes de ser inativado",
                null=True,
                verbose_name="Numeração de Antiguidade Anterior",
            ),
        ),
    ]
