# Generated by Django 4.2.7 on 2025-07-15 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("militares", "0067_militar_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioFuncao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_funcao",
                    models.CharField(max_length=100, verbose_name="Nome da Função"),
                ),
                (
                    "tipo_funcao",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("OPERACIONAL", "Operacional"),
                            ("COMISSAO", "Membro de Comissão"),
                            ("GESTAO", "Gestão"),
                            ("SUPORTE", "Suporte Técnico"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Função",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("INATIVO", "Inativo"),
                            ("SUSPENSO", "Suspenso"),
                        ],
                        default="ATIVO",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Término"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Registro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funcoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Função do Usuário",
                "verbose_name_plural": "Funções dos Usuários",
                "ordering": ["usuario__first_name", "data_inicio"],
                "unique_together": {("usuario", "nome_funcao", "data_inicio")},
            },
        ),
    ]
