# Generated by Django 4.2.7 on 2025-07-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0068_usuariofuncao"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoFuncao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Cargo/Função"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo/Função do Sistema",
                "verbose_name_plural": "Cargos/Funções do Sistema",
                "ordering": ["ordem", "nome"],
            },
        ),
    ]
