# Generated by Django 4.2.7 on 2025-07-15 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0070_auto_20250714_2315"),
    ]

    operations = [
        # NOTA: A criação de PermissaoFuncao foi movida para a migração 0140
        # porque ela depende de FuncaoMilitar que só é criado na migração 0138
        migrations.CreateModel(
            name="PerfilAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Perfil"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                # NOTA: O campo permissoes será adicionado na migração 0141
                # porque PermissaoFuncao só é criado na migração 0140
            ],
            options={
                "verbose_name": "Perfil de Acesso",
                "verbose_name_plural": "Perfis de Acesso",
                "ordering": ["nome"],
            },
        ),
    ]
