# Generated by Django 4.2.7 on 2025-07-15 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0071_adicionar_controle_acesso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissaofuncao",
            name="cargo_funcao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissoes",
                to="militares.cargofuncao",
                verbose_name="Cargo/Função",
            ),
        ),
    ]
