# Generated by Django 4.2.7 on 2025-07-15 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0071_adicionar_controle_acesso"),
    ]

    operations = [
        # NOTA: Esta operação foi removida porque PermissaoFuncao só é criado na migração 0140
        # O campo funcao_militar já é criado como opcional (null=True, blank=True) na migração 0140
    ]
