# Generated by Django 4.2.7 on 2025-07-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0072_tornar_cargo_funcao_opcional"),
    ]

    operations = [
        # NOTA: Esta alteração foi removida porque FuncaoMilitar só é criado na migração 0138
        # A alteração será feita na migração 0159_adicionar_funcao_militar_membrocomissao
        # migrations.AlterField(
        #     model_name="membrocomissao",
        #     name="cargo",
        #     field=models.ForeignKey(
        #         on_delete=django.db.models.deletion.PROTECT,
        #         to="militares.funcaomilitar",
        #         verbose_name="Função/Cargo do Usuário",
        #     ),
        # ),
    ]
