# Generated by Django 4.2.7 on 2025-07-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0073_alterar_cargo_membro_comissao"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usuariofuncao",
            unique_together=set(),
        ),
    ]
