# Generated by Django 5.2.3 on 2025-07-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0074_remove_unique_together_usuario_funcao"),
    ]

    operations = [
        migrations.AddField(
            model_name="assinaturaata",
            name="assinatura_digital",
            field=models.TextField(
                blank=True, null=True, verbose_name="Assinatura Digital"
            ),
        ),
        migrations.AddField(
            model_name="assinaturaata",
            name="certificado",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Certificado Digital",
            ),
        ),
        migrations.AddField(
            model_name="assinaturaata",
            name="hash_documento",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Hash do Documento"
            ),
        ),
        migrations.AddField(
            model_name="assinaturaata",
            name="ip_assinatura",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP da Assinatura"
            ),
        ),
        migrations.AddField(
            model_name="assinaturaata",
            name="timestamp",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Timestamp da Assinatura",
            ),
        ),
        migrations.AddField(
            model_name="assinaturaata",
            name="user_agent",
            field=models.TextField(blank=True, null=True, verbose_name="User Agent"),
        ),
    ]
