# Generated by Django 4.2.7 on 2025-07-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0075_add_electronic_signature_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="assinaturaquadroacesso",
            name="funcao_assinatura",
            field=models.CharField(
                blank=True,
                help_text="Função/cargo do usuário no momento da assinatura",
                max_length=100,
                null=True,
                verbose_name="Função no momento da assinatura",
            ),
        ),
    ]
