# Generated by Django 4.2.7 on 2025-07-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0076_add_funcao_assinatura"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="nota_cho",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Nota obtida no Curso de Habilitação de Oficiais (CHO)",
                max_digits=5,
                null=True,
                verbose_name="Nota do CHO",
            ),
        ),
    ]
