# Generated by Django 4.2.7 on 2025-07-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0078_add_nota_chc_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="militar",
            name="nota_chc",
        ),
        migrations.AddField(
            model_name="militar",
            name="nota_chsgt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Nota obtida no Curso de Habilitação de Sargentos (CHSGT)",
                max_digits=5,
                null=True,
                verbose_name="Nota do CHSGT",
            ),
        ),
    ]
