# Generated by Django 4.2.7 on 2025-07-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0079_remove_militar_nota_chc_militar_nota_chsgt"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="nota_chc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Nota obtida no Curso de Habilitação de Cabos (CHC)",
                max_digits=5,
                null=True,
                verbose_name="Nota do CHC",
            ),
        ),
    ]
