# Generated by Django 4.2.7 on 2025-07-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0081_add_funcao_assinatura_quadro_fixacao_vagas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assinaturaquadrofixacaovagas",
            name="tipo_assinatura",
            field=models.CharField(
                choices=[
                    ("APROVACAO", "Aprovação"),
                    ("HOMOLOGACAO", "Homologação"),
                    ("REVISAO", "Revisão"),
                    ("CONFERENCIA", "Conferência"),
                    ("ELETRONICA", "Eletrônica"),
                ],
                default="APROVACAO",
                max_length=15,
                verbose_name="Tipo de Assinatura",
            ),
        ),
    ]
