# Generated by Django 4.2.7 on 2025-07-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0082_add_eletronica_tipo_assinatura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quadrofixacaovagas",
            name="status",
            field=models.CharField(
                choices=[
                    ("RASCUNHO", "Rascunho"),
                    ("EM_ELABORACAO", "Em Elaboração"),
                    ("FINALIZADO", "Finalizado"),
                    ("APROVADO", "Aprovado"),
                    ("HOMOLOGADO", "Homologado"),
                ],
                default="RASCUNHO",
                max_length=15,
                verbose_name="Status",
            ),
        ),
    ]
