# Generated by Django 4.2.7 on 2025-07-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0083_add_homologado_status_quadro_fixacao_vagas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comissaopromocao",
            options={
                "ordering": ["tipo", "-data_criacao"],
                "verbose_name": "Comissão de Promoções",
                "verbose_name_plural": "Comissões de Promoções",
            },
        ),
        migrations.AddField(
            model_name="assinaturaata",
            name="funcao_assinatura",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Função para Assinatura",
            ),
        ),
        migrations.AddField(
            model_name="assinaturaata",
            name="tipo_assinatura",
            field=models.CharField(
                choices=[
                    ("ELABORACAO", "Elaboração"),
                    ("REVISAO", "Revisão"),
                    ("APROVACAO", "Aprovação"),
                    ("HOMOLOGACAO", "Homologação"),
                    ("OUTROS", "Outros"),
                ],
                default="APROVACAO",
                max_length=15,
                verbose_name="Tipo de Assinatura",
            ),
        ),
        migrations.AlterField(
            model_name="comissaopromocao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("CPO", "Comissão de Promoções de Oficiais"),
                    ("CPP", "Comissão de Promoções de Praças"),
                ],
                max_length=3,
                verbose_name="Tipo de Comissão",
            ),
        ),
        migrations.AlterField(
            model_name="modeloata",
            name="tipo_comissao",
            field=models.CharField(
                choices=[
                    ("CPO", "Comissão de Promoções de Oficiais"),
                    ("CPP", "Comissão de Promoções de Praças"),
                    ("GERAL", "Geral (Ambos os tipos)"),
                ],
                default="GERAL",
                max_length=10,
                verbose_name="Tipo de Comissão",
            ),
        ),
        migrations.AlterField(
            model_name="permissaofuncao",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("MILITARES", "Gestão de Militares"),
                    ("FICHAS_CONCEITO", "Fichas de Conceito"),
                    ("QUADROS_ACESSO", "Quadros de Acesso"),
                    ("PROMOCOES", "Promoções"),
                    ("VAGAS", "Gestão de Vagas"),
                    ("COMISSAO", "Comissão de Promoções"),
                    ("DOCUMENTOS", "Documentos"),
                    ("USUARIOS", "Gestão de Usuários"),
                    ("RELATORIOS", "Relatórios"),
                    ("CONFIGURACOES", "Configurações do Sistema"),
                ],
                max_length=20,
                verbose_name="Módulo",
            ),
        ),
    ]
