# Generated by Django 4.2.7 on 2025-07-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0084_alter_comissaopromocao_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="votodeliberacao",
            name="assinado",
            field=models.BooleanField(
                default=False, verbose_name="Assinado Eletronicamente"
            ),
        ),
        migrations.AddField(
            model_name="votodeliberacao",
            name="data_assinatura",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Assinatura Eletrônica"
            ),
        ),
    ]
