# Generated by Django 4.2.7 on 2025-07-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0085_votodeliberacao_assinado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="votodeliberacao",
            name="funcao_assinatura",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Função para Assinatura",
            ),
        ),
        migrations.AddField(
            model_name="votodeliberacao",
            name="observacoes_assinatura",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações da Assinatura"
            ),
        ),
        migrations.AddField(
            model_name="votodeliberacao",
            name="tipo_assinatura",
            field=models.CharField(
                choices=[
                    ("VOTO", "Voto"),
                    ("APROVACAO", "Aprovação"),
                    ("REVISAO", "Revisão"),
                    ("OUTROS", "Outros"),
                ],
                default="VOTO",
                max_length=15,
                verbose_name="Tipo de Assinatura",
            ),
        ),
    ]
