# Generated by Django 4.2.7 on 2025-07-21 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0087_alter_intersticio_posto_alter_intersticio_quadro_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarioPromocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ano",
                    models.CharField(
                        choices=[
                            ("2020", "2020"),
                            ("2021", "2021"),
                            ("2022", "2022"),
                            ("2023", "2023"),
                            ("2024", "2024"),
                            ("2025", "2025"),
                            ("2026", "2026"),
                            ("2027", "2027"),
                            ("2028", "2028"),
                            ("2029", "2029"),
                            ("2030", "2030"),
                        ],
                        max_length=4,
                        verbose_name="Ano",
                    ),
                ),
                (
                    "semestre",
                    models.CharField(
                        choices=[("1", "1º Semestre"), ("2", "2º Semestre")],
                        max_length=1,
                        verbose_name="Semestre",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendário de Promoção",
                "verbose_name_plural": "Calendários de Promoção",
                "ordering": ["-ano", "-semestre"],
                "unique_together": {("ano", "semestre")},
            },
        ),
        migrations.CreateModel(
            name="ItemCalendarioPromocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_atividade",
                    models.CharField(
                        choices=[
                            ("FIXACAO_VAGAS", "Fixação de vagas (DGP/CBMEPI)"),
                            (
                                "ENCAMINHAMENTO_FICHAS",
                                "Encaminhamento das fichas de assentamentos e Fichas de Conceito da Praça",
                            ),
                            ("INSPECAO_SAUDE", "Inspeção de Saúde"),
                            ("PUBLICACAO_INSPECAO", "Publicação da Inspeção de Saúde"),
                            (
                                "PRAZO_RECURSO_INSPECAO",
                                "Prazo para interposição de recurso da Inspeção de Saúde",
                            ),
                            (
                                "ANALISE_RECURSO_INSPECAO",
                                "Prazo para análise de interposição de recurso da Inspeção de Saúde",
                            ),
                            (
                                "INSPECAO_RECURSOS",
                                "Prazo para Inspeção de Saúde de recursos deferidos",
                            ),
                            (
                                "PUBLICACAO_RECURSOS",
                                "Publicação da Inspeção de Saúde de recursos deferidos",
                            ),
                            (
                                "ANALISE_QUADRO",
                                "Análise e aprovação do Quadro de Acesso",
                            ),
                            ("PUBLICACAO_QUADRO", "Publicação do Quadro de Acesso"),
                            (
                                "PRAZO_RECURSO_QUADRO",
                                "Prazo para interposição de recurso do Quadro de Acesso",
                            ),
                            (
                                "ANALISE_RECURSO_QUADRO",
                                "Prazo para análise de interposição de recurso do Quadro de Acesso",
                            ),
                            (
                                "ANALISE_ALTERACOES",
                                "Análise e aprovação das alterações do Quadro de Acesso",
                            ),
                            (
                                "PUBLICACAO_ALTERACOES",
                                "Publicação das alterações do Quadro de Acesso",
                            ),
                            (
                                "PROPOSTA_PROMOCAO",
                                "Encaminhamento da Proposta de Promoção",
                            ),
                            ("DATA_PROMOCAO", "Data da Promoção"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Atividade",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_fim", models.DateField(verbose_name="Data de Fim")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "calendario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="militares.calendariopromocao",
                        verbose_name="Calendário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Calendário de Promoção",
                "verbose_name_plural": "Itens do Calendário de Promoção",
                "ordering": ["calendario", "ordem"],
                "unique_together": {("calendario", "tipo_atividade")},
            },
        ),
    ]
