# Generated by Django 4.2.7 on 2025-07-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0088_calendariopromocao_itemcalendariopromocao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendariopromocao",
            options={
                "ordering": ["-ano", "-semestre", "tipo"],
                "verbose_name": "Calendário de Promoção",
                "verbose_name_plural": "Calendários de Promoção",
            },
        ),
        migrations.AlterUniqueTogether(
            name="calendariopromocao",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="calendariopromocao",
            name="tipo",
            field=models.CharField(
                choices=[("OFICIAIS", "Oficiais"), ("PRACAS", "Praças")],
                default="OFICIAIS",
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="calendariopromocao",
            unique_together={("ano", "semestre", "tipo")},
        ),
    ]
