# Generated by Django 4.2.7 on 2025-07-21 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("militares", "0089_add_calendario_promocao_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendariopromocao",
            options={
                "ordering": ["-ano", "-semestre", "tipo", "-data_criacao"],
                "verbose_name": "Calendário de Promoção",
                "verbose_name_plural": "Calendários de Promoção",
            },
        ),
        migrations.AlterUniqueTogether(
            name="calendariopromocao",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="calendariopromocao",
            name="aprovado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calendarios_aprovados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprovado por",
            ),
        ),
        migrations.AddField(
            model_name="calendariopromocao",
            name="data_aprovacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Aprovação"
            ),
        ),
        migrations.AddField(
            model_name="calendariopromocao",
            name="data_homologacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Homologação"
            ),
        ),
        migrations.AddField(
            model_name="calendariopromocao",
            name="homologado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calendarios_homologados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Homologado por",
            ),
        ),
        migrations.AddField(
            model_name="calendariopromocao",
            name="numero",
            field=models.CharField(
                blank=True,
                help_text="Numeração automática e única, ex: CAL-OF-2025/1 ou CAL-OF-2025/1-A01",
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Numeração do Calendário",
            ),
        ),
        migrations.AddField(
            model_name="calendariopromocao",
            name="status",
            field=models.CharField(
                choices=[
                    ("RASCUNHO", "Rascunho"),
                    ("EM_ELABORACAO", "Em Elaboração"),
                    ("APROVADO", "Aprovado"),
                    ("HOMOLOGADO", "Homologado"),
                ],
                default="RASCUNHO",
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="itemcalendariopromocao",
            name="tipo_atividade",
            field=models.CharField(
                choices=[
                    ("FIXACAO_VAGAS", "Fixação de vagas (DGP/CBMEPI)"),
                    (
                        "ENCAMINHAMENTO_FICHAS",
                        "Atualização das fichas de conceito e assentamentos",
                    ),
                    ("INSPECAO_SAUDE", "Inspeção de Saúde"),
                    ("PUBLICACAO_INSPECAO", "Publicação da Inspeção de Saúde"),
                    (
                        "PRAZO_RECURSO_INSPECAO",
                        "Prazo para interposição de recurso da Inspeção de Saúde",
                    ),
                    (
                        "ANALISE_RECURSO_INSPECAO",
                        "Prazo para análise de interposição de recurso da Inspeção de Saúde",
                    ),
                    (
                        "INSPECAO_RECURSOS",
                        "Prazo para Inspeção de Saúde de recursos deferidos",
                    ),
                    (
                        "PUBLICACAO_RECURSOS",
                        "Publicação da Inspeção de Saúde de recursos deferidos",
                    ),
                    ("ANALISE_QUADRO", "Análise e aprovação do Quadro de Acesso"),
                    ("PUBLICACAO_QUADRO", "Publicação do Quadro de Acesso"),
                    (
                        "PRAZO_RECURSO_QUADRO",
                        "Prazo para interposição de recurso do Quadro de Acesso",
                    ),
                    (
                        "ANALISE_RECURSO_QUADRO",
                        "Prazo para análise de interposição de recurso do Quadro de Acesso",
                    ),
                    (
                        "ANALISE_ALTERACOES",
                        "Análise e aprovação das alterações do Quadro de Acesso",
                    ),
                    (
                        "PUBLICACAO_ALTERACOES",
                        "Publicação das alterações do Quadro de Acesso",
                    ),
                    ("PROPOSTA_PROMOCAO", "Encaminhamento da Proposta de Promoção"),
                    ("DATA_PROMOCAO", "Data da Promoção"),
                ],
                max_length=50,
                verbose_name="Tipo de Atividade",
            ),
        ),
    ]
