# Generated by Django 4.2.7 on 2025-07-22 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("militares", "0090_alter_calendariopromocao_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssinaturaCalendarioPromocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_assinatura",
                    models.CharField(
                        choices=[
                            ("ELABORACAO", "Elaboração"),
                            ("REVISAO", "Revisão"),
                            ("APROVACAO", "Aprovação"),
                            ("HOMOLOGACAO", "Homologação"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Assinatura",
                    ),
                ),
                (
                    "data_assinatura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Assinatura"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "hash_assinatura",
                    models.CharField(max_length=255, verbose_name="Hash da Assinatura"),
                ),
                (
                    "codigo_verificacao",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código de Verificação"
                    ),
                ),
                (
                    "assinado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assinado por",
                    ),
                ),
                (
                    "calendario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to="militares.calendariopromocao",
                        verbose_name="Calendário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura de Calendário de Promoção",
                "verbose_name_plural": "Assinaturas de Calendários de Promoção",
                "ordering": ["-data_assinatura"],
            },
        ),
    ]
