# Generated by Django 4.2.7 on 2025-07-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0091_assinaturacalendariopromocao"),
    ]

    operations = [
        migrations.AddField(
            model_name="assinaturacalendariopromocao",
            name="funcao_assinatura",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Função para Assinatura",
            ),
        ),
    ]
