# Generated by Django 5.2.3 on 2025-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0092_assinaturacalendariopromocao_funcao_assinatura"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="funcao_assinatura",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Função para Assinatura",
            ),
        ),
    ]
