# Generated by Django 5.2.3 on 2025-07-22 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0096_add_funcao_assinatura_documento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlmanaqueMilitar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("OFICIAIS", "Oficiais"),
                            ("PRACAS", "Praças"),
                            ("GERAL", "Geral"),
                        ],
                        default="GERAL",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "data_geracao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Geração"
                    ),
                ),
                (
                    "arquivo_pdf",
                    models.FileField(
                        upload_to="almanaques/", verbose_name="Arquivo PDF"
                    ),
                ),
                (
                    "total_oficiais",
                    models.IntegerField(default=0, verbose_name="Total de Oficiais"),
                ),
                (
                    "total_pracas",
                    models.IntegerField(default=0, verbose_name="Total de Praças"),
                ),
                (
                    "total_geral",
                    models.IntegerField(default=0, verbose_name="Total Geral"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Almanaque Militar",
                "verbose_name_plural": "Almanaques Militares",
                "ordering": ["-data_geracao"],
            },
        ),
        migrations.CreateModel(
            name="AssinaturaAlmanaque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo_funcao",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Cargo/Função",
                    ),
                ),
                (
                    "data_assinatura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Assinatura"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "almanaque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.almanaquemilitar",
                        verbose_name="Almanaque",
                    ),
                ),
                (
                    "assinado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assinado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura de Almanaque",
                "verbose_name_plural": "Assinaturas de Almanaques",
                "ordering": ["data_assinatura"],
                "unique_together": {("almanaque", "assinado_por")},
            },
        ),
    ]
