# Generated by Django 4.2.7 on 2025-07-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0097_almanaquemilitar_assinaturaalmanaque"),
    ]

    operations = [
        migrations.AddField(
            model_name="almanaquemilitar",
            name="conteudo_html",
            field=models.TextField(blank=True, null=True, verbose_name="Conteúdo HTML"),
        ),
    ]
