# Generated by Django 4.2.7 on 2025-07-24 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("militares", "0099_almanaquemilitar_conteudo_html"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assinaturaalmanaque",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="almanaquemilitar",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="almanaquemilitar",
            name="data_atualizacao",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AddField(
            model_name="almanaquemilitar",
            name="numero",
            field=models.CharField(
                blank=True,
                help_text="Numeração automática e única, ex: ALM-OF-2025/07/23 ou ALM-PR-2025/07/23",
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Numeração do Almanaque",
            ),
        ),
        migrations.AddField(
            model_name="almanaquemilitar",
            name="status",
            field=models.CharField(
                choices=[
                    ("RASCUNHO", "Rascunho"),
                    ("EM_ELABORACAO", "Em Elaboração"),
                    ("FINALIZADO", "Finalizado"),
                    ("APROVADO", "Aprovado"),
                    ("HOMOLOGADO", "Homologado"),
                ],
                default="RASCUNHO",
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="assinaturaalmanaque",
            name="tipo_assinatura",
            field=models.CharField(
                choices=[
                    ("APROVACAO", "Aprovação"),
                    ("HOMOLOGACAO", "Homologação"),
                    ("REVISAO", "Revisão"),
                    ("CONFERENCIA", "Conferência"),
                    ("ELETRONICA", "Eletrônica"),
                ],
                default="APROVACAO",
                max_length=15,
                verbose_name="Tipo de Assinatura",
            ),
        ),
        migrations.AlterField(
            model_name="almanaquemilitar",
            name="arquivo_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="almanaques/",
                verbose_name="Arquivo PDF",
            ),
        ),
        migrations.AlterField(
            model_name="assinaturaalmanaque",
            name="almanaque",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assinaturas",
                to="militares.almanaquemilitar",
                verbose_name="Almanaque",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assinaturaalmanaque",
            unique_together={("almanaque", "assinado_por", "tipo_assinatura")},
        ),
    ]
