# Generated by Django 4.2.7 on 2025-07-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0100_alter_assinaturaalmanaque_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="almanaquemilitar",
            name="data_ultima_promocao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Última Promoção"
            ),
        ),
    ]
