# Generated by Django 5.2.3 on 2025-07-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0101_add_data_ultima_promocao_almanaque"),
    ]

    operations = [
        # NOTA: AlterField de permissaofuncao removido - modelo só é criado na migração 0140
        # migrations.AlterField(
        #     model_name="permissaofuncao",
        #     name="modulo",
        #     field=models.CharField(
        #         choices=[...],
        #         max_length=20,
        #         verbose_name="Módulo",
        #     ),
        # ),
    ]
