# Generated by Django 5.2.3 on 2025-07-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0101_add_data_ultima_promocao_almanaque"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissaofuncao",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("MILITARES", "Militares"),
                    ("FICHAS_CONCEITO", "Fichas Conceito"),
                    ("QUADROS_ACESSO", "Quadros Acesso"),
                    ("PROMOCOES", "Promocoes"),
                    ("VAGAS", "Vagas"),
                    ("COMISSAO", "Comissao"),
                    ("DOCUMENTOS", "Documentos"),
                    ("USUARIOS", "Usuarios"),
                    ("RELATORIOS", "Relatorios"),
                    ("CONFIGURACOES", "Configuracoes"),
                    ("ALMANAQUES", "Almanaques"),
                    ("CALENDARIOS", "Calendarios"),
                    ("NOTIFICACOES", "Notificacoes"),
                    ("MODELOS_ATA", "Modelos Ata"),
                    ("CARGOS_COMISSAO", "Cargos Comissao"),
                    ("QUADROS_FIXACAO", "Quadros Fixacao"),
                    ("ASSINATURAS", "Assinaturas"),
                    ("ESTATISTICAS", "Estatisticas"),
                    ("EXPORTACAO", "Exportacao"),
                    ("IMPORTACAO", "Importacao"),
                    ("BACKUP", "Backup"),
                    ("AUDITORIA", "Auditoria"),
                    ("DASHBOARD", "Dashboard"),
                    ("BUSCA", "Busca"),
                    ("AJAX", "Ajax"),
                    ("API", "Api"),
                    ("SESSAO", "Sessao"),
                    ("FUNCAO", "Funcao"),
                    ("PERFIL", "Perfil"),
                    ("SISTEMA", "Sistema"),
                ],
                max_length=20,
                verbose_name="Módulo",
            ),
        ),
    ]
