# Generated by Django 5.2.3 on 2025-08-05 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0102_adicionar_modulos_permissao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("INFO", "Informação"),
                            ("WARNING", "Aviso"),
                            ("ERROR", "Erro"),
                            ("CRITICAL", "Crítico"),
                            ("DEBUG", "Debug"),
                        ],
                        default="INFO",
                        max_length=10,
                        verbose_name="Nível",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("MILITARES", "Militares"),
                            ("FICHAS_CONCEITO", "Fichas Conceito"),
                            ("QUADROS_ACESSO", "Quadros Acesso"),
                            ("PROMOCOES", "Promoções"),
                            ("VAGAS", "Vagas"),
                            ("COMISSAO", "Comissão"),
                            ("DOCUMENTOS", "Documentos"),
                            ("USUARIOS", "Usuários"),
                            ("RELATORIOS", "Relatórios"),
                            ("CONFIGURACOES", "Configurações"),
                            ("ALMANAQUES", "Almanaques"),
                            ("CALENDARIOS", "Calendários"),
                            ("NOTIFICACOES", "Notificações"),
                            ("MODELOS_ATA", "Modelos Ata"),
                            ("CARGOS_COMISSAO", "Cargos Comissão"),
                            ("QUADROS_FIXACAO", "Quadros Fixação"),
                            ("ASSINATURAS", "Assinaturas"),
                            ("ESTATISTICAS", "Estatísticas"),
                            ("EXPORTACAO", "Exportação"),
                            ("IMPORTACAO", "Importação"),
                            ("BACKUP", "Backup"),
                            ("AUDITORIA", "Auditoria"),
                            ("DASHBOARD", "Dashboard"),
                            ("BUSCA", "Busca"),
                            ("AJAX", "Ajax"),
                            ("API", "Api"),
                            ("SESSAO", "Sessão"),
                            ("FUNCAO", "Função"),
                            ("PERFIL", "Perfil"),
                            ("SISTEMA", "Sistema"),
                            ("AUTENTICIDADE", "Verificação de Autenticidade"),
                            ("LOGIN", "Login/Logout"),
                            ("SEGURANCA", "Segurança"),
                            ("PERMISSOES", "Permissões"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Módulo",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("CRIAR", "Criar"),
                            ("EDITAR", "Editar"),
                            ("EXCLUIR", "Excluir"),
                            ("VISUALIZAR", "Visualizar"),
                            ("LISTAR", "Listar"),
                            ("BUSCAR", "Buscar"),
                            ("FILTRAR", "Filtrar"),
                            ("EXPORTAR", "Exportar"),
                            ("IMPORTAR", "Importar"),
                            ("APROVAR", "Aprovar"),
                            ("REPROVAR", "Reprovar"),
                            ("HOMOLOGAR", "Homologar"),
                            ("DESHOMOLOGAR", "Deshomologar"),
                            ("ASSINAR", "Assinar"),
                            ("GERAR_PDF", "Gerar PDF"),
                            ("IMPRIMIR", "Imprimir"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("ALTERAR_SENHA", "Alterar Senha"),
                            ("RESETAR_SENHA", "Resetar Senha"),
                            ("ATRIBUIR_PERMISSAO", "Atribuir Permissão"),
                            ("REMOVER_PERMISSAO", "Remover Permissão"),
                            ("ATIVAR", "Ativar"),
                            ("INATIVAR", "Inativar"),
                            ("BACKUP", "Backup"),
                            ("RESTAURAR", "Restaurar"),
                            ("VERIFICAR_AUTENTICIDADE", "Verificar Autenticidade"),
                            ("GERAR_CODIGO", "Gerar Código"),
                            ("VALIDAR_CODIGO", "Validar Código"),
                            ("ENVIAR_EMAIL", "Enviar Email"),
                            ("ENVIAR_NOTIFICACAO", "Enviar Notificação"),
                            ("PROCESSAR_ARQUIVO", "Processar Arquivo"),
                            ("EXECUTAR_COMANDO", "Executar Comando"),
                            ("ATUALIZAR_DADOS", "Atualizar Dados"),
                            ("SINCRONIZAR", "Sincronizar"),
                            ("CALCULAR", "Calcular"),
                            ("VALIDAR", "Validar"),
                            ("PROCESSAR", "Processar"),
                            ("ANALISAR", "Analisar"),
                            ("CONFIGURAR", "Configurar"),
                            ("TESTAR", "Testar"),
                            ("MONITORAR", "Monitorar"),
                            ("LIMPAR", "Limpar"),
                            ("ORDENAR", "Ordenar"),
                            ("REORDENAR", "Reordenar"),
                            ("MIGRAR", "Migrar"),
                            ("CONVERTER", "Converter"),
                            ("CORRIGIR", "Corrigir"),
                            ("RESTAURAR", "Restaurar"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=30,
                        verbose_name="Ação",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "detalhes",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Detalhes Adicionais"
                    ),
                ),
                (
                    "modelo_afetado",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Modelo Afetado",
                    ),
                ),
                (
                    "objeto_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID do Objeto",
                    ),
                ),
                (
                    "objeto_str",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Representação do Objeto",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "metodo_http",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Método HTTP"
                    ),
                ),
                (
                    "tempo_execucao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Tempo de Execução (segundos)",
                    ),
                ),
                ("erro", models.TextField(blank=True, null=True, verbose_name="Erro")),
                (
                    "traceback",
                    models.TextField(blank=True, null=True, verbose_name="Traceback"),
                ),
                (
                    "processado",
                    models.BooleanField(default=False, verbose_name="Processado"),
                ),
                (
                    "notificado",
                    models.BooleanField(default=False, verbose_name="Notificado"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_sistema",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log do Sistema",
                "verbose_name_plural": "Logs do Sistema",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="militares_l_timesta_3f48eb_idx"
                    ),
                    models.Index(fields=["nivel"], name="militares_l_nivel_390b36_idx"),
                    models.Index(
                        fields=["modulo"], name="militares_l_modulo_6dbfda_idx"
                    ),
                    models.Index(fields=["acao"], name="militares_l_acao_540132_idx"),
                    models.Index(
                        fields=["usuario"], name="militares_l_usuario_3c3df8_idx"
                    ),
                    models.Index(
                        fields=["modelo_afetado"], name="militares_l_modelo__7e1178_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="militares_l_ip_addr_5cdae1_idx"
                    ),
                ],
            },
        ),
    ]
