# Generated by Django 4.2.7 on 2025-08-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0103_add_log_sistema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocao",
            name="criterio",
            field=models.CharField(
                choices=[
                    ("ANTIGUIDADE", "Antiguidade"),
                    ("MERECIMENTO", "Merecimento"),
                    ("POST_MORTEM", "Post Mortem"),
                    ("RESSARCIMENTO", "Ressarcimento de Preterição"),
                    ("CONDICOES_ESPECIAIS", "Condições Especiais"),
                ],
                max_length=20,
                verbose_name="Critério",
            ),
        ),
    ]
