# Generated by Django 5.0.2 on 2025-08-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0104_add_condicoes_especiais_criterio"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendariopromocao",
            name="permanente",
            field=models.BooleanField(
                default=False,
                help_text="Se marcado, este calendário será válido para todos os anos futuros",
                verbose_name="Calendário Permanente",
            ),
        ),
    ]
