# Generated by Django 5.0.2 on 2025-08-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0105_calendariopromocao_permanente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendariopromocao",
            name="ano",
            field=models.CharField(
                choices=[
                    ("2020", "2020"),
                    ("2021", "2021"),
                    ("2022", "2022"),
                    ("2023", "2023"),
                    ("2024", "2024"),
                    ("2025", "2025"),
                    ("2026", "2026"),
                    ("2027", "2027"),
                    ("2028", "2028"),
                    ("2029", "2029"),
                    ("2030", "2030"),
                    ("CUSTOM", "Ano Personalizado"),
                ],
                max_length=10,
                verbose_name="Ano",
            ),
        ),
    ]
