# Generated by Django 5.0.2 on 2025-08-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0106_alter_calendariopromocao_ano"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendariopromocao",
            name="permanente",
        ),
    ]
