# Generated by Django 5.0.2 on 2025-08-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0107_remove_permanente_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocao",
            name="numero_ato",
            field=models.CharField(max_length=200, verbose_name="Número do Ato"),
        ),
    ]
