# Generated by Django 5.0.2 on 2025-08-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0108_alter_numero_ato_max_length"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fichaconceitooficiais",
            old_name="tempo_posto",
            new_name="tempo_posto_anos",
        ),
        migrations.RenameField(
            model_name="fichaconceitopracas",
            old_name="tempo_posto",
            new_name="tempo_posto_anos",
        ),
        migrations.AddField(
            model_name="fichaconceitooficiais",
            name="tempo_posto_dias",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tempo no Posto (dias)"
            ),
        ),
        migrations.AddField(
            model_name="fichaconceitooficiais",
            name="tempo_posto_meses",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tempo no Posto (meses)"
            ),
        ),
        migrations.AddField(
            model_name="fichaconceitopracas",
            name="tempo_posto_dias",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tempo no Posto (dias)"
            ),
        ),
        migrations.AddField(
            model_name="fichaconceitopracas",
            name="tempo_posto_meses",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tempo no Posto (meses)"
            ),
        ),
    ]
