# Generated by Django 5.0.2 on 2025-08-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "militares",
            "0109_rename_tempo_posto_fichaconceitooficiais_tempo_posto_anos_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="promocao",
            name="is_historica",
            field=models.BooleanField(
                default=False,
                help_text="Se marcado, esta promoção não altera o posto atual do militar",
                verbose_name="Promoção Histórica",
            ),
        ),
    ]
