# Generated by Django 5.0.2 on 2025-08-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0110_promocao_is_historica"),
    ]

    operations = [
        # NOTA: AlterField de permissaofuncao removido - modelo só é criado na migração 0140
        # migrations.AlterField(
        #     model_name="permissaofuncao",
        #     name="acesso",
        #     field=models.CharField(
        #         choices=[...],
        #         max_length=25,
        #         verbose_name="Tipo de Acesso",
        #     ),
        # ),
    ]
