# Generated by Django 5.0.2 on 2025-08-29 23:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0111_aumentar_tamanho_campo_acesso"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medalha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                (
                    "nome",
                    models.CharField(max_length=120, verbose_name="Nome da Medalha"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("HONRA", "Medalha de Honra (Ex.: Imperador Dom Pedro II)"),
                            ("TEMPO_SERVICO", "Medalha de Tempo de Serviço"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "grau_tempo_servico",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BRONZE_10", "Bronze - 10 anos"),
                            ("PRATA_20", "Prata - 20 anos"),
                            ("OURO_30", "Ouro - 30 anos"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Grau (Tempo de Serviço)",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "publico_alvo_padrao",
                    models.CharField(
                        choices=[
                            ("BOMBEIRO_MILITAR", "Bombeiro Militar (CBMEPI)"),
                            ("MILITAR_FFAA", "Militar das Forças Armadas"),
                            ("MILITAR_COIRMA", "Militar de Instituição Coirmã"),
                            ("CIVIL", "Personalidade Civil"),
                        ],
                        default="BOMBEIRO_MILITAR",
                        max_length=20,
                        verbose_name="Público-Alvo Padrão",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativa")),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Medalha",
                "verbose_name_plural": "Medalhas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ConcessaoMedalha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria_externa",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BOMBEIRO_MILITAR", "Bombeiro Militar (CBMEPI)"),
                            ("MILITAR_FFAA", "Militar das Forças Armadas"),
                            ("MILITAR_COIRMA", "Militar de Instituição Coirmã"),
                            ("CIVIL", "Personalidade Civil"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Categoria Externa",
                    ),
                ),
                (
                    "nome_externo",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nome do Agraciado Externo",
                    ),
                ),
                (
                    "documento_externo",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Documento (CPF/RG ou similar)",
                    ),
                ),
                (
                    "orgao_externo",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Órgão/Instituição",
                    ),
                ),
                (
                    "data_concessao",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data da Concessão",
                    ),
                ),
                (
                    "portaria_numero",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Nº da Portaria/Boletim",
                    ),
                ),
                (
                    "portaria_data",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Portaria"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concessoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medalhas_recebidas",
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
                (
                    "medalha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concessoes",
                        to="militares.medalha",
                        verbose_name="Medalha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concessão de Medalha",
                "verbose_name_plural": "Concessões de Medalhas",
                "indexes": [
                    models.Index(
                        fields=["medalha", "data_concessao"],
                        name="militares_c_medalha_1b29b6_idx",
                    ),
                    models.Index(
                        fields=["militar", "medalha"],
                        name="militares_c_militar_8e161e_idx",
                    ),
                ],
            },
        ),
    ]
