# Generated by Django 5.0.2 on 2025-08-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0112_medalha_concessaomedalha"),
    ]

    operations = [
        migrations.AddField(
            model_name="concessaomedalha",
            name="documento_tipo",
            field=models.CharField(
                choices=[
                    ("PORTARIA", "Portaria"),
                    ("BOLETIM", "Boletim"),
                    ("DOE_PI", "DOE-PI"),
                ],
                default="PORTARIA",
                max_length=10,
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="concessaomedalha",
            name="portaria_numero",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Nº do Documento"
            ),
        ),
    ]
