# Generated by Django 5.0.2 on 2025-08-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0113_concessaomedalha_documento_tipo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="concessaomedalha",
            name="indicado_por_funcao",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Função de quem indicou",
            ),
        ),
        migrations.AddField(
            model_name="concessaomedalha",
            name="indicado_por_nome",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Indicado por"
            ),
        ),
    ]
