# Generated by Django 5.0.2 on 2025-08-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0114_concessaomedalha_indicado_por_funcao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="concessaomedalha",
            name="forca_externa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FAB", "Força Aérea Brasileira"),
                    ("EB", "Exército Brasileiro"),
                    ("MB", "Marinha do Brasil"),
                    ("PM", "Polícia Militar (Coirmã)"),
                    ("CBM", "Corpo de Bombeiros Militar (Coirmã)"),
                    ("PC", "Polícia Civil"),
                    ("OUTRA", "Outra Instituição"),
                ],
                max_length=10,
                null=True,
                verbose_name="Força/Instituição (externo)",
            ),
        ),
        migrations.AddField(
            model_name="concessaomedalha",
            name="funcao_externa",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Função (civil)"
            ),
        ),
        migrations.AddField(
            model_name="concessaomedalha",
            name="posto_graduacao_externo",
            field=models.CharField(
                blank=True,
                max_length=80,
                null=True,
                verbose_name="Posto/Graduação (externo)",
            ),
        ),
        migrations.AddField(
            model_name="concessaomedalha",
            name="uf_externa",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="UF (coirmã)"
            ),
        ),
    ]
