# Generated by Django 5.0.2 on 2025-08-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0115_concessaomedalha_forca_externa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concessaomedalha",
            name="funcao_externa",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Cargo/Função"
            ),
        ),
    ]
