# Generated by Django 5.0.2 on 2025-08-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0116_alter_concessaomedalha_funcao_externa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concessaomedalha",
            name="documento_externo",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="CPF"
            ),
        ),
        migrations.AlterField(
            model_name="concessaomedalha",
            name="forca_externa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FAB", "Força Aérea Brasileira"),
                    ("EB", "Exército Brasileiro"),
                    ("MB", "Marinha do Brasil"),
                    ("PM", "Polícia Militar"),
                    ("CBM", "Corpo de Bombeiros Militar"),
                ],
                max_length=10,
                null=True,
                verbose_name="Força/Instituição (externo)",
            ),
        ),
    ]
