# Generated by Django 5.0.2 on 2025-08-30 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0117_alter_concessaomedalha_documento_externo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="concessaomedalha",
            name="cancelado",
            field=models.BooleanField(default=False, verbose_name="Cancelado"),
        ),
        migrations.AddField(
            model_name="concessaomedalha",
            name="cancelado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Cancelado em"
            ),
        ),
        migrations.AddField(
            model_name="concessaomedalha",
            name="cancelado_motivo",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motivo do Cancelamento"
            ),
        ),
        migrations.AddField(
            model_name="concessaomedalha",
            name="cancelado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="concessoes_canceladas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cancelado por",
            ),
        ),
    ]
