# Generated by Django 5.0.2 on 2025-08-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0118_concessaomedalha_cancelado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concessaomedalha",
            name="portaria_data",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Publicação"
            ),
        ),
    ]
