# Generated by Django 5.0.2 on 2025-08-30 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0119_alter_concessaomedalha_portaria_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="concessaomedalha",
            name="outorgada_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Outorgada em"
            ),
        ),
        migrations.AddField(
            model_name="concessaomedalha",
            name="outorgada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="concessoes_outorgadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Outorgada por",
            ),
        ),
        migrations.AddField(
            model_name="concessaomedalha",
            name="status",
            field=models.CharField(
                choices=[("PROPOSTA", "Proposta"), ("OUTORGADA", "Outorgada")],
                default="PROPOSTA",
                max_length=12,
                verbose_name="Status",
            ),
        ),
    ]
