# Generated by Django 5.0.2 on 2025-08-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0121_alter_concessaomedalha_documento_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concessaomedalha",
            name="documento_tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PORTARIA", "Portaria"),
                    ("BOLETIM", "Boletim"),
                    ("DOE_PI", "DOE-PI"),
                ],
                max_length=10,
                null=True,
                verbose_name="Ato",
            ),
        ),
    ]
