# Generated by Django 5.0.2 on 2025-08-30 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0122_alter_concessaomedalha_documento_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropostaMedalha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_proposta",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número da Proposta"
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        default="PROPOSTA PARA CONCESSÃO DA OUTORGA DE MEDALHA 'IMPERADOR DOM PEDRO II'",
                        max_length=200,
                        verbose_name="Título da Proposta",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("ENVIADA", "Enviada"),
                            ("APROVADA", "Aprovada"),
                            ("REJEITADA", "Rejeitada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "aprovado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Aprovação"
                    ),
                ),
                (
                    "observacoes_aprovacao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações da Aprovação"
                    ),
                ),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="propostas_aprovadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "concessoes",
                    models.ManyToManyField(
                        to="militares.concessaomedalha",
                        verbose_name="Concessões Selecionadas",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposta de Medalha",
                "verbose_name_plural": "Propostas de Medalhas",
                "ordering": ["-criado_em"],
            },
        ),
    ]
