# Generated by Django 5.0.2 on 2025-08-30 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0124_add_assinatura_concessao_medalha"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssinaturaPropostaMedalha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_assinatura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Assinatura"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações da Assinatura"
                    ),
                ),
                (
                    "tipo_assinatura",
                    models.CharField(
                        choices=[
                            ("APROVACAO", "Aprovação"),
                            ("HOMOLOGACAO", "Homologação"),
                            ("REVISAO", "Revisão"),
                            ("CONFERENCIA", "Conferência"),
                            ("ELETRONICA", "Eletrônica"),
                        ],
                        default="APROVACAO",
                        max_length=15,
                        verbose_name="Tipo de Assinatura",
                    ),
                ),
                (
                    "funcao_assinatura",
                    models.CharField(
                        blank=True,
                        help_text="Função/cargo do usuário no momento da assinatura",
                        max_length=100,
                        null=True,
                        verbose_name="Função no momento da assinatura",
                    ),
                ),
                (
                    "assinado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assinado por",
                    ),
                ),
                (
                    "proposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to="militares.propostamedalha",
                        verbose_name="Proposta de Medalha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura da Proposta de Medalha",
                "verbose_name_plural": "Assinaturas das Propostas de Medalhas",
                "ordering": ["-data_assinatura"],
                "unique_together": {("proposta", "assinado_por", "tipo_assinatura")},
            },
        ),
    ]
