# Generated by Django 5.0.2 on 2025-09-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0125_add_assinatura_proposta_medalha"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="agencia",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Agência"
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="banco_codigo",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Código do Banco"
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="banco_nome",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nome do Banco"
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="cnh_categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("AB", "AB"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("ACC", "ACC"),
                ],
                max_length=3,
                null=True,
                verbose_name="Categoria da CNH",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="cnh_numero",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Número da CNH"
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="cnh_validade",
            field=models.DateField(
                blank=True, null=True, verbose_name="Validade da CNH"
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="conta",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Conta"
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="etnia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BRANCA", "Branca"),
                    ("PRETA", "Preta"),
                    ("PARDA", "Parda"),
                    ("AMARELA", "Amarela"),
                    ("INDIGENA", "Indígena"),
                    ("NAO_INFORMADO", "Não informado"),
                ],
                max_length=20,
                null=True,
                verbose_name="Etnia",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="fator_rh",
            field=models.CharField(
                blank=True,
                choices=[("POSITIVO", "Positivo"), ("NEGATIVO", "Negativo")],
                max_length=10,
                null=True,
                verbose_name="Fator Rh",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="grupo_sanguineo",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("AB", "AB"), ("O", "O")],
                max_length=2,
                null=True,
                verbose_name="Grupo Sanguíneo",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="nacionalidade",
            field=models.CharField(
                choices=[
                    ("BRASILEIRA", "Brasileira"),
                    ("BRASILEIRA_NATURALIZADA", "Brasileira Naturalizada"),
                    ("ESTRANGEIRA", "Estrangeira"),
                ],
                default="BRASILEIRA",
                max_length=30,
                verbose_name="Nacionalidade",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="naturalidade",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Naturalidade"
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="nome_mae",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nome da Mãe"
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="nome_pai",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nome do Pai"
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="pis_pasep",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="PIS/PASEP"
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="titulo_eleitor",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Título de Eleitor"
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="uf_naturalidade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapá"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantins"),
                ],
                max_length=2,
                null=True,
                verbose_name="UF",
            ),
        ),
    ]
