# Generated by Django 5.0.2 on 2025-09-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0126_adicionar_dados_pessoais_completos"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="altura",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Altura (cm)",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="calca",
            field=models.CharField(
                blank=True,
                choices=[
                    ("36", "36"),
                    ("38", "38"),
                    ("40", "40"),
                    ("42", "42"),
                    ("44", "44"),
                    ("46", "46"),
                    ("48", "48"),
                    ("50", "50"),
                    ("52", "52"),
                    ("54", "54"),
                ],
                max_length=10,
                null=True,
                verbose_name="Calça",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="camisa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PP", "PP"),
                    ("P", "P"),
                    ("M", "M"),
                    ("G", "G"),
                    ("GG", "GG"),
                    ("XG", "XG"),
                ],
                max_length=10,
                null=True,
                verbose_name="Camisa",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="colete_tamanho",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PP", "PP"),
                    ("P", "P"),
                    ("M", "M"),
                    ("G", "G"),
                    ("GG", "GG"),
                    ("XG", "XG"),
                ],
                max_length=10,
                null=True,
                verbose_name="Tamanho do Colete",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="colete_tipo",
            field=models.CharField(
                blank=True,
                choices=[("MASCULINO", "Masculino"), ("FEMININO", "Feminino")],
                max_length=20,
                null=True,
                verbose_name="Tipo do Colete",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="combat_shirt",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PP", "PP"),
                    ("P", "P"),
                    ("M", "M"),
                    ("G", "G"),
                    ("GG", "GG"),
                    ("XG", "XG"),
                ],
                max_length=10,
                null=True,
                verbose_name="Combat Shirt",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="comprimento_calca",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CURTA", "Calça Curta"),
                    ("NORMAL", "Calça Normal"),
                    ("LONGA", "Calça Longa"),
                ],
                max_length=20,
                null=True,
                verbose_name="Comprimento da Calça",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="coturno",
            field=models.CharField(
                blank=True,
                choices=[
                    ("35", "35"),
                    ("36", "36"),
                    ("37", "37"),
                    ("38", "38"),
                    ("39", "39"),
                    ("40", "40"),
                    ("41", "41"),
                    ("42", "42"),
                    ("43", "43"),
                    ("44", "44"),
                    ("45", "45"),
                    ("46", "46"),
                ],
                max_length=10,
                null=True,
                verbose_name="Coturno",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="gorro",
            field=models.CharField(
                blank=True,
                choices=[
                    ("54", "54"),
                    ("55", "55"),
                    ("56", "56"),
                    ("57", "57"),
                    ("58", "58"),
                    ("59", "59"),
                    ("60", "60"),
                    ("61", "61"),
                    ("62", "62"),
                ],
                max_length=10,
                null=True,
                verbose_name="Gorro",
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="peso",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Peso (kg)",
            ),
        ),
    ]
