# Generated by Django 5.0.2 on 2025-09-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0127_adicionar_dados_fisicos_fardamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="militar",
            name="colete_tamanho",
        ),
        migrations.RemoveField(
            model_name="militar",
            name="colete_tipo",
        ),
    ]
