# Generated by Django 5.0.2 on 2025-09-17 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0128_remover_campos_colete"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qualificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CURSO", "Curso"),
                            ("CERTIFICACAO", "Certificação"),
                            ("TREINAMENTO", "Treinamento"),
                            ("ESPECIALIZACAO", "Especialização"),
                            ("POS_GRADUACAO", "Pós-Graduação"),
                            ("MESTRADO", "Mestrado"),
                            ("DOUTORADO", "Doutorado"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Qualificação",
                    ),
                ),
                (
                    "nome_curso",
                    models.CharField(
                        max_length=200, verbose_name="Nome do Curso/Certificação"
                    ),
                ),
                (
                    "carga_horaria",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Carga Horária (CH)"
                    ),
                ),
                (
                    "instituicao",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Instituição",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Início"
                    ),
                ),
                (
                    "data_conclusao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "status_verificacao",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("VERIFICADO", "Verificado"),
                            ("REJEITADO", "Rejeitado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status de Verificação",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "arquivo_certificado",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="qualificacoes/",
                        verbose_name="Arquivo do Certificado",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualificacoes",
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qualificação",
                "verbose_name_plural": "Qualificações",
                "ordering": ["-data_conclusao", "-data_cadastro"],
            },
        ),
    ]
