# Generated by Django 5.0.2 on 2025-09-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0129_adicionar_qualificacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="classificacao",
            field=models.CharField(
                choices=[
                    ("ATIVO", "Ativo"),
                    ("NVRR", "NVRR"),
                    ("INATIVO", "Inativo"),
                    ("AGREGADO", "Agregado"),
                    ("PRESO", "Preso"),
                    ("RR", "RR"),
                    ("FALECIDO", "Falecido"),
                    ("LICENCIADO_A_PEDIDO", "Licenciado a Pedido"),
                    ("FUN_CIVIL", "Fun Civil"),
                    ("SAV", "SAV"),
                ],
                default="ATIVO",
                max_length=20,
                verbose_name="Classificação",
            ),
        ),
    ]
