# Generated by Django 5.0.2 on 2025-09-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0130_adicionar_classificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="comportamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BOM", "Bom"),
                    ("EXCEPCIONAL", "Excepcional"),
                    ("OTIMO", "Ótimo"),
                    ("INSUFICIENTE", "Insuciente"),
                    ("MAU", "Mau"),
                    ("NAO_TEM", "Não Tem"),
                ],
                max_length=20,
                null=True,
                verbose_name="Comportamento",
            ),
        ),
    ]
