# Generated by Django 5.0.2 on 2025-09-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0133_atualizar_pm_para_bm_e_adicionar_gamil"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="rgbm",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="RGBM (Identidade Militar)",
            ),
        ),
    ]
