# Generated by Django 5.0.2 on 2025-09-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0134_adicionar_campo_rgbm"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="secao_eleitoral",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Seção Eleitoral"
            ),
        ),
        migrations.AddField(
            model_name="militar",
            name="zona_eleitoral",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Zona Eleitoral"
            ),
        ),
    ]
