# Generated by Django 5.0.2 on 2025-09-17 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0135_adicionar_campos_eleitorais"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funcao",
                    models.CharField(
                        help_text="Ex: A disposição da SENASP",
                        max_length=200,
                        verbose_name="Função",
                    ),
                ),
                (
                    "lotacao",
                    models.CharField(
                        help_text="Ex: Diretoria de Gestão de Pessoas - DGP",
                        max_length=300,
                        verbose_name="Lotação",
                    ),
                ),
                (
                    "tipo_funcao",
                    models.CharField(
                        choices=[
                            ("COMANDO", "Comando"),
                            ("ADMINISTRATIVA", "Administrativa"),
                            ("OPERACIONAL", "Operacional"),
                            ("TECNICA", "Técnica"),
                            ("INSTRUCAO", "Instrução"),
                            ("OUTRAS", "Outras"),
                        ],
                        default="ADMINISTRATIVA",
                        max_length=20,
                        verbose_name="Tipo de Função",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATUAL", "Atual"),
                            ("ANTERIOR", "Anterior"),
                            ("TEMPORARIA", "Temporária"),
                            ("COMANDO", "Comando"),
                            ("AFASTAMENTO", "Afastamento"),
                        ],
                        default="ATUAL",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_fim",
                    models.DateField(
                        blank=True,
                        help_text="Deixe em branco para lotação atual",
                        null=True,
                        verbose_name="Data de Fim",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotacoes",
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lotação",
                "verbose_name_plural": "Lotações",
                "ordering": ["-data_inicio", "-data_cadastro"],
                "unique_together": {("militar", "data_inicio", "funcao")},
            },
        ),
    ]
