# Generated by Django 5.0.2 on 2025-09-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0136_create_lotacao_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("ATUAL", "Atual"),
                    ("ANTERIOR", "Anterior"),
                    ("TEMPORARIA", "Temporária"),
                    ("COMANDO", "Comando"),
                    ("AFASTAMENTO", "Afastamento"),
                ],
                default="ANTERIOR",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
