# Generated by Django 5.0.2 on 2025-09-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0137_alterar_default_status_lotacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuncaoMilitar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nome da Função"
                    ),
                ),
                (
                    "acesso_sigilo",
                    models.CharField(
                        choices=[
                            ("NEGADO", "Negado"),
                            ("RESTRITO", "Restrito"),
                            ("CONFIDENCIAL", "Confidencial"),
                            ("SECRETO", "Secreto"),
                            ("ULTRA_SECRETO", "Ultra Secreto"),
                        ],
                        default="NEGADO",
                        max_length=20,
                        verbose_name="Acesso/Sigilo",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "acesso",
                    models.CharField(
                        choices=[
                            ("TOTAL", "Total"),
                            ("UNIDADE", "Unidade"),
                            ("DEPARTAMENTO", "Departamento"),
                            ("SECAO", "Seção"),
                            ("NENHUM", "Nenhum"),
                        ],
                        default="NENHUM",
                        max_length=20,
                        verbose_name="Acesso",
                    ),
                ),
                (
                    "nivel",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Nível 1"),
                            (2, "Nível 2"),
                            (3, "Nível 3"),
                            (4, "Nível 4"),
                            (5, "Nível 5"),
                        ],
                        default=1,
                        verbose_name="Nível",
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("OPERACIONAL", "Operacional"),
                            ("COMISSAO", "Comissão"),
                            ("GESTAO", "Gestão"),
                            ("SUPORTE", "Suporte Técnico"),
                            ("USUARIO", "Usuário"),
                            ("OUTROS", "Outros"),
                        ],
                        default="OUTROS",
                        max_length=20,
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "publicacao",
                    models.CharField(
                        choices=[
                            ("DIGITADOR", "Digitador"),
                            ("REVISOR", "Revisor"),
                            ("APROVADOR", "Aprovador"),
                            ("EDITOR_GERAL", "Editor Geral"),
                            ("NENHUM", "Nenhum"),
                        ],
                        default="NENHUM",
                        max_length=20,
                        verbose_name="Publicação",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Função Militar",
                "verbose_name_plural": "Funções Militares",
                "ordering": ["ordem", "nome"],
            },
        ),
    ]
