# Generated by Django 5.0.2 on 2025-09-17 19:30

from django.db import migrations, models
import django.db.models.deletion


def criar_cargo_padrao(apps, schema_editor):
    """Criar cargo padrão para funções existentes"""
    FuncaoMilitar = apps.get_model('militares', 'FuncaoMilitar')
    UsuarioFuncao = apps.get_model('militares', 'UsuarioFuncao')
    
    # Buscar ou criar função padrão
    funcao_padrao, _ = FuncaoMilitar.objects.get_or_create(
        nome="Função Padrão",
        defaults={
            'descricao': 'Função criada automaticamente durante migração',
            'ativo': True,
            'ordem': 0,
            'acesso_sigilo': 'NEGADO',
            'acesso': 'NENHUM',
            'nivel': 1,
            'grupo': 'OUTROS',
            'publicacao': 'NENHUM'
        }
    )
    
    # Atualizar todas as funções existentes
    UsuarioFuncao.objects.filter(cargo_funcao__isnull=True).update(cargo_funcao=funcao_padrao)


def reverse_criar_cargo_padrao(apps, schema_editor):
    """Reverter a criação da função padrão"""
    FuncaoMilitar = apps.get_model('militares', 'FuncaoMilitar')
    FuncaoMilitar.objects.filter(nome="Função Padrão").delete()


def remover_funcoes_duplicadas(apps, schema_editor):
    """Remove funções duplicadas (usuario, cargo_funcao, data_inicio) mantendo apenas uma"""
    UsuarioFuncao = apps.get_model('militares', 'UsuarioFuncao')
    from collections import defaultdict
    agrupados = defaultdict(list)
    for funcao in UsuarioFuncao.objects.all():
        chave = (funcao.usuario_id, funcao.cargo_funcao_id, funcao.data_inicio)
        agrupados[chave].append(funcao)
    for chave, funcoes in agrupados.items():
        if len(funcoes) > 1:
            # Mantém a primeira, remove as demais
            for funcao in funcoes[1:]:
                funcao.delete()


def reverse_remover_funcoes_duplicadas(apps, schema_editor):
    """Reverter remoção de funções duplicadas - não é possível recuperar dados deletados"""
    pass




class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0138_add_funcao_militar"),
        # UsuarioFuncao existe desde 0068, então não precisa de dependência explícita
        # A dependência de 0138 garante que FuncaoMilitar existe
    ]

    operations = [
        # Adicionar campo cargo_funcao como nullable (agora FuncaoMilitar existe)
        migrations.AddField(
            model_name='usuariofuncao',
            name='cargo_funcao',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='militares.funcaomilitar',
                verbose_name='Cargo/Função'
            ),
        ),
        # Migrar dados existentes
        migrations.RunPython(criar_cargo_padrao, reverse_criar_cargo_padrao),
        # Remover duplicados
        migrations.RunPython(remover_funcoes_duplicadas, reverse_remover_funcoes_duplicadas),
        # Remover unique_together antigo usando SQL direto (campo nome_funcao não existe mais)
        # Isso precisa ser feito antes do AlterUniqueTogether para evitar erro
        migrations.RunSQL(
            sql="""
                DO $$
                DECLARE
                    idx_name text;
                BEGIN
                    -- Buscar e remover índices únicos que usam nome_funcao
                    FOR idx_name IN 
                        SELECT indexname 
                        FROM pg_indexes 
                        WHERE tablename = 'militares_usuariofuncao' 
                        AND indexdef LIKE '%unique%'
                        AND (indexdef LIKE '%nome_funcao%' OR indexdef LIKE '%usuario%nome%')
                    LOOP
                        EXECUTE 'DROP INDEX IF EXISTS ' || idx_name;
                    END LOOP;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Remover unique_together do estado do modelo primeiro (vazio)
        migrations.AlterUniqueTogether(
            name='usuariofuncao',
            unique_together=set(),
        ),
        # Tornar o campo obrigatório
        migrations.AlterField(
            model_name='usuariofuncao',
            name='cargo_funcao',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='militares.funcaomilitar',
                verbose_name='Cargo/Função'
            ),
        ),
        # Adicionar novo unique_together com cargo_funcao
        migrations.AlterUniqueTogether(
            name='usuariofuncao',
            unique_together={('usuario', 'cargo_funcao', 'data_inicio')},
        ),
        # Atualizar campo publicacao do FuncaoMilitar
        migrations.AlterField(
            model_name="funcaomilitar",
            name="publicacao",
            field=models.CharField(
                choices=[
                    ("EDITOR_GERAL", "Editor Geral"),
                    ("EDITOR_ADJUNTO", "Editor Adjunto"),
                    ("EDITOR", "Editor"),
                    ("APROVADOR", "Aprovador"),
                    ("REVISOR", "Revisor"),
                    ("DIGITADOR", "Digitador"),
                    ("NENHUM", "Nenhum"),
                ],
                default="NENHUM",
                max_length=20,
                verbose_name="Publicação",
            ),
        ),
    ]
