# Generated by Django 5.0.2 on 2025-09-17 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0139_update_publicacao_choices"),
    ]

    operations = [
        # Criar PermissaoFuncao (movido da migração 0071 porque depende de FuncaoMilitar)
        migrations.CreateModel(
            name="PermissaoFuncao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("MILITARES", "Gestão de Militares"),
                            ("FICHAS_CONCEITO", "Fichas de Conceito"),
                            ("QUADROS_ACESSO", "Quadros de Acesso"),
                            ("PROMOCOES", "Promoções"),
                            ("VAGAS", "Gestão de Vagas"),
                            ("COMISSAO", "Comissão de Promoção"),
                            ("DOCUMENTOS", "Documentos"),
                            ("USUARIOS", "Gestão de Usuários"),
                            ("RELATORIOS", "Relatórios"),
                            ("CONFIGURACOES", "Configurações do Sistema"),
                        ],
                        max_length=20,
                        verbose_name="Módulo",
                    ),
                ),
                (
                    "acesso",
                    models.CharField(
                        choices=[
                            ("VISUALIZAR", "Visualizar"),
                            ("CRIAR", "Criar"),
                            ("EDITAR", "Editar"),
                            ("EXCLUIR", "Excluir"),
                            ("APROVAR", "Aprovar"),
                            ("HOMOLOGAR", "Homologar"),
                            ("GERAR_PDF", "Gerar PDF"),
                            ("IMPRIMIR", "Imprimir"),
                            ("ASSINAR", "Assinar"),
                            ("ADMINISTRAR", "Administrar"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Acesso",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "funcao_militar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissoes",
                        to="militares.funcaomilitar",
                        verbose_name="Função Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permissão de Função",
                "verbose_name_plural": "Permissões de Funções",
                "ordering": ["funcao_militar__nome", "modulo", "acesso"],
                "unique_together": {("funcao_militar", "modulo", "acesso")},
            },
        ),
        # Atualizar campo acesso do FuncaoMilitar
        migrations.AlterField(
            model_name="funcaomilitar",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("TOTAL", "Total"),
                    ("DEPARTAMENTO", "Departamento"),
                    ("UNIDADE", "Unidade"),
                    ("ORGAO", "Órgão"),
                    ("SECAO", "Seção"),
                    ("NENHUM", "Nenhum"),
                ],
                default="NENHUM",
                max_length=20,
                verbose_name="Acesso",
            ),
        ),
    ]
