# Generated by Django 5.0.2 on 2025-09-17 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0140_update_acesso_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotacao",
            name="funcao_militar",
            field=models.ForeignKey(
                blank=True,
                help_text="Selecione uma função militar cadastrada no sistema",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="militares.funcaomilitar",
                verbose_name="Função Militar",
            ),
        ),
        # Adicionar campo permissoes ao PerfilAcesso (removido da migração 0071)
        migrations.AddField(
            model_name="perfilacesso",
            name="permissoes",
            field=models.ManyToManyField(
                blank=True,
                to="militares.permissaofuncao",
                verbose_name="Permissões",
            ),
        ),
    ]
