# Generated by Django 5.0.2 on 2025-09-17 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0141_add_funcao_militar_to_lotacao"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lotacao",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="lotacao",
            name="funcao",
        ),
        migrations.RemoveField(
            model_name="lotacao",
            name="funcao_militar",
        ),
        migrations.RemoveField(
            model_name="lotacao",
            name="tipo_funcao",
        ),
        migrations.CreateModel(
            name="MilitarFuncao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_funcao",
                    models.CharField(
                        choices=[
                            ("PRINCIPAL", "Principal"),
                            ("ADICIONAL", "Adicional"),
                            ("TEMPORARIA", "Temporária"),
                            ("COMISSAO", "Comissão"),
                        ],
                        default="PRINCIPAL",
                        max_length=20,
                        verbose_name="Tipo de Função",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_fim",
                    models.DateField(
                        blank=True,
                        help_text="Deixe em branco para função atual",
                        null=True,
                        verbose_name="Data de Fim",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "funcao_militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.funcaomilitar",
                        verbose_name="Função Militar",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funcoes",
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Função do Militar",
                "verbose_name_plural": "Funções dos Militares",
                "ordering": ["-data_inicio", "-data_cadastro"],
                "unique_together": {("militar", "funcao_militar", "data_inicio")},
            },
        ),
    ]
