# Generated by Django 5.0.2 on 2025-09-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0142_separate_lotacao_funcoes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orgao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Órgão"),
                ),
                (
                    "sigla",
                    models.CharField(
                        help_text="Sigla única do órgão",
                        max_length=20,
                        unique=True,
                        verbose_name="Sigla",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem para exibição em listas e menus",
                        verbose_name="Ordem de Exibição",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional do órgão",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o órgão está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Órgão",
                "verbose_name_plural": "Órgãos",
                "ordering": ["ordem", "nome"],
                "unique_together": {("sigla",)},
            },
        ),
    ]
