# Generated by Django 5.0.2 on 2025-09-17 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0143_orgao"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrandeComando",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome do Grande Comando"
                    ),
                ),
                (
                    "sigla",
                    models.CharField(
                        help_text="Sigla do grande comando",
                        max_length=20,
                        verbose_name="Sigla",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem para exibição no organograma",
                        verbose_name="Ordem de Exibição",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional do grande comando",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o grande comando está ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grandes_comandos",
                        to="militares.orgao",
                        verbose_name="Órgão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grande Comando",
                "verbose_name_plural": "Grandes Comandos",
                "ordering": ["orgao__ordem", "ordem", "nome"],
                "unique_together": {("orgao", "sigla")},
            },
        ),
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Unidade"),
                ),
                (
                    "sigla",
                    models.CharField(
                        help_text="Sigla da unidade",
                        max_length=20,
                        verbose_name="Sigla",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem para exibição no organograma",
                        verbose_name="Ordem de Exibição",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional da unidade",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se a unidade está ativa",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "grande_comando",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades",
                        to="militares.grandecomando",
                        verbose_name="Grande Comando",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade",
                "verbose_name_plural": "Unidades",
                "ordering": [
                    "grande_comando__orgao__ordem",
                    "grande_comando__ordem",
                    "ordem",
                    "nome",
                ],
                "unique_together": {("grande_comando", "sigla")},
            },
        ),
        migrations.CreateModel(
            name="SubUnidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome da Sub-Unidade"
                    ),
                ),
                (
                    "sigla",
                    models.CharField(
                        help_text="Sigla da sub-unidade",
                        max_length=20,
                        verbose_name="Sigla",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem para exibição no organograma",
                        verbose_name="Ordem de Exibição",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional da sub-unidade",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se a sub-unidade está ativa",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_unidades",
                        to="militares.unidade",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-Unidade",
                "verbose_name_plural": "Sub-Unidades",
                "ordering": [
                    "unidade__grande_comando__orgao__ordem",
                    "unidade__grande_comando__ordem",
                    "unidade__ordem",
                    "ordem",
                    "nome",
                ],
                "unique_together": {("unidade", "sigla")},
            },
        ),
    ]
