# Generated by Django 5.0.2 on 2025-09-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0146_grandecomando_cidade_grandecomando_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grandecomando",
            name="endereco",
            field=models.TextField(
                blank=True,
                help_text="Endereço completo do grande comando",
                null=True,
                verbose_name="Endereço Completo",
            ),
        ),
        migrations.AddField(
            model_name="orgao",
            name="endereco",
            field=models.TextField(
                blank=True,
                help_text="Endereço completo do órgão",
                null=True,
                verbose_name="Endereço Completo",
            ),
        ),
        migrations.AddField(
            model_name="subunidade",
            name="endereco",
            field=models.TextField(
                blank=True,
                help_text="Endereço completo da sub-unidade",
                null=True,
                verbose_name="Endereço Completo",
            ),
        ),
        migrations.AddField(
            model_name="unidade",
            name="endereco",
            field=models.TextField(
                blank=True,
                help_text="Endereço completo da unidade",
                null=True,
                verbose_name="Endereço Completo",
            ),
        ),
    ]
