# Generated by Django 5.0.2 on 2025-09-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0147_grandecomando_endereco_orgao_endereco_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="militarfuncao",
            name="status",
            field=models.CharField(
                choices=[
                    ("ATUAL", "Atual"),
                    ("ANTERIOR", "Anterior"),
                    ("TEMPORARIA", "Temporária"),
                ],
                default="ATUAL",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
