# Generated by Django 5.0.2 on 2025-09-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0148_militarfuncao_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intersticio",
            name="quadro",
            field=models.CharField(
                choices=[
                    ("COMB", "Combatente"),
                    ("SAUDE", "Saúde"),
                    ("ENG", "Engenheiro"),
                    ("COMP", "Complementar"),
                    ("NVRR", "NVRR"),
                    ("PRACAS", "Praças"),
                    ("RESERVA_REMUNERADA", "Reserva Remunerada"),
                ],
                max_length=20,
                verbose_name="Quadro",
            ),
        ),
        migrations.AlterField(
            model_name="militar",
            name="quadro",
            field=models.CharField(
                choices=[
                    ("COMB", "Combatente"),
                    ("SAUDE", "Saúde"),
                    ("ENG", "Engenheiro"),
                    ("COMP", "Complementar"),
                    ("NVRR", "NVRR"),
                    ("PRACAS", "Praças"),
                    ("RESERVA_REMUNERADA", "Reserva Remunerada"),
                ],
                default="COMB",
                max_length=20,
                verbose_name="Quadro",
            ),
        ),
        migrations.AlterField(
            model_name="previsaovaga",
            name="quadro",
            field=models.CharField(
                choices=[
                    ("COMB", "Combatente"),
                    ("SAUDE", "Saúde"),
                    ("ENG", "Engenheiro"),
                    ("COMP", "Complementar"),
                    ("NVRR", "NVRR"),
                    ("PRACAS", "Praças"),
                    ("RESERVA_REMUNERADA", "Reserva Remunerada"),
                ],
                max_length=20,
                verbose_name="Quadro",
            ),
        ),
        migrations.AlterField(
            model_name="vaga",
            name="quadro",
            field=models.CharField(
                choices=[
                    ("COMB", "Combatente"),
                    ("SAUDE", "Saúde"),
                    ("ENG", "Engenheiro"),
                    ("COMP", "Complementar"),
                    ("RESERVA_REMUNERADA", "Reserva Remunerada"),
                ],
                max_length=20,
                verbose_name="Quadro",
            ),
        ),
        migrations.AlterField(
            model_name="vagamanual",
            name="quadro",
            field=models.CharField(
                choices=[
                    ("COMB", "Combatente"),
                    ("SAUDE", "Saúde"),
                    ("ENG", "Engenheiro"),
                    ("COMP", "Complementar"),
                    ("RESERVA_REMUNERADA", "Reserva Remunerada"),
                ],
                max_length=20,
                verbose_name="Quadro",
            ),
        ),
    ]
