# Generated by Django 5.0.2 on 2025-09-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0149_add_reserva_remunerada_quadro"),
    ]

    operations = [
        migrations.AddField(
            model_name="militarfuncao",
            name="posto_final",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CB", "Coronel"),
                    ("TC", "Tenente Coronel"),
                    ("MJ", "Major"),
                    ("CP", "Capitão"),
                    ("1T", "1º Tenente"),
                    ("2T", "2º Tenente"),
                    ("AS", "Aspirante a Oficial"),
                    ("AA", "Aluno de Adaptação"),
                    ("NVRR", "Navegador"),
                    ("ST", "Subtenente"),
                    ("1S", "1º Sargento"),
                    ("2S", "2º Sargento"),
                    ("3S", "3º Sargento"),
                    ("CAB", "Cabo"),
                    ("SD", "Soldado"),
                ],
                help_text="Posto do militar no fim da função",
                max_length=4,
                null=True,
                verbose_name="Posto Final",
            ),
        ),
        migrations.AddField(
            model_name="militarfuncao",
            name="posto_inicial",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CB", "Coronel"),
                    ("TC", "Tenente Coronel"),
                    ("MJ", "Major"),
                    ("CP", "Capitão"),
                    ("1T", "1º Tenente"),
                    ("2T", "2º Tenente"),
                    ("AS", "Aspirante a Oficial"),
                    ("AA", "Aluno de Adaptação"),
                    ("NVRR", "Navegador"),
                    ("ST", "Subtenente"),
                    ("1S", "1º Sargento"),
                    ("2S", "2º Sargento"),
                    ("3S", "3º Sargento"),
                    ("CAB", "Cabo"),
                    ("SD", "Soldado"),
                ],
                help_text="Posto do militar no início da função",
                max_length=4,
                null=True,
                verbose_name="Posto Inicial",
            ),
        ),
    ]
