# Generated by Django 5.0.2 on 2025-09-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0151_update_latitude_longitude_precision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grandecomando",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Coordenada de latitude (opcional)",
                max_digits=18,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="grandecomando",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Coordenada de longitude (opcional)",
                max_digits=18,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="orgao",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Coordenada de latitude (opcional)",
                max_digits=18,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="orgao",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Coordenada de longitude (opcional)",
                max_digits=18,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="subunidade",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Coordenada de latitude (opcional)",
                max_digits=18,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="subunidade",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Coordenada de longitude (opcional)",
                max_digits=18,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="unidade",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Coordenada de latitude (opcional)",
                max_digits=18,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="unidade",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Coordenada de longitude (opcional)",
                max_digits=18,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
