# Generated by Django 5.0.2 on 2025-09-18 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0152_update_latitude_longitude_precision_v2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Elogio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Elogio Individual"),
                            ("COLETIVO", "Elogio Coletivo"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de Elogio",
                    ),
                ),
                ("data_elogio", models.DateField(verbose_name="Data do Elogio")),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Portaria, Boletim, etc.",
                        max_length=50,
                        null=True,
                        verbose_name="Número do Documento",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do Elogio")),
                (
                    "autoridade_elogiou",
                    models.CharField(
                        max_length=200, verbose_name="Autoridade que Elogiou"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Registro"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elogios",
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elogio",
                "verbose_name_plural": "Elogios",
                "ordering": ["-data_elogio", "-data_registro"],
            },
        ),
        migrations.CreateModel(
            name="Punicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("REPRENSAO", "Repreensão"),
                            ("DETENCAO", "Detenção"),
                            ("PRISAO", "Prisão"),
                            (
                                "FALTA_APROVEITAMENTO",
                                "Falta de Aproveitamento em Cursos Militares",
                            ),
                        ],
                        max_length=25,
                        verbose_name="Tipo de Punição",
                    ),
                ),
                ("data_punicao", models.DateField(verbose_name="Data da Punição")),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Portaria, Boletim, etc.",
                        max_length=50,
                        null=True,
                        verbose_name="Número do Documento",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição da Punição")),
                (
                    "autoridade_puniu",
                    models.CharField(
                        max_length=200, verbose_name="Autoridade que Puniu"
                    ),
                ),
                (
                    "periodo_punicao",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 30 dias, 1 ano, etc.",
                        max_length=100,
                        null=True,
                        verbose_name="Período da Punição",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Registro"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punicoes",
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Punição",
                "verbose_name_plural": "Punições",
                "ordering": ["-data_punicao", "-data_registro"],
            },
        ),
    ]
