# Generated by Django 5.0.2 on 2025-09-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0153_add_elogios_punicoes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichaconceitopracas",
            name="falta_aproveitamento",
        ),
        migrations.RemoveField(
            model_name="fichaconceitopracas",
            name="punicao_detencao",
        ),
        migrations.RemoveField(
            model_name="fichaconceitopracas",
            name="punicao_prisao",
        ),
        migrations.AddField(
            model_name="fichaconceitopracas",
            name="punicao_advertencia",
            field=models.PositiveIntegerField(default=0, verbose_name="Advertência"),
        ),
        migrations.AddField(
            model_name="fichaconceitopracas",
            name="punicao_demissao",
            field=models.PositiveIntegerField(default=0, verbose_name="Demissão"),
        ),
        migrations.AddField(
            model_name="fichaconceitopracas",
            name="punicao_exclusao_disciplina",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Exclusão a Bem da Disciplina"
            ),
        ),
        migrations.AddField(
            model_name="fichaconceitopracas",
            name="punicao_licenciamento",
            field=models.PositiveIntegerField(default=0, verbose_name="Licenciamento"),
        ),
        migrations.AddField(
            model_name="fichaconceitopracas",
            name="punicao_reforma_disciplinar",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Reforma Disciplinar Compulsória"
            ),
        ),
        migrations.AddField(
            model_name="fichaconceitopracas",
            name="punicao_suspensao",
            field=models.PositiveIntegerField(default=0, verbose_name="Suspensão"),
        ),
        migrations.AlterField(
            model_name="punicao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ADVERTENCIA", "Advertência"),
                    ("REPRENSAO", "Repreensão"),
                    ("SUSPENSAO", "Suspensão"),
                    ("REFORMA_DISCIPLINAR", "Reforma Disciplinar Compulsória"),
                    ("DEMISSAO", "Demissão"),
                    ("LICENCIAMENTO", "Licenciamento"),
                    ("EXCLUSAO_DISCIPLINA", "Exclusão a Bem da Disciplina"),
                ],
                max_length=25,
                verbose_name="Tipo de Punição",
            ),
        ),
    ]
