# Generated by Django 5.0.2 on 2025-09-18 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0155_add_usuario_sessao_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuariosessao",
            name="funcao_militar",
        ),
        migrations.RemoveField(
            model_name="usuariosessao",
            name="grande_comando",
        ),
        migrations.RemoveField(
            model_name="usuariosessao",
            name="orgao",
        ),
        migrations.RemoveField(
            model_name="usuariosessao",
            name="sub_unidade",
        ),
        migrations.RemoveField(
            model_name="usuariosessao",
            name="unidade",
        ),
        migrations.CreateModel(
            name="UsuarioFuncaoMilitar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "funcao_militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.funcaomilitar",
                        verbose_name="Função Militar",
                    ),
                ),
                (
                    "grande_comando",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.grandecomando",
                        verbose_name="Grande Comando",
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.orgao",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "sub_unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.subunidade",
                        verbose_name="Sub-Unidade",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.unidade",
                        verbose_name="Unidade",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funcoes_militares",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Função Militar do Usuário",
                "verbose_name_plural": "Funções Militares dos Usuários",
                "ordering": ["funcao_militar__ordem", "funcao_militar__nome"],
                "unique_together": {("usuario", "funcao_militar")},
            },
        ),
        migrations.AddField(
            model_name="usuariosessao",
            name="funcao_militar_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="militares.usuariofuncaomilitar",
                verbose_name="Função Militar do Usuário",
            ),
        ),
    ]
