# Generated by Django 5.0.2 on 2025-09-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0156_remove_usuariosessao_funcao_militar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="punicao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ADVERTENCIA", "Advertência"),
                    ("REPRENSAO", "Repreensão"),
                    ("SUSPENSAO", "Suspensão"),
                    ("DETENCAO", "Detenção"),
                    ("PRISAO", "Prisão"),
                    ("REFORMA_DISCIPLINAR", "Reforma Disciplinar Compulsória"),
                    ("DEMISSAO", "Demissão"),
                    ("LICENCIAMENTO", "Licenciamento"),
                    ("EXCLUSAO_DISCIPLINA", "Exclusão a Bem da Disciplina"),
                ],
                max_length=25,
                verbose_name="Tipo de Punição",
            ),
        ),
    ]
