# Generated by Django 5.0.2 on 2025-09-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0157_add_detencao_prisao_punicoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="militar",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("PRONTO", "Pronto"),
                    (
                        "CEDIDO_FUNCAO_BM_FORCA_NACIONAL",
                        "Cedido Função BM/Força Nacional",
                    ),
                    ("CEDIDO_FUNCAO_BM_SSP_PI", "Cedido Função BM/SSP-PI"),
                    ("CEDIDO_FUNCAO_BM_MP_PI", "Cedido Função BM/MP-PI"),
                    ("ADIDO_GAMIL", "Adido ao Gamil"),
                    ("ADIDO_SSP_PI", "Adido a SSP-PI"),
                    ("AFASTAMENTO_FERIAS", "Afastamento/Férias"),
                    ("AFASTAMENTO_LICENCA_ESPECIAL", "Afastamento/Licença Especial"),
                    (
                        "AFASTAMENTO_LICENCA_INTERESSE_PARTICULAR",
                        "Afastamento/Licença para Tratar de Interesse Particular",
                    ),
                    (
                        "AFASTAMENTO_TRATAMENTO_SAUDE_FAMILIA",
                        "Afastamento/Para Tratamento de Saúde de Pessoa da Família",
                    ),
                    (
                        "AFASTAMENTO_TRATAMENTO_SAUDE_PROPRIA",
                        "Afastamento/Para Tratamento de Saúde Própria",
                    ),
                    ("AFASTAMENTO_TEMPORARIO_LUTO", "Afastamento Temporariamente/Luto"),
                    (
                        "AFASTAMENTO_TEMPORARIO_NUPCIAS",
                        "Afastamento Temporariamente/Núpcias",
                    ),
                    (
                        "AFASTAMENTO_TEMPORARIO_INSTALACAO",
                        "Afastamento Temporariamente/Instalação",
                    ),
                    (
                        "AFASTAMENTO_TEMPORARIO_TRANSITO",
                        "Afastamento Temporariamente/Trânsito",
                    ),
                    (
                        "AFASTAMENTO_TEMPORARIO_CURSO",
                        "Afastamento Temporariamente/Frequentando Curso",
                    ),
                    ("AGREGADO_FUNCAO_CIVIL", "Agregado/Função Civil"),
                    ("AGREGADO_LTSP", "Agregado/LTSP"),
                    ("AGREGADO_LTSP_FAMILIA", "Agregado/LTSP Família"),
                    (
                        "AGREGADO_CANDIDATO_CARGO_ELETIVO",
                        "Agregado/Candidato a Cargo Eletivo",
                    ),
                    ("AUSENTE", "Ausente"),
                    ("DESERTOR", "Desertor"),
                    ("DESAPARECIDO", "Desaparecido"),
                    (
                        "AGUARDANDO_TRANSFERENCIA_RR_PEDIDO",
                        "Aguardando Transferência para RR/A Pedido",
                    ),
                    (
                        "AGUARDANDO_TRANSFERENCIA_RR_CONDICAO_ESPECIAL",
                        "Aguardando Transferência para RR/Condição Especial",
                    ),
                    (
                        "AGUARDANDO_TRANSFERENCIA_RR_EX_OFICIO",
                        "Aguardando Transferência para RR/Ex-Ofício",
                    ),
                    (
                        "DESLIGAMENTO_RESERVA_REMUNERADA",
                        "Desligamento ou Exclusão do Serviço Ativo/Reserva Remunerada",
                    ),
                    (
                        "DESLIGAMENTO_REFORMADO",
                        "Desligamento ou Exclusão do Serviço Ativo/Reformado",
                    ),
                    (
                        "DESLIGAMENTO_DEMITIDO",
                        "Desligamento ou Exclusão do Serviço Ativo/Demitido",
                    ),
                    (
                        "DESLIGAMENTO_PERDA_POSTO_PATENTE",
                        "Desligamento ou Exclusão do Serviço Ativo/Perda de Posto e Patente",
                    ),
                    (
                        "DESLIGAMENTO_EXCLUSAO_DISCIPLINA",
                        "Desligamento ou Exclusão do Serviço Ativo/Exclusão a Bem da Disciplina",
                    ),
                    (
                        "DESLIGAMENTO_DESERTOR",
                        "Desligamento ou Exclusão do Serviço Ativo/Desertor",
                    ),
                    (
                        "DESLIGAMENTO_FALECIDO",
                        "Desligamento ou Exclusão do Serviço Ativo/Falecido",
                    ),
                    (
                        "DESLIGAMENTO_EXTRAVIADO",
                        "Desligamento ou Exclusão do Serviço Ativo/Extraviado",
                    ),
                    ("LICENCIADO_PEDIDO", "Licenciado a Pedido"),
                    (
                        "LICENCIADO_EX_OFICIO_TEMPO_SERVICO",
                        "Licenciado Ex-Ofício por Conclusão do Tempo de Serviço",
                    ),
                    (
                        "LICENCIADO_EX_OFICIO_CONVENIENCIA",
                        "Licenciado Ex-Ofício por Conveniência do Serviço",
                    ),
                    (
                        "LICENCIADO_EX_OFICIO_DISCIPLINA",
                        "Licenciado Ex-Ofício a Bem da Disciplina",
                    ),
                    ("LICENCIADO_EX_OFICIO", "Licenciado Ex-Ofício"),
                    ("LICENCA_MATERNIDADE", "Licença Maternidade"),
                    ("LICENCA_PATERNIDADE", "Licença Paternidade"),
                    ("INATIVO", "Inativo"),
                ],
                default="PRONTO",
                max_length=50,
                verbose_name="Situação",
            ),
        ),
    ]
