# Generated by Django 5.0.2 on 2025-09-18 19:38

import django.db.models.deletion
from django.db import migrations, models


def corrigir_dados_inconsistentes(apps, schema_editor):
    """
    Corrige dados inconsistentes na tabela militares_membrocomissao.
    Remove a restrição de chave estrangeira temporariamente, corrige os dados,
    e depois recria a restrição.
    """
    from django.db import connection
    
    cursor = connection.cursor()
    
    # 1. Remover a restrição de chave estrangeira temporariamente
    print("Removendo restrição de chave estrangeira temporariamente...")
    cursor.execute("""
        ALTER TABLE militares_membrocomissao 
        DROP CONSTRAINT IF EXISTS militares_membrocomi_cargo_id_8dd996c8_fk_militares
    """)
    
    # 2. Tornar o campo nullable
    print("Tornando campo cargo_id nullable...")
    cursor.execute("""
        ALTER TABLE militares_membrocomissao 
        ALTER COLUMN cargo_id DROP NOT NULL
    """)
    
    # 3. Corrigir dados inconsistentes
    print("Corrigindo dados inconsistentes...")
    cursor.execute("""
        UPDATE militares_membrocomissao 
        SET cargo_id = NULL 
        WHERE cargo_id NOT IN (SELECT id FROM militares_funcaomilitar)
    """)
    
    # 4. Recriar a restrição de chave estrangeira
    print("Recriando restrição de chave estrangeira...")
    cursor.execute("""
        ALTER TABLE militares_membrocomissao 
        ADD CONSTRAINT militares_membrocomi_cargo_id_8dd996c8_fk_militares 
        FOREIGN KEY (cargo_id) REFERENCES militares_funcaomilitar(id) 
        DEFERRABLE INITIALLY DEFERRED
    """)


def reverter_correcao(apps, schema_editor):
    """
    Função de reversão - não faz nada pois não podemos recuperar os dados perdidos
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0158_add_inativo_situacao_choice"),
    ]

    operations = [
        migrations.RunPython(corrigir_dados_inconsistentes, reverter_correcao),
        migrations.AddField(
            model_name="membrocomissao",
            name="funcao_militar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="militares.funcaomilitar",
                verbose_name="Função Militar",
            ),
        ),
        migrations.AlterField(
            model_name="membrocomissao",
            name="cargo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="militares.funcaomilitar",
                verbose_name="Função/Cargo do Usuário",
            ),
        ),
    ]
