# Generated by Django 5.0.2 on 2025-09-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0159_adicionar_funcao_militar_membrocomissao"),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioFuncao',
        ),
    ]
