# Generated by Django 5.0.2 on 2025-09-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0160_remove_usuariofuncao_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name='CargoFuncao',
        ),
    ]
