# Generated by Django 5.0.2 on 2025-09-19 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0162_atualizar_permissaofuncao"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="permissaofuncao",
            unique_together={("funcao_militar", "modulo", "acesso")},
        ),
        migrations.AlterField(
            model_name="membrocomissao",
            name="cargo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="membros_cargo",
                to="militares.funcaomilitar",
                verbose_name="Função/Cargo do Usuário",
            ),
        ),
        # NOTA: Removido RemoveField de cargo_funcao - esse campo nunca existiu em PermissaoFuncao
        # O campo cargo_funcao existia apenas em UsuarioFuncao, que já foi removido na migração 0160
    ]
