# Generated by Django 5.0.2 on 2025-09-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0163_adicionar_nivel_acesso"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariofuncaomilitar",
            name="nivel_acesso",
            field=models.CharField(
                choices=[
                    ("TOTAL", "Total - Acesso completo ao sistema"),
                    ("ORGAO", "Órgão - Acesso ao órgão + descendência"),
                    (
                        "GRANDE_COMANDO",
                        "Grande Comando - Acesso ao grande comando + descendência",
                    ),
                    ("UNIDADE", "Unidade - Acesso à unidade + descendência"),
                    ("SUBUNIDADE", "Subunidade - Acesso apenas à subunidade"),
                    ("NENHUM", "Nenhum - Apenas alterações pessoais"),
                ],
                default="NENHUM",
                help_text="Define o nível de acesso hierárquico do usuário",
                max_length=20,
                verbose_name="Nível de Acesso",
            ),
        ),
    ]
