# Generated by Django 5.0.2 on 2025-09-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0164_adicionar_nivel_acesso_usuario_funcao"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nome de Usuário"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_ultimo_acesso",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Acesso"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
            ],
            options={
                "verbose_name": "Usuário Master",
                "verbose_name_plural": "Usuários Master",
                "ordering": ["nome_completo"],
            },
        ),
        migrations.AlterField(
            model_name="funcaomilitar",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("TOTAL", "Total"),
                    ("ORGAO", "Órgão"),
                    ("GRANDE_COMANDO", "Grande Comando"),
                    ("UNIDADE", "Unidade"),
                    ("SUBUNIDADE", "Subunidade"),
                    ("NENHUM", "Nenhum"),
                ],
                default="NENHUM",
                max_length=20,
                verbose_name="Acesso",
            ),
        ),
        migrations.AlterField(
            model_name="usuariofuncaomilitar",
            name="nivel_acesso",
            field=models.CharField(
                choices=[
                    ("TOTAL", "Total"),
                    ("ORGAO", "Órgão"),
                    ("GRANDE_COMANDO", "Grande Comando"),
                    ("UNIDADE", "Unidade"),
                    ("SUBUNIDADE", "Subunidade"),
                    ("NENHUM", "Nenhum"),
                ],
                default="NENHUM",
                help_text="Define o nível de acesso hierárquico do usuário",
                max_length=20,
                verbose_name="Nível de Acesso",
            ),
        ),
    ]
