# Generated by Django 5.0.2 on 2025-09-20 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0165_usuariomaster_alter_funcaomilitar_acesso_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_administracao",
            field=models.BooleanField(default=False, verbose_name="Administração"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_almanaques",
            field=models.BooleanField(default=False, verbose_name="Almanaques"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_apenas_visualizacao",
            field=models.BooleanField(
                default=False,
                help_text="Se marcado, o usuário terá apenas permissão de visualização",
                verbose_name="Apenas Visualização",
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_calendarios",
            field=models.BooleanField(default=False, verbose_name="Calendários"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_comissoes",
            field=models.BooleanField(default=False, verbose_name="Comissões"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_dashboard",
            field=models.BooleanField(default=True, verbose_name="Dashboard"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_efetivo",
            field=models.BooleanField(default=False, verbose_name="Efetivo"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_fichas_oficiais",
            field=models.BooleanField(default=False, verbose_name="Fichas de Oficiais"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_fichas_pracas",
            field=models.BooleanField(default=False, verbose_name="Fichas de Praças"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_gerenciar_intersticios",
            field=models.BooleanField(
                default=False, verbose_name="Gerenciar Interstícios"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_gerenciar_previsao",
            field=models.BooleanField(default=False, verbose_name="Gerenciar Previsão"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_inativos",
            field=models.BooleanField(default=False, verbose_name="Inativos"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_intersticios",
            field=models.BooleanField(default=False, verbose_name="Interstícios"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_logs",
            field=models.BooleanField(default=False, verbose_name="Logs"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_lotacoes",
            field=models.BooleanField(default=False, verbose_name="Lotações"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_medalhas",
            field=models.BooleanField(default=False, verbose_name="Medalhas"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_meus_votos",
            field=models.BooleanField(default=False, verbose_name="Meus Votos"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_permissoes",
            field=models.BooleanField(default=False, verbose_name="Permissões"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_promocoes",
            field=models.BooleanField(default=False, verbose_name="Promoções"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_quadros_acesso",
            field=models.BooleanField(default=False, verbose_name="Quadros de Acesso"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_quadros_fixacao",
            field=models.BooleanField(default=False, verbose_name="Quadros de Fixação"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_usuarios",
            field=models.BooleanField(default=False, verbose_name="Usuários"),
        ),
        migrations.AlterField(
            model_name="funcaomilitar",
            name="grupo",
            field=models.CharField(
                choices=[
                    ("ADMINISTRATIVO", "Administrativo"),
                    ("OPERACIONAL", "Operacional"),
                    ("COMISSAO", "Comissão"),
                    ("GESTAO", "Gestão"),
                    ("SUPORTE", "Suporte Técnico"),
                    ("OUTROS", "Outros"),
                ],
                default="OUTROS",
                max_length=20,
                verbose_name="Grupo",
            ),
        ),
        migrations.CreateModel(
            name="FuncaoMenuConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_dashboard",
                    models.BooleanField(default=True, verbose_name="Dashboard"),
                ),
                (
                    "show_efetivo",
                    models.BooleanField(default=False, verbose_name="Efetivo"),
                ),
                (
                    "show_inativos",
                    models.BooleanField(default=False, verbose_name="Inativos"),
                ),
                (
                    "show_usuarios",
                    models.BooleanField(default=False, verbose_name="Usuários"),
                ),
                (
                    "show_permissoes",
                    models.BooleanField(default=False, verbose_name="Permissões"),
                ),
                (
                    "show_fichas_oficiais",
                    models.BooleanField(
                        default=False, verbose_name="Fichas de Oficiais"
                    ),
                ),
                (
                    "show_fichas_pracas",
                    models.BooleanField(default=False, verbose_name="Fichas de Praças"),
                ),
                (
                    "show_quadros_acesso",
                    models.BooleanField(
                        default=False, verbose_name="Quadros de Acesso"
                    ),
                ),
                (
                    "show_quadros_fixacao",
                    models.BooleanField(
                        default=False, verbose_name="Quadros de Fixação"
                    ),
                ),
                (
                    "show_almanaques",
                    models.BooleanField(default=False, verbose_name="Almanaques"),
                ),
                (
                    "show_promocoes",
                    models.BooleanField(default=False, verbose_name="Promoções"),
                ),
                (
                    "show_calendarios",
                    models.BooleanField(default=False, verbose_name="Calendários"),
                ),
                (
                    "show_comissoes",
                    models.BooleanField(default=False, verbose_name="Comissões"),
                ),
                (
                    "show_meus_votos",
                    models.BooleanField(default=False, verbose_name="Meus Votos"),
                ),
                (
                    "show_intersticios",
                    models.BooleanField(default=False, verbose_name="Interstícios"),
                ),
                (
                    "show_gerenciar_intersticios",
                    models.BooleanField(
                        default=False, verbose_name="Gerenciar Interstícios"
                    ),
                ),
                (
                    "show_gerenciar_previsao",
                    models.BooleanField(
                        default=False, verbose_name="Gerenciar Previsão"
                    ),
                ),
                (
                    "show_administracao",
                    models.BooleanField(default=False, verbose_name="Administração"),
                ),
                ("show_logs", models.BooleanField(default=False, verbose_name="Logs")),
                (
                    "show_medalhas",
                    models.BooleanField(default=False, verbose_name="Medalhas"),
                ),
                (
                    "show_lotacoes",
                    models.BooleanField(default=False, verbose_name="Lotações"),
                ),
                (
                    "is_consultor",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, o usuário terá apenas permissão de visualização",
                        verbose_name="Apenas Visualização",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "funcao_militar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_config",
                        to="militares.funcaomilitar",
                        verbose_name="Função Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Menu por Função",
                "verbose_name_plural": "Configurações de Menu por Função",
                "ordering": ["funcao_militar__nome"],
            },
        ),
    ]
