# Generated by Django 5.0.2 on 2025-09-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0166_funcaomilitar_menu_administracao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichaconceitopracas",
            name="falta_aproveitamento",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Falta de Aproveitamento em Cursos Militares"
            ),
        ),
    ]
