# Generated by Django 5.0.2 on 2025-09-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0167_add_falta_aproveitamento_to_fichaconceitopracas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichaconceitopracas",
            name="punicao_advertencia",
        ),
        migrations.RemoveField(
            model_name="fichaconceitopracas",
            name="punicao_demissao",
        ),
        migrations.RemoveField(
            model_name="fichaconceitopracas",
            name="punicao_exclusao_disciplina",
        ),
        migrations.RemoveField(
            model_name="fichaconceitopracas",
            name="punicao_licenciamento",
        ),
        migrations.RemoveField(
            model_name="fichaconceitopracas",
            name="punicao_reforma_disciplinar",
        ),
        migrations.RemoveField(
            model_name="fichaconceitopracas",
            name="punicao_suspensao",
        ),
        migrations.AddField(
            model_name="fichaconceitopracas",
            name="punicao_detencao",
            field=models.PositiveIntegerField(default=0, verbose_name="Detenção"),
        ),
        migrations.AddField(
            model_name="fichaconceitopracas",
            name="punicao_prisao",
            field=models.PositiveIntegerField(default=0, verbose_name="Prisão"),
        ),
    ]
