# Generated by Django 5.0.2 on 2025-09-21 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0168_remove_invalid_punicao_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecaoPromocoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Seção"),
                ),
                (
                    "sigla",
                    models.CharField(
                        help_text="Ex: SPPROM", max_length=20, verbose_name="Sigla"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVA", "Ativa"),
                            ("INATIVA", "Inativa"),
                            ("SUSPENSA", "Suspensa"),
                        ],
                        default="ATIVA",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "data_ativacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Ativação"
                    ),
                ),
                (
                    "data_desativacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Desativação"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "auxiliar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secoes_auxiliadas",
                        to="militares.militar",
                        verbose_name="Auxiliar da Seção",
                    ),
                ),
                (
                    "chefe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secoes_chefiadas",
                        to="militares.militar",
                        verbose_name="Chefe da Seção",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção de Promoções",
                "verbose_name_plural": "Seções de Promoções",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PermissaoSubmenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submenu",
                    models.CharField(
                        choices=[
                            ("FICHAS_OFICIAIS", "Fichas de Conceito (Oficiais)"),
                            ("FICHAS_PRACAS", "Fichas de Conceito (Praças)"),
                            ("QUADROS_ACESSO", "Quadros de Acesso"),
                            ("QUADROS_FIXACAO", "Quadros de Fixação de Vagas"),
                            ("ALMANAQUES", "Almanaques"),
                            ("PROMOCOES", "Promoções"),
                            ("CALENDARIOS", "Calendários de Promoções"),
                            ("COMISSOES", "Comissões de Promoções"),
                            ("MEUS_VOTOS", "Meus Votos"),
                            ("INTERSTICIOS", "Interstícios"),
                            ("GERENCIAR_INTERSTICIOS", "Gerenciar Interstícios"),
                            ("GERENCIAR_PREVISAO", "Gerenciar Previsão"),
                            ("GERENCIAR_SECOES", "Gerenciar Seções"),
                            ("DASHBOARD_SECOES", "Dashboard Seções"),
                            ("MILITARES", "Militares"),
                            ("USUARIOS", "Usuários"),
                            ("PERMISSOES", "Permissões"),
                            ("RELATORIOS", "Relatórios"),
                            ("CONFIGURACOES", "Configurações"),
                        ],
                        max_length=30,
                        verbose_name="Submenu",
                    ),
                ),
                (
                    "acesso",
                    models.CharField(
                        choices=[
                            ("VISUALIZAR", "Visualizar"),
                            ("CRIAR", "Criar"),
                            ("EDITAR", "Editar"),
                            ("EXCLUIR", "Excluir"),
                            ("APROVAR", "Aprovar"),
                            ("HOMOLOGAR", "Homologar"),
                            ("GERAR_PDF", "Gerar PDF"),
                            ("IMPRIMIR", "Imprimir"),
                            ("ASSINAR", "Assinar"),
                            ("ADMINISTRAR", "Administrar"),
                            ("TOTAL", "Acesso Total"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de Acesso",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "funcao_militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissoes_submenu",
                        to="militares.funcaomilitar",
                        verbose_name="Função Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permissão de Submenu",
                "verbose_name_plural": "Permissões de Submenu",
                "ordering": ["funcao_militar__nome", "submenu", "acesso"],
                "unique_together": {("funcao_militar", "submenu", "acesso")},
            },
        ),
    ]
