# Generated by Django 5.0.2 on 2025-09-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0169_add_permissao_submenu"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomilitar",
            name="almanaques_criar",
            field=models.BooleanField(default=False, verbose_name="Criar Almanaques"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="almanaques_editar",
            field=models.BooleanField(default=False, verbose_name="Editar Almanaques"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="almanaques_excluir",
            field=models.BooleanField(default=False, verbose_name="Excluir Almanaques"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="almanaques_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Almanaques"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="calendarios_criar",
            field=models.BooleanField(default=False, verbose_name="Criar Calendários"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="calendarios_editar",
            field=models.BooleanField(default=False, verbose_name="Editar Calendários"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="calendarios_excluir",
            field=models.BooleanField(
                default=False, verbose_name="Excluir Calendários"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="calendarios_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Calendários"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="comissoes_criar",
            field=models.BooleanField(default=False, verbose_name="Criar Comissões"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="comissoes_editar",
            field=models.BooleanField(default=False, verbose_name="Editar Comissões"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="comissoes_excluir",
            field=models.BooleanField(default=False, verbose_name="Excluir Comissões"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="comissoes_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Comissões"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="fichas_oficiais_criar",
            field=models.BooleanField(
                default=False, verbose_name="Criar Fichas de Oficiais"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="fichas_oficiais_editar",
            field=models.BooleanField(
                default=False, verbose_name="Editar Fichas de Oficiais"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="fichas_oficiais_excluir",
            field=models.BooleanField(
                default=False, verbose_name="Excluir Fichas de Oficiais"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="fichas_oficiais_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Fichas de Oficiais"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="fichas_pracas_criar",
            field=models.BooleanField(
                default=False, verbose_name="Criar Fichas de Praças"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="fichas_pracas_editar",
            field=models.BooleanField(
                default=False, verbose_name="Editar Fichas de Praças"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="fichas_pracas_excluir",
            field=models.BooleanField(
                default=False, verbose_name="Excluir Fichas de Praças"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="fichas_pracas_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Fichas de Praças"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="lotacoes_criar",
            field=models.BooleanField(default=False, verbose_name="Criar Lotações"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="lotacoes_editar",
            field=models.BooleanField(default=False, verbose_name="Editar Lotações"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="lotacoes_excluir",
            field=models.BooleanField(default=False, verbose_name="Excluir Lotações"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="lotacoes_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Lotações"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="pode_acessar_logs",
            field=models.BooleanField(default=False, verbose_name="Acessar Logs"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="pode_gerenciar_medalhas",
            field=models.BooleanField(default=False, verbose_name="Gerenciar Medalhas"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="pode_gerenciar_permissoes",
            field=models.BooleanField(
                default=False, verbose_name="Gerenciar Permissões"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="pode_gerenciar_usuarios",
            field=models.BooleanField(default=False, verbose_name="Gerenciar Usuários"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="promocoes_criar",
            field=models.BooleanField(default=False, verbose_name="Criar Promoções"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="promocoes_editar",
            field=models.BooleanField(default=False, verbose_name="Editar Promoções"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="promocoes_excluir",
            field=models.BooleanField(default=False, verbose_name="Excluir Promoções"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="promocoes_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Promoções"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="quadros_acesso_criar",
            field=models.BooleanField(
                default=False, verbose_name="Criar Quadros de Acesso"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="quadros_acesso_editar",
            field=models.BooleanField(
                default=False, verbose_name="Editar Quadros de Acesso"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="quadros_acesso_excluir",
            field=models.BooleanField(
                default=False, verbose_name="Excluir Quadros de Acesso"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="quadros_acesso_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Quadros de Acesso"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="quadros_fixacao_criar",
            field=models.BooleanField(
                default=False, verbose_name="Criar Quadros de Fixação"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="quadros_fixacao_editar",
            field=models.BooleanField(
                default=False, verbose_name="Editar Quadros de Fixação"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="quadros_fixacao_excluir",
            field=models.BooleanField(
                default=False, verbose_name="Excluir Quadros de Fixação"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="quadros_fixacao_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Quadros de Fixação"
            ),
        ),
    ]
