# Generated by Django 5.0.2 on 2025-09-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0170_add_crud_permissions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assinaturaalmanaque",
            old_name="cargo_funcao",
            new_name="funcao_militar",
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_elegiveis",
            field=models.BooleanField(default=False, verbose_name="Elegíveis"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_fichas_cpo",
            field=models.BooleanField(
                default=False, verbose_name="Fichas de Oficiais (CPO)"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_fichas_cpp",
            field=models.BooleanField(
                default=False, verbose_name="Fichas de Praças (CPP)"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_medalhas_concessoes",
            field=models.BooleanField(
                default=False, verbose_name="Concessões de Medalhas"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_medalhas_propostas",
            field=models.BooleanField(
                default=False, verbose_name="Propostas de Medalhas"
            ),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_propostas",
            field=models.BooleanField(default=False, verbose_name="Propostas"),
        ),
    ]
