# Generated by Django 5.0.2 on 2025-09-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0171_add_submenus_especificos"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_ativos",
            field=models.BooleanField(default=False, verbose_name="Ativos"),
        ),
    ]
