# Generated by Django 5.0.2 on 2025-09-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0172_add_menu_ativos"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomilitar",
            name="pode_transferir",
            field=models.BooleanField(
                default=False,
                help_text="Permite transferir militares entre lotações",
                verbose_name="Pode Transferir",
            ),
        ),
    ]
