# Generated by Django 5.0.2 on 2025-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0173_funcaomilitar_pode_transferir"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_secao_promocoes",
            field=models.BooleanField(default=False, verbose_name="Seção de Promoções"),
        ),
        migrations.AddField(
            model_name="funcaomilitar",
            name="menu_secao_promocoes",
            field=models.BooleanField(default=False, verbose_name="Seção de Promoções"),
        ),
    ]
