# Generated by Django 5.0.2 on 2025-09-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0174_add_menu_secao_promocoes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funcaomilitar",
            name="menu_fichas_cpo",
        ),
        migrations.RemoveField(
            model_name="funcaomilitar",
            name="menu_fichas_cpp",
        ),
    ]
