# Generated by Django 5.0.2 on 2025-09-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0177_adicionar_modulos_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissaofuncao",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("MENU_SECAO_PROMOCOES", "Seção de Promoções"),
                    ("MENU_FICHAS_OFICIAIS", "Fichas Oficiais"),
                    ("MENU_FICHAS_PRACAS", "Fichas Praças"),
                    ("MENU_CALENDARIOS", "Calendários"),
                    ("MENU_QUADROS_FIXACAO", "Quadros Fixação"),
                    ("MENU_QUADROS_ACESSO", "Quadros Acesso"),
                    ("MENU_COMISSOES", "Comissões"),
                    ("MENU_MEUS_VOTOS", "Meus Votos"),
                    ("MENU_PROMOCOES", "Promoções"),
                    ("MENU_ALMANAQUES", "Almanaques"),
                    ("MENU_EFETIVO", "Efetivo"),
                    ("MENU_ATIVOS", "Ativos"),
                    ("MENU_INATIVOS", "Inativos"),
                    ("MENU_LOTACOES", "Lotações"),
                    ("MENU_MEDALHAS", "Medalhas"),
                    ("MENU_MEDALHAS_CONCESSOES", "Concessões de Medalhas"),
                    ("MENU_MEDALHAS_PROPOSTAS", "Propostas de Medalhas"),
                    ("MENU_ELEGIVEIS", "Elegíveis"),
                    ("MENU_PROPOSTAS", "Propostas"),
                    ("MENU_INTERSTICIOS", "Interstícios"),
                    ("MENU_GERENCIAR_INTERSTICIOS", "Gerenciar Interstícios"),
                    ("MENU_GERENCIAR_PREVISAO", "Gerenciar Previsão"),
                    ("MENU_USUARIOS", "Usuários"),
                    ("MENU_PERMISSOES", "Permissões"),
                    ("MENU_LOGS", "Logs"),
                    ("MENU_ADMINISTRACAO", "Administração"),
                    ("MENU_DASHBOARD", "Dashboard"),
                    ("MENU_RELATORIOS", "Relatórios"),
                    ("MENU_CONFIGURACOES", "Configurações"),
                ],
                max_length=50,
                verbose_name="Módulo",
            ),
        ),
    ]
