# Generated by Django 5.0.2 on 2025-09-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0179_adicionar_permissoes_botoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissaofuncao",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("MENU_SECAO_PROMOCOES", "Seção de Promoções"),
                    ("MENU_FICHAS_OFICIAIS", "Fichas Oficiais"),
                    ("MENU_FICHAS_PRACAS", "Fichas Praças"),
                    ("MENU_CALENDARIOS", "Calendários"),
                    ("MENU_QUADROS_FIXACAO", "Quadros Fixação"),
                    ("MENU_QUADROS_ACESSO", "Quadros Acesso"),
                    ("MENU_COMISSOES", "Comissões"),
                    ("MENU_MEUS_VOTOS", "Meus Votos"),
                    ("MENU_PROMOCOES", "Promoções"),
                    ("MENU_ALMANAQUES", "Almanaques"),
                    ("MENU_EFETIVO", "Efetivo"),
                    ("MENU_ATIVOS", "Ativos"),
                    ("MENU_INATIVOS", "Inativos"),
                    ("MENU_LOTACOES", "Lotações"),
                    ("MENU_MEDALHAS", "Medalhas"),
                    ("MENU_MEDALHAS_CONCESSOES", "Concessões de Medalhas"),
                    ("MENU_MEDALHAS_PROPOSTAS", "Propostas de Medalhas"),
                    ("MENU_ELEGIVEIS", "Elegíveis"),
                    ("MENU_PROPOSTAS", "Propostas"),
                    ("MENU_INTERSTICIOS", "Interstícios"),
                    ("MENU_GERENCIAR_INTERSTICIOS", "Gerenciar Interstícios"),
                    ("MENU_GERENCIAR_PREVISAO", "Gerenciar Previsão"),
                    ("MENU_USUARIOS", "Usuários"),
                    ("MENU_PERMISSOES", "Permissões"),
                    ("MENU_LOGS", "Logs"),
                    ("MENU_ADMINISTRACAO", "Administração"),
                    ("MENU_DASHBOARD", "Dashboard"),
                    ("MENU_RELATORIOS", "Relatórios"),
                    ("MENU_CONFIGURACOES", "Configurações"),
                    ("BOTAO_CRIAR", "Botão - Criar"),
                    ("BOTAO_EDITAR", "Botão - Editar"),
                    ("BOTAO_EXCLUIR", "Botão - Excluir"),
                    ("BOTAO_ATIVAR", "Botão - Ativar"),
                    ("BOTAO_INATIVAR", "Botão - Inativar"),
                    ("BOTAO_APROVAR", "Botão - Aprovar"),
                    ("BOTAO_HOMOLOGAR", "Botão - Homologar"),
                    ("BOTAO_ASSINAR", "Botão - Assinar"),
                    ("BOTAO_VOTAR", "Botão - Votar"),
                    ("BOTAO_GERAR_PDF", "Botão - Gerar PDF"),
                    ("BOTAO_IMPRIMIR", "Botão - Imprimir"),
                    ("BOTAO_EXPORTAR_EXCEL", "Botão - Exportar Excel"),
                    ("BOTAO_EXPORTAR_PDF", "Botão - Exportar PDF"),
                    ("BOTAO_REORDENAR", "Botão - Reordenar"),
                    ("BOTAO_CONFIGURAR", "Botão - Configurar"),
                ],
                max_length=50,
                verbose_name="Módulo",
            ),
        ),
    ]
