# Generated by Django 5.0.2 on 2025-09-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0180_simplificar_botoes_paginas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissaofuncao",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("MENU_SECAO_PROMOCOES", "Seção de Promoções"),
                    ("MENU_EFETIVO", "Efetivo"),
                    ("MENU_MEDALHAS", "Medalhas"),
                    ("MENU_CONFIGURACOES", "Configurações"),
                    ("MENU_DASHBOARD", "Dashboard"),
                    ("MENU_RELATORIOS", "Relatórios"),
                    ("SUBMENU_FICHAS_OFICIAIS", "Fichas Oficiais"),
                    ("SUBMENU_FICHAS_PRACAS", "Fichas Praças"),
                    ("SUBMENU_CALENDARIOS", "Calendários"),
                    ("SUBMENU_QUADROS_FIXACAO", "Quadros Fixação"),
                    ("SUBMENU_QUADROS_ACESSO", "Quadros Acesso"),
                    ("SUBMENU_COMISSOES", "Comissões"),
                    ("SUBMENU_MEUS_VOTOS", "Meus Votos"),
                    ("SUBMENU_PROMOCOES", "Promoções"),
                    ("SUBMENU_ALMANAQUES", "Almanaques"),
                    ("SUBMENU_ATIVOS", "Ativos"),
                    ("SUBMENU_INATIVOS", "Inativos"),
                    ("SUBMENU_LOTACOES", "Lotações"),
                    ("SUBMENU_MEDALHAS_CONCESSOES", "Concessões de Medalhas"),
                    ("SUBMENU_MEDALHAS_PROPOSTAS", "Propostas de Medalhas"),
                    ("SUBMENU_ELEGIVEIS", "Elegíveis"),
                    ("SUBMENU_PROPOSTAS", "Propostas"),
                    ("SUBMENU_INTERSTICIOS", "Interstícios"),
                    ("SUBMENU_GERENCIAR_INTERSTICIOS", "Gerenciar Interstícios"),
                    ("SUBMENU_GERENCIAR_PREVISAO", "Gerenciar Previsão"),
                    ("SUBMENU_USUARIOS", "Usuários"),
                    ("SUBMENU_PERMISSOES", "Permissões"),
                    ("SUBMENU_LOGS", "Logs"),
                    ("SUBMENU_ADMINISTRACAO", "Administração"),
                ],
                max_length=50,
                verbose_name="Módulo",
            ),
        ),
    ]
