# Generated by Django 5.0.2 on 2025-09-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0181_sistema_hierarquico_menus"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_elegiveis",
            field=models.BooleanField(default=False, verbose_name="Elegíveis"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_medalhas_concessoes",
            field=models.BooleanField(
                default=False, verbose_name="Concessões de Medalhas"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_medalhas_propostas",
            field=models.BooleanField(
                default=False, verbose_name="Propostas de Medalhas"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_propostas",
            field=models.BooleanField(default=False, verbose_name="Propostas"),
        ),
    ]
