# Generated by Django 5.0.2 on 2025-09-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0182_add_medalhas_submenu_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="almanaques_assinar",
            field=models.BooleanField(default=False, verbose_name="Assinar Almanaques"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="almanaques_criar",
            field=models.BooleanField(default=False, verbose_name="Criar Almanaques"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="almanaques_editar",
            field=models.BooleanField(default=False, verbose_name="Editar Almanaques"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="almanaques_excluir",
            field=models.BooleanField(default=False, verbose_name="Excluir Almanaques"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="almanaques_gerar_pdf",
            field=models.BooleanField(
                default=False, verbose_name="Gerar PDF Almanaques"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="almanaques_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Almanaques"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="calendarios_criar",
            field=models.BooleanField(default=False, verbose_name="Criar Calendários"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="calendarios_editar",
            field=models.BooleanField(default=False, verbose_name="Editar Calendários"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="calendarios_excluir",
            field=models.BooleanField(
                default=False, verbose_name="Excluir Calendários"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="calendarios_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Calendários"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="comissoes_criar",
            field=models.BooleanField(default=False, verbose_name="Criar Comissões"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="comissoes_editar",
            field=models.BooleanField(default=False, verbose_name="Editar Comissões"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="comissoes_excluir",
            field=models.BooleanField(default=False, verbose_name="Excluir Comissões"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="comissoes_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Comissões"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="meus_votos_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Meus Votos"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="meus_votos_votar",
            field=models.BooleanField(default=False, verbose_name="Votar"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="promocoes_criar",
            field=models.BooleanField(default=False, verbose_name="Criar Promoções"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="promocoes_editar",
            field=models.BooleanField(default=False, verbose_name="Editar Promoções"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="promocoes_excluir",
            field=models.BooleanField(default=False, verbose_name="Excluir Promoções"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="promocoes_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Promoções"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="quadros_fixacao_assinar",
            field=models.BooleanField(
                default=False, verbose_name="Assinar Quadros de Fixação"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="quadros_fixacao_criar",
            field=models.BooleanField(
                default=False, verbose_name="Criar Quadros de Fixação"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="quadros_fixacao_editar",
            field=models.BooleanField(
                default=False, verbose_name="Editar Quadros de Fixação"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="quadros_fixacao_excluir",
            field=models.BooleanField(
                default=False, verbose_name="Excluir Quadros de Fixação"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="quadros_fixacao_gerar_pdf",
            field=models.BooleanField(
                default=False, verbose_name="Gerar PDF Quadros de Fixação"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="quadros_fixacao_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Quadros de Fixação"
            ),
        ),
    ]
