# Generated by Django 5.0.2 on 2025-09-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0183_add_secao_promocoes_botoes_permissoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="fichas_oficiais_criar",
            field=models.BooleanField(
                default=False, verbose_name="Criar Fichas de Oficiais"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="fichas_oficiais_editar",
            field=models.BooleanField(
                default=False, verbose_name="Editar Fichas de Oficiais"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="fichas_oficiais_excluir",
            field=models.BooleanField(
                default=False, verbose_name="Excluir Fichas de Oficiais"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="fichas_oficiais_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Fichas de Oficiais"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="fichas_pracas_criar",
            field=models.BooleanField(
                default=False, verbose_name="Criar Fichas de Praças"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="fichas_pracas_editar",
            field=models.BooleanField(
                default=False, verbose_name="Editar Fichas de Praças"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="fichas_pracas_excluir",
            field=models.BooleanField(
                default=False, verbose_name="Excluir Fichas de Praças"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="fichas_pracas_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Fichas de Praças"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="quadros_acesso_criar",
            field=models.BooleanField(
                default=False, verbose_name="Criar Quadros de Acesso"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="quadros_acesso_editar",
            field=models.BooleanField(
                default=False, verbose_name="Editar Quadros de Acesso"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="quadros_acesso_excluir",
            field=models.BooleanField(
                default=False, verbose_name="Excluir Quadros de Acesso"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="quadros_acesso_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Quadros de Acesso"
            ),
        ),
    ]
