# Generated by Django 5.0.2 on 2025-09-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0185_add_tipo_comissao_to_funcao_militar"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariofuncaomilitar",
            name="tipo_funcao",
            field=models.CharField(
                choices=[
                    ("PRINCIPAL", "Principal"),
                    ("ADICIONAL", "Adicional"),
                    ("TEMPORARIA", "Temporária"),
                    ("COMISSAO", "Comissão"),
                ],
                default="PRINCIPAL",
                help_text="Define o tipo da função: Principal (obrigatória), Adicional, Temporária ou Comissão",
                max_length=20,
                verbose_name="Tipo de Função",
            ),
        ),
    ]
