# Generated by Django 5.0.2 on 2025-09-26 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0186_add_tipo_funcao_to_usuario_funcao_militar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funcaomenuconfig",
            options={
                "ordering": ["-data_criacao"],
                "permissions": [
                    ("can_manage_notas", "Pode gerenciar notas"),
                    ("can_review_notas", "Pode revisar notas"),
                    ("can_approve_notas", "Pode aprovar notas"),
                    ("can_publish_notas", "Pode publicar notas"),
                ],
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
            },
        ),
        migrations.AlterField(
            model_name="permissaofuncao",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("MENU_SECAO_PROMOCOES", "Seção de Promoções"),
                    ("MENU_EFETIVO", "Efetivo"),
                    ("MENU_MEDALHAS", "Medalhas"),
                    ("MENU_CONFIGURACOES", "Configurações"),
                    ("MENU_DASHBOARD", "Dashboard"),
                    ("MENU_RELATORIOS", "Relatórios"),
                    ("SUBMENU_FICHAS_OFICIAIS", "Fichas Oficiais"),
                    ("SUBMENU_FICHAS_PRACAS", "Fichas Praças"),
                    ("SUBMENU_CALENDARIOS", "Calendários"),
                    ("SUBMENU_QUADROS_FIXACAO", "Quadros Fixação"),
                    ("SUBMENU_QUADROS_ACESSO", "Quadros Acesso"),
                    ("SUBMENU_COMISSOES", "Comissões"),
                    ("SUBMENU_MEUS_VOTOS", "Meus Votos"),
                    ("SUBMENU_PROMOCOES", "Promoções"),
                    ("SUBMENU_ALMANAQUES", "Almanaques"),
                    ("SUBMENU_ATIVOS", "Ativos"),
                    ("SUBMENU_INATIVOS", "Inativos"),
                    ("SUBMENU_LOTACOES", "Lotações"),
                    ("ATIVOS_VISUALIZAR", "Visualizar Militares Ativos"),
                    ("ATIVOS_CRIAR", "Criar Militares Ativos"),
                    ("ATIVOS_EDITAR", "Editar Militares Ativos"),
                    ("ATIVOS_EXCLUIR", "Excluir Militares Ativos"),
                    ("ATIVOS_TRANSFERIR", "Transferir Militares Ativos"),
                    ("ATIVOS_PROMOVER", "Promover Militares Ativos"),
                    ("ATIVOS_INATIVAR", "Inativar Militares Ativos"),
                    ("ATIVOS_FICHA_CONCEITO", "Gerenciar Fichas de Conceito"),
                    ("ATIVOS_EXPORTAR", "Exportar Militares Ativos"),
                    ("ATIVOS_DASHBOARD", "Dashboard Militares Ativos"),
                    ("ATIVOS_REORDENAR", "Reordenar Militares Ativos"),
                    ("INATIVOS_VISUALIZAR", "Visualizar Militares Inativos"),
                    ("INATIVOS_EDITAR", "Editar Militares Inativos"),
                    ("INATIVOS_EXCLUIR", "Excluir Militares Inativos"),
                    ("INATIVOS_REATIVAR", "Reativar Militares Inativos"),
                    ("LOTACOES_VISUALIZAR", "Visualizar Lotações"),
                    ("LOTACOES_CRIAR", "Criar Lotações"),
                    ("LOTACOES_EDITAR", "Editar Lotações"),
                    ("LOTACOES_EXCLUIR", "Excluir Lotações"),
                    ("DETAIL_FICHAS_CONCEITO", "Visualizar Fichas de Conceito"),
                    ("DETAIL_PUNICOES", "Visualizar Punições e Elogios"),
                    ("DETAIL_MEDALHAS", "Visualizar Medalhas"),
                    ("DETAIL_CONTATO", "Visualizar Contato"),
                    ("QUADROS_FIXACAO_VISUALIZAR", "Visualizar Quadros de Fixação"),
                    ("QUADROS_FIXACAO_CRIAR", "Criar Quadros de Fixação"),
                    ("QUADROS_FIXACAO_EDITAR", "Editar Quadros de Fixação"),
                    ("QUADROS_FIXACAO_EXCLUIR", "Excluir Quadros de Fixação"),
                    ("QUADROS_ACESSO_VISUALIZAR", "Visualizar Quadros de Acesso"),
                    ("QUADROS_ACESSO_CRIAR", "Criar Quadros de Acesso"),
                    ("QUADROS_ACESSO_EDITAR", "Editar Quadros de Acesso"),
                    ("QUADROS_ACESSO_EXCLUIR", "Excluir Quadros de Acesso"),
                    (
                        "COMISSOES_OFICIAIS_VISUALIZAR",
                        "Visualizar Comissões de Oficiais",
                    ),
                    ("COMISSOES_OFICIAIS_CRIAR", "Criar Comissões de Oficiais"),
                    ("COMISSOES_OFICIAIS_EDITAR", "Editar Comissões de Oficiais"),
                    ("COMISSOES_OFICIAIS_EXCLUIR", "Excluir Comissões de Oficiais"),
                    ("COMISSOES_PRACAS_VISUALIZAR", "Visualizar Comissões de Praças"),
                    ("COMISSOES_PRACAS_CRIAR", "Criar Comissões de Praças"),
                    ("COMISSOES_PRACAS_EDITAR", "Editar Comissões de Praças"),
                    ("COMISSOES_PRACAS_EXCLUIR", "Excluir Comissões de Praças"),
                    ("QUADROS_ACESSO_ASSINAR", "Assinar Quadros de Acesso"),
                    ("QUADROS_ACESSO_HOMOLOGAR", "Homologar Quadros de Acesso"),
                    ("QUADROS_ACESSO_DESHOMOLOGAR", "Deshomologar Quadros de Acesso"),
                    ("QUADROS_ACESSO_ELABORAR", "Elaborar Quadros de Acesso"),
                    ("QUADROS_ACESSO_REGENERAR", "Regenerar Quadros de Acesso"),
                    ("QUADROS_ACESSO_GERAR_PDF", "Gerar PDF de Quadros de Acesso"),
                    ("SUBMENU_MEDALHAS_CONCESSOES", "Concessões de Medalhas"),
                    ("SUBMENU_MEDALHAS_PROPOSTAS", "Propostas de Medalhas"),
                    ("SUBMENU_ELEGIVEIS", "Elegíveis"),
                    ("SUBMENU_PROPOSTAS", "Propostas"),
                    ("SUBMENU_NOTAS_LISTA", "Lista de Notas"),
                    ("NOTAS_VISUALIZAR", "Visualizar Notas"),
                    ("NOTAS_CRIAR", "Criar Notas"),
                    ("NOTAS_EDITAR", "Editar Notas"),
                    ("NOTAS_EXCLUIR", "Excluir Notas"),
                    ("NOTAS_REVISAR", "Revisar Notas"),
                    ("NOTAS_APROVAR", "Aprovar Notas"),
                    ("NOTAS_PUBLICAR", "Publicar Notas"),
                    ("NOTAS_ADMINISTRAR", "Administrar Notas"),
                    ("SUBMENU_INTERSTICIOS", "Interstícios"),
                    ("SUBMENU_GERENCIAR_INTERSTICIOS", "Gerenciar Interstícios"),
                    ("SUBMENU_GERENCIAR_PREVISAO", "Gerenciar Previsão"),
                    ("SUBMENU_USUARIOS", "Usuários"),
                    ("SUBMENU_PERMISSOES", "Permissões"),
                    ("SUBMENU_LOGS", "Logs"),
                    ("SUBMENU_ADMINISTRACAO", "Administração"),
                ],
                max_length=50,
                verbose_name="Módulo",
            ),
        ),
        migrations.CreateModel(
            name="TituloPublicacaoConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ordem de exibição (deixe vazio para ordem automática)",
                        null=True,
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título da publicação",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PORTARIA", "Portaria"),
                            ("ORDEM_SERVICO", "Ordem de Serviço"),
                            ("INSTRUCAO", "Instrução"),
                            ("CIRCULAR", "Circular"),
                            ("COMUNICADO", "Comunicado"),
                            ("EDITAL", "Edital"),
                            ("RESOLUCAO", "Resolução"),
                            ("DECRETO", "Decreto"),
                            ("LEI", "Lei"),
                            ("OUTROS", "Outros"),
                        ],
                        default="PORTARIA",
                        help_text="Tipo da publicação",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "topicos",
                    models.TextField(
                        blank=True,
                        help_text="Tópicos ou descrição da publicação (um por linha)",
                        verbose_name="Tópicos",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Se este título está ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="titulos_publicacao_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Título de Publicação",
                "verbose_name_plural": "Configurações de Títulos de Publicações",
                "ordering": ["ordem", "titulo"],
            },
        ),
    ]
