# Generated by Django 5.0.2 on 2025-09-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0186_add_tipo_funcao_to_usuario_funcao_militar"),
    ]

    operations = []
