# Generated by Django 5.0.2 on 2025-09-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0187_alter_funcaomenuconfig_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_titulos_publicacao",
            field=models.BooleanField(
                default=False, verbose_name="Títulos de Publicações"
            ),
        ),
    ]
