# Generated by Django 5.0.2 on 2025-09-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0187_add_notas_module"),
    ]

    operations = [
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_notas',
            field=models.BooleanField(default=True, verbose_name='Notas'),
        ),
    ]
