# Generated by Django 5.0.2 on 2025-09-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0188_funcaomenuconfig_show_titulos_publicacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titulopublicacaoconfig",
            name="topicos",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Selecione os tópicos..."),
                    ("1_PARTE_SERVICOS_DIARIOS", "1ª PARTE - SERVIÇOS DIÁRIOS"),
                    ("2_PARTE_INSTRUCAO", "2ª PARTE - INSTRUÇÃO"),
                    ("3_PARTE_ASSUNTOS_GERAIS", "3ª PARTE - ASSUNTOS GERAIS"),
                    ("3_PARTE_ADMINISTRATIVOS", "3ª PARTE - ADMINISTRATIVOS"),
                    ("4_PARTE_JUSTICA", "4ª PARTE - JUSTIÇA"),
                    ("4_PARTE_DISCIPLINA", "4ª PARTE - DISCIPLINA"),
                    ("5_PARTE_PROMOCOES", "5ª PARTE - PROMOÇÕES"),
                    ("6_PARTE_DESIGNACOES", "6ª PARTE - DESIGNAÇÕES"),
                    ("7_PARTE_TRANSFERENCIAS", "7ª PARTE - TRANSFERÊNCIAS"),
                    ("8_PARTE_APOSENTADORIAS", "8ª PARTE - APOSENTADORIAS"),
                    ("9_PARTE_FALECIMENTOS", "9ª PARTE - FALECIMENTOS"),
                    ("10_PARTE_CONDECORACOES", "10ª PARTE - CONDECORAÇÕES"),
                    ("11_PARTE_CURSOS", "11ª PARTE - CURSOS"),
                    ("12_PARTE_FERIAS", "12ª PARTE - FÉRIAS"),
                    ("13_PARTE_LICENCAS", "13ª PARTE - LICENÇAS"),
                    ("14_PARTE_PUNICOES", "14ª PARTE - PUNIÇÕES"),
                    ("15_PARTE_ELOGIOS", "15ª PARTE - ELOGIOS"),
                    ("16_PARTE_ORDEM_UNIDADE", "16ª PARTE - ORDEM DA UNIDADE"),
                    ("17_PARTE_ACIDENTES", "17ª PARTE - ACIDENTES"),
                    ("18_PARTE_VIATURAS", "18ª PARTE - VIATURAS"),
                    ("19_PARTE_EQUIPAMENTOS", "19ª PARTE - EQUIPAMENTOS"),
                    ("20_PARTE_OUTROS", "20ª PARTE - OUTROS"),
                ],
                help_text="Selecione os tópicos da publicação",
                max_length=50,
                null=True,
                verbose_name="Tópicos",
            ),
        ),
    ]
