# Generated by Django 5.0.2 on 2025-09-25 23:40

from django.db import migrations


def update_show_notas_default(apps, schema_editor):
    FuncaoMenuConfig = apps.get_model('militares', 'FuncaoMenuConfig')
    # Atualizar todas as configurações existentes para ter show_notas=True
    FuncaoMenuConfig.objects.all().update(show_notas=True)


def reverse_update_show_notas_default(apps, schema_editor):
    FuncaoMenuConfig = apps.get_model('militares', 'FuncaoMenuConfig')
    # Reverter para False (opcional)
    FuncaoMenuConfig.objects.all().update(show_notas=False)


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0188_add_show_notas_field"),
    ]

    operations = [
        migrations.RunPython(update_show_notas_default, reverse_update_show_notas_default),
    ]
