# Generated by Django 5.0.2 on 2025-09-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0189_update_show_notas_default"),
    ]

    operations = [
        # NOTA: Esta migração foi uma duplicata da 0188_add_show_notas_field
        # O campo show_notas já foi adicionado na migração 0188
        # Mantendo a migração vazia para preservar a numeração
    ]
