# Generated by Django 5.0.2 on 2025-09-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0189_alter_titulopublicacaoconfig_topicos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titulopublicacaoconfig",
            name="topicos",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Selecione os tópicos..."),
                    ("1_PARTE_SERVICOS_DIARIOS", "1ª PARTE - SERVIÇOS DIÁRIOS"),
                    ("2_PARTE_INSTRUCAO", "2ª PARTE - INSTRUÇÃO"),
                    ("3_PARTE_ASSUNTOS_GERAIS", "3ª PARTE - ASSUNTOS GERAIS"),
                    ("3_PARTE_ADMINISTRATIVOS", "3ª PARTE - ADMINISTRATIVOS"),
                    ("4_PARTE_JUSTICA", "4ª PARTE - JUSTIÇA"),
                    ("4_PARTE_DISCIPLINA", "4ª PARTE - DISCIPLINA"),
                ],
                help_text="Selecione os tópicos da publicação",
                max_length=50,
                null=True,
                verbose_name="Tópicos",
            ),
        ),
    ]
