# Generated by Django 5.0.2 on 2025-09-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0190_add_show_notas_field_v2"),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcaomenuconfig',
            name='show_notas',
            field=models.BooleanField(default=True, verbose_name='Notas'),
        ),
    ]
