# Generated by Django 5.0.2 on 2025-09-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0190_alter_titulopublicacaoconfig_topicos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titulopublicacaoconfig",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("", "Selecione o tipo..."),
                    ("OSTENSIVO", "Ostensivo"),
                    ("RESERVADO", "Reservado"),
                ],
                default="PORTARIA",
                help_text="Tipo da publicação",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
