# Generated by Django 5.0.2 on 2025-09-26 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0191_alter_titulopublicacaoconfig_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="titulopublicacaoconfig",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("", "Selecione o tipo..."),
                    ("OSTENSIVO", "Ostensivo"),
                    ("RESERVADO", "Reservado"),
                    ("ESPECIAL", "Especial"),
                ],
                default="PORTARIA",
                help_text="Tipo da publicação",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.CreateModel(
            name="Publicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Número da publicação (ex: 001/2024)",
                        max_length=50,
                        verbose_name="Número",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título da publicação",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NOTA", "Nota"),
                            ("BOLETIM_OSTENSIVO", "Boletim Ostensivo"),
                            ("BOLETIM_RESERVADO", "Boletim Reservado"),
                            ("BOLETIM_ESPECIAL", "Boletim Especial"),
                        ],
                        help_text="Tipo da publicação",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("PUBLICADO", "Publicado"),
                            ("ARQUIVADO", "Arquivado"),
                        ],
                        default="RASCUNHO",
                        help_text="Status da publicação",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(
                        help_text="Conteúdo da publicação", verbose_name="Conteúdo"
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora da publicação",
                        null=True,
                        verbose_name="Data de Publicação",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Se esta publicação está ativa",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publicacoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "publicado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publicacoes_publicadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Publicado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publicação",
                "verbose_name_plural": "Publicações",
                "ordering": ["-data_publicacao", "-data_criacao"],
                "unique_together": {("numero", "tipo")},
            },
        ),
    ]
