# Generated by Django 5.0.2 on 2025-09-26 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0193_add_origem_publicacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacao",
            name="grande_comando",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publicacoes",
                to="militares.grandecomando",
                verbose_name="Grande Comando",
            ),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="orgao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publicacoes",
                to="militares.orgao",
                verbose_name="Órgão",
            ),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="sub_unidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publicacoes",
                to="militares.subunidade",
                verbose_name="Sub-Unidade",
            ),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="unidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publicacoes",
                to="militares.unidade",
                verbose_name="Unidade",
            ),
        ),
    ]
