# Generated by Django 5.0.2 on 2025-09-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0195_add_new_publication_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacao",
            name="tipo_publicacao",
            field=models.CharField(
                blank=True,
                help_text="Tipo específico da publicação (ex: Portaria, Instrução, etc.)",
                max_length=50,
                null=True,
                verbose_name="Tipo de Publicação",
            ),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="topicos",
            field=models.CharField(
                blank=True,
                help_text="Tópicos da publicação (ex: 1ª PARTE - SERVIÇOS DIÁRIOS)",
                max_length=200,
                null=True,
                verbose_name="Tópicos",
            ),
        ),
    ]
