# Generated by Django 5.0.2 on 2025-09-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0196_publicacao_tipo_publicacao_publicacao_topicos"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacao",
            name="numero_boletim",
            field=models.CharField(
                blank=True,
                help_text="Número do boletim onde esta nota foi publicada",
                max_length=50,
                null=True,
                verbose_name="Número do Boletim",
            ),
        ),
    ]
