# Generated by Django 5.0.2 on 2025-09-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0197_publicacao_numero_boletim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("RASCUNHO", "Rascunho"),
                    ("REVISADA", "Revisada"),
                    ("APROVADA", "Aprovada"),
                    ("EDITADA", "Editada"),
                    ("PUBLICADA", "Publicada"),
                    ("ARQUIVADA", "Arquivada"),
                ],
                default="RASCUNHO",
                help_text="Status da publicação",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
