# Generated by Django 5.0.2 on 2025-09-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0198_alter_publicacao_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacao",
            name="militares_indexados",
            field=models.ManyToManyField(
                blank=True,
                help_text="Militares mencionados ou relacionados a esta publicação",
                related_name="publicacoes_indexadas",
                to="militares.militar",
                verbose_name="Militares Indexados",
            ),
        ),
    ]
