# Generated by Django 5.0.2 on 2025-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0199_add_militares_indexados_to_publicacao'),
    ]

    operations = [
        # NOTA: Esta migração foi uma duplicata da 0199_add_militares_indexados_to_publicacao
        # O campo militares_indexados já foi adicionado na migração anterior
        # Mantendo a migração vazia para preservar a numeração
    ]
