# Generated by Django 5.0.2 on 2025-09-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0191_force_show_notas_field"),
        ("militares", "0200_add_militares_indexados_to_publicacao"),
    ]

    operations = []
