# Generated by Django 5.0.2 on 2025-09-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0201_merge_20250928_1037"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_ativos",
            field=models.BooleanField(default=False, verbose_name="Militares Ativos"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_avisos",
            field=models.BooleanField(default=False, verbose_name="Avisos"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_boletins_especiais",
            field=models.BooleanField(default=False, verbose_name="Boletins Especiais"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_boletins_ostensivos",
            field=models.BooleanField(
                default=False, verbose_name="Boletins Ostensivos"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_boletins_reservados",
            field=models.BooleanField(
                default=False, verbose_name="Boletins Reservados"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_configuracoes",
            field=models.BooleanField(default=False, verbose_name="Configurações"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_ordens_servico",
            field=models.BooleanField(default=False, verbose_name="Ordens de Serviço"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_publicacoes",
            field=models.BooleanField(default=False, verbose_name="Publicações"),
        ),
        migrations.AlterField(
            model_name="funcaomenuconfig",
            name="show_calendarios",
            field=models.BooleanField(
                default=False, verbose_name="Calendários de Promoções"
            ),
        ),
        migrations.AlterField(
            model_name="funcaomenuconfig",
            name="show_comissoes",
            field=models.BooleanField(
                default=False, verbose_name="Comissões de Promoções"
            ),
        ),
        migrations.AlterField(
            model_name="funcaomenuconfig",
            name="show_fichas_oficiais",
            field=models.BooleanField(
                default=False, verbose_name="Fichas de Conceito (Oficiais)"
            ),
        ),
        migrations.AlterField(
            model_name="funcaomenuconfig",
            name="show_fichas_pracas",
            field=models.BooleanField(
                default=False, verbose_name="Fichas de Conceito (Praças)"
            ),
        ),
        migrations.AlterField(
            model_name="funcaomenuconfig",
            name="show_gerenciar_previsao",
            field=models.BooleanField(
                default=False, verbose_name="Gerenciar Previsão de Vagas"
            ),
        ),
        migrations.AlterField(
            model_name="funcaomenuconfig",
            name="show_inativos",
            field=models.BooleanField(default=False, verbose_name="Militares Inativos"),
        ),
        migrations.AlterField(
            model_name="funcaomenuconfig",
            name="show_logs",
            field=models.BooleanField(default=False, verbose_name="Logs do Sistema"),
        ),
        migrations.AlterField(
            model_name="funcaomenuconfig",
            name="show_notas",
            field=models.BooleanField(default=False, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="funcaomenuconfig",
            name="show_permissoes",
            field=models.BooleanField(default=False, verbose_name="Funções Militares"),
        ),
        migrations.AlterField(
            model_name="funcaomenuconfig",
            name="show_quadros_fixacao",
            field=models.BooleanField(
                default=False, verbose_name="Quadros de Fixação de Vagas"
            ),
        ),
        migrations.AlterField(
            model_name="funcaomenuconfig",
            name="show_usuarios",
            field=models.BooleanField(default=False, verbose_name="Gerenciar Usuários"),
        ),
    ]
