# Generated by Django 5.0.2 on 2025-09-29 14:02

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0203_add_assinatura_nota"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloNota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Modelo"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "tipo_publicacao",
                    models.CharField(
                        choices=[
                            ("NOTA", "Nota"),
                            ("BOLETIM_OSTENSIVO", "Boletim Ostensivo"),
                            ("GERAL", "Geral (Todos os tipos)"),
                        ],
                        default="NOTA",
                        max_length=20,
                        verbose_name="Tipo de Publicação",
                    ),
                ),
                (
                    "conteudo",
                    django_ckeditor_5.fields.CKEditor5Field(
                        help_text="Conteúdo HTML do modelo de nota",
                        verbose_name="Conteúdo do Modelo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "padrao",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, será usado como modelo padrão para novas notas",
                        verbose_name="Modelo Padrão",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Nota",
                "verbose_name_plural": "Modelos de Nota",
                "ordering": ["-padrao", "nome"],
            },
        ),
    ]
