# Generated by Django 5.0.2 on 2025-09-29 15:26

import django.db.models.deletion
import militares.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0204_add_modelo_nota"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnexoNota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        help_text="Arquivo anexado à nota",
                        upload_to=militares.models.anexo_upload_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "nome_original",
                    models.CharField(
                        help_text="Nome original do arquivo",
                        max_length=255,
                        verbose_name="Nome Original",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        help_text="Descrição opcional do anexo",
                        max_length=200,
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "tamanho",
                    models.PositiveIntegerField(
                        help_text="Tamanho do arquivo em bytes",
                        verbose_name="Tamanho (bytes)",
                    ),
                ),
                (
                    "tipo_mime",
                    models.CharField(
                        help_text="Tipo MIME do arquivo",
                        max_length=100,
                        verbose_name="Tipo MIME",
                    ),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Upload"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Se o anexo está ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "publicacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="militares.publicacao",
                        verbose_name="Publicação",
                    ),
                ),
                (
                    "upload_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anexos_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Upload por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo de Nota",
                "verbose_name_plural": "Anexos de Nota",
                "ordering": ["-data_upload"],
            },
        ),
    ]
