# Generated by Django 5.0.2 on 2025-09-29 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0208_fix_anexo_foreign_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="anexonota",
            name="tipo_mime",
            field=models.CharField(
                help_text="Tipo MIME do arquivo",
                max_length=100,
                verbose_name="Tipo MIME",
            ),
        ),
        migrations.CreateModel(
            name="HistoricoDevolucaoNota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_devolucao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Devolução"
                    ),
                ),
                (
                    "motivo_devolucao",
                    models.TextField(verbose_name="Motivo da Devolução"),
                ),
                (
                    "assinaturas_removidas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Assinaturas Removidas"
                    ),
                ),
                (
                    "devolvido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Devolvido por",
                    ),
                ),
                (
                    "nota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_devolucoes",
                        to="militares.publicacao",
                        verbose_name="Nota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Devolução",
                "verbose_name_plural": "Histórico de Devoluções",
                "ordering": ["-data_devolucao"],
            },
        ),
    ]
