# Generated by Django 5.0.2 on 2025-09-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0209_add_historico_devolucao"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacao",
            name="editada_apos_devolucao",
            field=models.BooleanField(
                default=False,
                help_text="Indica se a nota foi editada após ser devolvida",
                verbose_name="Editada Após Devolução",
            ),
        ),
    ]
