# Generated by Django 5.0.2 on 2025-09-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0210_add_editada_apos_devolucao"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacao",
            name="data_boletim",
            field=models.DateField(
                blank=True,
                help_text="Data de criação do boletim para controle diário",
                null=True,
                verbose_name="Data do Boletim",
            ),
        ),
        migrations.AlterField(
            model_name="publicacao",
            name="numero",
            field=models.CharField(
                blank=True,
                help_text="Número da publicação (ex: 001/2024)",
                max_length=50,
                verbose_name="Número",
            ),
        ),
    ]
