# Generated by Django 5.0.2 on 2025-09-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0211_publicacao_data_boletim_alter_publicacao_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacao",
            name="data_disponibilizacao",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e hora em que o boletim foi disponibilizado",
                null=True,
                verbose_name="Data de Disponibilização",
            ),
        ),
    ]
