# Generated by Django 5.0.2 on 2025-10-01 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0213_alter_publicacao_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoArquivamentoNota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivo_arquivamento",
                    models.TextField(
                        help_text="Justificativa para o arquivamento da nota",
                        verbose_name="Motivo do Arquivamento",
                    ),
                ),
                (
                    "data_arquivamento",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Arquivamento"
                    ),
                ),
                (
                    "arquivado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_arquivadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Arquivado por",
                    ),
                ),
                (
                    "nota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicos_arquivamento",
                        to="militares.publicacao",
                        verbose_name="Nota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Arquivamento de Nota",
                "verbose_name_plural": "Históricos de Arquivamento de Notas",
                "ordering": ["-data_arquivamento"],
            },
        ),
    ]
