# Generated by Django 5.0.2 on 2025-10-01 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0214_historicoarquivamentonota"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicodevolucaonota",
            options={
                "ordering": ["-data_devolucao"],
                "verbose_name": "Histórico de Devolução de Nota",
                "verbose_name_plural": "Históricos de Devolução de Notas",
            },
        ),
        migrations.RemoveField(
            model_name="historicodevolucaonota",
            name="assinaturas_removidas",
        ),
        migrations.AlterField(
            model_name="historicodevolucaonota",
            name="devolvido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notas_devolvidas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Devolvido por",
            ),
        ),
        migrations.AlterField(
            model_name="historicodevolucaonota",
            name="motivo_devolucao",
            field=models.TextField(
                help_text="Justificativa para a devolução da nota",
                verbose_name="Motivo da Devolução",
            ),
        ),
        migrations.AlterField(
            model_name="historicodevolucaonota",
            name="nota",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historicos_devolucao",
                to="militares.publicacao",
                verbose_name="Nota",
            ),
        ),
    ]
