# Generated by Django 5.0.2 on 2025-10-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0215_alter_historicodevolucaonota_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assinaturanota",
            name="assinatura_digital",
            field=models.TextField(
                blank=True, null=True, verbose_name="Assinatura Digital"
            ),
        ),
        migrations.AddField(
            model_name="assinaturanota",
            name="assinatura_fisica",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="assinaturas_fisicas/",
                verbose_name="Assinatura Física (Imagem)",
            ),
        ),
        migrations.AddField(
            model_name="assinaturanota",
            name="certificado",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Certificado Digital",
            ),
        ),
        migrations.AddField(
            model_name="assinaturanota",
            name="hash_documento",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Hash do Documento"
            ),
        ),
        migrations.AddField(
            model_name="assinaturanota",
            name="ip_assinatura",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP da Assinatura"
            ),
        ),
        migrations.AddField(
            model_name="assinaturanota",
            name="timestamp",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Timestamp da Assinatura",
            ),
        ),
        migrations.AddField(
            model_name="assinaturanota",
            name="tipo_midia",
            field=models.CharField(
                choices=[("FISICA", "Física"), ("ELETRONICA", "Eletrônica")],
                default="FISICA",
                max_length=10,
                verbose_name="Tipo de Mídia",
            ),
        ),
        migrations.AddField(
            model_name="assinaturanota",
            name="user_agent",
            field=models.TextField(blank=True, null=True, verbose_name="User Agent"),
        ),
        migrations.AlterField(
            model_name="assinaturanota",
            name="tipo_assinatura",
            field=models.CharField(
                choices=[
                    ("REVISAO", "Revisão"),
                    ("APROVACAO", "Aprovação"),
                    ("EDICAO", "Edição"),
                    ("HOMOLOGACAO", "Homologação"),
                    ("CONFERENCIA", "Conferência"),
                    ("ELETRONICA", "Eletrônica"),
                    ("EDITOR_CHEFE", "Editor Chefe"),
                    ("EDITOR_ADJUNTO", "Editor Adjunto"),
                    ("EDITOR_GERAL", "Editor Geral"),
                ],
                default="APROVACAO",
                max_length=15,
                verbose_name="Tipo de Assinatura",
            ),
        ),
    ]
