# Generated by Django 5.0.2 on 2025-10-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0216_add_assinatura_fisica_eletronica"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicodevolucaonota",
            name="assinaturas_removidas",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número de assinaturas removidas na devolução",
                verbose_name="Assinaturas Removidas",
            ),
        ),
    ]
