# Generated by Django 5.0.2 on 2025-10-02 23:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0217_historicodevolucaonota_assinaturas_removidas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoEscala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_escala",
                    models.CharField(
                        choices=[
                            ("EXPEDIENTE", "Expediente (06h - 07:30 às 13:30)"),
                            ("24_72", "Operacional 24/72"),
                            ("12_36", "Operacional 12/36"),
                            ("6_18", "Operacional 6/18"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "horas_trabalho",
                    models.IntegerField(help_text="Horas de trabalho por turno"),
                ),
                (
                    "horas_folga",
                    models.IntegerField(help_text="Horas de folga entre turnos"),
                ),
                (
                    "horas_inicio",
                    models.TimeField(help_text="Horário de início do turno"),
                ),
                ("horas_fim", models.TimeField(help_text="Horário de fim do turno")),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Configuração de Escala",
                "verbose_name_plural": "Configurações de Escala",
            },
        ),
        migrations.CreateModel(
            name="Escala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ]
                    ),
                ),
                ("ano", models.IntegerField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lotacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalas",
                        to="militares.lotacao",
                    ),
                ),
                (
                    "tipo_escala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.configuracaoescala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escala",
                "verbose_name_plural": "Escalas",
                "unique_together": {("lotacao", "mes", "ano", "tipo_escala")},
            },
        ),
        migrations.CreateModel(
            name="EscalaOperacaoPlanejada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_escala", models.DateField()),
                ("horas_previstas", models.IntegerField(default=8)),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escala Operação Planejada",
                "verbose_name_plural": "Escalas Operações Planejadas",
            },
        ),
        migrations.CreateModel(
            name="OperacaoPlanejada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                ("ativa", models.BooleanField(default=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lotacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operacoes_planejadas",
                        to="militares.lotacao",
                    ),
                ),
                (
                    "militares_escalados",
                    models.ManyToManyField(
                        blank=True,
                        through="militares.EscalaOperacaoPlanejada",
                        to="militares.militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operação Planejada",
                "verbose_name_plural": "Operações Planejadas",
            },
        ),
        migrations.AddField(
            model_name="escalaoperacaoplanejada",
            name="operacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="militares.operacaoplanejada",
            ),
        ),
        migrations.CreateModel(
            name="BancoHorasMilitar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.IntegerField()),
                ("ano", models.IntegerField()),
                ("horas_trabalhadas", models.IntegerField(default=0)),
                ("horas_folga", models.IntegerField(default=0)),
                ("saldo_horas", models.IntegerField(default=0)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banco_horas",
                        to="militares.militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banco de Horas Militar",
                "verbose_name_plural": "Bancos de Horas Militares",
                "unique_together": {("militar", "mes", "ano")},
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoHorasMilitar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horas_minimas_mes",
                    models.IntegerField(
                        default=0,
                        help_text="Horas mínimas que o militar deve trabalhar por mês",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "horas_maximas_mes",
                    models.IntegerField(
                        default=200,
                        help_text="Horas máximas que o militar pode trabalhar por mês",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_horas",
                        to="militares.militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Horas Militar",
                "verbose_name_plural": "Configurações de Horas Militares",
                "unique_together": {("militar", "ativo")},
            },
        ),
        migrations.CreateModel(
            name="EscalaMilitar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_turno", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRONTO", "Pronto para escala"),
                            ("INDISPONIVEL", "Indisponível"),
                            ("FOLGA", "Em folga"),
                            ("OPERACAO_PLANEJADA", "Operação planejada"),
                        ],
                        default="PRONTO",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "operacao_planejada",
                    models.BooleanField(
                        default=False, help_text="Marcar se é operação planejada"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escala_militares",
                        to="militares.escala",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalas_militar",
                        to="militares.militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escala Militar",
                "verbose_name_plural": "Escalas Militares",
                "unique_together": {("escala", "militar", "data_turno")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="escalaoperacaoplanejada",
            unique_together={("operacao", "militar", "data_escala")},
        ),
    ]
