# Generated by Django 5.0.2 on 2025-10-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "militares",
            "0218_configuracaoescala_escala_escalaoperacaoplanejada_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="escalas_adicionar_militar",
            field=models.BooleanField(
                default=False, verbose_name="Adicionar Militar à Escala"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="escalas_configurar_horas",
            field=models.BooleanField(
                default=False, verbose_name="Configurar Horas dos Militares"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="escalas_criar",
            field=models.BooleanField(default=False, verbose_name="Criar Escalas"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="escalas_editar",
            field=models.BooleanField(default=False, verbose_name="Editar Escalas"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="escalas_excluir",
            field=models.BooleanField(default=False, verbose_name="Excluir Escalas"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="escalas_gerar_pdf",
            field=models.BooleanField(default=False, verbose_name="Gerar PDF Escalas"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="escalas_operacoes_planejadas",
            field=models.BooleanField(
                default=False, verbose_name="Gerenciar Operações Planejadas"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="escalas_remover_militar",
            field=models.BooleanField(
                default=False, verbose_name="Remover Militar da Escala"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="escalas_visualizar",
            field=models.BooleanField(default=False, verbose_name="Visualizar Escalas"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_escalas",
            field=models.BooleanField(default=False, verbose_name="Escalas de Serviço"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_escalas_banco_horas",
            field=models.BooleanField(default=False, verbose_name="Banco de Horas"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_escalas_configuracao",
            field=models.BooleanField(
                default=False, verbose_name="Configurações de Escala"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_escalas_dashboard",
            field=models.BooleanField(default=False, verbose_name="Dashboard Escalas"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_escalas_lista",
            field=models.BooleanField(default=False, verbose_name="Lista de Escalas"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_escalas_operacoes",
            field=models.BooleanField(
                default=False, verbose_name="Operações Planejadas"
            ),
        ),
    ]
