# Generated by Django 5.0.2 on 2025-10-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0219_funcaomenuconfig_escalas_adicionar_militar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaoescala",
            name="horas_fim",
            field=models.TimeField(
                blank=True,
                help_text="Horário de fim do turno. Deixe em branco para calcular automaticamente baseado na hora de início",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="configuracaoescala",
            name="horas_folga",
            field=models.IntegerField(
                blank=True,
                help_text="Horas de folga entre turnos. Deixe em branco para escalas que não precisam de folga (como expediente)",
                null=True,
            ),
        ),
    ]
