# Generated by Django 5.0.2 on 2025-10-03 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0220_alter_configuracaoescala_horas_fim_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracaoescala",
            name="horas_fim",
        ),
        migrations.RemoveField(
            model_name="configuracaoescala",
            name="horas_inicio",
        ),
    ]
