# Generated by Django 5.0.2 on 2025-10-03 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0221_remove_hours_from_configuracao_escala"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EscalaServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título da Escala"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "tipo_escala",
                    models.CharField(
                        choices=[
                            ("DIARIA", "Escala Diária"),
                            ("SEMANAL", "Escala Semanal"),
                            ("MENSAL", "Escala Mensal"),
                        ],
                        default="DIARIA",
                        max_length=20,
                        verbose_name="Tipo de Escala",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("ATIVA", "Ativa"),
                            ("FINALIZADA", "Finalizada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_fim", models.DateField(verbose_name="Data de Fim")),
                (
                    "mes_referencia",
                    models.PositiveIntegerField(verbose_name="Mês de Referência"),
                ),
                (
                    "ano_referencia",
                    models.PositiveIntegerField(verbose_name="Ano de Referência"),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("MANHA", "Manhã"),
                            ("TARDE", "Tarde"),
                            ("NOITE", "Noite"),
                            ("INTEGRAL", "Integral"),
                        ],
                        default="INTEGRAL",
                        max_length=20,
                        verbose_name="Turno",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalas_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "grande_comando",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.grandecomando",
                        verbose_name="Grande Comando",
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.orgao",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "sub_unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.subunidade",
                        verbose_name="Sub-Unidade",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.unidade",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escala de Serviço",
                "verbose_name_plural": "Escalas de Serviço",
                "ordering": ["-data_criacao"],
                "unique_together": {
                    ("mes_referencia", "ano_referencia", "unidade", "tipo_escala")
                },
            },
        ),
        migrations.CreateModel(
            name="EscalaServicoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_servico", models.DateField(verbose_name="Data do Serviço")),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("COMANDO", "Comando"),
                            ("PLANTÃO", "Plantão"),
                            ("GUARDA", "Guarda"),
                            ("SERVIÇO", "Serviço"),
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("OPERACIONAL", "Operacional"),
                        ],
                        default="SERVIÇO",
                        max_length=20,
                        verbose_name="Tipo de Serviço",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "escala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="militares.escalaservico",
                        verbose_name="Escala",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Escala de Serviço",
                "verbose_name_plural": "Itens da Escala de Serviço",
                "ordering": ["data_servico", "militar__nome_completo"],
                "unique_together": {("escala", "militar", "data_servico")},
            },
        ),
    ]