# Generated by Django 5.0.2 on 2025-10-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0223_allow_null_militar_escala_item"),
    ]

    operations = [
        migrations.DeleteModel(
            name='EscalaServicoItem',
        ),
        migrations.DeleteModel(
            name='EscalaServico',
        ),
    ]
