# Generated by Django 5.0.2 on 2025-10-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0229_add_escalas_fields_manual"),
    ]

    operations = [
        # NOTA: Removendo operações de remoção de campos de modelos que podem não existir
        # ou que já foram removidos em migrações anteriores
        # Esses modelos serão deletados no final desta migração de qualquer forma
        migrations.RunSQL(
            sql="""
            -- Remover campos apenas se existirem
            DO $$
            BEGIN
                -- Remover tipo_escala de escala se existir
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'militares_escala' 
                    AND column_name = 'tipo_escala'
                ) THEN
                    ALTER TABLE militares_escala DROP COLUMN tipo_escala;
                END IF;
                
                -- Remover outros campos se as tabelas existirem
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'militares_configuracaohorasmilitar') THEN
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'militares_configuracaohorasmilitar' AND column_name = 'criado_por_id') THEN
                        ALTER TABLE militares_configuracaohorasmilitar DROP COLUMN criado_por_id;
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'militares_configuracaohorasmilitar' AND column_name = 'militar_id') THEN
                        ALTER TABLE militares_configuracaohorasmilitar DROP COLUMN militar_id;
                    END IF;
                END IF;
                
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'militares_escala') THEN
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'militares_escala' AND column_name = 'criado_por_id') THEN
                        ALTER TABLE militares_escala DROP COLUMN criado_por_id;
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'militares_escala' AND column_name = 'lotacao_id') THEN
                        ALTER TABLE militares_escala DROP COLUMN lotacao_id;
                    END IF;
                END IF;
                
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'militares_escalaoperacaoplanejada') THEN
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'militares_escalaoperacaoplanejada' AND column_name = 'criado_por_id') THEN
                        ALTER TABLE militares_escalaoperacaoplanejada DROP COLUMN criado_por_id;
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'militares_escalaoperacaoplanejada' AND column_name = 'militar_id') THEN
                        ALTER TABLE militares_escalaoperacaoplanejada DROP COLUMN militar_id;
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'militares_escalaoperacaoplanejada' AND column_name = 'operacao_id') THEN
                        ALTER TABLE militares_escalaoperacaoplanejada DROP COLUMN operacao_id;
                    END IF;
                END IF;
                
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'militares_operacaoplanejada') THEN
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'militares_operacaoplanejada' AND column_name = 'criado_por_id') THEN
                        ALTER TABLE militares_operacaoplanejada DROP COLUMN criado_por_id;
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'militares_operacaoplanejada' AND column_name = 'lotacao_id') THEN
                        ALTER TABLE militares_operacaoplanejada DROP COLUMN lotacao_id;
                    END IF;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Adicionar campos apenas se não existirem
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- Lista de campos para adicionar
                DECLARE
                    campos TEXT[] := ARRAY[
                        'show_criar_ficha_conceito_oficial',
                        'show_criar_ficha_conceito_praca',
                        'show_grandes_comandos',
                        'show_minha_ficha_cadastro',
                        'show_minha_ficha_conceito_oficial',
                        'show_minha_ficha_conceito_praca',
                        'show_minhas_informacoes',
                        'show_organograma',
                        'show_orgaos',
                        'show_pessoal',
                        'show_relatorios',
                        'show_relatorios_gerais',
                        'show_relatorios_medalhas',
                        'show_relatorios_militares',
                        'show_relatorios_promocoes',
                        'show_relatorios_publicacoes',
                        'show_sub_unidades',
                        'show_unidades'
                    ];
                    campo TEXT;
                BEGIN
                    FOREACH campo IN ARRAY campos
                    LOOP
                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'militares_funcaomenuconfig' 
                            AND column_name = campo
                        ) THEN
                            EXECUTE format('ALTER TABLE militares_funcaomenuconfig ADD COLUMN %I BOOLEAN DEFAULT FALSE', campo);
                        END IF;
                    END LOOP;
                END;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="permissaofuncao",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("MENU_DASHBOARD", "Dashboard"),
                    ("MENU_EFETIVO", "Efetivo"),
                    ("MENU_SECAO_PROMOCOES", "Seção de Promoções"),
                    ("MENU_MEDALHAS", "Medalhas"),
                    ("MENU_PUBLICACOES", "Publicações"),
                    ("MENU_ESCALAS", "Escalas de Serviço"),
                    ("MENU_CONFIGURACOES", "Configurações"),
                    ("MENU_RELATORIOS", "Relatórios"),
                    ("MENU_PESSOAL", "Pessoal"),
                    ("SUBMENU_MINHAS_INFORMACOES", "Minhas Informações"),
                    ("SUBMENU_MINHA_FICHA_CADASTRO", "Minha Ficha de Cadastro"),
                    (
                        "SUBMENU_MINHA_FICHA_CONCEITO_OFICIAL",
                        "Minha Ficha de Conceito (Oficial)",
                    ),
                    (
                        "SUBMENU_MINHA_FICHA_CONCEITO_PRACA",
                        "Minha Ficha de Conceito (Praça)",
                    ),
                    (
                        "SUBMENU_CRIAR_FICHA_CONCEITO_OFICIAL",
                        "Criar Ficha de Conceito (Oficial)",
                    ),
                    (
                        "SUBMENU_CRIAR_FICHA_CONCEITO_PRACA",
                        "Criar Ficha de Conceito (Praça)",
                    ),
                    ("SUBMENU_ATIVOS", "Militares Ativos"),
                    ("SUBMENU_INATIVOS", "Militares Inativos"),
                    ("SUBMENU_LOTACOES", "Lotações"),
                    ("SUBMENU_FICHAS_OFICIAIS", "Fichas de Conceito (Oficiais)"),
                    ("SUBMENU_FICHAS_PRACAS", "Fichas de Conceito (Praças)"),
                    ("SUBMENU_QUADROS_ACESSO", "Quadros de Acesso"),
                    ("SUBMENU_QUADROS_FIXACAO", "Quadros de Fixação de Vagas"),
                    ("SUBMENU_CALENDARIOS", "Calendários de Promoções"),
                    ("SUBMENU_COMISSOES", "Comissões de Promoções"),
                    ("SUBMENU_MEUS_VOTOS", "Meus Votos"),
                    ("SUBMENU_PROMOCOES", "Promoções"),
                    ("SUBMENU_ALMANAQUES", "Almanaques"),
                    ("SUBMENU_INTERSTICIOS", "Interstícios"),
                    ("SUBMENU_GERENCIAR_INTERSTICIOS", "Gerenciar Interstícios"),
                    ("SUBMENU_GERENCIAR_PREVISAO", "Gerenciar Previsão"),
                    ("SUBMENU_MEDALHAS_CONCESSOES", "Concessões de Medalhas"),
                    ("SUBMENU_MEDALHAS_PROPOSTAS", "Propostas de Medalhas"),
                    ("SUBMENU_ELEGIVEIS", "Elegíveis"),
                    ("SUBMENU_PROPOSTAS", "Propostas"),
                    ("SUBMENU_CONCEDER_MEDALHA", "Conceder Medalha"),
                    ("SUBMENU_PUBLICACOES", "Publicações"),
                    ("SUBMENU_NOTAS", "Notas"),
                    ("SUBMENU_BOLETINS_OSTENSIVOS", "Boletins Ostensivos"),
                    ("SUBMENU_BOLETINS_RESERVADOS", "Boletins Reservados"),
                    ("SUBMENU_BOLETINS_ESPECIAIS", "Boletins Especiais"),
                    ("SUBMENU_AVISOS", "Avisos"),
                    ("SUBMENU_ORDENS_SERVICO", "Ordens de Serviço"),
                    ("SUBMENU_ESCALAS_DASHBOARD", "Dashboard de Escalas"),
                    ("SUBMENU_ESCALAS_LISTA", "Lista de Escalas"),
                    ("SUBMENU_ESCALAS_CONFIGURACAO", "Configurações de Escalas"),
                    ("SUBMENU_ESCALAS_BANCO_HORAS", "Banco de Horas"),
                    ("SUBMENU_ESCALAS_OPERACOES", "Operações de Escalas"),
                    ("SUBMENU_USUARIOS", "Gerenciar Usuários"),
                    ("SUBMENU_PERMISSOES", "Funções Militares"),
                    ("SUBMENU_ORGAOS", "Órgãos"),
                    ("SUBMENU_ORGANOGRAMA", "Organograma"),
                    ("SUBMENU_LOGS", "Logs do Sistema"),
                    ("SUBMENU_TITULOS_PUBLICACAO", "Títulos de Publicações"),
                    ("SUBMENU_ADMINISTRACAO", "Administração"),
                    ("SUBMENU_GRANDES_COMANDOS", "Grandes Comandos"),
                    ("SUBMENU_UNIDADES", "Unidades"),
                    ("SUBMENU_SUB_UNIDADES", "Sub-Unidades"),
                    ("SUBMENU_RELATORIOS_MILITARES", "Relatórios de Militares"),
                    ("SUBMENU_RELATORIOS_PROMOCOES", "Relatórios de Promoções"),
                    ("SUBMENU_RELATORIOS_MEDALHAS", "Relatórios de Medalhas"),
                    ("SUBMENU_RELATORIOS_PUBLICACOES", "Relatórios de Publicações"),
                    ("SUBMENU_RELATORIOS_GERAIS", "Relatórios Gerais"),
                    ("ATIVOS_VISUALIZAR", "Visualizar Militares Ativos"),
                    ("ATIVOS_CRIAR", "Criar Militares Ativos"),
                    ("ATIVOS_EDITAR", "Editar Militares Ativos"),
                    ("ATIVOS_EXCLUIR", "Excluir Militares Ativos"),
                    ("ATIVOS_TRANSFERIR", "Transferir Militares Ativos"),
                    ("ATIVOS_PROMOVER", "Promover Militares Ativos"),
                    ("ATIVOS_INATIVAR", "Inativar Militares Ativos"),
                    ("ATIVOS_FICHA_CONCEITO", "Gerenciar Fichas de Conceito"),
                    ("ATIVOS_EXPORTAR", "Exportar Militares Ativos"),
                    ("ATIVOS_DASHBOARD", "Dashboard Militares Ativos"),
                    ("ATIVOS_REORDENAR", "Reordenar Militares Ativos"),
                    ("INATIVOS_VISUALIZAR", "Visualizar Militares Inativos"),
                    ("INATIVOS_EDITAR", "Editar Militares Inativos"),
                    ("INATIVOS_EXPORTAR", "Exportar Militares Inativos"),
                    ("LOTACOES_VISUALIZAR", "Visualizar Lotações"),
                    ("LOTACOES_CRIAR", "Criar Lotações"),
                    ("LOTACOES_EDITAR", "Editar Lotações"),
                    ("LOTACOES_EXCLUIR", "Excluir Lotações"),
                    ("INATIVOS_EDITAR", "Editar Militares Inativos"),
                    ("INATIVOS_EXCLUIR", "Excluir Militares Inativos"),
                    ("INATIVOS_REATIVAR", "Reativar Militares Inativos"),
                    ("LOTACOES_VISUALIZAR", "Visualizar Lotações"),
                    ("LOTACOES_CRIAR", "Criar Lotações"),
                    ("LOTACOES_EDITAR", "Editar Lotações"),
                    ("LOTACOES_EXCLUIR", "Excluir Lotações"),
                    ("DETAIL_FICHAS_CONCEITO", "Visualizar Fichas de Conceito"),
                    ("DETAIL_PUNICOES", "Visualizar Punições e Elogios"),
                    ("DETAIL_MEDALHAS", "Visualizar Medalhas"),
                    ("DETAIL_CONTATO", "Visualizar Contato"),
                    ("QUADROS_FIXACAO_VISUALIZAR", "Visualizar Quadros de Fixação"),
                    ("QUADROS_FIXACAO_CRIAR", "Criar Quadros de Fixação"),
                    ("QUADROS_FIXACAO_EDITAR", "Editar Quadros de Fixação"),
                    ("QUADROS_FIXACAO_EXCLUIR", "Excluir Quadros de Fixação"),
                    ("QUADROS_ACESSO_VISUALIZAR", "Visualizar Quadros de Acesso"),
                    ("QUADROS_ACESSO_CRIAR", "Criar Quadros de Acesso"),
                    ("QUADROS_ACESSO_EDITAR", "Editar Quadros de Acesso"),
                    ("QUADROS_ACESSO_EXCLUIR", "Excluir Quadros de Acesso"),
                    (
                        "COMISSOES_OFICIAIS_VISUALIZAR",
                        "Visualizar Comissões de Oficiais",
                    ),
                    ("COMISSOES_OFICIAIS_CRIAR", "Criar Comissões de Oficiais"),
                    ("COMISSOES_OFICIAIS_EDITAR", "Editar Comissões de Oficiais"),
                    ("COMISSOES_OFICIAIS_EXCLUIR", "Excluir Comissões de Oficiais"),
                    ("COMISSOES_PRACAS_VISUALIZAR", "Visualizar Comissões de Praças"),
                    ("COMISSOES_PRACAS_CRIAR", "Criar Comissões de Praças"),
                    ("COMISSOES_PRACAS_EDITAR", "Editar Comissões de Praças"),
                    ("COMISSOES_PRACAS_EXCLUIR", "Excluir Comissões de Praças"),
                    ("QUADROS_ACESSO_ASSINAR", "Assinar Quadros de Acesso"),
                    ("QUADROS_ACESSO_HOMOLOGAR", "Homologar Quadros de Acesso"),
                    ("QUADROS_ACESSO_DESHOMOLOGAR", "Deshomologar Quadros de Acesso"),
                    ("QUADROS_ACESSO_ELABORAR", "Elaborar Quadros de Acesso"),
                    ("QUADROS_ACESSO_REGENERAR", "Regenerar Quadros de Acesso"),
                    ("QUADROS_ACESSO_GERAR_PDF", "Gerar PDF de Quadros de Acesso"),
                    ("SUBMENU_MEDALHAS_CONCESSOES", "Concessões de Medalhas"),
                    ("SUBMENU_MEDALHAS_PROPOSTAS", "Propostas de Medalhas"),
                    ("SUBMENU_ELEGIVEIS", "Elegíveis"),
                    ("SUBMENU_PROPOSTAS", "Propostas"),
                    ("SUBMENU_NOTAS_LISTA", "Lista de Notas"),
                    ("SUBMENU_PUBLICACOES", "Publicações"),
                    ("SUBMENU_NOTAS", "Notas"),
                    ("NOTAS_VISUALIZAR", "Visualizar Notas"),
                    ("NOTAS_CRIAR", "Criar Notas"),
                    ("NOTAS_EDITAR", "Editar Notas"),
                    ("NOTAS_EXCLUIR", "Excluir Notas"),
                    ("NOTAS_REVISAR", "Revisar Notas"),
                    ("NOTAS_APROVAR", "Aprovar Notas"),
                    ("NOTAS_PUBLICAR", "Publicar Notas"),
                    ("NOTAS_ADMINISTRAR", "Administrar Notas"),
                    ("PUBLICACOES_VISUALIZAR", "Visualizar Publicações"),
                    ("PUBLICACOES_CRIAR", "Criar Publicações"),
                    ("PUBLICACOES_EDITAR", "Editar Publicações"),
                    ("PUBLICACOES_EXCLUIR", "Excluir Publicações"),
                    ("PUBLICACOES_PUBLICAR", "Publicar Publicações"),
                    ("SUBMENU_INTERSTICIOS", "Interstícios"),
                    ("SUBMENU_GERENCIAR_INTERSTICIOS", "Gerenciar Interstícios"),
                    ("SUBMENU_GERENCIAR_PREVISAO", "Gerenciar Previsão"),
                    ("SUBMENU_USUARIOS", "Usuários"),
                    ("SUBMENU_PERMISSOES", "Permissões"),
                    ("SUBMENU_LOGS", "Logs"),
                    ("SUBMENU_ADMINISTRACAO", "Administração"),
                ],
                max_length=50,
                verbose_name="Módulo",
            ),
        ),
        migrations.DeleteModel(
            name="BancoHorasMilitar",
        ),
        migrations.DeleteModel(
            name="ConfiguracaoEscala",
        ),
        migrations.DeleteModel(
            name="ConfiguracaoHorasMilitar",
        ),
        migrations.DeleteModel(
            name="Escala",
        ),
        migrations.DeleteModel(
            name="EscalaOperacaoPlanejada",
        ),
        migrations.DeleteModel(
            name="OperacaoPlanejada",
        ),
    ]
