# Generated by Django 5.0.2 on 2025-10-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0230_add_menu_fields"),
    ]

    operations = [
        # NOTA: Verificar e adicionar campos apenas se não existirem
        migrations.RunSQL(
            sql="""
            DO $$
            DECLARE
                campos TEXT[] := ARRAY[
                    'show_orgaos',
                    'show_organograma',
                    'show_grandes_comandos',
                    'show_unidades',
                    'show_sub_unidades',
                    'show_pessoal',
                    'show_relatorios',
                    'show_relatorios_gerais',
                    'show_relatorios_militares',
                    'show_relatorios_promocoes',
                    'show_relatorios_medalhas',
                    'show_relatorios_publicacoes',
                    'show_minhas_informacoes',
                    'show_minha_ficha_cadastro',
                    'show_minha_ficha_conceito_oficial',
                    'show_minha_ficha_conceito_praca',
                    'show_criar_ficha_conceito_oficial',
                    'show_criar_ficha_conceito_praca'
                ];
                campo TEXT;
            BEGIN
                FOREACH campo IN ARRAY campos
                LOOP
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'militares_funcaomenuconfig' 
                        AND column_name = campo
                    ) THEN
                        EXECUTE format('ALTER TABLE militares_funcaomenuconfig ADD COLUMN %I BOOLEAN DEFAULT FALSE', campo);
                    END IF;
                END LOOP;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # NOTA: Os campos já foram adicionados condicionalmente pelo RunSQL acima
        # Mantendo a migração apenas com o RunSQL para evitar duplicação
    ]
