# Generated by Django 5.0.2 on 2025-10-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0231_add_missing_menu_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicacao",
            name="origem_publicacao",
            field=models.CharField(
                blank=True,
                help_text="Origem da publicação no organograma (ex: Comando Geral, DGP, etc.)",
                max_length=200,
                null=True,
                verbose_name="Origem da Publicação",
            ),
        ),
    ]
