# Generated by Django 5.0.2 on 2025-10-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0232_aumentar_limite_origem_publicacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="escalamilitar",
            name="equipe",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Equipe"
            ),
        ),
        migrations.AddField(
            model_name="escalamilitar",
            name="funcao_operacional",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Função Operacional"
            ),
        ),
        migrations.AddField(
            model_name="escalamilitar",
            name="viatura",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Viatura"
            ),
        ),
    ]
