# Generated by Django 5.0.2 on 2025-10-08 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0233_add_operational_fields_to_escala_militar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="escalaservico",
            name="aprovado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalas_aprovadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprovado por",
            ),
        ),
        migrations.AddField(
            model_name="escalaservico",
            name="data_aprovacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Aprovação"
            ),
        ),
        migrations.AddField(
            model_name="escalaservico",
            name="data_revisao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Revisão"
            ),
        ),
        migrations.AddField(
            model_name="escalaservico",
            name="observacoes_aprovacao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações da Aprovação"
            ),
        ),
        migrations.AddField(
            model_name="escalaservico",
            name="observacoes_revisao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações da Revisão"
            ),
        ),
        migrations.AddField(
            model_name="escalaservico",
            name="revisado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalas_revisadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revisado por",
            ),
        ),
        migrations.AlterField(
            model_name="escalaservico",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_revisao", "Em Revisão"),
                    ("aprovada", "Aprovada"),
                    ("ativa", "Ativa"),
                    ("concluida", "Concluída"),
                    ("cancelada", "Cancelada"),
                ],
                default="pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
