# Generated by Django 5.0.2 on 2025-10-08 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0234_add_review_approval_fields_to_escala"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssinaturaEscala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_assinatura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Assinatura"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações da Assinatura"
                    ),
                ),
                (
                    "tipo_assinatura",
                    models.CharField(
                        choices=[
                            ("REVISAO", "Revisão"),
                            ("APROVACAO", "Aprovação"),
                            ("HOMOLOGACAO", "Homologação"),
                            ("CONFERENCIA", "Conferência"),
                            ("ELETRONICA", "Eletrônica"),
                        ],
                        default="APROVACAO",
                        max_length=15,
                        verbose_name="Tipo de Assinatura",
                    ),
                ),
                (
                    "funcao_assinatura",
                    models.CharField(
                        blank=True,
                        help_text="Função/cargo do usuário no momento da assinatura",
                        max_length=100,
                        null=True,
                        verbose_name="Função no momento da assinatura",
                    ),
                ),
                (
                    "tipo_midia",
                    models.CharField(
                        choices=[("FISICA", "Física"), ("ELETRONICA", "Eletrônica")],
                        default="FISICA",
                        max_length=10,
                        verbose_name="Tipo de Mídia",
                    ),
                ),
                (
                    "assinatura_fisica",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="assinaturas_fisicas/",
                        verbose_name="Assinatura Física (Imagem)",
                    ),
                ),
                (
                    "hash_documento",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Hash do Documento",
                    ),
                ),
                (
                    "timestamp",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Timestamp da Assinatura",
                    ),
                ),
                (
                    "assinatura_digital",
                    models.TextField(
                        blank=True, null=True, verbose_name="Assinatura Digital"
                    ),
                ),
                (
                    "certificado",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Certificado Digital",
                    ),
                ),
                (
                    "ip_assinatura",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP da Assinatura"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "assinado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assinado por",
                    ),
                ),
                (
                    "escala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to="militares.escalaservico",
                        verbose_name="Escala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura da Escala",
                "verbose_name_plural": "Assinaturas das Escalas",
                "ordering": ["-data_assinatura"],
                "unique_together": {("escala", "assinado_por", "tipo_assinatura")},
            },
        ),
    ]
