# Generated by Django 5.0.2 on 2025-10-08 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0235_add_assinatura_escala_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlteracaoEscala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_alteracao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Alteração"
                    ),
                ),
                (
                    "tipo_alteracao",
                    models.CharField(
                        choices=[
                            ("ADICIONAR_MILITAR", "Adicionar Militar"),
                            ("REMOVER_MILITAR", "Remover Militar"),
                            ("ALTERAR_DADOS_MILITAR", "Alterar Dados do Militar"),
                            ("ALTERAR_DADOS_ESCALA", "Alterar Dados da Escala"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Alteração",
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(
                        help_text="Motivo obrigatório para a alteração",
                        verbose_name="Justificativa",
                    ),
                ),
                (
                    "dados_anteriores",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Dados Anteriores"
                    ),
                ),
                (
                    "dados_novos",
                    models.JSONField(blank=True, null=True, verbose_name="Dados Novos"),
                ),
                (
                    "valida_ate_data",
                    models.DateField(
                        help_text="Data limite para esta alteração",
                        verbose_name="Válida até",
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(default=True, verbose_name="Alteração Ativa"),
                ),
                (
                    "alterado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alterado por",
                    ),
                ),
                (
                    "escala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alteracoes",
                        to="militares.escalaservico",
                        verbose_name="Escala",
                    ),
                ),
                (
                    "militar_afetado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.militar",
                        verbose_name="Militar Afetado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alteração da Escala",
                "verbose_name_plural": "Alterações das Escalas",
                "ordering": ["-data_alteracao"],
            },
        ),
    ]
