# Generated by Django 5.0.2 on 2025-10-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0236_add_alteracao_escala_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="escalamilitar",
            name="secao",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Seção"
            ),
        ),
    ]
