# Generated by Django 5.0.2 on 2025-10-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0237_add_secao_field_to_escala_militar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="escalamilitar",
            options={"ordering": ["escala", "funcao", "militar__nome_completo"]},
        ),
        migrations.AlterUniqueTogether(
            name="escalamilitar",
            unique_together=set(),
        ),
    ]
