# Generated by Django 5.0.2 on 2025-10-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0238_remove_unique_together_escala_militar"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacao",
            name="boletim_reservado",
            field=models.ForeignKey(
                blank=True,
                help_text="Boletim reservado onde esta nota está incluída",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notas_incluidas_reservadas",
                to="militares.publicacao",
                verbose_name="Boletim Reservado",
            ),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="numero_boletim_reservado",
            field=models.CharField(
                blank=True,
                help_text="Número do boletim reservado onde esta nota foi publicada",
                max_length=50,
                null=True,
                verbose_name="Número do Boletim Reservado",
            ),
        ),
    ]
