# Generated by Django 5.0.2 on 2025-10-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0240_add_submenu_notas_reservadas"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacao",
            name="boletim_especial",
            field=models.ForeignKey(
                blank=True,
                help_text="Boletim especial onde esta nota está incluída",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notas_incluidas_especiais",
                to="militares.publicacao",
                verbose_name="Boletim Especial",
            ),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="numero_boletim_especial",
            field=models.CharField(
                blank=True,
                help_text="Número do boletim especial onde esta nota foi publicada",
                max_length=50,
                null=True,
                verbose_name="Número do Boletim Especial",
            ),
        ),
        migrations.AlterField(
            model_name="permissaosubmenu",
            name="submenu",
            field=models.CharField(
                choices=[
                    ("FICHAS_OFICIAIS", "Fichas de Conceito (Oficiais)"),
                    ("FICHAS_PRACAS", "Fichas de Conceito (Praças)"),
                    ("QUADROS_ACESSO", "Quadros de Acesso"),
                    ("QUADROS_FIXACAO", "Quadros de Fixação de Vagas"),
                    ("ALMANAQUES", "Almanaques"),
                    ("PROMOCOES", "Promoções"),
                    ("CALENDARIOS", "Calendários de Promoções"),
                    ("COMISSOES", "Comissões de Promoções"),
                    ("MEUS_VOTOS", "Meus Votos"),
                    ("INTERSTICIOS", "Interstícios"),
                    ("GERENCIAR_INTERSTICIOS", "Gerenciar Interstícios"),
                    ("GERENCIAR_PREVISAO", "Gerenciar Previsão"),
                    ("GERENCIAR_SECOES", "Gerenciar Seções"),
                    ("DASHBOARD_SECOES", "Dashboard Seções"),
                    ("MILITARES", "Militares"),
                    ("USUARIOS", "Usuários"),
                    ("PERMISSOES", "Permissões"),
                    ("RELATORIOS", "Relatórios"),
                    ("CONFIGURACOES", "Configurações"),
                    ("NOTAS", "Notas"),
                    ("NOTAS_RESERVADAS", "Notas Reservadas"),
                    ("BOLETINS_OSTENSIVOS", "Boletins Ostensivos"),
                    ("BOLETINS_RESERVADOS", "Boletins Reservados"),
                    ("BOLETINS_ESPECIAIS", "Boletins Especiais"),
                    ("AVISOS", "Avisos"),
                    ("ORDENS_SERVICO", "Ordens de Serviço"),
                ],
                max_length=30,
                verbose_name="Submenu",
            ),
        ),
    ]
