# Generated by Django 5.0.2 on 2025-10-16 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0241_add_boletim_especial_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BancoHoras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_movimentacao",
                    models.DateField(verbose_name="Data da Movimentação"),
                ),
                (
                    "tipo_movimentacao",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SAIDA", "Saída"),
                            ("COMPENSACAO", "Compensação"),
                            ("AJUSTE", "Ajuste Manual"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Movimentação",
                    ),
                ),
                (
                    "horas",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Horas"
                    ),
                ),
                (
                    "saldo_anterior",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Saldo Anterior"
                    ),
                ),
                (
                    "saldo_atual",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Saldo Atual"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "escala",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.escalaservico",
                        verbose_name="Escala",
                    ),
                ),
                (
                    "escala_militar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.escalamilitar",
                        verbose_name="Militar da Escala",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banco de Horas",
                "verbose_name_plural": "Banco de Horas",
                "ordering": ["-data_movimentacao", "militar__nome_completo"],
                "unique_together": {
                    (
                        "militar",
                        "data_movimentacao",
                        "tipo_movimentacao",
                        "escala_militar",
                    )
                },
            },
        ),
    ]
