# Generated by Django 5.0.2 on 2025-10-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0240_aumentar_tamanho_organizacao_escala"),
        ("militares", "0242_bancohoras"),
    ]

    operations = []
