# Generated by Django 5.0.2 on 2025-10-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0243_merge_20251021_1147"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoPlanejadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_planejadas_por_militar_mes",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Número máximo de planejadas que um militar pode ter por mês",
                        verbose_name="Quantidade de Planejadas por Militar/Mês",
                    ),
                ),
                (
                    "valor_planejada_normal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Valor pago por planejada em dias normais",
                        max_digits=10,
                        verbose_name="Valor da Planejada Normal",
                    ),
                ),
                (
                    "valor_planejada_fim_semana",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Valor pago por planejada em fins de semana e feriados",
                        max_digits=10,
                        verbose_name="Valor da Planejada em Fins de Semana",
                    ),
                ),
                (
                    "horas_turno_p1",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Quantidade de horas do turno P1",
                        verbose_name="Horas do Turno P1",
                    ),
                ),
                (
                    "horas_turno_p2",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Quantidade de horas do turno P2",
                        verbose_name="Horas do Turno P2",
                    ),
                ),
                (
                    "horas_turno_p3",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Quantidade de horas do turno P3",
                        verbose_name="Horas do Turno P3",
                    ),
                ),
                (
                    "horas_turno_p4",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Quantidade de horas do turno P4",
                        verbose_name="Horas do Turno P4",
                    ),
                ),
                (
                    "intervalo_entre_escalas_horas",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Intervalo mínimo em horas entre uma escala normal e uma planejada",
                        verbose_name="Intervalo entre Escalas (horas)",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se esta configuração está ativa",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Observações sobre a configuração",
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Planejadas",
                "verbose_name_plural": "Configurações de Planejadas",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
