# Generated by Django 5.0.2 on 2025-10-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0244_configuracaoplanejadas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaoplanejadas",
            name="intervalo_entre_escalas_horas",
            field=models.PositiveIntegerField(
                default=12,
                help_text="Intervalo padrão em horas (usado quando não há regra específica)",
                verbose_name="Intervalo Padrão entre Escalas (horas)",
            ),
        ),
        migrations.CreateModel(
            name="IntervaloEscalaPlanejada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_intervalo",
                    models.CharField(
                        choices=[
                            ("FIXO", "Intervalo Fixo"),
                            ("PROPORCIONAL", "Intervalo Proporcional à Escala"),
                            ("MINIMO", "Intervalo Mínimo"),
                        ],
                        default="PROPORCIONAL",
                        help_text="Como calcular o intervalo entre escalas",
                        max_length=20,
                        verbose_name="Tipo de Intervalo",
                    ),
                ),
                (
                    "horas_escala",
                    models.PositiveIntegerField(
                        help_text="Duração da escala normal em horas",
                        verbose_name="Horas da Escala Normal",
                    ),
                ),
                (
                    "horas_intervalo",
                    models.PositiveIntegerField(
                        help_text="Quantas horas de folga após esta escala",
                        verbose_name="Horas de Intervalo",
                    ),
                ),
                (
                    "multiplicador",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplicador para calcular o intervalo (ex: 1.0 = mesmo tempo, 1.5 = 1.5x o tempo)",
                        max_digits=3,
                        verbose_name="Multiplicador",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Se esta regra de intervalo está ativa",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Observações sobre esta regra de intervalo",
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervalo entre Escala e Planejada",
                "verbose_name_plural": "Intervalos entre Escalas e Planejadas",
                "ordering": ["horas_escala", "tipo_intervalo"],
                "unique_together": {("tipo_intervalo", "horas_escala")},
            },
        ),
    ]
