# Generated by Django 5.0.2 on 2025-10-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "militares",
            "0245_alter_configuracaoplanejadas_intervalo_entre_escalas_horas_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracaoplanejadas",
            name="horas_turno_p1",
        ),
        migrations.RemoveField(
            model_name="configuracaoplanejadas",
            name="horas_turno_p2",
        ),
        migrations.RemoveField(
            model_name="configuracaoplanejadas",
            name="horas_turno_p3",
        ),
        migrations.RemoveField(
            model_name="configuracaoplanejadas",
            name="horas_turno_p4",
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="horas_planejada_p1",
            field=models.PositiveIntegerField(
                default=6,
                help_text="Quantidade de horas da planejada tipo P1 (6h)",
                verbose_name="Horas da Planejada P1",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="horas_planejada_p2",
            field=models.PositiveIntegerField(
                default=12,
                help_text="Quantidade de horas da planejada tipo P2 (12h)",
                verbose_name="Horas da Planejada P2",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="horas_planejada_p3",
            field=models.PositiveIntegerField(
                default=18,
                help_text="Quantidade de horas da planejada tipo P3 (18h)",
                verbose_name="Horas da Planejada P3",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="horas_planejada_p4",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Quantidade de horas da planejada tipo P4 (24h)",
                verbose_name="Horas da Planejada P4",
            ),
        ),
    ]
