# Generated by Django 5.0.2 on 2025-10-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0246_remove_configuracaoplanejadas_horas_turno_p1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracaoplanejadas",
            name="intervalo_entre_escalas_horas",
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="intervalo_turno_12h",
            field=models.PositiveIntegerField(
                default=12,
                help_text="Intervalo mínimo em horas após turno de 12h para poder fazer planejada",
                verbose_name="Intervalo para Turno de 12h",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="intervalo_turno_18h",
            field=models.PositiveIntegerField(
                default=18,
                help_text="Intervalo mínimo em horas após turno de 18h para poder fazer planejada",
                verbose_name="Intervalo para Turno de 18h",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="intervalo_turno_24h",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Intervalo mínimo em horas após turno de 24h para poder fazer planejada",
                verbose_name="Intervalo para Turno de 24h",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="intervalo_turno_6h",
            field=models.PositiveIntegerField(
                default=6,
                help_text="Intervalo mínimo em horas após turno de 6h para poder fazer planejada",
                verbose_name="Intervalo para Turno de 6h",
            ),
        ),
    ]
