# Generated by Django 5.0.2 on 2025-10-22 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "militares",
            "0247_remove_configuracaoplanejadas_intervalo_entre_escalas_horas_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrcamentoPlanejadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "mes",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total disponibilizado para planejadas no mês",
                        max_digits=12,
                        verbose_name="Valor Total Disponível",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Orçamento de Planejadas",
                "verbose_name_plural": "Orçamentos de Planejadas",
                "ordering": ["-ano", "-mes"],
                "unique_together": {("ano", "mes")},
            },
        ),
        migrations.CreateModel(
            name="DistribuicaoOrcamentoPlanejadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_planejadas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor destinado para planejadas desta instância",
                        max_digits=12,
                        verbose_name="Valor para Planejadas",
                    ),
                ),
                (
                    "percentual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentual do orçamento total destinado a esta instância",
                        max_digits=5,
                        verbose_name="Percentual",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "grande_comando",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.grandecomando",
                        verbose_name="Grande Comando",
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.orgao",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "sub_unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.subunidade",
                        verbose_name="Sub-Unidade",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.unidade",
                        verbose_name="Unidade",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribuicoes",
                        to="militares.orcamentoplanejadas",
                        verbose_name="Orçamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribuição de Orçamento",
                "verbose_name_plural": "Distribuições de Orçamento",
                "ordering": [
                    "orcamento__ano",
                    "orcamento__mes",
                    "orgao__nome",
                    "grande_comando__nome",
                    "unidade__nome",
                ],
                "unique_together": {
                    ("orcamento", "orgao", "grande_comando", "unidade", "sub_unidade")
                },
            },
        ),
    ]
