# Generated by Django 5.0.2 on 2025-10-22 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0248_orcamentoplanejadas_distribuicaoorcamentoplanejadas"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrcamentoMensalOrganizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_mensal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor que a organização pode gastar por mês com planejadas",
                        max_digits=12,
                        verbose_name="Valor Mensal",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "grande_comando",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.grandecomando",
                        verbose_name="Grande Comando",
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.orgao",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "sub_unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.subunidade",
                        verbose_name="Sub-Unidade",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.unidade",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orçamento Mensal por Organização",
                "verbose_name_plural": "Orçamentos Mensais por Organização",
                "ordering": [
                    "orgao__nome",
                    "grande_comando__nome",
                    "unidade__nome",
                    "sub_unidade__nome",
                ],
                "unique_together": {
                    ("orgao", "grande_comando", "unidade", "sub_unidade")
                },
            },
        ),
    ]
