# Generated by Django 5.0.2 on 2025-10-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0249_orcamentomensalorganizacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Planejada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Operação"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("origem", models.CharField(max_length=100, verbose_name="Origem")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "data_operacao",
                    models.DateTimeField(verbose_name="Data da Operação"),
                ),
                (
                    "semana",
                    models.CharField(
                        choices=[
                            ("segunda", "Segunda-feira"),
                            ("terca", "Terça-feira"),
                            ("quarta", "Quarta-feira"),
                            ("quinta", "Quinta-feira"),
                            ("sexta", "Sexta-feira"),
                            ("sabado", "Sábado"),
                            ("domingo", "Domingo"),
                        ],
                        max_length=20,
                        verbose_name="Dia da Semana",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("cotas", models.IntegerField(default=1, verbose_name="Cotas")),
                (
                    "saldo",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Saldo"
                    ),
                ),
                (
                    "policiais",
                    models.IntegerField(default=1, verbose_name="Número de Policiais"),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                            ("suspenso", "Suspenso"),
                        ],
                        default="ativo",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Operação Planejada",
                "verbose_name_plural": "Operações Planejadas",
                "ordering": ["-data_operacao", "nome"],
            },
        ),
        migrations.DeleteModel(
            name="OrcamentoMensalOrganizacao",
        ),
    ]
