# Generated by Django 5.0.2 on 2025-10-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0250_planejada_delete_orcamentomensalorganizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="valor_planejada_p1_fds",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor específico para planejada P1 em fins de semana",
                max_digits=10,
                verbose_name="Valor P1 - Fins de Semana",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="valor_planejada_p1_normal",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor específico para planejada P1 em dias normais",
                max_digits=10,
                verbose_name="Valor P1 - Dias Normais",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="valor_planejada_p2_fds",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor específico para planejada P2 em fins de semana",
                max_digits=10,
                verbose_name="Valor P2 - Fins de Semana",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="valor_planejada_p2_normal",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor específico para planejada P2 em dias normais",
                max_digits=10,
                verbose_name="Valor P2 - Dias Normais",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="valor_planejada_p3_fds",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor específico para planejada P3 em fins de semana",
                max_digits=10,
                verbose_name="Valor P3 - Fins de Semana",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="valor_planejada_p3_normal",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor específico para planejada P3 em dias normais",
                max_digits=10,
                verbose_name="Valor P3 - Dias Normais",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="valor_planejada_p4_fds",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor específico para planejada P4 em fins de semana",
                max_digits=10,
                verbose_name="Valor P4 - Fins de Semana",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="valor_planejada_p4_normal",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor específico para planejada P4 em dias normais",
                max_digits=10,
                verbose_name="Valor P4 - Dias Normais",
            ),
        ),
        migrations.AddField(
            model_name="planejada",
            name="hora_inicio",
            field=models.TimeField(default="08:00", verbose_name="Hora de Início"),
        ),
        migrations.AddField(
            model_name="planejada",
            name="hora_termino",
            field=models.TimeField(default="14:00", verbose_name="Hora de Término"),
        ),
        migrations.AddField(
            model_name="planejada",
            name="tipo_planejada",
            field=models.CharField(
                blank=True,
                default="P1",
                max_length=10,
                null=True,
                verbose_name="Tipo de Planejada",
            ),
        ),
    ]
