# Generated by Django 5.0.2 on 2025-10-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0251_configuracaoplanejadas_valor_planejada_p1_fds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="valor_por_hora_fds",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor por hora em fins de semana e feriados",
                max_digits=10,
                verbose_name="Valor por Hora - Fins de Semana",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="valor_por_hora_normal",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor por hora em dias normais (P1=6h, P2=12h, P3=18h, P4=24h)",
                max_digits=10,
                verbose_name="Valor por Hora - Dias Normais",
            ),
        ),
    ]
