# Generated by Django 5.0.2 on 2025-10-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0252_add_valor_por_hora_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="planejada",
            name="feriado_municipal",
            field=models.BooleanField(
                default=False,
                help_text="Marque se for um feriado municipal não cadastrado no sistema",
                verbose_name="Feriado Municipal",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaoplanejadas",
            name="valor_por_hora_fds",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor fixo por planejada em fins de semana e feriados",
                max_digits=10,
                verbose_name="Valor por Planejada - Fins de Semana",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaoplanejadas",
            name="valor_por_hora_normal",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor fixo por planejada em dias normais (P1=1x, P2=2x, P3=3x, P4=4x)",
                max_digits=10,
                verbose_name="Valor por Planejada - Dias Normais",
            ),
        ),
    ]
