# Generated by Django 5.0.2 on 2025-10-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0253_add_feriado_municipal_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planejada",
            name="feriado_municipal",
            field=models.BooleanField(
                default=False,
                help_text="Marque se for um feriado não cadastrado no sistema",
                verbose_name="Feriado",
            ),
        ),
        migrations.AlterField(
            model_name="planejada",
            name="policiais",
            field=models.IntegerField(default=1, verbose_name="Número de Bombeiros"),
        ),
    ]
