# Generated by Django 5.0.2 on 2025-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0254_remove_cotas_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="planejada",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Valor Total da Planejada",
            ),
        ),
    ]
