# Generated by Django 5.0.2 on 2025-10-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0255_add_valor_total_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="planejada",
            name="militares",
            field=models.ManyToManyField(
                blank=True,
                related_name="planejadas",
                to="militares.militar",
                verbose_name="Militares",
            ),
        ),
    ]
