# Generated by Django 5.0.2 on 2025-10-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0257_militar_gratificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="militar",
            name="voluntario_operacoes",
            field=models.CharField(
                choices=[
                    ("SIM", "Sim"),
                    ("NAO", "Não"),
                    ("NAO_INFORMADO", "Não Informado"),
                ],
                default="NAO_INFORMADO",
                max_length=20,
                verbose_name="Voluntário para Operações Planejadas",
            ),
        ),
    ]
