# Generated by Django 5.0.2 on 2025-10-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0258_militar_voluntario_operacoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="militar",
            name="voluntario_operacoes",
            field=models.CharField(
                choices=[
                    ("SIM", "Sim"),
                    ("NAO", "Não"),
                    ("NAO_INFORMADO", "Não Informado"),
                ],
                default="NAO_INFORMADO",
                help_text="Marque se deseja participar como voluntário de operações planejadas",
                max_length=20,
                verbose_name="Voluntário para Operações Planejadas",
            ),
        ),
        migrations.AddConstraint(
            model_name="planejada",
            constraint=models.UniqueConstraint(
                fields=("nome", "data_operacao", "cidade"),
                name="unique_planejada_nome_data_cidade",
            ),
        ),
    ]
