# Generated by Django 5.0.2 on 2025-10-24 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0259_add_unique_constraint_planejada"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbonoPlanejada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_operacao", models.DateField(verbose_name="Data da Operação")),
                (
                    "tipo_planejada",
                    models.CharField(
                        choices=[
                            ("P1", "P1"),
                            ("P2", "P2"),
                            ("P3", "P3"),
                            ("P4", "P4"),
                            ("P5", "P5"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Planejada",
                    ),
                ),
                (
                    "horas",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Horas"
                    ),
                ),
                ("cidade", models.CharField(max_length=200, verbose_name="Cidade")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
                (
                    "planejada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.planejada",
                        verbose_name="Planejada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abono de Planejada",
                "verbose_name_plural": "Abonos de Planejadas",
                "ordering": ["-data_operacao", "militar__nome_completo"],
                "unique_together": {("militar", "planejada", "data_operacao")},
            },
        ),
    ]
