# Generated by Django 5.0.2 on 2025-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0261_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="planejada",
            name="data_nota",
            field=models.DateField(blank=True, null=True, verbose_name="Data da Nota"),
        ),
        migrations.AddField(
            model_name="planejada",
            name="link_pdf_nota",
            field=models.URLField(
                blank=True,
                help_text="Link direto para o PDF da nota",
                null=True,
                verbose_name="Link PDF da Nota",
            ),
        ),
        migrations.AddField(
            model_name="planejada",
            name="numero_nota",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Ordem de Operação Planejada",
            ),
        ),
    ]
