# Generated by Django 5.2.3 on 2025-10-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0262_add_link_pdf_nota"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planejada",
            name="data_nota",
        ),
    ]
