# Generated by Django 5.0.2 on 2025-10-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0263_remove_data_nota_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="planejada",
            name="assinado_aprovador",
            field=models.BooleanField(
                default=False, verbose_name="Aprovado pelo Aprovador"
            ),
        ),
        migrations.AddField(
            model_name="planejada",
            name="assinado_operador",
            field=models.BooleanField(
                default=False, verbose_name="Assinado pelo Operador"
            ),
        ),
        migrations.AddField(
            model_name="planejada",
            name="atestado_fiscal",
            field=models.BooleanField(
                default=False, verbose_name="Atestado pelo Fiscal"
            ),
        ),
        migrations.AddField(
            model_name="planejada",
            name="data_aprovacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Aprovação"
            ),
        ),
        migrations.AddField(
            model_name="planejada",
            name="data_assinatura_operador",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Assinatura do Operador"
            ),
        ),
        migrations.AddField(
            model_name="planejada",
            name="data_atestado_fiscal",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data do Atestado do Fiscal"
            ),
        ),
    ]
