# Generated by Django 5.0.2 on 2025-10-25 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0265_add_assinatura_fields_publicacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planejada",
            name="assinado_aprovador",
        ),
        migrations.RemoveField(
            model_name="planejada",
            name="assinado_operador",
        ),
        migrations.RemoveField(
            model_name="planejada",
            name="atestado_fiscal",
        ),
        migrations.RemoveField(
            model_name="planejada",
            name="data_aprovacao",
        ),
        migrations.RemoveField(
            model_name="planejada",
            name="data_atestado_fiscal",
        ),
        migrations.RemoveField(
            model_name="publicacao",
            name="assinado_aprovador",
        ),
        migrations.RemoveField(
            model_name="publicacao",
            name="assinado_operador",
        ),
        migrations.RemoveField(
            model_name="publicacao",
            name="atestado_fiscal",
        ),
        migrations.RemoveField(
            model_name="publicacao",
            name="data_aprovacao",
        ),
        migrations.RemoveField(
            model_name="publicacao",
            name="data_assinatura_operador",
        ),
        migrations.RemoveField(
            model_name="publicacao",
            name="data_atestado_fiscal",
        ),
        migrations.AddField(
            model_name="planejada",
            name="assinatura_aprovador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planejadas_aprovador",
                to="militares.militar",
                verbose_name="Assinatura do Aprovador",
            ),
        ),
        migrations.AddField(
            model_name="planejada",
            name="assinatura_fiscal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planejadas_fiscal",
                to="militares.militar",
                verbose_name="Assinatura do Fiscal",
            ),
        ),
        migrations.AddField(
            model_name="planejada",
            name="assinatura_operador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planejadas_operador",
                to="militares.militar",
                verbose_name="Assinatura do Operador",
            ),
        ),
        migrations.AddField(
            model_name="planejada",
            name="data_assinatura_aprovador",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Assinatura do Aprovador"
            ),
        ),
        migrations.AddField(
            model_name="planejada",
            name="data_assinatura_fiscal",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Assinatura do Fiscal"
            ),
        ),
    ]
