# Generated by Django 5.0.2 on 2025-10-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0266_add_assinaturas_planejada"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_fiscal_planejadas",
            field=models.BooleanField(
                default=False, verbose_name="Fiscal de Planejadas"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_operador_planejadas",
            field=models.BooleanField(
                default=False, verbose_name="Operador de Planejadas"
            ),
        ),
        migrations.AlterField(
            model_name="funcaomilitar",
            name="publicacao",
            field=models.CharField(
                choices=[
                    ("EDITOR_GERAL", "Editor Geral"),
                    ("EDITOR_ADJUNTO", "Editor Adjunto"),
                    ("EDITOR", "Editor"),
                    ("APROVADOR", "Aprovador"),
                    ("REVISOR", "Revisor"),
                    ("DIGITADOR", "Digitador"),
                    ("OPERADOR_PLANEJADAS", "Operador de Planejadas"),
                    ("FISCAL_PLANEJADAS", "Fiscal de Planejadas"),
                    ("NENHUM", "Nenhum"),
                ],
                default="NENHUM",
                max_length=20,
                verbose_name="Publicação",
            ),
        ),
    ]
