# Generated by Django 5.0.2 on 2025-10-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0267_funcaomenuconfig_show_fiscal_planejadas_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funcaomenuconfig",
            name="show_fiscal_planejadas",
        ),
        migrations.RemoveField(
            model_name="funcaomenuconfig",
            name="show_operador_planejadas",
        ),
    ]
