# Generated by Django 5.0.2 on 2025-10-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0268_remove_funcaomenuconfig_show_fiscal_planejadas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="planejadas_adicionar_militar",
            field=models.BooleanField(
                default=False, verbose_name="Adicionar Militar à Planejada"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="planejadas_assinatura_fiscal",
            field=models.BooleanField(
                default=False, verbose_name="Assinar como Fiscal"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="planejadas_assinatura_operador",
            field=models.BooleanField(
                default=False, verbose_name="Assinar como Operador"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="planejadas_criar",
            field=models.BooleanField(default=False, verbose_name="Criar Planejadas"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="planejadas_editar",
            field=models.BooleanField(default=False, verbose_name="Editar Planejadas"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="planejadas_excluir",
            field=models.BooleanField(default=False, verbose_name="Excluir Planejadas"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="planejadas_remover_militar",
            field=models.BooleanField(
                default=False, verbose_name="Remover Militar da Planejada"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="planejadas_visualizar",
            field=models.BooleanField(
                default=False, verbose_name="Visualizar Planejadas"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_fiscal_planejadas",
            field=models.BooleanField(
                default=False, verbose_name="Fiscal de Planejadas"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_operador_planejadas",
            field=models.BooleanField(
                default=False, verbose_name="Operador de Planejadas"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_planejadas",
            field=models.BooleanField(
                default=False, verbose_name="Operações Planejadas"
            ),
        ),
    ]
