# Generated by Django 5.0.2 on 2025-10-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0272_add_instancia_fields_to_planejada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planejada",
            name="origem",
            field=models.CharField(max_length=200, verbose_name="Origem"),
        ),
    ]
