# Generated by Django 5.0.2 on 2025-10-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0273_increase_origem_field_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_escalas_abonar",
            field=models.BooleanField(default=False, verbose_name="Abonar Escalas"),
        ),
    ]
