# Generated by Django 5.0.2 on 2025-10-28 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0275_add_liquidacao_submenu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planejada",
            name="data_exclusao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Exclusão"
            ),
        ),
        migrations.AddField(
            model_name="planejada",
            name="excluido",
            field=models.BooleanField(default=False, verbose_name="Excluído"),
        ),
        migrations.AddField(
            model_name="planejada",
            name="excluido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Excluído por",
            ),
        ),
        migrations.AddField(
            model_name="planejada",
            name="justificativa_exclusao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Justificativa da Exclusão"
            ),
        ),
    ]
