# Generated by Django 5.0.2 on 2025-10-28 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0276_add_exclusao_fields_to_planejada"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="planejada",
            name="unique_planejada_nome_data_cidade",
        ),
        migrations.AddConstraint(
            model_name="planejada",
            constraint=models.UniqueConstraint(
                condition=models.Q(("excluido", False)),
                fields=("nome", "data_operacao", "cidade"),
                name="unique_planejada_nome_data_cidade",
            ),
        ),
    ]
