# Generated by Django 5.0.2 on 2025-10-29 22:47

import django.db.models.deletion
import militares.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0278_funcaomenuconfig_show_afastamentos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoAfastamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PORTARIA", "Portaria"),
                            ("OFICIO", "Ofício"),
                            ("DECRETO", "Decreto"),
                            ("LICENCA_MEDICA", "Licença Médica"),
                            ("SOLICITACAO", "Solicitação"),
                            ("AUTORIZACAO", "Autorização"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=200, verbose_name="Título do Documento"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=militares.models.documento_afastamento_upload_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Upload"
                    ),
                ),
                (
                    "afastamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="militares.afastamento",
                        verbose_name="Afastamento",
                    ),
                ),
                (
                    "upload_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Upload por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento do Afastamento",
                "verbose_name_plural": "Documentos dos Afastamentos",
                "ordering": ["-data_upload"],
            },
        ),
    ]
