# Generated by Django 5.0.2 on 2025-10-31 02:04

import django.db.models.deletion
import militares.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0279_documentoafastamento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="afastamento",
            name="tipo_afastamento",
            field=models.CharField(
                choices=[
                    ("ADIDO_SSP_PI", "Adido a SSP-PI"),
                    ("ADIDO_GAMIL", "Adido ao Gamil"),
                    (
                        "AFASTAMENTO_TEMPORARIO_CURSO",
                        "Afastamento Temporariamente/Frequentando Curso",
                    ),
                    (
                        "AFASTAMENTO_TEMPORARIO_INSTALACAO",
                        "Afastamento Temporariamente/Instalação",
                    ),
                    ("AFASTAMENTO_TEMPORARIO_LUTO", "Afastamento Temporariamente/Luto"),
                    (
                        "AFASTAMENTO_TEMPORARIO_NUPCIAS",
                        "Afastamento Temporariamente/Núpcias",
                    ),
                    (
                        "AFASTAMENTO_TEMPORARIO_TRANSITO",
                        "Afastamento Temporariamente/Trânsito",
                    ),
                    ("AFASTAMENTO_DISPENSA_MEDICA", "Afastamento/Dispensa Médica"),
                    (
                        "AFASTAMENTO_DISPENSA_RECOMPENSA",
                        "Afastamento/Dispensa por Recompensa",
                    ),
                    ("AFASTAMENTO_FERIAS", "Afastamento/Férias"),
                    ("AFASTAMENTO_LICENCA_ESPECIAL", "Afastamento/Licença Especial"),
                    (
                        "AFASTAMENTO_LICENCA_TRATAMENTO_SAUDE",
                        "Afastamento/Licença para Tratamento de Saúde",
                    ),
                    (
                        "AFASTAMENTO_LICENCA_INTERESSE_PARTICULAR",
                        "Afastamento/Licença para Tratar de Interesse Particular",
                    ),
                    (
                        "AFASTAMENTO_TRATAMENTO_SAUDE_PROPRIA",
                        "Afastamento/Para Tratamento de Saúde Própria",
                    ),
                    (
                        "AFASTAMENTO_TRATAMENTO_SAUDE_FAMILIA",
                        "Afastamento/Para Tratamento de Saúde de Pessoa da Família",
                    ),
                    (
                        "AGREGADO_CANDIDATO_CARGO_ELETIVO",
                        "Agregado/Candidato a Cargo Eletivo",
                    ),
                    ("AGREGADO_FUNCAO_CIVIL", "Agregado/Função Civil"),
                    ("AGREGADO_LTSP", "Agregado/LTSP"),
                    ("AGREGADO_LTSP_FAMILIA", "Agregado/LTSP Família"),
                    (
                        "AGUARDANDO_TRANSFERENCIA_RR_PEDIDO",
                        "Aguardando Transferência para RR/A Pedido",
                    ),
                    (
                        "AGUARDANDO_TRANSFERENCIA_RR_CONDICAO_ESPECIAL",
                        "Aguardando Transferência para RR/Condição Especial",
                    ),
                    (
                        "AGUARDANDO_TRANSFERENCIA_RR_EX_OFICIO",
                        "Aguardando Transferência para RR/Ex-Ofício",
                    ),
                    ("AUSENTE", "Ausente"),
                    (
                        "CEDIDO_FUNCAO_BM_FORCA_NACIONAL",
                        "Cedido Função BM/Força Nacional",
                    ),
                    ("CEDIDO_FUNCAO_BM_MP_PI", "Cedido Função BM/MP-PI"),
                    ("CEDIDO_FUNCAO_BM_SSP_PI", "Cedido Função BM/SSP-PI"),
                    ("DESAPARECIDO", "Desaparecido"),
                    ("DESERTOR", "Desertor"),
                    (
                        "DESLIGAMENTO_DEMITIDO",
                        "Desligamento ou Exclusão do Serviço Ativo/Demitido",
                    ),
                    (
                        "DESLIGAMENTO_DESERTOR",
                        "Desligamento ou Exclusão do Serviço Ativo/Desertor",
                    ),
                    (
                        "DESLIGAMENTO_EXCLUSAO_DISCIPLINA",
                        "Desligamento ou Exclusão do Serviço Ativo/Exclusão a Bem da Disciplina",
                    ),
                    (
                        "DESLIGAMENTO_EXTRAVIADO",
                        "Desligamento ou Exclusão do Serviço Ativo/Extraviado",
                    ),
                    (
                        "DESLIGAMENTO_FALECIDO",
                        "Desligamento ou Exclusão do Serviço Ativo/Falecido",
                    ),
                    (
                        "DESLIGAMENTO_PERDA_POSTO_PATENTE",
                        "Desligamento ou Exclusão do Serviço Ativo/Perda de Posto e Patente",
                    ),
                    (
                        "DESLIGAMENTO_REFORMADO",
                        "Desligamento ou Exclusão do Serviço Ativo/Reformado",
                    ),
                    (
                        "DESLIGAMENTO_RESERVA_REMUNERADA",
                        "Desligamento ou Exclusão do Serviço Ativo/Reserva Remunerada",
                    ),
                    ("INATIVO", "Inativo"),
                    ("LICENCIADO_EX_OFICIO", "Licenciado Ex-Ofício"),
                    (
                        "LICENCIADO_EX_OFICIO_DISCIPLINA",
                        "Licenciado Ex-Ofício a Bem da Disciplina",
                    ),
                    (
                        "LICENCIADO_EX_OFICIO_TEMPO_SERVICO",
                        "Licenciado Ex-Ofício por Conclusão do Tempo de Serviço",
                    ),
                    (
                        "LICENCIADO_EX_OFICIO_CONVENIENCIA",
                        "Licenciado Ex-Ofício por Conveniência do Serviço",
                    ),
                    ("LICENCIADO_PEDIDO", "Licenciado a Pedido"),
                    ("LICENCA_MATERNIDADE", "Licença Maternidade"),
                    ("LICENCA_PATERNIDADE", "Licença Paternidade"),
                    ("PRONTO", "Pronto"),
                ],
                help_text="Selecione a situação que será aplicada ao militar (todas as opções disponíveis no cadastro)",
                max_length=50,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="militar",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("PRONTO", "Pronto"),
                    (
                        "CEDIDO_FUNCAO_BM_FORCA_NACIONAL",
                        "Cedido Função BM/Força Nacional",
                    ),
                    ("CEDIDO_FUNCAO_BM_SSP_PI", "Cedido Função BM/SSP-PI"),
                    ("CEDIDO_FUNCAO_BM_MP_PI", "Cedido Função BM/MP-PI"),
                    ("ADIDO_GAMIL", "Adido ao Gamil"),
                    ("ADIDO_SSP_PI", "Adido a SSP-PI"),
                    ("AFASTAMENTO_FERIAS", "Afastamento/Férias"),
                    ("AFASTAMENTO_LICENCA_ESPECIAL", "Afastamento/Licença Especial"),
                    (
                        "AFASTAMENTO_LICENCA_INTERESSE_PARTICULAR",
                        "Afastamento/Licença para Tratar de Interesse Particular",
                    ),
                    (
                        "AFASTAMENTO_TRATAMENTO_SAUDE_FAMILIA",
                        "Afastamento/Para Tratamento de Saúde de Pessoa da Família",
                    ),
                    (
                        "AFASTAMENTO_TRATAMENTO_SAUDE_PROPRIA",
                        "Afastamento/Para Tratamento de Saúde Própria",
                    ),
                    ("AFASTAMENTO_DISPENSA_MEDICA", "Afastamento/Dispensa Médica"),
                    (
                        "AFASTAMENTO_LICENCA_TRATAMENTO_SAUDE",
                        "Afastamento/Licença para Tratamento de Saúde",
                    ),
                    (
                        "AFASTAMENTO_DISPENSA_RECOMPENSA",
                        "Afastamento/Dispensa por Recompensa",
                    ),
                    ("AFASTAMENTO_TEMPORARIO_LUTO", "Afastamento Temporariamente/Luto"),
                    (
                        "AFASTAMENTO_TEMPORARIO_NUPCIAS",
                        "Afastamento Temporariamente/Núpcias",
                    ),
                    (
                        "AFASTAMENTO_TEMPORARIO_INSTALACAO",
                        "Afastamento Temporariamente/Instalação",
                    ),
                    (
                        "AFASTAMENTO_TEMPORARIO_TRANSITO",
                        "Afastamento Temporariamente/Trânsito",
                    ),
                    (
                        "AFASTAMENTO_TEMPORARIO_CURSO",
                        "Afastamento Temporariamente/Frequentando Curso",
                    ),
                    ("AGREGADO_FUNCAO_CIVIL", "Agregado/Função Civil"),
                    ("AGREGADO_LTSP", "Agregado/LTSP"),
                    ("AGREGADO_LTSP_FAMILIA", "Agregado/LTSP Família"),
                    (
                        "AGREGADO_CANDIDATO_CARGO_ELETIVO",
                        "Agregado/Candidato a Cargo Eletivo",
                    ),
                    ("AUSENTE", "Ausente"),
                    ("DESERTOR", "Desertor"),
                    ("DESAPARECIDO", "Desaparecido"),
                    (
                        "AGUARDANDO_TRANSFERENCIA_RR_PEDIDO",
                        "Aguardando Transferência para RR/A Pedido",
                    ),
                    (
                        "AGUARDANDO_TRANSFERENCIA_RR_CONDICAO_ESPECIAL",
                        "Aguardando Transferência para RR/Condição Especial",
                    ),
                    (
                        "AGUARDANDO_TRANSFERENCIA_RR_EX_OFICIO",
                        "Aguardando Transferência para RR/Ex-Ofício",
                    ),
                    (
                        "DESLIGAMENTO_RESERVA_REMUNERADA",
                        "Desligamento ou Exclusão do Serviço Ativo/Reserva Remunerada",
                    ),
                    (
                        "DESLIGAMENTO_REFORMADO",
                        "Desligamento ou Exclusão do Serviço Ativo/Reformado",
                    ),
                    (
                        "DESLIGAMENTO_DEMITIDO",
                        "Desligamento ou Exclusão do Serviço Ativo/Demitido",
                    ),
                    (
                        "DESLIGAMENTO_PERDA_POSTO_PATENTE",
                        "Desligamento ou Exclusão do Serviço Ativo/Perda de Posto e Patente",
                    ),
                    (
                        "DESLIGAMENTO_EXCLUSAO_DISCIPLINA",
                        "Desligamento ou Exclusão do Serviço Ativo/Exclusão a Bem da Disciplina",
                    ),
                    (
                        "DESLIGAMENTO_DESERTOR",
                        "Desligamento ou Exclusão do Serviço Ativo/Desertor",
                    ),
                    (
                        "DESLIGAMENTO_FALECIDO",
                        "Desligamento ou Exclusão do Serviço Ativo/Falecido",
                    ),
                    (
                        "DESLIGAMENTO_EXTRAVIADO",
                        "Desligamento ou Exclusão do Serviço Ativo/Extraviado",
                    ),
                    ("LICENCIADO_PEDIDO", "Licenciado a Pedido"),
                    (
                        "LICENCIADO_EX_OFICIO_TEMPO_SERVICO",
                        "Licenciado Ex-Ofício por Conclusão do Tempo de Serviço",
                    ),
                    (
                        "LICENCIADO_EX_OFICIO_CONVENIENCIA",
                        "Licenciado Ex-Ofício por Conveniência do Serviço",
                    ),
                    (
                        "LICENCIADO_EX_OFICIO_DISCIPLINA",
                        "Licenciado Ex-Ofício a Bem da Disciplina",
                    ),
                    ("LICENCIADO_EX_OFICIO", "Licenciado Ex-Ofício"),
                    ("LICENCA_MATERNIDADE", "Licença Maternidade"),
                    ("LICENCA_PATERNIDADE", "Licença Paternidade"),
                    ("INATIVO", "Inativo"),
                ],
                default="PRONTO",
                max_length=50,
                verbose_name="Situação",
            ),
        ),
        migrations.CreateModel(
            name="Ferias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FRACIONADA_1", "Fracionada - 1º Período"),
                            ("FRACIONADA_2", "Fracionada - 2º Período"),
                            ("FRACIONADA_3", "Fracionada - 3º Período"),
                            ("INTEGRAL", "Integral"),
                            ("ABONO", "Abono de Férias"),
                        ],
                        default="INTEGRAL",
                        max_length=20,
                        verbose_name="Tipo de Férias",
                    ),
                ),
                (
                    "ano_referencia",
                    models.IntegerField(
                        help_text="Ano ao qual as férias se referem",
                        verbose_name="Ano de Referência",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_fim", models.DateField(verbose_name="Data de Fim")),
                (
                    "quantidade_dias",
                    models.IntegerField(
                        default=30,
                        help_text="Quantidade de dias de férias",
                        verbose_name="Quantidade de Dias",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANEJADA", "Planejada"),
                            ("GOZANDO", "Gozando"),
                            ("GOZADA", "Gozada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PLANEJADA",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "documento_referencia",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Ofício, Portaria, etc.",
                        max_length=200,
                        null=True,
                        verbose_name="Documento de Referência",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número do Documento",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ferias_cadastradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado por",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ferias",
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Férias",
                "verbose_name_plural": "Férias",
                "ordering": ["-ano_referencia", "-data_inicio", "-data_cadastro"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoFerias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PORTARIA", "Portaria"),
                            ("OFICIO", "Ofício"),
                            ("DECRETO", "Decreto"),
                            ("SOLICITACAO", "Solicitação"),
                            ("AUTORIZACAO", "Autorização"),
                            ("PLANO_FERIAS", "Plano de Férias"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=200, verbose_name="Título do Documento"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=militares.models.documento_ferias_upload_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Upload"
                    ),
                ),
                (
                    "upload_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Upload por",
                    ),
                ),
                (
                    "ferias",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="militares.ferias",
                        verbose_name="Férias",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Férias",
                "verbose_name_plural": "Documentos de Férias",
                "ordering": ["-data_upload"],
            },
        ),
        migrations.AddIndex(
            model_name="ferias",
            index=models.Index(
                fields=["-ano_referencia"], name="militares_f_ano_ref_be2e70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ferias",
            index=models.Index(
                fields=["-data_inicio"], name="militares_f_data_in_2acf11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ferias",
            index=models.Index(fields=["status"], name="militares_f_status_accce0_idx"),
        ),
        migrations.AddIndex(
            model_name="ferias",
            index=models.Index(
                fields=["militar"], name="militares_f_militar_62aaed_idx"
            ),
        ),
    ]
