# Generated by Django 5.0.2 on 2025-10-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0280_criar_modulo_ferias"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_ferias",
            field=models.BooleanField(default=False, verbose_name="Férias"),
        ),
    ]
