# Generated by Django 5.0.2 on 2025-10-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0282_criar_plano_ferias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planoferias",
            name="numero_documento",
            field=models.CharField(
                blank=True,
                help_text="Ex: DOE n° 001/2025 de 25/01/2025",
                max_length=200,
                null=True,
                verbose_name="Documento de Publicação",
            ),
        ),
    ]
