# Generated by Django 5.0.2 on 2025-10-31 22:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0283_alter_planoferias_numero_documento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ferias",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANEJADA", "Planejada"),
                    ("GOZANDO", "Usufruindo"),
                    ("GOZADA", "Usufruída"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="PLANEJADA",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="Viatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placa",
                    models.CharField(
                        help_text="Ex: ABC-1234 ou ABC1D23",
                        max_length=10,
                        unique=True,
                        verbose_name="Placa",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VTL", "Viatura Tática Leve"),
                            ("VTM", "Viatura Tática Média"),
                            ("VTP", "Viatura Tática Pesada"),
                            ("AMB", "Ambulância"),
                            ("CMD", "Comando"),
                            ("MAN", "Manutenção"),
                            ("OUT", "Outras"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Viatura",
                    ),
                ),
                (
                    "marca",
                    models.CharField(
                        help_text="Ex: Ford, Chevrolet, Mercedes-Benz",
                        max_length=100,
                        verbose_name="Marca",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        help_text="Ex: Ranger, D20, Sprinter",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "ano_fabricacao",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Ano de Fabricação",
                    ),
                ),
                (
                    "ano_modelo",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Ano do Modelo",
                    ),
                ),
                (
                    "chassi",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Chassi",
                    ),
                ),
                (
                    "renavam",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="RENAVAM",
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Cor"
                    ),
                ),
                (
                    "km_atual",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Kilometragem Atual"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("EM_USO", "Em Uso"),
                            ("MANUTENCAO", "Em Manutenção"),
                            ("BAIXA", "Dada de Baixa"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "combustivel",
                    models.CharField(
                        choices=[
                            ("GASOLINA", "Gasolina"),
                            ("DIESEL", "Diesel"),
                            ("ETANOL", "Etanol"),
                            ("FLEX", "Flex"),
                            ("ELETRICO", "Elétrico"),
                        ],
                        default="DIESEL",
                        max_length=20,
                        verbose_name="Combustível",
                    ),
                ),
                (
                    "capacidade_tanque",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Capacidade do Tanque (litros)",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_aquisicao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Aquisição"
                    ),
                ),
                (
                    "valor_aquisicao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor de Aquisição (R$)",
                    ),
                ),
                (
                    "fornecedor",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Fornecedor"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="viaturas_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "grande_comando",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.grandecomando",
                        verbose_name="Grande Comando",
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.orgao",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "sub_unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.subunidade",
                        verbose_name="Sub-Unidade",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.unidade",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Viatura",
                "verbose_name_plural": "Viaturas",
                "ordering": ["placa"],
                "indexes": [
                    models.Index(fields=["placa"], name="militares_v_placa_560a9e_idx"),
                    models.Index(
                        fields=["status"], name="militares_v_status_28b3c9_idx"
                    ),
                    models.Index(fields=["tipo"], name="militares_v_tipo_c6cb80_idx"),
                ],
            },
        ),
    ]
