# Generated by Django 5.0.2 on 2025-10-31 23:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0285_viatura_prefixo_alter_permissaofuncao_modulo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="viatura",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ABT", "Auto Bomba Tanque"),
                    ("ABCI", "Auto Bomba de Combate a Incêndio"),
                    ("ESC", "Auto Escada"),
                    ("APT", "Auto Plataforma"),
                    ("ASE", "Auto Socorro de Emergência"),
                    ("ASB", "Ambulância de Suporte Básico"),
                    ("ASA", "Ambulância de Suporte Avançado"),
                    ("VTL", "Viatura Tática Leve"),
                    ("VTM", "Viatura Tática Média"),
                    ("VTP", "Viatura Tática Pesada"),
                    ("RES", "Viatura de Resgate"),
                    ("SAL", "Viatura de Salvamento"),
                    ("HAZ", "Viatura Hazmat - Material Perigoso"),
                    ("CLIF", "Caminhão de Luta contra Incêndio Florestal"),
                    ("CMD", "Viatura de Comando"),
                    ("COM", "Viatura de Comunicações"),
                    ("OPE", "Viatura de Operações Especiais"),
                    ("BAR", "Barco/Bote"),
                    ("MOT", "Moto"),
                    ("MAN", "Viatura de Manutenção"),
                    ("OUT", "Outras"),
                ],
                max_length=10,
                verbose_name="Tipo de Viatura",
            ),
        ),
        migrations.AlterField(
            model_name="viatura",
            name="valor_aquisicao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Valor de Aquisição (R$)",
            ),
        ),
        migrations.CreateModel(
            name="AbastecimentoViatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_abastecimento",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data e Hora do Abastecimento",
                    ),
                ),
                (
                    "quantidade_litros",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Quantidade (Litros)",
                    ),
                ),
                (
                    "valor_litro",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Valor por Litro (R$)",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Valor Total (R$)",
                    ),
                ),
                (
                    "km_abastecimento",
                    models.PositiveIntegerField(verbose_name="KM no Abastecimento"),
                ),
                (
                    "tipo_combustivel",
                    models.CharField(
                        choices=[
                            ("GASOLINA", "Gasolina"),
                            ("DIESEL", "Diesel"),
                            ("ETANOL", "Etanol"),
                            ("FLEX", "Flex (Gasolina/Etanol)"),
                            ("GNV", "GNV (Gás Natural Veicular)"),
                            ("ELETRICO", "Elétrico"),
                        ],
                        default="DIESEL",
                        max_length=20,
                        verbose_name="Tipo de Combustível",
                    ),
                ),
                (
                    "posto_fornecedor",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Posto/Fornecedor",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abastecimentos_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abastecimentos_responsaveis",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável pelo Abastecimento",
                    ),
                ),
                (
                    "viatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abastecimentos",
                        to="militares.viatura",
                        verbose_name="Viatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abastecimento de Viatura",
                "verbose_name_plural": "Abastecimentos de Viaturas",
                "ordering": ["-data_abastecimento", "-km_abastecimento"],
                "indexes": [
                    models.Index(
                        fields=["viatura", "-data_abastecimento"],
                        name="militares_a_viatura_2b6723_idx",
                    ),
                    models.Index(
                        fields=["data_abastecimento"],
                        name="militares_a_data_ab_b4ec87_idx",
                    ),
                    models.Index(
                        fields=["tipo_combustivel"],
                        name="militares_a_tipo_co_f85cdf_idx",
                    ),
                ],
            },
        ),
    ]
