# Generated by Django 5.0.2 on 2025-10-31 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0286_alter_viatura_tipo_alter_viatura_valor_aquisicao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abastecimentoviatura",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="abastecimentos_responsaveis",
                to="militares.militar",
                verbose_name="Responsável pelo Abastecimento",
            ),
        ),
    ]
