# Generated by Django 5.0.2 on 2025-11-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0287_alter_abastecimentoviatura_responsavel"),
    ]

    operations = [
        migrations.AddField(
            model_name="viatura",
            name="cartao_abastecimento",
            field=models.CharField(
                blank=True,
                help_text="Número do cartão utilizado para abastecimento",
                max_length=50,
                null=True,
                verbose_name="Cartão de Abastecimento",
            ),
        ),
    ]
