# Generated by Django 5.0.2 on 2025-11-01 01:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0288_add_cartao_abastecimento_to_viatura"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManutencaoViatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_manutencao",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data e Hora da Manutenção",
                    ),
                ),
                (
                    "tipo_manutencao",
                    models.CharField(
                        choices=[
                            ("PREVENTIVA", "Preventiva"),
                            ("CORRETIVA", "Corretiva"),
                            ("INSPECAO", "Inspeção"),
                            ("LUBRIFICACAO", "Lubrificação"),
                            ("CALIBRAGEM", "Calibragem de Pneus"),
                            ("REVISAO", "Revisão"),
                            ("PINTURA", "Pintura"),
                            ("OUTRA", "Outra"),
                        ],
                        default="PREVENTIVA",
                        max_length=20,
                        verbose_name="Tipo de Manutenção",
                    ),
                ),
                (
                    "km_manutencao",
                    models.PositiveIntegerField(verbose_name="KM na Manutenção"),
                ),
                (
                    "descricao_servico",
                    models.TextField(
                        help_text="Detalhamento dos serviços realizados",
                        verbose_name="Descrição do Serviço",
                    ),
                ),
                (
                    "fornecedor_oficina",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Fornecedor/Oficina",
                    ),
                ),
                (
                    "valor_manutencao",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Valor da Manutenção (R$)",
                    ),
                ),
                (
                    "pecas_trocadas",
                    models.TextField(
                        blank=True,
                        help_text="Lista de peças que foram substituídas",
                        null=True,
                        verbose_name="Peças Trocadas",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manutencoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manutencoes_responsaveis",
                        to="militares.militar",
                        verbose_name="Responsável pela Manutenção",
                    ),
                ),
                (
                    "viatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manutencoes",
                        to="militares.viatura",
                        verbose_name="Viatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manutenção de Viatura",
                "verbose_name_plural": "Manutenções de Viaturas",
                "ordering": ["-data_manutencao", "-km_manutencao"],
                "indexes": [
                    models.Index(
                        fields=["viatura", "-data_manutencao"],
                        name="militares_m_viatura_2d2fed_idx",
                    ),
                    models.Index(
                        fields=["data_manutencao"],
                        name="militares_m_data_ma_15d5e7_idx",
                    ),
                    models.Index(
                        fields=["tipo_manutencao"],
                        name="militares_m_tipo_ma_b336c6_idx",
                    ),
                ],
            },
        ),
    ]
