# Generated by Django 5.0.2 on 2025-11-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0289_add_manutencao_viatura"),
    ]

    operations = [
        migrations.AddField(
            model_name="manutencaoviatura",
            name="proximo_km_revisao",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="KM previsto para a próxima revisão (apenas para tipo Revisão)",
                null=True,
                verbose_name="KM para Próxima Revisão",
            ),
        ),
    ]
