# Generated by Django 5.0.2 on 2025-11-01 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0290_add_proximo_km_revisao_to_manutencao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="manutencaoviatura",
            name="fornecedor_oficina",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Oficina"
            ),
        ),
        migrations.CreateModel(
            name="HistoricoAbastecimentoAssinado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(verbose_name="Data Início do Período"),
                ),
                ("data_fim", models.DateField(verbose_name="Data Fim do Período")),
                (
                    "total_litros",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total de Litros"
                    ),
                ),
                (
                    "total_valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Gasto (R$)"
                    ),
                ),
                (
                    "quantidade_abastecimentos",
                    models.PositiveIntegerField(
                        verbose_name="Quantidade de Abastecimentos"
                    ),
                ),
                (
                    "data_geracao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Geração"
                    ),
                ),
                (
                    "hash_documento",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Hash do Documento",
                    ),
                ),
                (
                    "gerado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historicos_abastecimentos_gerados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gerado por",
                    ),
                ),
                (
                    "viatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicos_abastecimentos_assinados",
                        to="militares.viatura",
                        verbose_name="Viatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Abastecimento Assinado",
                "verbose_name_plural": "Históricos de Abastecimentos Assinados",
                "ordering": ["-data_geracao"],
            },
        ),
        migrations.CreateModel(
            name="AssinaturaHistoricoAbastecimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_assinatura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Assinatura"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações da Assinatura"
                    ),
                ),
                (
                    "tipo_assinatura",
                    models.CharField(
                        choices=[
                            ("APROVACAO", "Aprovação"),
                            ("CONFERENCIA", "Conferência"),
                            ("ELETRONICA", "Eletrônica"),
                            ("HOMOLOGACAO", "Homologação"),
                            ("REVISAO", "Revisão"),
                        ],
                        default="APROVACAO",
                        max_length=15,
                        verbose_name="Tipo de Assinatura",
                    ),
                ),
                (
                    "funcao_assinatura",
                    models.CharField(
                        blank=True,
                        help_text="Função/cargo do usuário no momento da assinatura",
                        max_length=100,
                        null=True,
                        verbose_name="Função no momento da assinatura",
                    ),
                ),
                (
                    "tipo_midia",
                    models.CharField(
                        choices=[("FISICA", "Física"), ("ELETRONICA", "Eletrônica")],
                        default="FISICA",
                        max_length=10,
                        verbose_name="Tipo de Mídia",
                    ),
                ),
                (
                    "assinatura_fisica",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="assinaturas_fisicas/",
                        verbose_name="Assinatura Física (Imagem)",
                    ),
                ),
                (
                    "hash_documento",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Hash do Documento",
                    ),
                ),
                (
                    "timestamp",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Timestamp da Assinatura",
                    ),
                ),
                (
                    "assinatura_digital",
                    models.TextField(
                        blank=True, null=True, verbose_name="Assinatura Digital"
                    ),
                ),
                (
                    "certificado",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Certificado Digital",
                    ),
                ),
                (
                    "ip_assinatura",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP da Assinatura"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "assinado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assinado por",
                    ),
                ),
                (
                    "historico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to="militares.historicoabastecimentoassinado",
                        verbose_name="Histórico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura do Histórico de Abastecimento",
                "verbose_name_plural": "Assinaturas dos Históricos de Abastecimentos",
                "ordering": ["-data_assinatura"],
                "unique_together": {("historico", "assinado_por", "tipo_assinatura")},
            },
        ),
    ]
