# Generated by Django 5.0.2 on 2025-11-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0291_add_historico_abastecimento_assinado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ferias",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANEJADA", "Planejada"),
                    ("GOZANDO", "Usufruindo"),
                    ("GOZADA", "Usufruída"),
                    ("CANCELADA", "Cancelada"),
                    ("REPROGRAMADA", "Reprogramada"),
                ],
                default="PLANEJADA",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
