# Generated by Django 5.0.2 on 2025-11-01 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0292_add_reprogramada_status_to_ferias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ferias",
            name="plano",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ferias",
                to="militares.planoferias",
                verbose_name="Plano de Férias",
            ),
        ),
    ]
