# Generated by Django 5.2.3 on 2025-11-02 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0293_alter_ferias_plano_cascade_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="abastecimentoviatura",
            name="com_aditivos",
            field=models.BooleanField(
                default=False,
                help_text="Indica se foram comprados também aditivos para o combustível",
                verbose_name="Com Aditivos",
            ),
        ),
        migrations.AddField(
            model_name="abastecimentoviatura",
            name="quantidade_aditivo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quantidade (litros ou unidade)",
                max_digits=10,
                null=True,
                verbose_name="Quantidade de Aditivo",
            ),
        ),
        migrations.AddField(
            model_name="abastecimentoviatura",
            name="tipo_aditivo",
            field=models.CharField(
                blank=True,
                help_text="Ex: Aditivo para diesel, limpa bicos, etc.",
                max_length=100,
                null=True,
                verbose_name="Tipo de Aditivo",
            ),
        ),
        migrations.AddField(
            model_name="abastecimentoviatura",
            name="valor_total_aditivo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Valor Total do Aditivo (R$)",
            ),
        ),
        migrations.AddField(
            model_name="abastecimentoviatura",
            name="valor_total_nota",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Soma do combustível + aditivos",
                max_digits=12,
                null=True,
                verbose_name="Valor Total da Nota (R$)",
            ),
        ),
        migrations.AddField(
            model_name="abastecimentoviatura",
            name="valor_unitario_aditivo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Valor Unitário do Aditivo (R$)",
            ),
        ),
    ]
