# Generated by Django 5.0.2 on 2025-11-02 11:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0294_abastecimentoviatura_com_aditivos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrocaOleoViatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_troca",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data e Hora da Troca",
                    ),
                ),
                (
                    "km_troca",
                    models.PositiveIntegerField(verbose_name="KM na Troca de Óleo"),
                ),
                (
                    "tipo_oleo",
                    models.CharField(
                        choices=[
                            ("MINERAL", "Óleo Mineral"),
                            ("SEMI_SINTETICO", "Óleo Semi-Sintético"),
                            ("SINTETICO", "Óleo Sintético"),
                            ("SINTETICO_PLUS", "Óleo Sintético Plus"),
                            ("OUTRO", "Outro"),
                        ],
                        default="SEMI_SINTETICO",
                        max_length=20,
                        verbose_name="Tipo de Óleo",
                    ),
                ),
                (
                    "quantidade_litros",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Quantidade (Litros)",
                    ),
                ),
                (
                    "valor_litro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor por Litro (R$)",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Valor Total (R$)",
                    ),
                ),
                (
                    "fornecedor_oficina",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Oficina/Fornecedor",
                    ),
                ),
                (
                    "trocou_filtro",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se também foi trocado o filtro de óleo",
                        verbose_name="Trocou Filtro de Óleo",
                    ),
                ),
                (
                    "valor_filtro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor do Filtro (R$)",
                    ),
                ),
                (
                    "proximo_km_troca",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="KM previsto para a próxima troca de óleo",
                        null=True,
                        verbose_name="KM para Próxima Troca",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trocas_oleo_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trocas_oleo_responsaveis",
                        to="militares.militar",
                        verbose_name="Responsável pela Troca",
                    ),
                ),
                (
                    "viatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trocas_oleo",
                        to="militares.viatura",
                        verbose_name="Viatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Troca de Óleo de Viatura",
                "verbose_name_plural": "Trocas de Óleo de Viaturas",
                "ordering": ["-data_troca", "-km_troca"],
                "indexes": [
                    models.Index(
                        fields=["viatura", "-data_troca"],
                        name="militares_t_viatura_b72805_idx",
                    ),
                    models.Index(
                        fields=["data_troca"], name="militares_t_data_tr_be991a_idx"
                    ),
                    models.Index(
                        fields=["tipo_oleo"], name="militares_t_tipo_ol_b6aaca_idx"
                    ),
                ],
            },
        ),
    ]
