# Generated by Django 5.0.2 on 2025-11-02 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0295_add_troca_oleo_viatura"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trocaoleoviatura",
            old_name="trocou_filtro",
            new_name="trocou_filtro_oleo",
        ),
        migrations.RemoveField(
            model_name="trocaoleoviatura",
            name="valor_filtro",
        ),
        migrations.AddField(
            model_name="trocaoleoviatura",
            name="outras_pecas",
            field=models.TextField(
                blank=True,
                help_text="Lista de outras peças que foram trocadas ou substituídas",
                null=True,
                verbose_name="Outras Peças",
            ),
        ),
        migrations.AddField(
            model_name="trocaoleoviatura",
            name="trocou_filtro_ar",
            field=models.BooleanField(
                default=False,
                help_text="Indica se também foi trocado o filtro de ar condicionado",
                verbose_name="Trocou Filtro de Ar Condicionado",
            ),
        ),
        migrations.AddField(
            model_name="trocaoleoviatura",
            name="trocou_filtro_combustivel",
            field=models.BooleanField(
                default=False,
                help_text="Indica se também foi trocado o filtro de combustível",
                verbose_name="Trocou Filtro de Combustível",
            ),
        ),
        migrations.AddField(
            model_name="trocaoleoviatura",
            name="valor_filtro_ar",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Valor do Filtro de Ar Condicionado (R$)",
            ),
        ),
        migrations.AddField(
            model_name="trocaoleoviatura",
            name="valor_filtro_combustivel",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Valor do Filtro de Combustível (R$)",
            ),
        ),
        migrations.AddField(
            model_name="trocaoleoviatura",
            name="valor_filtro_oleo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Valor do Filtro de Óleo (R$)",
            ),
        ),
        migrations.AddField(
            model_name="trocaoleoviatura",
            name="valor_outras_pecas",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Valor das Outras Peças (R$)",
            ),
        ),
    ]
