# Generated by Django 5.0.2 on 2025-11-02 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0296_add_filtros_e_pecas_troca_oleo"),
    ]

    operations = [
        migrations.AddField(
            model_name="trocaoleoviatura",
            name="adicionou_aditivo_arrefecimento",
            field=models.BooleanField(
                default=False,
                help_text="Indica se foi adicionado aditivo de arrefecimento",
                verbose_name="Adicionou Aditivo de Arrefecimento",
            ),
        ),
        migrations.AddField(
            model_name="trocaoleoviatura",
            name="quantidade_aditivo_arrefecimento",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantidade de Aditivo (Litros)",
            ),
        ),
        migrations.AddField(
            model_name="trocaoleoviatura",
            name="valor_aditivo_arrefecimento",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Valor do Aditivo de Arrefecimento (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="trocaoleoviatura",
            name="outras_pecas",
            field=models.TextField(
                blank=True,
                help_text="Lista de outras peças que foram trocadas ou substituídas (nome e valor)",
                null=True,
                verbose_name="Outras Peças",
            ),
        ),
    ]
