# Generated by Django 5.0.2 on 2025-11-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0297_add_aditivo_arrefecimento_troca_oleo"),
    ]

    operations = [
        migrations.AddField(
            model_name="trocaoleoviatura",
            name="valor_total_nota",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Soma total da nota fiscal (óleo + filtros + aditivo + outras peças)",
                max_digits=12,
                null=True,
                verbose_name="Valor Total da Nota (R$)",
            ),
        ),
    ]
