# Generated by Django 5.0.2 on 2025-11-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0298_add_valor_total_nota_troca_oleo"),
    ]

    operations = [
        migrations.AddField(
            model_name="trocaoleoviatura",
            name="nome_oleo",
            field=models.CharField(
                blank=True,
                help_text="Nome/comercial do óleo utilizado",
                max_length=200,
                null=True,
                verbose_name="Nome do Óleo",
            ),
        ),
    ]
