# Generated by Django 5.0.2 on 2025-11-02 14:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0299_add_nome_oleo_troca_oleo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenciamentoViatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ano_licenciamento",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Ano de Licenciamento",
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "valor_licenciamento",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Valor do Licenciamento (R$)",
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True,
                        help_text="Data em que o licenciamento foi pago",
                        null=True,
                        verbose_name="Data de Pagamento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PAGO", "Pago"),
                            ("PENDENTE", "Pendente"),
                            ("VENCIDO", "Vencido"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "proximo_vencimento",
                    models.DateField(
                        blank=True,
                        help_text="Data prevista para o próximo vencimento",
                        null=True,
                        verbose_name="Próximo Vencimento",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licenciamentos_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licenciamentos_responsaveis",
                        to="militares.militar",
                        verbose_name="Responsável pelo Licenciamento",
                    ),
                ),
                (
                    "viatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenciamentos",
                        to="militares.viatura",
                        verbose_name="Viatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licenciamento de Viatura",
                "verbose_name_plural": "Licenciamentos de Viaturas",
                "ordering": ["-ano_licenciamento", "-data_vencimento"],
                "indexes": [
                    models.Index(
                        fields=["viatura", "-ano_licenciamento"],
                        name="militares_l_viatura_bc3c2d_idx",
                    ),
                    models.Index(
                        fields=["data_vencimento"],
                        name="militares_l_data_ve_4dec8e_idx",
                    ),
                    models.Index(
                        fields=["status"], name="militares_l_status_a66745_idx"
                    ),
                ],
                "unique_together": {("viatura", "ano_licenciamento")},
            },
        ),
    ]
