# Generated by Django 5.0.2 on 2025-11-03 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0301_historicoalteracaoviatura"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LicencaEspecial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decenio",
                    models.IntegerField(
                        help_text="Qual decênio (1º, 2º, 3º, etc.) a partir da data de ingresso",
                        verbose_name="Decênio",
                    ),
                ),
                (
                    "quantidade_meses",
                    models.IntegerField(
                        help_text="Quantidade de meses da licença especial",
                        verbose_name="Quantidade de Meses",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_fim",
                    models.DateField(
                        blank=True,
                        help_text="Calculado automaticamente baseado na quantidade de meses",
                        null=True,
                        verbose_name="Data de Fim",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANEJADA", "Planejada"),
                            ("GOZANDO", "Usufruindo"),
                            ("GOZADA", "Usufruída"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PLANEJADA",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "documento_referencia",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Portaria, Decreto, etc.",
                        max_length=200,
                        null=True,
                        verbose_name="Documento de Referência",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número do Documento",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licencas_especiais_cadastradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado por",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licencas_especiais",
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licença Especial",
                "verbose_name_plural": "Licenças Especiais",
                "ordering": ["-data_inicio", "-data_cadastro"],
                "indexes": [
                    models.Index(
                        fields=["-data_inicio"], name="militares_l_data_in_b3adcd_idx"
                    ),
                    models.Index(
                        fields=["status"], name="militares_l_status_0e6198_idx"
                    ),
                    models.Index(
                        fields=["militar"], name="militares_l_militar_55e927_idx"
                    ),
                    models.Index(
                        fields=["decenio"], name="militares_l_decenio_859094_idx"
                    ),
                ],
            },
        ),
    ]
