# Generated by Django 5.2.3 on 2025-11-03 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0302_add_licenca_especial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoLicencaEspecial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ano_referencia",
                    models.IntegerField(
                        help_text="Ano ao qual as licenças especiais se referem",
                        verbose_name="Ano de Referência",
                    ),
                ),
                (
                    "ano_plano",
                    models.IntegerField(
                        help_text="Ano em que o plano foi criado",
                        verbose_name="Ano do Plano",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Ex: Plano de Licenças Especiais 2025",
                        max_length=200,
                        verbose_name="Título do Plano",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("EM_APROVACAO", "Em Aprovação"),
                            ("APROVADO", "Aprovado"),
                            ("PUBLICADO", "Publicado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "documento_referencia",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Portaria, Decreto, etc.",
                        max_length=200,
                        null=True,
                        verbose_name="Documento de Referência",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True,
                        help_text="Ex: DOE n° 001/2025 de 25/01/2025",
                        max_length=200,
                        null=True,
                        verbose_name="Documento de Publicação",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planos_licencas_especiais_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Licença Especial",
                "verbose_name_plural": "Planos de Licenças Especiais",
                "ordering": ["-ano_plano", "-ano_referencia", "-data_criacao"],
            },
        ),
        migrations.AddField(
            model_name="licencaespecial",
            name="plano",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licencas_especiais",
                to="militares.planolicencaespecial",
                verbose_name="Plano de Licença Especial",
            ),
        ),
        migrations.AddIndex(
            model_name="planolicencaespecial",
            index=models.Index(
                fields=["-ano_plano"], name="militares_p_ano_pla_cf92db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planolicencaespecial",
            index=models.Index(
                fields=["-ano_referencia"], name="militares_p_ano_ref_6673d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planolicencaespecial",
            index=models.Index(fields=["status"], name="militares_p_status_21832b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="planolicencaespecial",
            unique_together={("ano_referencia", "ano_plano")},
        ),
    ]
