# Generated by Django 5.2.3 on 2025-11-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0303_criar_plano_licenca_especial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planolicencaespecial",
            options={
                "ordering": ["-ano_plano", "-data_criacao"],
                "verbose_name": "Plano de Licença Especial",
                "verbose_name_plural": "Planos de Licenças Especiais",
            },
        ),
        migrations.RemoveIndex(
            model_name="planolicencaespecial",
            name="militares_p_ano_ref_6673d3_idx",
        ),
        migrations.AlterUniqueTogether(
            name="planolicencaespecial",
            unique_together={("ano_plano",)},
        ),
        migrations.RemoveField(
            model_name="planolicencaespecial",
            name="ano_referencia",
        ),
    ]
