# Generated by Django 5.0.2 on 2025-11-04 12:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0304_remover_ano_referencia_plano_licenca"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RodagemViatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_saida",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Data de Saída"
                    ),
                ),
                (
                    "hora_saida",
                    models.TimeField(
                        default=django.utils.timezone.now, verbose_name="Hora de Saída"
                    ),
                ),
                (
                    "data_retorno",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Retorno"
                    ),
                ),
                (
                    "hora_retorno",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Retorno"
                    ),
                ),
                ("km_inicial", models.PositiveIntegerField(verbose_name="KM Inicial")),
                (
                    "km_final",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="KM Final"
                    ),
                ),
                (
                    "km_rodado",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Calculado automaticamente",
                        verbose_name="KM Rodado",
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        choices=[
                            ("OPERACAO", "Operação"),
                            ("TREINAMENTO", "Treinamento"),
                            ("MANUTENCAO", "Manutenção"),
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("TRANSPORTE", "Transporte"),
                            ("OUTROS", "Outros"),
                        ],
                        default="OPERACAO",
                        max_length=20,
                        verbose_name="Objetivo",
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        blank=True,
                        help_text="Local de destino da viatura",
                        max_length=200,
                        null=True,
                        verbose_name="Destino",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ANDAMENTO", "Em Andamento"),
                            ("FINALIZADA", "Finalizada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="EM_ANDAMENTO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "condutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rodagens_condutor",
                        to="militares.militar",
                        verbose_name="Condutor",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rodagens_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "viatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rodagens",
                        to="militares.viatura",
                        verbose_name="Viatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rodagem de Viatura",
                "verbose_name_plural": "Rodagens de Viaturas",
                "ordering": ["-data_saida", "-hora_saida"],
                "indexes": [
                    models.Index(
                        fields=["viatura", "-data_saida"],
                        name="militares_r_viatura_b1359f_idx",
                    ),
                    models.Index(
                        fields=["data_saida"], name="militares_r_data_sa_727416_idx"
                    ),
                    models.Index(
                        fields=["status"], name="militares_r_status_41db17_idx"
                    ),
                    models.Index(
                        fields=["condutor"], name="militares_r_conduto_c78e6d_idx"
                    ),
                ],
            },
        ),
    ]
