# Generated by Django 5.0.2 on 2025-11-04 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0305_add_rodagem_viatura"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferenciaViatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_transferencia",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Transferência"
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(
                        help_text="Motivo da transferência",
                        verbose_name="Justificativa",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "grande_comando_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_destino",
                        to="militares.grandecomando",
                        verbose_name="Grande Comando de Destino",
                    ),
                ),
                (
                    "grande_comando_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_origem",
                        to="militares.grandecomando",
                        verbose_name="Grande Comando de Origem",
                    ),
                ),
                (
                    "orgao_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_destino",
                        to="militares.orgao",
                        verbose_name="Órgão de Destino",
                    ),
                ),
                (
                    "orgao_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_origem",
                        to="militares.orgao",
                        verbose_name="Órgão de Origem",
                    ),
                ),
                (
                    "sub_unidade_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_destino",
                        to="militares.subunidade",
                        verbose_name="Sub-Unidade de Destino",
                    ),
                ),
                (
                    "sub_unidade_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_origem",
                        to="militares.subunidade",
                        verbose_name="Sub-Unidade de Origem",
                    ),
                ),
                (
                    "transferido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Transferido por",
                    ),
                ),
                (
                    "unidade_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_destino",
                        to="militares.unidade",
                        verbose_name="Unidade de Destino",
                    ),
                ),
                (
                    "unidade_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_origem",
                        to="militares.unidade",
                        verbose_name="Unidade de Origem",
                    ),
                ),
                (
                    "viatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transferencias",
                        to="militares.viatura",
                        verbose_name="Viatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferência de Viatura",
                "verbose_name_plural": "Transferências de Viaturas",
                "ordering": ["-data_transferencia"],
                "indexes": [
                    models.Index(
                        fields=["viatura", "-data_transferencia"],
                        name="militares_t_viatura_3e3cbc_idx",
                    )
                ],
            },
        ),
    ]
