# Generated by Django 5.0.2 on 2025-11-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0306_transferenciaviatura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viatura",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ABT", "Auto Bomba Tanque"),
                    ("ABCI", "Auto Bomba de Combate a Incêndio"),
                    ("ESC", "Auto Escada"),
                    ("APT", "Auto Plataforma"),
                    ("ASE", "Auto Socorro de Emergência"),
                    ("ASB", "Ambulância de Suporte Básico"),
                    ("ASA", "Ambulância de Suporte Avançado"),
                    ("VTL", "Viatura Tática Leve"),
                    ("VTM", "Viatura Tática Média"),
                    ("VTP", "Viatura Tática Pesada"),
                    ("RES", "Viatura de Resgate"),
                    ("SAL", "Viatura de Salvamento"),
                    ("HAZ", "Viatura Hazmat - Material Perigoso"),
                    ("CLIF", "Caminhão de Luta contra Incêndio Florestal"),
                    ("CIF", "Viatura de Combate a Incêndio Florestal"),
                    ("CMD", "Viatura de Comando"),
                    ("COM", "Viatura de Comunicações"),
                    ("OPE", "Viatura de Operações Especiais"),
                    ("BAR", "Barco/Bote"),
                    ("MOT", "Moto"),
                    ("MAN", "Viatura de Manutenção"),
                    ("ADMIN", "Viatura Administrativa"),
                    ("OUT", "Outras"),
                ],
                max_length=10,
                verbose_name="Tipo de Viatura",
            ),
        ),
    ]
