# Generated by Django 5.0.2 on 2025-11-05 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0307_add_tipos_viaturas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_averbacoes",
            field=models.BooleanField(default=False, verbose_name="Averbações"),
        ),
        migrations.CreateModel(
            name="Averbacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tempo_contribuicao_dias",
                    models.PositiveIntegerField(
                        help_text="Quantidade de dias de tempo de contribuição",
                        verbose_name="Tempo de Contribuição (TC) em Dias",
                    ),
                ),
                (
                    "aproveitamento_dias",
                    models.PositiveIntegerField(
                        help_text="Quantidade de dias aproveitados (geralmente igual ao TC)",
                        verbose_name="Aproveitamento do Tempo em Dias",
                    ),
                ),
                (
                    "numero_ctc_inss",
                    models.CharField(
                        help_text="Ex: 0020469543",
                        max_length=50,
                        verbose_name="Número da CTC/INSS",
                    ),
                ),
                (
                    "assinado_por_nome",
                    models.CharField(
                        help_text="Nome completo da pessoa que assinou",
                        max_length=200,
                        verbose_name="Assinado por (Nome)",
                    ),
                ),
                (
                    "assinado_por_cargo",
                    models.CharField(
                        help_text="Cargo ou função da pessoa que assinou",
                        max_length=200,
                        verbose_name="Cargo/Função",
                    ),
                ),
                (
                    "orgao_local",
                    models.CharField(
                        help_text="Ex: TERESINA - AGÊNCIA DA PREVIDÊNCIA SOCIAL TERESINA - LESTE",
                        max_length=200,
                        verbose_name="Órgão Local",
                    ),
                ),
                (
                    "endereco_orgao",
                    models.TextField(
                        help_text="Endereço completo do órgão",
                        verbose_name="Endereço do Órgão",
                    ),
                ),
                (
                    "cep_orgao",
                    models.CharField(
                        blank=True,
                        help_text="CEP do órgão",
                        max_length=10,
                        null=True,
                        verbose_name="CEP",
                    ),
                ),
                (
                    "cidade_estado_orgao",
                    models.CharField(
                        help_text="Ex: TERESINA - PI",
                        max_length=200,
                        verbose_name="Cidade/Estado",
                    ),
                ),
                ("data_averbacao", models.DateField(verbose_name="Data da Averbação")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="averbacoes_cadastradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado por",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="averbacoes",
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Averbação",
                "verbose_name_plural": "Averbações",
                "ordering": ["-data_averbacao", "-data_cadastro"],
                "indexes": [
                    models.Index(
                        fields=["militar", "-data_averbacao"],
                        name="militares_a_militar_590ed6_idx",
                    ),
                    models.Index(
                        fields=["-data_averbacao"],
                        name="militares_a_data_av_178d71_idx",
                    ),
                ],
            },
        ),
    ]
