# Generated by Django 5.0.2 on 2025-11-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0308_criar_modulo_averbacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="averbacao",
            name="documento_publicacao",
            field=models.CharField(
                blank=True,
                help_text="Ex: Portaria Nº 123/2024, Boletim Especial Nº 456/2024, etc.",
                max_length=200,
                null=True,
                verbose_name="Documento que Publicou a Averbação",
            ),
        ),
    ]
