# Generated by Django 5.0.2 on 2025-11-05 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0309_adicionar_documento_publicacao_averbacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoAlteracaoAverbacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_alteracao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Alteração"
                    ),
                ),
                (
                    "campo_alterado",
                    models.CharField(max_length=100, verbose_name="Campo Alterado"),
                ),
                (
                    "valor_anterior",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valor Anterior"
                    ),
                ),
                (
                    "valor_novo",
                    models.TextField(blank=True, null=True, verbose_name="Valor Novo"),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alteracoes_averbacoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alterado por",
                    ),
                ),
                (
                    "averbacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_alteracoes",
                        to="militares.averbacao",
                        verbose_name="Averbação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Alteração de Averbação",
                "verbose_name_plural": "Históricos de Alterações de Averbações",
                "ordering": ["-data_alteracao"],
                "indexes": [
                    models.Index(
                        fields=["averbacao", "-data_alteracao"],
                        name="militares_h_averbac_3fda73_idx",
                    )
                ],
            },
        ),
    ]
