# Generated by Django 5.0.2 on 2025-11-05 18:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0310_historicoalteracaoaverbacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Arma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        help_text="Número de série da arma",
                        max_length=100,
                        unique=True,
                        verbose_name="Número de Série",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PISTOLA", "Pistola"),
                            ("REVOLVER", "Revólver"),
                            ("FUZIL", "Fuzil"),
                            ("CARABINA", "Carabina"),
                            ("ESPINGARDA", "Espingarda"),
                            ("METRALHADORA", "Metralhadora"),
                            ("SUBMETRALHADORA", "Submetralhadora"),
                            ("FACA", "Faca"),
                            ("BAIONETA", "Baioneta"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Arma",
                    ),
                ),
                (
                    "marca",
                    models.CharField(
                        help_text="Ex: Taurus, Glock, IMBEL",
                        max_length=100,
                        verbose_name="Marca",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        help_text="Ex: PT 100, G17, FAL",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "calibre",
                    models.CharField(
                        choices=[
                            ("380", ".380"),
                            ("9MM", "9mm"),
                            ("40", ".40"),
                            ("45", ".45"),
                            ("556", "5.56mm"),
                            ("762", "7.62mm"),
                            ("12", "12 Gauge"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Calibre",
                    ),
                ),
                (
                    "numero_canhao",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número do Canhão",
                    ),
                ),
                (
                    "capacidade_carregador",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantidade de munições",
                        null=True,
                        verbose_name="Capacidade do Carregador",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("EM_USO", "Em Uso"),
                            ("MANUTENCAO", "Em Manutenção"),
                            ("BAIXA", "Dada de Baixa"),
                            ("EXTRAVIADO", "Extraviado"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_entrega_responsavel",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Entrega ao Responsável",
                    ),
                ),
                (
                    "numero_registro_policia",
                    models.CharField(
                        blank=True,
                        help_text="Registro da arma na Polícia Federal",
                        max_length=100,
                        null=True,
                        verbose_name="Nº Registro na Polícia Federal",
                    ),
                ),
                (
                    "numero_guia_transito",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nº Guia de Trânsito",
                    ),
                ),
                (
                    "data_aquisicao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Aquisição"
                    ),
                ),
                (
                    "fornecedor",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Fornecedor"
                    ),
                ),
                (
                    "valor_aquisicao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Valor de Aquisição (R$)",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="armas_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "grande_comando",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.grandecomando",
                        verbose_name="Grande Comando",
                    ),
                ),
                (
                    "militar_responsavel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Militar que está com a arma no momento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="armas_responsavel",
                        to="militares.militar",
                        verbose_name="Militar Responsável",
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.orgao",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "sub_unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.subunidade",
                        verbose_name="Sub-Unidade",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.unidade",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arma",
                "verbose_name_plural": "Armas",
                "ordering": ["numero_serie"],
            },
        ),
        migrations.CreateModel(
            name="ArmaParticular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        help_text="Número de série da arma",
                        max_length=100,
                        verbose_name="Número de Série",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PISTOLA", "Pistola"),
                            ("REVOLVER", "Revólver"),
                            ("FUZIL", "Fuzil"),
                            ("CARABINA", "Carabina"),
                            ("ESPINGARDA", "Espingarda"),
                            ("FACA", "Faca"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Arma",
                    ),
                ),
                (
                    "marca",
                    models.CharField(
                        help_text="Ex: Taurus, Glock, IMBEL",
                        max_length=100,
                        verbose_name="Marca",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        help_text="Ex: PT 100, G17, FAL",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "calibre",
                    models.CharField(
                        choices=[
                            ("380", ".380"),
                            ("9MM", "9mm"),
                            ("40", ".40"),
                            ("45", ".45"),
                            ("556", "5.56mm"),
                            ("762", "7.62mm"),
                            ("12", "12 Gauge"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Calibre",
                    ),
                ),
                (
                    "numero_canhao",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número do Canhão",
                    ),
                ),
                (
                    "capacidade_carregador",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantidade de munições",
                        null=True,
                        verbose_name="Capacidade do Carregador",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("PENDENTE", "Pendente de Documentação"),
                            ("VENCIDO", "Documentação Vencida"),
                            ("IRREGULAR", "Irregular"),
                        ],
                        default="REGULAR",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "numero_registro_policia",
                    models.CharField(
                        help_text="Registro da arma na Polícia Federal",
                        max_length=100,
                        verbose_name="Nº Registro na Polícia Federal",
                    ),
                ),
                (
                    "data_validade_registro",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Validade do Registro",
                    ),
                ),
                (
                    "numero_guia_transito",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nº Guia de Trânsito",
                    ),
                ),
                (
                    "data_validade_guia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Validade da Guia"
                    ),
                ),
                (
                    "autorizado_uso_servico",
                    models.BooleanField(
                        default=False,
                        help_text="Se a arma está autorizada para uso durante o serviço",
                        verbose_name="Autorizado para Uso no Serviço",
                    ),
                ),
                (
                    "data_autorizacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Autorização"
                    ),
                ),
                (
                    "data_vencimento_autorizacao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Vencimento da Autorização",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "autorizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="armas_autorizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autorizado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="armas_particulares_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="armas_particulares",
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arma Particular",
                "verbose_name_plural": "Armas Particulares",
                "ordering": ["militar", "numero_serie"],
            },
        ),
        migrations.CreateModel(
            name="MovimentacaoArma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimentacao",
                    models.CharField(
                        choices=[
                            ("ENTREGA", "Entrega"),
                            ("DEVOLUCAO", "Devolução"),
                            ("TRANSFERENCIA", "Transferência"),
                            ("MANUTENCAO", "Envio para Manutenção"),
                            ("RETORNO_MANUTENCAO", "Retorno de Manutenção"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Movimentação",
                    ),
                ),
                (
                    "data_movimentacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data e Hora da Movimentação",
                    ),
                ),
                (
                    "organizacao_origem",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Organização de Origem",
                    ),
                ),
                (
                    "organizacao_destino",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Organização de Destino",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "arma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes",
                        to="militares.arma",
                        verbose_name="Arma",
                    ),
                ),
                (
                    "militar_destino",
                    models.ForeignKey(
                        blank=True,
                        help_text="Militar que recebe a arma",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacoes_arma_destino",
                        to="militares.militar",
                        verbose_name="Militar de Destino",
                    ),
                ),
                (
                    "militar_origem",
                    models.ForeignKey(
                        blank=True,
                        help_text="Militar que estava com a arma (para entregas/devoluções)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacoes_arma_origem",
                        to="militares.militar",
                        verbose_name="Militar de Origem",
                    ),
                ),
                (
                    "responsavel_movimentacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacoes_arma_responsaveis",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável pela Movimentação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Arma",
                "verbose_name_plural": "Movimentações de Armas",
                "ordering": ["-data_movimentacao"],
            },
        ),
        migrations.AddIndex(
            model_name="arma",
            index=models.Index(
                fields=["numero_serie"], name="militares_a_numero__b70b9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arma",
            index=models.Index(fields=["status"], name="militares_a_status_d0e2ee_idx"),
        ),
        migrations.AddIndex(
            model_name="arma",
            index=models.Index(fields=["tipo"], name="militares_a_tipo_ccbff7_idx"),
        ),
        migrations.AddIndex(
            model_name="arma",
            index=models.Index(
                fields=["militar_responsavel"], name="militares_a_militar_5afbfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="armaparticular",
            index=models.Index(
                fields=["militar", "numero_serie"],
                name="militares_a_militar_5a75d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="armaparticular",
            index=models.Index(fields=["status"], name="militares_a_status_d3affd_idx"),
        ),
        migrations.AddIndex(
            model_name="armaparticular",
            index=models.Index(
                fields=["autorizado_uso_servico"], name="militares_a_autoriz_79339b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="armaparticular",
            index=models.Index(
                fields=["data_validade_registro"], name="militares_a_data_va_578b03_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="armaparticular",
            unique_together={("militar", "numero_serie")},
        ),
        migrations.AddIndex(
            model_name="movimentacaoarma",
            index=models.Index(
                fields=["arma", "-data_movimentacao"],
                name="militares_m_arma_id_91e958_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="movimentacaoarma",
            index=models.Index(
                fields=["militar_destino", "-data_movimentacao"],
                name="militares_m_militar_604745_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="movimentacaoarma",
            index=models.Index(
                fields=["tipo_movimentacao"], name="militares_m_tipo_mo_50f65d_idx"
            ),
        ),
    ]
