# Generated by Django 5.0.2 on 2025-11-05 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0311_criar_material_belico"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="arma",
            name="militares_a_status_d0e2ee_idx",
        ),
        migrations.RemoveField(
            model_name="arma",
            name="status",
        ),
        migrations.AddField(
            model_name="arma",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("CAUTELA_INDIVIDUAL", "Cautela Individual"),
                    ("RESERVA_ARMAMENTO", "Reserva de Armamento"),
                    ("EXTRAVIADO", "Extraviado (Perda, Roubo, Furto)"),
                    ("ANEXADO_INQUERITO_PM", "Anexado a Inquérito PM"),
                    ("ANEXADO_INQUERITO_PC", "Anexado a Inquérito PC"),
                    ("EM_MANUTENCAO", "Em Manutenção"),
                ],
                default="CAUTELA_INDIVIDUAL",
                max_length=30,
                verbose_name="Situação",
            ),
        ),
        migrations.AddIndex(
            model_name="arma",
            index=models.Index(
                fields=["situacao"], name="militares_a_situaca_9166a4_idx"
            ),
        ),
    ]
