# Generated by Django 5.0.2 on 2025-11-05 18:56

import django.db.models.deletion
import militares.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0312_remove_arma_militares_a_status_d0e2ee_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoArma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        help_text="Imagem da arma",
                        upload_to=militares.models.arma_imagem_upload_path,
                        verbose_name="Imagem da Arma",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PISTOLA", "Pistola"),
                            ("REVOLVER", "Revólver"),
                            ("FUZIL", "Fuzil"),
                            ("CARABINA", "Carabina"),
                            ("ESPINGARDA", "Espingarda"),
                            ("METRALHADORA", "Metralhadora"),
                            ("SUBMETRALHADORA", "Submetralhadora"),
                            ("FACA", "Faca"),
                            ("BAIONETA", "Baioneta"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Arma",
                    ),
                ),
                (
                    "calibre",
                    models.CharField(
                        choices=[
                            ("380", ".380"),
                            ("9MM", "9mm"),
                            ("40", ".40"),
                            ("45", ".45"),
                            ("556", "5.56mm"),
                            ("762", "7.62mm"),
                            ("12", "12 Gauge"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Calibre",
                    ),
                ),
                (
                    "marca",
                    models.CharField(
                        help_text="Ex: Taurus, Glock, IMBEL",
                        max_length=100,
                        verbose_name="Marca",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        help_text="Ex: PT 100 AF, PT 100 PLUS, 24/7 PRO",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuracoes_arma_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Arma",
                "verbose_name_plural": "Configurações de Armas",
                "ordering": ["marca", "modelo"],
                "indexes": [
                    models.Index(
                        fields=["tipo", "calibre"], name="militares_c_tipo_4d4788_idx"
                    ),
                    models.Index(
                        fields=["marca", "modelo"], name="militares_c_marca_27dd50_idx"
                    ),
                    models.Index(fields=["ativo"], name="militares_c_ativo_93d816_idx"),
                ],
                "unique_together": {("tipo", "calibre", "marca", "modelo")},
            },
        ),
    ]
