# Generated by Django 5.0.2 on 2025-11-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0313_configuracaoarma"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arma",
            name="numero_canhao",
        ),
        migrations.AddField(
            model_name="arma",
            name="alma_raiada",
            field=models.BooleanField(
                default=False,
                help_text="Se a arma possui alma raiada",
                verbose_name="Alma Raiada",
            ),
        ),
        migrations.AddField(
            model_name="arma",
            name="direcao_raias",
            field=models.CharField(
                blank=True,
                choices=[("DIREITA", "Direita"), ("ESQUERDA", "Esquerda")],
                help_text="Direção das raias (apenas se alma raiada)",
                max_length=10,
                null=True,
                verbose_name="Direção das Raias",
            ),
        ),
        migrations.AddField(
            model_name="arma",
            name="quantidade_raias",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Número de raias (apenas se alma raiada)",
                null=True,
                verbose_name="Quantidade de Raias",
            ),
        ),
    ]
