# Generated by Django 5.0.2 on 2025-11-05 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0316_historicoalteracaoarma"),
    ]

    operations = [
        migrations.AddField(
            model_name="arma",
            name="delegado_inquerito_pc",
            field=models.CharField(
                blank=True,
                help_text="Nome do delegado responsável (apenas para Anexado a Inquérito PC)",
                max_length=200,
                null=True,
                verbose_name="Delegado Responsável",
            ),
        ),
        migrations.AddField(
            model_name="arma",
            name="encarregado_inquerito_pm",
            field=models.ForeignKey(
                blank=True,
                help_text="Oficial encarregado do inquérito (apenas para Anexado a Inquérito PM)",
                limit_choices_to={
                    "posto_graduacao__in": ["CB", "TC", "MJ", "CP", "1T", "2T"]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="armas_inquerito_pm",
                to="militares.militar",
                verbose_name="Encarregado do Inquérito PM",
            ),
        ),
        migrations.AddField(
            model_name="arma",
            name="numero_inquerito_pc",
            field=models.CharField(
                blank=True,
                help_text="Número do inquérito (apenas para Anexado a Inquérito PC)",
                max_length=100,
                null=True,
                verbose_name="Nº Inquérito PC",
            ),
        ),
        migrations.AddField(
            model_name="arma",
            name="numero_inquerito_pm",
            field=models.CharField(
                blank=True,
                help_text="Número do inquérito (apenas para Anexado a Inquérito PM)",
                max_length=100,
                null=True,
                verbose_name="Nº Inquérito PM",
            ),
        ),
        migrations.AlterField(
            model_name="arma",
            name="militar_responsavel",
            field=models.ForeignKey(
                blank=True,
                help_text="Militar que está com a arma no momento (apenas para Cautela Individual)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="armas_responsavel",
                to="militares.militar",
                verbose_name="Militar Responsável",
            ),
        ),
    ]
