# Generated by Django 5.0.2 on 2025-11-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0317_arma_delegado_inquerito_pc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaoarma",
            name="assinatura_entregando",
            field=models.ImageField(
                blank=True,
                help_text="Assinatura do responsável que está entregando a arma",
                null=True,
                upload_to="assinaturas_movimentacoes/",
                verbose_name="Assinatura de Quem Está Entregando",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="assinatura_recebendo",
            field=models.ImageField(
                blank=True,
                help_text="Assinatura do responsável que está recebendo a arma",
                null=True,
                upload_to="assinaturas_movimentacoes/",
                verbose_name="Assinatura de Quem Está Recebendo",
            ),
        ),
    ]
