# Generated by Django 5.0.2 on 2025-11-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0318_adicionar_assinaturas_movimentacao_arma"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaoarma",
            name="quantidade_carregadores",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quantidade de carregadores que acompanham a arma",
                null=True,
                verbose_name="Quantidade de Carregadores",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="quantidade_municoes_catalogadas",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quantidade de munições catalogadas que acompanham a arma",
                null=True,
                verbose_name="Quantidade de Munições Catalogadas",
            ),
        ),
    ]
