# Generated by Django 5.0.2 on 2025-11-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0319_adicionar_carregadores_municoes_movimentacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaoarma",
            name="numeracao_carregadores",
            field=models.TextField(
                blank=True,
                help_text="Digite a numeração de cada carregador, separada por vírgula ou quebra de linha. Ex: 001, 002, 003 ou 001\n002\n003",
                null=True,
                verbose_name="Numeração dos Carregadores",
            ),
        ),
    ]
