# Generated by Django 5.0.2 on 2025-11-05 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0320_adicionar_numeracao_carregadores_movimentacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaoarma",
            name="data_assinatura_entregando",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Data da Assinatura de Quem Está Entregando",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="data_assinatura_recebendo",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Data da Assinatura de Quem Está Recebendo",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="funcao_assinatura_entregando",
            field=models.CharField(
                blank=True,
                help_text="Função do militar que está entregando a arma",
                max_length=200,
                null=True,
                verbose_name="Função de Quem Está Entregando",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="funcao_assinatura_recebendo",
            field=models.CharField(
                blank=True,
                help_text="Função do militar que está recebendo a arma",
                max_length=200,
                null=True,
                verbose_name="Função de Quem Está Recebendo",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="militar_entregando",
            field=models.ForeignKey(
                blank=True,
                help_text="Militar responsável por entregar a arma",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentacoes_arma_entregando",
                to="militares.militar",
                verbose_name="Militar que Está Entregando",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="militar_recebendo",
            field=models.ForeignKey(
                blank=True,
                help_text="Militar responsável por receber a arma",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentacoes_arma_recebendo",
                to="militares.militar",
                verbose_name="Militar que Está Recebendo",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoarma",
            name="assinatura_entregando",
            field=models.ImageField(
                blank=True,
                help_text="Assinatura física (imagem) do responsável que está entregando a arma (opcional)",
                null=True,
                upload_to="assinaturas_movimentacoes/",
                verbose_name="Assinatura Física de Quem Está Entregando",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoarma",
            name="assinatura_recebendo",
            field=models.ImageField(
                blank=True,
                help_text="Assinatura física (imagem) do responsável que está recebendo a arma (opcional)",
                null=True,
                upload_to="assinaturas_movimentacoes/",
                verbose_name="Assinatura Física de Quem Está Recebendo",
            ),
        ),
    ]
