# Generated by Django 5.0.2 on 2025-11-05 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0321_adicionar_assinaturas_eletronicas_movimentacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movimentacaoarma",
            name="assinatura_entregando",
        ),
        migrations.RemoveField(
            model_name="movimentacaoarma",
            name="assinatura_recebendo",
        ),
        migrations.RemoveField(
            model_name="movimentacaoarma",
            name="data_assinatura_entregando",
        ),
        migrations.RemoveField(
            model_name="movimentacaoarma",
            name="data_assinatura_recebendo",
        ),
        migrations.RemoveField(
            model_name="movimentacaoarma",
            name="funcao_assinatura_entregando",
        ),
        migrations.RemoveField(
            model_name="movimentacaoarma",
            name="funcao_assinatura_recebendo",
        ),
        migrations.RemoveField(
            model_name="movimentacaoarma",
            name="militar_entregando",
        ),
        migrations.RemoveField(
            model_name="movimentacaoarma",
            name="militar_recebendo",
        ),
        migrations.CreateModel(
            name="AssinaturaMovimentacaoArma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_assinatura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Assinatura"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações da Assinatura"
                    ),
                ),
                (
                    "tipo_assinatura",
                    models.CharField(
                        choices=[
                            ("ENTREGANDO", "Entregando"),
                            ("RECEBENDO", "Recebendo"),
                            ("APROVACAO", "Aprovação"),
                            ("REVISAO", "Revisão"),
                            ("OUTROS", "Outros"),
                        ],
                        default="ENTREGANDO",
                        max_length=20,
                        verbose_name="Tipo de Assinatura",
                    ),
                ),
                (
                    "funcao_assinatura",
                    models.CharField(
                        blank=True,
                        help_text="Função/cargo do usuário no momento da assinatura",
                        max_length=200,
                        null=True,
                        verbose_name="Função no momento da assinatura",
                    ),
                ),
                (
                    "assinado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assinado por",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Militar associado à assinatura (se houver)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
                (
                    "movimentacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to="militares.movimentacaoarma",
                        verbose_name="Movimentação de Arma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura de Movimentação de Arma",
                "verbose_name_plural": "Assinaturas de Movimentações de Armas",
                "ordering": ["-data_assinatura"],
            },
        ),
    ]
