# Generated by Django 5.0.2 on 2025-11-05 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0322_criar_modelo_assinatura_movimentacao_arma"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CautelaArma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_carregadores",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantidade de carregadores que acompanham a arma",
                        null=True,
                        verbose_name="Quantidade de Carregadores",
                    ),
                ),
                (
                    "numeracao_carregadores",
                    models.TextField(
                        blank=True,
                        help_text="Digite a numeração de cada carregador, separada por vírgula ou quebra de linha.",
                        null=True,
                        verbose_name="Numeração dos Carregadores",
                    ),
                ),
                (
                    "quantidade_municoes_catalogadas",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantidade de munições catalogadas que acompanham a arma",
                        null=True,
                        verbose_name="Quantidade de Munições Catalogadas",
                    ),
                ),
                (
                    "data_entrega",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Entrega"
                    ),
                ),
                (
                    "data_devolucao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Devolução"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "ativa",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se a cautela está ativa (arma ainda com o militar)",
                        verbose_name="Cautela Ativa",
                    ),
                ),
                (
                    "arma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cautelas",
                        to="militares.arma",
                        verbose_name="Arma",
                    ),
                ),
                (
                    "devolvido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_devolvidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Devolvido por",
                    ),
                ),
                (
                    "entregue_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_entregues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entregue por",
                    ),
                ),
                (
                    "grande_comando",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_armas",
                        to="militares.grandecomando",
                        verbose_name="Grande Comando",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_armas",
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_armas",
                        to="militares.orgao",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "sub_unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_armas",
                        to="militares.subunidade",
                        verbose_name="Sub-Unidade",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_armas",
                        to="militares.unidade",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cautela de Arma",
                "verbose_name_plural": "Cautelas de Armas",
                "ordering": ["-data_entrega"],
                "indexes": [
                    models.Index(
                        fields=["arma", "-data_entrega"],
                        name="militares_c_arma_id_251339_idx",
                    ),
                    models.Index(
                        fields=["militar", "-data_entrega"],
                        name="militares_c_militar_06b933_idx",
                    ),
                    models.Index(
                        fields=["ativa", "-data_entrega"],
                        name="militares_c_ativa_5cc29e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TransferenciaArma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_carregadores",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantidade de carregadores que acompanham a arma",
                        null=True,
                        verbose_name="Quantidade de Carregadores",
                    ),
                ),
                (
                    "numeracao_carregadores",
                    models.TextField(
                        blank=True,
                        help_text="Digite a numeração de cada carregador, separada por vírgula ou quebra de linha.",
                        null=True,
                        verbose_name="Numeração dos Carregadores",
                    ),
                ),
                (
                    "quantidade_municoes_catalogadas",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantidade de munições catalogadas que acompanham a arma",
                        null=True,
                        verbose_name="Quantidade de Munições Catalogadas",
                    ),
                ),
                (
                    "data_transferencia",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Transferência"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "arma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transferencias",
                        to="militares.arma",
                        verbose_name="Arma",
                    ),
                ),
                (
                    "grande_comando_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_arma_destino",
                        to="militares.grandecomando",
                        verbose_name="Grande Comando de Destino",
                    ),
                ),
                (
                    "grande_comando_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_arma_origem",
                        to="militares.grandecomando",
                        verbose_name="Grande Comando de Origem",
                    ),
                ),
                (
                    "orgao_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_arma_destino",
                        to="militares.orgao",
                        verbose_name="Órgão de Destino",
                    ),
                ),
                (
                    "orgao_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_arma_origem",
                        to="militares.orgao",
                        verbose_name="Órgão de Origem",
                    ),
                ),
                (
                    "sub_unidade_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_arma_destino",
                        to="militares.subunidade",
                        verbose_name="Sub-Unidade de Destino",
                    ),
                ),
                (
                    "sub_unidade_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_arma_origem",
                        to="militares.subunidade",
                        verbose_name="Sub-Unidade de Origem",
                    ),
                ),
                (
                    "transferido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_arma_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Transferido por",
                    ),
                ),
                (
                    "unidade_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_arma_destino",
                        to="militares.unidade",
                        verbose_name="Unidade de Destino",
                    ),
                ),
                (
                    "unidade_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_arma_origem",
                        to="militares.unidade",
                        verbose_name="Unidade de Origem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferência de Arma",
                "verbose_name_plural": "Transferências de Armas",
                "ordering": ["-data_transferencia"],
                "indexes": [
                    models.Index(
                        fields=["arma", "-data_transferencia"],
                        name="militares_t_arma_id_2b1fb9_idx",
                    )
                ],
            },
        ),
    ]
