# Generated by Django 5.0.2 on 2025-11-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0323_add_transferencia_cautela_arma"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="configuracaoarma",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="configuracaoarma",
            name="tipo_acessorio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CARREGADOR", "Carregador"),
                    ("MIRA_TELESCOPICA", "Mira Telescópica"),
                    ("MIRA_REFLEXO", "Mira Reflexo"),
                    ("MIRA_LASER", "Mira Laser"),
                    ("MIRA_FIBRA", "Mira de Fibra Óptica"),
                    ("MIRA_NOTURNA", "Mira Noturna"),
                    ("CORONHA", "Coronha"),
                    ("CORONHA_TATICA", "Coronha Tática"),
                    ("EMPUNHADURA", "Empunhadura"),
                    ("EMPUNHADURA_TATICA", "Empunhadura Tática"),
                    ("GUARDA_MAO", "Guarda-mão"),
                    ("GUARDA_MAO_TATICA", "Guarda-mão Tática"),
                    ("SUPORTE_LANTERNA", "Suporte para Lanterna"),
                    ("SUPORTE_LASER", "Suporte para Laser"),
                    ("SUPORTE_MIRA", "Suporte para Mira"),
                    ("CORREIA", "Correia"),
                    ("CORREIA_TATICA", "Correia Tática"),
                    ("BOLSA_CARREGADOR", "Bolsa para Carregadores"),
                    ("COLDRE", "Coldre"),
                    ("COLDRE_TATICO", "Coldre Tático"),
                    ("SILENCIADOR", "Silenciador"),
                    ("COMPENSADOR", "Compensador"),
                    ("EXTENSOR_CARREGADOR", "Extensor de Carregador"),
                    ("BASE_ACESSORIO", "Base para Acessórios"),
                    ("RING_MOUNT", "Ring Mount"),
                    ("WEAVER_MOUNT", "Weaver Mount"),
                    ("PICATINNY_MOUNT", "Picatinny Mount"),
                    ("ADAPTADOR", "Adaptador"),
                    ("LIMPEZA", "Kit de Limpeza"),
                    ("MUNICAO", "Munição"),
                    ("MUNICAO_ESPECIAL", "Munição Especial"),
                    ("PROTECAO_OUVIDO", "Proteção Auditiva"),
                    ("PROTECAO_OLHO", "Proteção Ocular"),
                    ("OUTROS", "Outros"),
                ],
                help_text="Selecione o tipo de acessório (apenas quando Tipo de Arma for Acessório)",
                max_length=30,
                null=True,
                verbose_name="Tipo de Acessório",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaoarma",
            name="calibre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("380", ".380"),
                    ("9MM", "9mm"),
                    ("40", ".40"),
                    ("45", ".45"),
                    ("556", "5.56mm"),
                    ("762", "7.62mm"),
                    ("12", "12 Gauge"),
                    ("OUTROS", "Outros"),
                ],
                help_text="Calibre (não obrigatório para acessórios)",
                max_length=20,
                null=True,
                verbose_name="Calibre",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaoarma",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PISTOLA", "Pistola"),
                    ("REVOLVER", "Revólver"),
                    ("FUZIL", "Fuzil"),
                    ("CARABINA", "Carabina"),
                    ("ESPINGARDA", "Espingarda"),
                    ("METRALHADORA", "Metralhadora"),
                    ("SUBMETRALHADORA", "Submetralhadora"),
                    ("FACA", "Faca"),
                    ("BAIONETA", "Baioneta"),
                    ("ACESSORIO", "Acessório"),
                    ("OUTROS", "Outros"),
                ],
                max_length=20,
                verbose_name="Tipo de Arma",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="configuracaoarma",
            unique_together={("tipo", "calibre", "marca", "modelo", "tipo_acessorio")},
        ),
    ]
