# Generated by Django 5.0.2 on 2025-11-06 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0324_adicionar_tipo_acessorio_configuracao_arma"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="configuracaoarma",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="configuracaoarma",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tipo", "ACESSORIO")),
                fields=("tipo", "calibre", "marca", "modelo", "tipo_acessorio"),
                name="unique_configuracao_acessorio",
            ),
        ),
        migrations.AddConstraint(
            model_name="configuracaoarma",
            constraint=models.UniqueConstraint(
                condition=~models.Q(("tipo", "ACESSORIO")),
                fields=("tipo", "calibre", "marca", "modelo"),
                name="unique_configuracao_arma",
            ),
        ),
    ]
