# Generated by Django 5.0.2 on 2025-11-06 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0325_ajustar_unique_constraint_configuracao_arma"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="configuracaoarma",
            name="unique_configuracao_arma",
        ),
        migrations.AddConstraint(
            model_name="configuracaoarma",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tipo", "ACESSORIO"), _negated=True),
                fields=("tipo", "calibre", "marca", "modelo"),
                name="unique_configuracao_arma",
            ),
        ),
    ]
