# Generated by Django 5.0.2 on 2025-11-06 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0326_corrigir_unique_constraint_configuracao_arma"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaoarma",
            name="cnpj_empresa_manutencao",
            field=models.CharField(
                blank=True,
                help_text="Formato: XX.XXX.XXX/XXXX-XX",
                max_length=18,
                null=True,
                verbose_name="CNPJ da Empresa",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="empresa_manutencao",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Empresa de Manutenção",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="endereco_empresa_manutencao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Endereço da Empresa"
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="grande_comando_manutencao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manutencoes_arma_gc",
                to="militares.grandecomando",
                verbose_name="Grande Comando de Manutenção",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="militar_recebeu_manutencao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manutencoes_arma_recebeu",
                to="militares.militar",
                verbose_name="Militar que Recebeu (Manutenção Interna)",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="orgao_manutencao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manutencoes_arma_orgao",
                to="militares.orgao",
                verbose_name="Órgão de Manutenção",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="responsavel_empresa_manutencao",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Responsável na Empresa",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="sub_unidade_manutencao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manutencoes_arma_sub",
                to="militares.subunidade",
                verbose_name="Sub-Unidade de Manutenção",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="tipo_manutencao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INTERNA", "Manutenção Interna"),
                    ("EXTERNA", "Manutenção Externa"),
                ],
                help_text="Tipo de manutenção (Interna ou Externa)",
                max_length=10,
                null=True,
                verbose_name="Tipo de Manutenção",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="unidade_manutencao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manutencoes_arma_unidade",
                to="militares.unidade",
                verbose_name="Unidade de Manutenção",
            ),
        ),
    ]
