# Generated by Django 5.0.2 on 2025-11-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0327_add_campos_manutencao_arma"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoarma",
            name="observacoes",
            field=models.TextField(
                blank=True,
                help_text="Campo livre para anotações e informações adicionais",
                null=True,
                verbose_name="Observações",
            ),
        ),
    ]
