# Generated by Django 5.0.2 on 2025-11-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0328_add_observacoes_configuracao_arma"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracaoarma",
            name="observacoes",
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="motivos_manutencao",
            field=models.TextField(
                blank=True,
                help_text="Descreva os motivos pelos quais a arma está sendo enviada para manutenção",
                null=True,
                verbose_name="Motivos da Manutenção",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoarma",
            name="reparos_realizados",
            field=models.TextField(
                blank=True,
                help_text="Descreva os reparos realizados na arma durante a manutenção",
                null=True,
                verbose_name="Reparos Realizados",
            ),
        ),
    ]
