# Generated by Django 5.0.2 on 2025-11-06 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0329_add_motivos_manutencao_reparos_realizados"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CautelaArmaColetiva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        help_text="Descrição da cautela coletiva (ex: Instrução de tiro, Operação X, etc)",
                        max_length=200,
                        verbose_name="Descrição/Finalidade",
                    ),
                ),
                (
                    "tipo_finalidade",
                    models.CharField(
                        choices=[
                            ("ENSINO", "Ensino"),
                            ("INSTRUCAO", "Instrução"),
                            ("OPERACAO", "Operação"),
                            ("TREINAMENTO", "Treinamento"),
                            ("OUTROS", "Outros"),
                        ],
                        default="INSTRUCAO",
                        max_length=20,
                        verbose_name="Tipo de Finalidade",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data de Início"
                    ),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Fim"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "ativa",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se a cautela está ativa",
                        verbose_name="Cautela Ativa",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_coletivas_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "finalizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_coletivas_finalizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Finalizado por",
                    ),
                ),
                (
                    "grande_comando",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_coletivas_armas",
                        to="militares.grandecomando",
                        verbose_name="Grande Comando",
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_coletivas_armas",
                        to="militares.orgao",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Militar responsável pela cautela coletiva",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_coletivas_responsavel",
                        to="militares.militar",
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "sub_unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_coletivas_armas",
                        to="militares.subunidade",
                        verbose_name="Sub-Unidade",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_coletivas_armas",
                        to="militares.unidade",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cautela Coletiva de Armas",
                "verbose_name_plural": "Cautelas Coletivas de Armas",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="CautelaArmaColetivaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_carregadores",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantidade de carregadores que acompanham a arma",
                        null=True,
                        verbose_name="Quantidade de Carregadores",
                    ),
                ),
                (
                    "numeracao_carregadores",
                    models.TextField(
                        blank=True,
                        help_text="Digite a numeração de cada carregador, separada por vírgula ou quebra de linha.",
                        null=True,
                        verbose_name="Numeração dos Carregadores",
                    ),
                ),
                (
                    "quantidade_municoes_catalogadas",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantidade de munições catalogadas que acompanham a arma",
                        null=True,
                        verbose_name="Quantidade de Munições Catalogadas",
                    ),
                ),
                (
                    "data_entrega",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data da Entrega",
                    ),
                ),
                (
                    "data_devolucao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Devolução"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "devolvida",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se a arma foi devolvida",
                        verbose_name="Arma Devolvida",
                    ),
                ),
                (
                    "arma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cautelas_coletivas",
                        to="militares.arma",
                        verbose_name="Arma",
                    ),
                ),
                (
                    "cautela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="armas",
                        to="militares.cautelaarmacoletiva",
                        verbose_name="Cautela Coletiva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Cautela Coletiva",
                "verbose_name_plural": "Itens de Cautela Coletiva",
                "ordering": ["-data_entrega"],
            },
        ),
        migrations.AddIndex(
            model_name="cautelaarmacoletiva",
            index=models.Index(
                fields=["responsavel", "-data_inicio"],
                name="militares_c_respons_c0e0aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cautelaarmacoletiva",
            index=models.Index(
                fields=["ativa", "-data_inicio"], name="militares_c_ativa_c0bd2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cautelaarmacoletiva",
            index=models.Index(
                fields=["tipo_finalidade", "-data_inicio"],
                name="militares_c_tipo_fi_2f563f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cautelaarmacoletivaitem",
            index=models.Index(
                fields=["cautela", "-data_entrega"],
                name="militares_c_cautela_ad3686_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cautelaarmacoletivaitem",
            index=models.Index(
                fields=["arma", "-data_entrega"], name="militares_c_arma_id_d87dea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cautelaarmacoletivaitem",
            index=models.Index(
                fields=["devolvida", "-data_entrega"],
                name="militares_c_devolvi_3d3c50_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cautelaarmacoletivaitem",
            unique_together={("cautela", "arma")},
        ),
    ]
