# Generated by Django 5.0.2 on 2025-11-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0330_add_cautela_arma_coletiva"),
    ]

    operations = [
        migrations.AddField(
            model_name="cautelaarmacoletiva",
            name="documento_referencia",
            field=models.CharField(
                blank=True,
                help_text="Número ou identificação do documento que autoriza a cautela coletiva (ex: Portaria, Ofício, etc)",
                max_length=200,
                null=True,
                verbose_name="Documento de Referência",
            ),
        ),
    ]
