# Generated by Django 5.0.2 on 2025-11-06 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0331_add_documento_referencia_cautela_coletiva"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssinaturaCautelaArma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_assinatura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Assinatura"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações da Assinatura"
                    ),
                ),
                (
                    "tipo_assinatura",
                    models.CharField(
                        choices=[
                            ("RECEBENDO", "Recebendo"),
                            ("ENTREGANDO", "Entregando"),
                            ("APROVACAO", "Aprovação"),
                            ("REVISAO", "Revisão"),
                            ("OUTROS", "Outros"),
                        ],
                        default="RECEBENDO",
                        max_length=20,
                        verbose_name="Tipo de Assinatura",
                    ),
                ),
                (
                    "funcao_assinatura",
                    models.CharField(
                        blank=True,
                        help_text="Função/cargo do usuário no momento da assinatura",
                        max_length=200,
                        null=True,
                        verbose_name="Função no momento da assinatura",
                    ),
                ),
                (
                    "assinado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assinado por",
                    ),
                ),
                (
                    "cautela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to="militares.cautelaarma",
                        verbose_name="Cautela de Arma",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Militar que assina a cautela",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura de Cautela de Arma",
                "verbose_name_plural": "Assinaturas de Cautelas de Armas",
                "ordering": ["-data_assinatura"],
                "unique_together": {("cautela", "militar", "tipo_assinatura")},
            },
        ),
    ]
