# Generated by Django 5.0.2 on 2025-11-07 01:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0333_add_assinatura_cautela_arma_coletiva"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Municao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calibre",
                    models.CharField(
                        choices=[
                            ("380", ".380"),
                            ("9MM", "9mm"),
                            ("40", ".40"),
                            ("45", ".45"),
                            ("556", "5.56mm"),
                            ("762", "7.62mm"),
                            ("12", "12 Gauge"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Calibre",
                    ),
                ),
                (
                    "quantidade_estoque",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantidade atual em estoque",
                        verbose_name="Quantidade em Estoque",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="municoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "grande_comando",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="municoes",
                        to="militares.grandecomando",
                        verbose_name="Grande Comando",
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="municoes",
                        to="militares.orgao",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "sub_unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="municoes",
                        to="militares.subunidade",
                        verbose_name="Sub-Unidade",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="municoes",
                        to="militares.unidade",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Munição",
                "verbose_name_plural": "Munições",
                "ordering": [
                    "calibre",
                    "orgao",
                    "grande_comando",
                    "unidade",
                    "sub_unidade",
                ],
            },
        ),
        migrations.CreateModel(
            name="EntradaMunicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "data_entrada",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data da Entrada",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entradas_municao",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "municao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entradas",
                        to="militares.municao",
                        verbose_name="Munição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de Munição",
                "verbose_name_plural": "Entradas de Munição",
                "ordering": ["-data_entrada"],
            },
        ),
        migrations.CreateModel(
            name="SaidaMunicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "tipo_saida",
                    models.CharField(
                        choices=[
                            ("CAUTELA_INDIVIDUAL", "Cautela Individual"),
                            ("CAUTELA_COLETIVA", "Cautela Coletiva"),
                            ("TREINAMENTO", "Treinamento"),
                            ("OPERACAO", "Operação"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Saída",
                    ),
                ),
                (
                    "data_saida",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data da Saída"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "quantidade_devolvida",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantidade já devolvida desta saída",
                        verbose_name="Quantidade Devolvida",
                    ),
                ),
                (
                    "totalmente_devolvida",
                    models.BooleanField(
                        default=False, verbose_name="Totalmente Devolvida"
                    ),
                ),
                (
                    "cautela_coletiva",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cautela coletiva relacionada (se aplicável)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saidas_municao",
                        to="militares.cautelaarmacoletiva",
                        verbose_name="Cautela Coletiva",
                    ),
                ),
                (
                    "cautela_individual",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cautela individual relacionada (se aplicável)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saidas_municao",
                        to="militares.cautelaarma",
                        verbose_name="Cautela Individual",
                    ),
                ),
                (
                    "municao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saidas",
                        to="militares.municao",
                        verbose_name="Munição",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saidas_municao",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saída de Munição",
                "verbose_name_plural": "Saídas de Munição",
                "ordering": ["-data_saida"],
            },
        ),
        migrations.CreateModel(
            name="DevolucaoMunicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_devolvida",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade Devolvida",
                    ),
                ),
                (
                    "data_devolucao",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data da Devolução",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devolucoes_municao",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "saida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devolucoes",
                        to="militares.saidamunicao",
                        verbose_name="Saída Relacionada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devolução de Munição",
                "verbose_name_plural": "Devoluções de Munição",
                "ordering": ["-data_devolucao"],
            },
        ),
        migrations.AddIndex(
            model_name="municao",
            index=models.Index(
                fields=["calibre", "-quantidade_estoque"],
                name="militares_m_calibre_247a17_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="municao",
            index=models.Index(
                fields=["orgao", "grande_comando", "unidade", "sub_unidade"],
                name="militares_m_orgao_i_677f2b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="municao",
            unique_together={
                ("calibre", "orgao", "grande_comando", "unidade", "sub_unidade")
            },
        ),
        migrations.AddIndex(
            model_name="entradamunicao",
            index=models.Index(
                fields=["municao", "-data_entrada"],
                name="militares_e_municao_eb9d27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entradamunicao",
            index=models.Index(
                fields=["-data_entrada"], name="militares_e_data_en_3e5e70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saidamunicao",
            index=models.Index(
                fields=["municao", "-data_saida"], name="militares_s_municao_71aa60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saidamunicao",
            index=models.Index(
                fields=["tipo_saida", "-data_saida"],
                name="militares_s_tipo_sa_b2fdef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saidamunicao",
            index=models.Index(
                fields=["cautela_individual"], name="militares_s_cautela_a03dac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saidamunicao",
            index=models.Index(
                fields=["cautela_coletiva"], name="militares_s_cautela_05bf53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devolucaomunicao",
            index=models.Index(
                fields=["saida", "-data_devolucao"],
                name="militares_d_saida_i_4f02f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devolucaomunicao",
            index=models.Index(
                fields=["-data_devolucao"], name="militares_d_data_de_dac4a3_idx"
            ),
        ),
    ]
