# Generated by Django 5.0.2 on 2025-11-07 01:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0334_criar_controle_municao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="saidamunicao",
            name="cautela_coletiva",
            field=models.ForeignKey(
                blank=True,
                help_text="Cautela coletiva de arma relacionada (se aplicável)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saidas_municao",
                to="militares.cautelaarmacoletiva",
                verbose_name="Cautela Coletiva de Arma",
            ),
        ),
        migrations.AlterField(
            model_name="saidamunicao",
            name="cautela_individual",
            field=models.ForeignKey(
                blank=True,
                help_text="Cautela individual de arma relacionada (se aplicável)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saidas_municao",
                to="militares.cautelaarma",
                verbose_name="Cautela Individual de Arma",
            ),
        ),
        migrations.CreateModel(
            name="CautelaMunicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        help_text="Quantidade de munições em cautela",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "data_entrega",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Entrega"
                    ),
                ),
                (
                    "data_devolucao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Devolução"
                    ),
                ),
                (
                    "quantidade_devolvida",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantidade já devolvida desta cautela",
                        verbose_name="Quantidade Devolvida",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "ativa",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se a cautela está ativa (munição ainda com o militar)",
                        verbose_name="Cautela Ativa",
                    ),
                ),
                (
                    "devolvido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_municoes_devolvidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Devolvido por",
                    ),
                ),
                (
                    "entregue_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_municoes_entregues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entregue por",
                    ),
                ),
                (
                    "grande_comando",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_municoes",
                        to="militares.grandecomando",
                        verbose_name="Grande Comando",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_municoes",
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
                (
                    "municao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cautelas",
                        to="militares.municao",
                        verbose_name="Munição",
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_municoes",
                        to="militares.orgao",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "sub_unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_municoes",
                        to="militares.subunidade",
                        verbose_name="Sub-Unidade",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_municoes",
                        to="militares.unidade",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cautela de Munição",
                "verbose_name_plural": "Cautelas de Munições",
                "ordering": ["-data_entrega"],
            },
        ),
        migrations.AddField(
            model_name="saidamunicao",
            name="cautela_municao",
            field=models.ForeignKey(
                blank=True,
                help_text="Cautela de munição relacionada (se aplicável)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saidas_municao",
                to="militares.cautelamunicao",
                verbose_name="Cautela de Munição",
            ),
        ),
        migrations.AddIndex(
            model_name="cautelamunicao",
            index=models.Index(
                fields=["municao", "-data_entrega"],
                name="militares_c_municao_bf217d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cautelamunicao",
            index=models.Index(
                fields=["militar", "-data_entrega"],
                name="militares_c_militar_f20f16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cautelamunicao",
            index=models.Index(
                fields=["ativa", "-data_entrega"], name="militares_c_ativa_fa92ba_idx"
            ),
        ),
    ]
