# Generated by Django 5.0.2 on 2025-11-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0335_criar_cautela_municao"),
    ]

    operations = [
        migrations.AddField(
            model_name="arma",
            name="estado_conservacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOVA", "Nova"),
                    ("OTIMO", "Ótimo"),
                    ("BOM", "Bom"),
                    ("REGULAR", "Regular"),
                    ("RUIM", "Ruim"),
                    ("INSERVIVEL", "Inservível"),
                ],
                help_text="Estado de conservação atual da arma",
                max_length=20,
                null=True,
                verbose_name="Estado de Conservação",
            ),
        ),
    ]
