# Generated by Django 5.0.2 on 2025-11-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0336_adicionar_estado_conservacao_arma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arma",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("CAUTELA_INDIVIDUAL", "Cautela Individual"),
                    ("RESERVA_ARMAMENTO", "Reserva de Armamento"),
                    ("EXTRAVIADO", "Extraviado (Perda, Roubo, Furto)"),
                    ("ANEXADO_INQUERITO_PM", "Anexado a Inquérito PM"),
                    ("ANEXADO_INQUERITO_PC", "Anexado a Inquérito PC"),
                    ("EM_MANUTENCAO", "Em Manutenção"),
                    ("INSERVIVEL", "Inservível"),
                ],
                default="RESERVA_ARMAMENTO",
                max_length=30,
                verbose_name="Situação",
            ),
        ),
    ]
