# Generated by Django 5.0.2 on 2025-11-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0337_adicionar_situacao_inservivel"),
    ]

    operations = [
        migrations.AddField(
            model_name="arma",
            name="cod_tombamento",
            field=models.CharField(
                blank=True,
                help_text="Código do tombamento (ex: 163978)",
                max_length=50,
                null=True,
                verbose_name="COD",
            ),
        ),
        migrations.AddField(
            model_name="arma",
            name="local_tombamento",
            field=models.CharField(
                blank=True,
                help_text="Local do tombamento (ex: BM-4)",
                max_length=200,
                null=True,
                verbose_name="Local",
            ),
        ),
        migrations.AddField(
            model_name="arma",
            name="nome_tombamento",
            field=models.CharField(
                blank=True,
                help_text="Nome completo do tombamento (ex: PISTOLA BERETTA APX FULL SICE CAL. 9X19MM + MALETA + 4 CARREGADORES)",
                max_length=500,
                null=True,
                verbose_name="Nome do Tombamento",
            ),
        ),
        migrations.AddField(
            model_name="arma",
            name="numero_tombamento",
            field=models.CharField(
                blank=True,
                help_text="Número do tombamento (ex: 321-02-90)",
                max_length=50,
                null=True,
                verbose_name="Nº Tombamento",
            ),
        ),
    ]
