# Generated by Django 5.0.2 on 2025-11-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0338_adicionar_campos_tombamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_armas_instituicao",
            field=models.BooleanField(
                default=False, verbose_name="Armas da Instituição"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_armas_particulares",
            field=models.BooleanField(default=False, verbose_name="Armas Particulares"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_cautelas_armas",
            field=models.BooleanField(default=False, verbose_name="Cautelas de Armas"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_cautelas_municoes",
            field=models.BooleanField(
                default=False, verbose_name="Cautelas de Munição"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_controle_combustivel",
            field=models.BooleanField(
                default=False, verbose_name="Controle de Combustível"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_controle_movimentacoes",
            field=models.BooleanField(
                default=False, verbose_name="Controle de Movimentações"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_controle_municao",
            field=models.BooleanField(
                default=False, verbose_name="Controle de Munição"
            ),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_licenciamentos",
            field=models.BooleanField(default=False, verbose_name="Licenciamentos"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_manutencoes",
            field=models.BooleanField(default=False, verbose_name="Manutenções"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_material_belico",
            field=models.BooleanField(default=False, verbose_name="Material Bélico"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_painel_guarda",
            field=models.BooleanField(default=False, verbose_name="Painel de Guarda"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_rodagens",
            field=models.BooleanField(default=False, verbose_name="Rodagens"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_trocas_oleo",
            field=models.BooleanField(default=False, verbose_name="Trocas de Óleo"),
        ),
        migrations.AddField(
            model_name="funcaomenuconfig",
            name="show_viaturas",
            field=models.BooleanField(default=False, verbose_name="Frota"),
        ),
    ]
