# Generated by Django 5.2.3 on 2025-11-09 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0339_adicionar_campos_frota_material_belico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BemMovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tombamento', models.CharField(help_text='Número único de tombamento do bem', max_length=50, unique=True, verbose_name='Número de Tombamento')),
                ('descricao', models.CharField(help_text='Descrição detalhada do bem móvel', max_length=500, verbose_name='Descrição do Bem')),
                ('categoria', models.CharField(choices=[('MOBILIARIO', 'Mobiliário'), ('EQUIPAMENTO_INFORMATICA', 'Equipamento de Informática'), ('EQUIPAMENTO_AUDIO_VIDEO', 'Equipamento de Áudio e Vídeo'), ('MAQUINAS_EQUIPAMENTOS', 'Máquinas e Equipamentos'), ('VEICULOS', 'Veículos'), ('FERAMENTAS', 'Ferramentas'), ('APARELHOS_ELETRODOMESTICOS', 'Aparelhos Eletrodomésticos'), ('EQUIPAMENTO_COMUNICACAO', 'Equipamento de Comunicação'), ('EQUIPAMENTO_SEGURANCA', 'Equipamento de Segurança'), ('OUTROS', 'Outros')], max_length=50, verbose_name='Categoria')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série')),
                ('patrimonio', models.CharField(blank=True, help_text='Número de patrimônio (se houver)', max_length=100, null=True, verbose_name='Patrimônio')),
                ('localizacao_detalhada', models.CharField(blank=True, help_text='Ex: Sala 101, Almoxarifado, etc.', max_length=200, null=True, verbose_name='Localização Detalhada')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Aquisição (R$)')),
                ('fornecedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fornecedor')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal')),
                ('situacao', models.CharField(choices=[('EM_USO', 'Em Uso'), ('DISPONIVEL', 'Disponível'), ('MANUTENCAO', 'Em Manutenção'), ('BAIXADO', 'Baixado'), ('EXTRAVIADO', 'Extraviado'), ('DANIFICADO', 'Danificado')], default='EM_USO', max_length=20, verbose_name='Situação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Bem Móvel',
                'verbose_name_plural': 'Bens Móveis',
                'ordering': ['numero_tombamento'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoTombamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_alterado', models.CharField(max_length=100, verbose_name='Campo Alterado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_novo', models.TextField(blank=True, null=True, verbose_name='Valor Novo')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Histórico de Tombamento',
                'verbose_name_plural': 'Históricos de Tombamentos',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='TombamentoBemMovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tombamento', models.CharField(choices=[('ENTRADA', 'Entrada/Tombamento'), ('TRANSFERENCIA', 'Transferência'), ('BAIXA', 'Baixa'), ('REAVALIACAO', 'Reavaliação')], max_length=20, verbose_name='Tipo de Tombamento')),
                ('data_tombamento', models.DateField(verbose_name='Data do Tombamento')),
                ('valor_atual', models.DecimalField(blank=True, decimal_places=2, help_text='Valor atual do bem (para reavaliações)', max_digits=12, null=True, verbose_name='Valor Atual (R$)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Tombamento de Bem Móvel',
                'verbose_name_plural': 'Tombamentos de Bens Móveis',
                'ordering': ['-data_tombamento', '-data_criacao'],
            },
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_constraint c
                    JOIN pg_class t ON c.conrelid = t.oid
                    WHERE c.conname = 'unique_escala_data_org_tipo'
                    AND t.relname = 'militares_escalaservico'
                ) THEN
                    ALTER TABLE militares_escalaservico 
                    DROP CONSTRAINT unique_escala_data_org_tipo;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # NOTA: Campos show_* de FuncaoMenuConfig já existem, então não precisam ser adicionados novamente
        # migrations.AddField para show_* foram removidos para evitar erro de coluna duplicada
        migrations.AlterField(
            model_name='permissaofuncao',
            name='modulo',
            field=models.CharField(choices=[('MENU_DASHBOARD', 'Dashboard'), ('MENU_EFETIVO', 'Efetivo'), ('MENU_AFASTAMENTOS', 'Afastamentos'), ('MENU_FERIAS', 'Férias'), ('MENU_VIATURAS', 'Viaturas'), ('MENU_SECAO_PROMOCOES', 'Seção de Promoções'), ('MENU_MEDALHAS', 'Medalhas'), ('MENU_PUBLICACOES', 'Publicações'), ('MENU_ESCALAS', 'Escalas de Serviço'), ('MENU_PLANEJADAS', 'Operações Planejadas'), ('MENU_CONFIGURACOES', 'Configurações'), ('MENU_RELATORIOS', 'Relatórios'), ('MENU_PESSOAL', 'Pessoal'), ('SUBMENU_MINHAS_INFORMACOES', 'Minhas Informações'), ('SUBMENU_MINHA_FICHA_CADASTRO', 'Minha Ficha de Cadastro'), ('SUBMENU_MINHA_FICHA_CONCEITO_OFICIAL', 'Minha Ficha de Conceito (Oficial)'), ('SUBMENU_MINHA_FICHA_CONCEITO_PRACA', 'Minha Ficha de Conceito (Praça)'), ('SUBMENU_CRIAR_FICHA_CONCEITO_OFICIAL', 'Criar Ficha de Conceito (Oficial)'), ('SUBMENU_CRIAR_FICHA_CONCEITO_PRACA', 'Criar Ficha de Conceito (Praça)'), ('SUBMENU_ATIVOS', 'Militares Ativos'), ('SUBMENU_INATIVOS', 'Militares Inativos'), ('SUBMENU_LOTACOES', 'Lotações'), ('SUBMENU_AFASTAMENTOS', 'Afastamentos'), ('SUBMENU_FICHAS_OFICIAIS', 'Fichas de Conceito (Oficiais)'), ('SUBMENU_FICHAS_PRACAS', 'Fichas de Conceito (Praças)'), ('SUBMENU_QUADROS_ACESSO', 'Quadros de Acesso'), ('SUBMENU_QUADROS_FIXACAO', 'Quadros de Fixação de Vagas'), ('SUBMENU_CALENDARIOS', 'Calendários de Promoções'), ('SUBMENU_COMISSOES', 'Comissões de Promoções'), ('SUBMENU_MEUS_VOTOS', 'Meus Votos'), ('SUBMENU_PROMOCOES', 'Promoções'), ('SUBMENU_ALMANAQUES', 'Almanaques'), ('SUBMENU_INTERSTICIOS', 'Interstícios'), ('SUBMENU_GERENCIAR_INTERSTICIOS', 'Gerenciar Interstícios'), ('SUBMENU_GERENCIAR_PREVISAO', 'Gerenciar Previsão'), ('SUBMENU_MEDALHAS_CONCESSOES', 'Concessões de Medalhas'), ('SUBMENU_MEDALHAS_PROPOSTAS', 'Propostas de Medalhas'), ('SUBMENU_ELEGIVEIS', 'Elegíveis'), ('SUBMENU_PROPOSTAS', 'Propostas'), ('SUBMENU_CONCEDER_MEDALHA', 'Conceder Medalha'), ('SUBMENU_PUBLICACOES', 'Publicações'), ('SUBMENU_NOTAS', 'Notas'), ('SUBMENU_NOTAS_RESERVADAS', 'Notas Reservadas'), ('SUBMENU_BOLETINS_OSTENSIVOS', 'Boletins Ostensivos'), ('SUBMENU_BOLETINS_RESERVADOS', 'Boletins Reservados'), ('SUBMENU_BOLETINS_ESPECIAIS', 'Boletins Especiais'), ('SUBMENU_AVISOS', 'Avisos'), ('SUBMENU_ORDENS_SERVICO', 'Ordens de Serviço'), ('SUBMENU_ESCALAS_DASHBOARD', 'Dashboard de Escalas'), ('SUBMENU_ESCALAS_LISTA', 'Lista de Escalas'), ('SUBMENU_ESCALAS_CONFIGURACAO', 'Configurações de Escalas'), ('SUBMENU_ESCALAS_BANCO_HORAS', 'Banco de Horas'), ('SUBMENU_ESCALAS_OPERACOES', 'Operações de Escalas'), ('SUBMENU_USUARIOS', 'Gerenciar Usuários'), ('SUBMENU_PERMISSOES', 'Funções Militares'), ('SUBMENU_ORGAOS', 'Órgãos'), ('SUBMENU_ORGANOGRAMA', 'Organograma'), ('SUBMENU_LOGS', 'Logs do Sistema'), ('SUBMENU_TITULOS_PUBLICACAO', 'Títulos de Publicações'), ('SUBMENU_ADMINISTRACAO', 'Administração'), ('SUBMENU_GRANDES_COMANDOS', 'Grandes Comandos'), ('SUBMENU_UNIDADES', 'Unidades'), ('SUBMENU_SUB_UNIDADES', 'Sub-Unidades'), ('SUBMENU_RELATORIOS_MILITARES', 'Relatórios de Militares'), ('SUBMENU_RELATORIOS_PROMOCOES', 'Relatórios de Promoções'), ('SUBMENU_RELATORIOS_MEDALHAS', 'Relatórios de Medalhas'), ('SUBMENU_RELATORIOS_PUBLICACOES', 'Relatórios de Publicações'), ('SUBMENU_RELATORIOS_GERAIS', 'Relatórios Gerais'), ('ATIVOS_VISUALIZAR', 'Visualizar Militares Ativos'), ('ATIVOS_CRIAR', 'Criar Militares Ativos'), ('ATIVOS_EDITAR', 'Editar Militares Ativos'), ('ATIVOS_EXCLUIR', 'Excluir Militares Ativos'), ('ATIVOS_TRANSFERIR', 'Transferir Militares Ativos'), ('ATIVOS_PROMOVER', 'Promover Militares Ativos'), ('ATIVOS_INATIVAR', 'Inativar Militares Ativos'), ('ATIVOS_FICHA_CONCEITO', 'Gerenciar Fichas de Conceito'), ('ATIVOS_EXPORTAR', 'Exportar Militares Ativos'), ('ATIVOS_DASHBOARD', 'Dashboard Militares Ativos'), ('ATIVOS_REORDENAR', 'Reordenar Militares Ativos'), ('INATIVOS_VISUALIZAR', 'Visualizar Militares Inativos'), ('INATIVOS_EDITAR', 'Editar Militares Inativos'), ('INATIVOS_EXPORTAR', 'Exportar Militares Inativos'), ('LOTACOES_VISUALIZAR', 'Visualizar Lotações'), ('LOTACOES_CRIAR', 'Criar Lotações'), ('LOTACOES_EDITAR', 'Editar Lotações'), ('LOTACOES_EXCLUIR', 'Excluir Lotações'), ('INATIVOS_EDITAR', 'Editar Militares Inativos'), ('INATIVOS_EXCLUIR', 'Excluir Militares Inativos'), ('INATIVOS_REATIVAR', 'Reativar Militares Inativos'), ('LOTACOES_VISUALIZAR', 'Visualizar Lotações'), ('LOTACOES_CRIAR', 'Criar Lotações'), ('LOTACOES_EDITAR', 'Editar Lotações'), ('LOTACOES_EXCLUIR', 'Excluir Lotações'), ('DETAIL_FICHAS_CONCEITO', 'Visualizar Fichas de Conceito'), ('DETAIL_PUNICOES', 'Visualizar Punições e Elogios'), ('DETAIL_MEDALHAS', 'Visualizar Medalhas'), ('DETAIL_CONTATO', 'Visualizar Contato'), ('QUADROS_FIXACAO_VISUALIZAR', 'Visualizar Quadros de Fixação'), ('QUADROS_FIXACAO_CRIAR', 'Criar Quadros de Fixação'), ('QUADROS_FIXACAO_EDITAR', 'Editar Quadros de Fixação'), ('QUADROS_FIXACAO_EXCLUIR', 'Excluir Quadros de Fixação'), ('QUADROS_ACESSO_VISUALIZAR', 'Visualizar Quadros de Acesso'), ('QUADROS_ACESSO_CRIAR', 'Criar Quadros de Acesso'), ('QUADROS_ACESSO_EDITAR', 'Editar Quadros de Acesso'), ('QUADROS_ACESSO_EXCLUIR', 'Excluir Quadros de Acesso'), ('COMISSOES_OFICIAIS_VISUALIZAR', 'Visualizar Comissões de Oficiais'), ('COMISSOES_OFICIAIS_CRIAR', 'Criar Comissões de Oficiais'), ('COMISSOES_OFICIAIS_EDITAR', 'Editar Comissões de Oficiais'), ('COMISSOES_OFICIAIS_EXCLUIR', 'Excluir Comissões de Oficiais'), ('COMISSOES_PRACAS_VISUALIZAR', 'Visualizar Comissões de Praças'), ('COMISSOES_PRACAS_CRIAR', 'Criar Comissões de Praças'), ('COMISSOES_PRACAS_EDITAR', 'Editar Comissões de Praças'), ('COMISSOES_PRACAS_EXCLUIR', 'Excluir Comissões de Praças'), ('QUADROS_ACESSO_ASSINAR', 'Assinar Quadros de Acesso'), ('QUADROS_ACESSO_HOMOLOGAR', 'Homologar Quadros de Acesso'), ('QUADROS_ACESSO_DESHOMOLOGAR', 'Deshomologar Quadros de Acesso'), ('QUADROS_ACESSO_ELABORAR', 'Elaborar Quadros de Acesso'), ('QUADROS_ACESSO_REGENERAR', 'Regenerar Quadros de Acesso'), ('QUADROS_ACESSO_GERAR_PDF', 'Gerar PDF de Quadros de Acesso'), ('SUBMENU_MEDALHAS_CONCESSOES', 'Concessões de Medalhas'), ('SUBMENU_MEDALHAS_PROPOSTAS', 'Propostas de Medalhas'), ('SUBMENU_ELEGIVEIS', 'Elegíveis'), ('SUBMENU_PROPOSTAS', 'Propostas'), ('SUBMENU_NOTAS_LISTA', 'Lista de Notas'), ('SUBMENU_PUBLICACOES', 'Publicações'), ('SUBMENU_NOTAS', 'Notas'), ('NOTAS_VISUALIZAR', 'Visualizar Notas'), ('NOTAS_CRIAR', 'Criar Notas'), ('NOTAS_EDITAR', 'Editar Notas'), ('NOTAS_EXCLUIR', 'Excluir Notas'), ('NOTAS_REVISAR', 'Revisar Notas'), ('NOTAS_APROVAR', 'Aprovar Notas'), ('NOTAS_PUBLICAR', 'Publicar Notas'), ('NOTAS_ADMINISTRAR', 'Administrar Notas'), ('PUBLICACOES_VISUALIZAR', 'Visualizar Publicações'), ('PUBLICACOES_CRIAR', 'Criar Publicações'), ('PUBLICACOES_EDITAR', 'Editar Publicações'), ('PUBLICACOES_EXCLUIR', 'Excluir Publicações'), ('PUBLICACOES_PUBLICAR', 'Publicar Publicações'), ('SUBMENU_INTERSTICIOS', 'Interstícios'), ('SUBMENU_GERENCIAR_INTERSTICIOS', 'Gerenciar Interstícios'), ('SUBMENU_GERENCIAR_PREVISAO', 'Gerenciar Previsão'), ('SUBMENU_USUARIOS', 'Usuários'), ('SUBMENU_PERMISSOES', 'Permissões'), ('SUBMENU_LOGS', 'Logs'), ('SUBMENU_ADMINISTRACAO', 'Administração'), ('SUBMENU_PLANEJADAS', 'Operações Planejadas'), ('SUBMENU_OPERADOR_PLANEJADAS', 'Operador de Planejadas'), ('SUBMENU_FISCAL_PLANEJADAS', 'Fiscal de Planejadas'), ('SUBMENU_LIQUIDACAO', 'Liquidação'), ('PLANEJADAS_VISUALIZAR', 'Visualizar Planejadas'), ('PLANEJADAS_CRIAR', 'Criar Planejadas'), ('PLANEJADAS_EDITAR', 'Editar Planejadas'), ('PLANEJADAS_EXCLUIR', 'Excluir Planejadas'), ('PLANEJADAS_ADICIONAR_MILITAR', 'Adicionar Militar à Planejada'), ('PLANEJADAS_REMOVER_MILITAR', 'Remover Militar da Planejada'), ('PLANEJADAS_ASSINAR_OPERADOR', 'Assinar como Operador'), ('PLANEJADAS_ASSINAR_FISCAL', 'Assinar como Fiscal'), ('ORCAMENTOS_PLANEJADAS_VISUALIZAR', 'Visualizar Orçamentos de Planejadas'), ('ORCAMENTOS_PLANEJADAS_CRIAR', 'Criar Orçamentos de Planejadas'), ('ORCAMENTOS_PLANEJADAS_EDITAR', 'Editar Orçamentos de Planejadas'), ('ORCAMENTOS_PLANEJADAS_EXCLUIR', 'Excluir Orçamentos de Planejadas'), ('ORCAMENTOS_PLANEJADAS_DISTRIBUIR', 'Distribuir Orçamentos'), ('ORCAMENTOS_PLANEJADAS_APROVAR', 'Aprovar Orçamentos'), ('VIATURAS', 'Viaturas'), ('ARMAS', 'Armas'), ('PUBLICACOES', 'Publicações'), ('ELOGIOS', 'Elogios'), ('PUNICOES', 'Punições'), ('FICHAS_CONCEITO', 'Fichas de Conceito'), ('QUADROS_FIXACAO', 'Quadros de Fixação'), ('QUADROS_ACESSO', 'Quadros de Acesso'), ('COMISSOES', 'Comissões'), ('ESCALAS', 'Escalas de Serviço'), ('NOTAS', 'Notas'), ('BOLETINS_OSTENSIVOS', 'Boletins Ostensivos'), ('BOLETINS_RESERVADOS', 'Boletins Reservados'), ('BOLETINS_ESPECIAIS', 'Boletins Especiais'), ('AVISOS', 'Avisos'), ('ORDENS_SERVICO', 'Ordens de Serviço'), ('MEDALHAS', 'Medalhas'), ('USUARIOS', 'Usuários'), ('RELATORIOS', 'Relatórios'), ('PLANEJADAS', 'Operações Planejadas'), ('ORCAMENTOS_PLANEJADAS', 'Orçamentos de Planejadas'), ('AFASTAMENTOS', 'Afastamentos'), ('MILITARES', 'Militares'), ('ATIVOS', 'Militares Ativos'), ('INATIVOS', 'Militares Inativos'), ('LOTACOES', 'Lotações')], max_length=50, verbose_name='Módulo'),
        ),
        migrations.AddField(
            model_name='bemmovel',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_moveis_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='bemmovel',
            name='grande_comando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_moveis', to='militares.grandecomando', verbose_name='Grande Comando'),
        ),
        migrations.AddField(
            model_name='bemmovel',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_moveis', to='militares.orgao', verbose_name='Órgão'),
        ),
        migrations.AddField(
            model_name='bemmovel',
            name='responsavel_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_moveis_responsavel', to='militares.militar', verbose_name='Responsável Atual'),
        ),
        migrations.AddField(
            model_name='bemmovel',
            name='sub_unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_moveis', to='militares.subunidade', verbose_name='Sub-Unidade'),
        ),
        migrations.AddField(
            model_name='bemmovel',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_moveis', to='militares.unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='historicotombamento',
            name='alterado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_tombamento', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='tombamentobemmovel',
            name='bem_movel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tombamentos', to='militares.bemmovel', verbose_name='Bem Móvel'),
        ),
        migrations.AddField(
            model_name='tombamentobemmovel',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tombamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='tombamentobemmovel',
            name='grande_comando_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tombamentos_destino', to='militares.grandecomando', verbose_name='Grande Comando de Destino'),
        ),
        migrations.AddField(
            model_name='tombamentobemmovel',
            name='grande_comando_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tombamentos_origem', to='militares.grandecomando', verbose_name='Grande Comando de Origem'),
        ),
        migrations.AddField(
            model_name='tombamentobemmovel',
            name='orgao_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tombamentos_destino', to='militares.orgao', verbose_name='Órgão de Destino'),
        ),
        migrations.AddField(
            model_name='tombamentobemmovel',
            name='orgao_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tombamentos_origem', to='militares.orgao', verbose_name='Órgão de Origem'),
        ),
        migrations.AddField(
            model_name='tombamentobemmovel',
            name='responsavel_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tombamentos_responsavel_destino', to='militares.militar', verbose_name='Responsável de Destino'),
        ),
        migrations.AddField(
            model_name='tombamentobemmovel',
            name='responsavel_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tombamentos_responsavel_origem', to='militares.militar', verbose_name='Responsável de Origem'),
        ),
        migrations.AddField(
            model_name='tombamentobemmovel',
            name='sub_unidade_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tombamentos_destino', to='militares.subunidade', verbose_name='Sub-Unidade de Destino'),
        ),
        migrations.AddField(
            model_name='tombamentobemmovel',
            name='sub_unidade_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tombamentos_origem', to='militares.subunidade', verbose_name='Sub-Unidade de Origem'),
        ),
        migrations.AddField(
            model_name='tombamentobemmovel',
            name='unidade_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tombamentos_destino', to='militares.unidade', verbose_name='Unidade de Destino'),
        ),
        migrations.AddField(
            model_name='tombamentobemmovel',
            name='unidade_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tombamentos_origem', to='militares.unidade', verbose_name='Unidade de Origem'),
        ),
        migrations.AddField(
            model_name='historicotombamento',
            name='tombamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='militares.tombamentobemmovel', verbose_name='Tombamento'),
        ),
        migrations.AddIndex(
            model_name='bemmovel',
            index=models.Index(fields=['numero_tombamento'], name='militares_b_numero__fa2569_idx'),
        ),
        migrations.AddIndex(
            model_name='bemmovel',
            index=models.Index(fields=['categoria', 'situacao'], name='militares_b_categor_f1b891_idx'),
        ),
        migrations.AddIndex(
            model_name='bemmovel',
            index=models.Index(fields=['orgao', 'grande_comando', 'unidade', 'sub_unidade'], name='militares_b_orgao_i_6e9518_idx'),
        ),
        migrations.AddIndex(
            model_name='bemmovel',
            index=models.Index(fields=['responsavel_atual'], name='militares_b_respons_f744fa_idx'),
        ),
        migrations.AddIndex(
            model_name='tombamentobemmovel',
            index=models.Index(fields=['bem_movel', '-data_tombamento'], name='militares_t_bem_mov_457bad_idx'),
        ),
        migrations.AddIndex(
            model_name='tombamentobemmovel',
            index=models.Index(fields=['tipo_tombamento', '-data_tombamento'], name='militares_t_tipo_to_11ba86_idx'),
        ),
        migrations.AddIndex(
            model_name='tombamentobemmovel',
            index=models.Index(fields=['-data_tombamento'], name='militares_t_data_to_04ff7c_idx'),
        ),
        migrations.AddIndex(
            model_name='historicotombamento',
            index=models.Index(fields=['tombamento', '-data_alteracao'], name='militares_h_tombame_a9c837_idx'),
        ),
        migrations.AddIndex(
            model_name='historicotombamento',
            index=models.Index(fields=['-data_alteracao'], name='militares_h_data_al_dc720d_idx'),
        ),
    ]
