# Generated by Django 5.2.3 on 2025-11-09 13:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0341_funcaomenuconfig_show_bens_moveis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # NOTA: Campos show_* de FuncaoMenuConfig já existem, então não precisam ser adicionados novamente
        # migrations.AddField para show_* foram removidos para evitar erro de coluna duplicada
        migrations.AlterField(
            model_name='permissaofuncao',
            name='modulo',
            field=models.CharField(choices=[('MENU_DASHBOARD', 'Dashboard'), ('MENU_EFETIVO', 'Efetivo'), ('MENU_AFASTAMENTOS', 'Afastamentos'), ('MENU_FERIAS', 'Férias'), ('MENU_VIATURAS', 'Viaturas'), ('MENU_SECAO_PROMOCOES', 'Seção de Promoções'), ('MENU_MEDALHAS', 'Medalhas'), ('MENU_PUBLICACOES', 'Publicações'), ('MENU_ESCALAS', 'Escalas de Serviço'), ('MENU_PLANEJADAS', 'Operações Planejadas'), ('MENU_CONFIGURACOES', 'Configurações'), ('MENU_RELATORIOS', 'Relatórios'), ('MENU_PESSOAL', 'Pessoal'), ('MENU_BENS_MOVEIS', 'Bens Móveis'), ('MENU_ALMOXARIFADO', 'Almoxarifado'), ('SUBMENU_MINHAS_INFORMACOES', 'Minhas Informações'), ('SUBMENU_MINHA_FICHA_CADASTRO', 'Minha Ficha de Cadastro'), ('SUBMENU_MINHA_FICHA_CONCEITO_OFICIAL', 'Minha Ficha de Conceito (Oficial)'), ('SUBMENU_MINHA_FICHA_CONCEITO_PRACA', 'Minha Ficha de Conceito (Praça)'), ('SUBMENU_CRIAR_FICHA_CONCEITO_OFICIAL', 'Criar Ficha de Conceito (Oficial)'), ('SUBMENU_CRIAR_FICHA_CONCEITO_PRACA', 'Criar Ficha de Conceito (Praça)'), ('SUBMENU_ATIVOS', 'Militares Ativos'), ('SUBMENU_INATIVOS', 'Militares Inativos'), ('SUBMENU_LOTACOES', 'Lotações'), ('SUBMENU_AFASTAMENTOS', 'Afastamentos'), ('SUBMENU_FICHAS_OFICIAIS', 'Fichas de Conceito (Oficiais)'), ('SUBMENU_FICHAS_PRACAS', 'Fichas de Conceito (Praças)'), ('SUBMENU_QUADROS_ACESSO', 'Quadros de Acesso'), ('SUBMENU_QUADROS_FIXACAO', 'Quadros de Fixação de Vagas'), ('SUBMENU_CALENDARIOS', 'Calendários de Promoções'), ('SUBMENU_COMISSOES', 'Comissões de Promoções'), ('SUBMENU_MEUS_VOTOS', 'Meus Votos'), ('SUBMENU_PROMOCOES', 'Promoções'), ('SUBMENU_ALMANAQUES', 'Almanaques'), ('SUBMENU_INTERSTICIOS', 'Interstícios'), ('SUBMENU_GERENCIAR_INTERSTICIOS', 'Gerenciar Interstícios'), ('SUBMENU_GERENCIAR_PREVISAO', 'Gerenciar Previsão'), ('SUBMENU_MEDALHAS_CONCESSOES', 'Concessões de Medalhas'), ('SUBMENU_MEDALHAS_PROPOSTAS', 'Propostas de Medalhas'), ('SUBMENU_ELEGIVEIS', 'Elegíveis'), ('SUBMENU_PROPOSTAS', 'Propostas'), ('SUBMENU_CONCEDER_MEDALHA', 'Conceder Medalha'), ('SUBMENU_PUBLICACOES', 'Publicações'), ('SUBMENU_NOTAS', 'Notas'), ('SUBMENU_NOTAS_RESERVADAS', 'Notas Reservadas'), ('SUBMENU_BOLETINS_OSTENSIVOS', 'Boletins Ostensivos'), ('SUBMENU_BOLETINS_RESERVADOS', 'Boletins Reservados'), ('SUBMENU_BOLETINS_ESPECIAIS', 'Boletins Especiais'), ('SUBMENU_AVISOS', 'Avisos'), ('SUBMENU_ORDENS_SERVICO', 'Ordens de Serviço'), ('SUBMENU_ESCALAS_DASHBOARD', 'Dashboard de Escalas'), ('SUBMENU_ESCALAS_LISTA', 'Lista de Escalas'), ('SUBMENU_ESCALAS_CONFIGURACAO', 'Configurações de Escalas'), ('SUBMENU_ESCALAS_BANCO_HORAS', 'Banco de Horas'), ('SUBMENU_ESCALAS_OPERACOES', 'Operações de Escalas'), ('SUBMENU_USUARIOS', 'Gerenciar Usuários'), ('SUBMENU_PERMISSOES', 'Funções Militares'), ('SUBMENU_ORGAOS', 'Órgãos'), ('SUBMENU_ORGANOGRAMA', 'Organograma'), ('SUBMENU_LOGS', 'Logs do Sistema'), ('SUBMENU_TITULOS_PUBLICACAO', 'Títulos de Publicações'), ('SUBMENU_ADMINISTRACAO', 'Administração'), ('SUBMENU_GRANDES_COMANDOS', 'Grandes Comandos'), ('SUBMENU_UNIDADES', 'Unidades'), ('SUBMENU_SUB_UNIDADES', 'Sub-Unidades'), ('SUBMENU_RELATORIOS_MILITARES', 'Relatórios de Militares'), ('SUBMENU_RELATORIOS_PROMOCOES', 'Relatórios de Promoções'), ('SUBMENU_RELATORIOS_MEDALHAS', 'Relatórios de Medalhas'), ('SUBMENU_RELATORIOS_PUBLICACOES', 'Relatórios de Publicações'), ('SUBMENU_RELATORIOS_GERAIS', 'Relatórios Gerais'), ('ATIVOS_VISUALIZAR', 'Visualizar Militares Ativos'), ('ATIVOS_CRIAR', 'Criar Militares Ativos'), ('ATIVOS_EDITAR', 'Editar Militares Ativos'), ('ATIVOS_EXCLUIR', 'Excluir Militares Ativos'), ('ATIVOS_TRANSFERIR', 'Transferir Militares Ativos'), ('ATIVOS_PROMOVER', 'Promover Militares Ativos'), ('ATIVOS_INATIVAR', 'Inativar Militares Ativos'), ('ATIVOS_FICHA_CONCEITO', 'Gerenciar Fichas de Conceito'), ('ATIVOS_EXPORTAR', 'Exportar Militares Ativos'), ('ATIVOS_DASHBOARD', 'Dashboard Militares Ativos'), ('ATIVOS_REORDENAR', 'Reordenar Militares Ativos'), ('INATIVOS_VISUALIZAR', 'Visualizar Militares Inativos'), ('INATIVOS_EDITAR', 'Editar Militares Inativos'), ('INATIVOS_EXPORTAR', 'Exportar Militares Inativos'), ('LOTACOES_VISUALIZAR', 'Visualizar Lotações'), ('LOTACOES_CRIAR', 'Criar Lotações'), ('LOTACOES_EDITAR', 'Editar Lotações'), ('LOTACOES_EXCLUIR', 'Excluir Lotações'), ('INATIVOS_EDITAR', 'Editar Militares Inativos'), ('INATIVOS_EXCLUIR', 'Excluir Militares Inativos'), ('INATIVOS_REATIVAR', 'Reativar Militares Inativos'), ('LOTACOES_VISUALIZAR', 'Visualizar Lotações'), ('LOTACOES_CRIAR', 'Criar Lotações'), ('LOTACOES_EDITAR', 'Editar Lotações'), ('LOTACOES_EXCLUIR', 'Excluir Lotações'), ('DETAIL_FICHAS_CONCEITO', 'Visualizar Fichas de Conceito'), ('DETAIL_PUNICOES', 'Visualizar Punições e Elogios'), ('DETAIL_MEDALHAS', 'Visualizar Medalhas'), ('DETAIL_CONTATO', 'Visualizar Contato'), ('QUADROS_FIXACAO_VISUALIZAR', 'Visualizar Quadros de Fixação'), ('QUADROS_FIXACAO_CRIAR', 'Criar Quadros de Fixação'), ('QUADROS_FIXACAO_EDITAR', 'Editar Quadros de Fixação'), ('QUADROS_FIXACAO_EXCLUIR', 'Excluir Quadros de Fixação'), ('QUADROS_ACESSO_VISUALIZAR', 'Visualizar Quadros de Acesso'), ('QUADROS_ACESSO_CRIAR', 'Criar Quadros de Acesso'), ('QUADROS_ACESSO_EDITAR', 'Editar Quadros de Acesso'), ('QUADROS_ACESSO_EXCLUIR', 'Excluir Quadros de Acesso'), ('COMISSOES_OFICIAIS_VISUALIZAR', 'Visualizar Comissões de Oficiais'), ('COMISSOES_OFICIAIS_CRIAR', 'Criar Comissões de Oficiais'), ('COMISSOES_OFICIAIS_EDITAR', 'Editar Comissões de Oficiais'), ('COMISSOES_OFICIAIS_EXCLUIR', 'Excluir Comissões de Oficiais'), ('COMISSOES_PRACAS_VISUALIZAR', 'Visualizar Comissões de Praças'), ('COMISSOES_PRACAS_CRIAR', 'Criar Comissões de Praças'), ('COMISSOES_PRACAS_EDITAR', 'Editar Comissões de Praças'), ('COMISSOES_PRACAS_EXCLUIR', 'Excluir Comissões de Praças'), ('QUADROS_ACESSO_ASSINAR', 'Assinar Quadros de Acesso'), ('QUADROS_ACESSO_HOMOLOGAR', 'Homologar Quadros de Acesso'), ('QUADROS_ACESSO_DESHOMOLOGAR', 'Deshomologar Quadros de Acesso'), ('QUADROS_ACESSO_ELABORAR', 'Elaborar Quadros de Acesso'), ('QUADROS_ACESSO_REGENERAR', 'Regenerar Quadros de Acesso'), ('QUADROS_ACESSO_GERAR_PDF', 'Gerar PDF de Quadros de Acesso'), ('SUBMENU_MEDALHAS_CONCESSOES', 'Concessões de Medalhas'), ('SUBMENU_MEDALHAS_PROPOSTAS', 'Propostas de Medalhas'), ('SUBMENU_ELEGIVEIS', 'Elegíveis'), ('SUBMENU_PROPOSTAS', 'Propostas'), ('SUBMENU_NOTAS_LISTA', 'Lista de Notas'), ('SUBMENU_PUBLICACOES', 'Publicações'), ('SUBMENU_NOTAS', 'Notas'), ('NOTAS_VISUALIZAR', 'Visualizar Notas'), ('NOTAS_CRIAR', 'Criar Notas'), ('NOTAS_EDITAR', 'Editar Notas'), ('NOTAS_EXCLUIR', 'Excluir Notas'), ('NOTAS_REVISAR', 'Revisar Notas'), ('NOTAS_APROVAR', 'Aprovar Notas'), ('NOTAS_PUBLICAR', 'Publicar Notas'), ('NOTAS_ADMINISTRAR', 'Administrar Notas'), ('PUBLICACOES_VISUALIZAR', 'Visualizar Publicações'), ('PUBLICACOES_CRIAR', 'Criar Publicações'), ('PUBLICACOES_EDITAR', 'Editar Publicações'), ('PUBLICACOES_EXCLUIR', 'Excluir Publicações'), ('PUBLICACOES_PUBLICAR', 'Publicar Publicações'), ('SUBMENU_INTERSTICIOS', 'Interstícios'), ('SUBMENU_GERENCIAR_INTERSTICIOS', 'Gerenciar Interstícios'), ('SUBMENU_GERENCIAR_PREVISAO', 'Gerenciar Previsão'), ('SUBMENU_USUARIOS', 'Usuários'), ('SUBMENU_PERMISSOES', 'Permissões'), ('SUBMENU_LOGS', 'Logs'), ('SUBMENU_ADMINISTRACAO', 'Administração'), ('SUBMENU_PLANEJADAS', 'Operações Planejadas'), ('SUBMENU_OPERADOR_PLANEJADAS', 'Operador de Planejadas'), ('SUBMENU_FISCAL_PLANEJADAS', 'Fiscal de Planejadas'), ('SUBMENU_LIQUIDACAO', 'Liquidação'), ('PLANEJADAS_VISUALIZAR', 'Visualizar Planejadas'), ('PLANEJADAS_CRIAR', 'Criar Planejadas'), ('PLANEJADAS_EDITAR', 'Editar Planejadas'), ('PLANEJADAS_EXCLUIR', 'Excluir Planejadas'), ('PLANEJADAS_ADICIONAR_MILITAR', 'Adicionar Militar à Planejada'), ('PLANEJADAS_REMOVER_MILITAR', 'Remover Militar da Planejada'), ('PLANEJADAS_ASSINAR_OPERADOR', 'Assinar como Operador'), ('PLANEJADAS_ASSINAR_FISCAL', 'Assinar como Fiscal'), ('ORCAMENTOS_PLANEJADAS_VISUALIZAR', 'Visualizar Orçamentos de Planejadas'), ('ORCAMENTOS_PLANEJADAS_CRIAR', 'Criar Orçamentos de Planejadas'), ('ORCAMENTOS_PLANEJADAS_EDITAR', 'Editar Orçamentos de Planejadas'), ('ORCAMENTOS_PLANEJADAS_EXCLUIR', 'Excluir Orçamentos de Planejadas'), ('ORCAMENTOS_PLANEJADAS_DISTRIBUIR', 'Distribuir Orçamentos'), ('ORCAMENTOS_PLANEJADAS_APROVAR', 'Aprovar Orçamentos'), ('VIATURAS', 'Viaturas'), ('ARMAS', 'Armas'), ('PUBLICACOES', 'Publicações'), ('ELOGIOS', 'Elogios'), ('PUNICOES', 'Punições'), ('FICHAS_CONCEITO', 'Fichas de Conceito'), ('QUADROS_FIXACAO', 'Quadros de Fixação'), ('QUADROS_ACESSO', 'Quadros de Acesso'), ('COMISSOES', 'Comissões'), ('ESCALAS', 'Escalas de Serviço'), ('NOTAS', 'Notas'), ('BOLETINS_OSTENSIVOS', 'Boletins Ostensivos'), ('BOLETINS_RESERVADOS', 'Boletins Reservados'), ('BOLETINS_ESPECIAIS', 'Boletins Especiais'), ('AVISOS', 'Avisos'), ('ORDENS_SERVICO', 'Ordens de Serviço'), ('MEDALHAS', 'Medalhas'), ('USUARIOS', 'Usuários'), ('RELATORIOS', 'Relatórios'), ('PLANEJADAS', 'Operações Planejadas'), ('ORCAMENTOS_PLANEJADAS', 'Orçamentos de Planejadas'), ('AFASTAMENTOS', 'Afastamentos'), ('MILITARES', 'Militares'), ('ATIVOS', 'Militares Ativos'), ('INATIVOS', 'Militares Inativos'), ('LOTACOES', 'Lotações'), ('ALMOXARIFADO', 'Almoxarifado')], max_length=50, verbose_name='Módulo'),
        ),
        migrations.CreateModel(
            name='ItemAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de identificação do item', max_length=50, unique=True, verbose_name='Código do Item')),
                ('descricao', models.CharField(help_text='Descrição detalhada do item', max_length=500, verbose_name='Descrição do Item')),
                ('categoria', models.CharField(choices=[('MATERIAL_ESCRITORIO', 'Material de Escritório'), ('MATERIAL_LIMPEZA', 'Material de Limpeza'), ('MATERIAL_CONSTRUCAO', 'Material de Construção'), ('FERRAMENTAS', 'Ferramentas'), ('EQUIPAMENTOS', 'Equipamentos'), ('UNIFORMES', 'Uniformes'), ('EPI', 'EPI - Equipamento de Proteção Individual'), ('COMBUSTIVEL', 'Combustível'), ('ALIMENTOS', 'Alimentos'), ('OUTROS', 'Outros')], max_length=50, verbose_name='Categoria')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('M', 'Metro'), ('CM', 'Centímetro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cúbico'), ('CX', 'Caixa'), ('PC', 'Peça'), ('RL', 'Rolo'), ('FD', 'Fardo'), ('SC', 'Saco'), ('OUTROS', 'Outros')], default='UN', max_length=20, verbose_name='Unidade de Medida')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Quantidade mínima em estoque', max_digits=10, verbose_name='Estoque Mínimo')),
                ('estoque_maximo', models.DecimalField(decimal_places=2, default=0, help_text='Quantidade máxima em estoque', max_digits=10, verbose_name='Estoque Máximo')),
                ('quantidade_atual', models.DecimalField(decimal_places=2, default=0, help_text='Quantidade atual em estoque', max_digits=10, verbose_name='Quantidade Atual')),
                ('localizacao', models.CharField(blank=True, help_text='Localização física do item no almoxarifado', max_length=200, null=True, verbose_name='Localização')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Valor unitário médio do item', max_digits=12, null=True, verbose_name='Valor Unitário (R$)')),
                ('fornecedor_principal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fornecedor Principal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_almoxarifado_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Item do Almoxarifado',
                'verbose_name_plural': 'Itens do Almoxarifado',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(help_text='Ex: Entrada, Saída, Ajuste', max_length=50, verbose_name='Tipo de Movimentação')),
                ('campo_alterado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo Alterado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_novo', models.TextField(blank=True, null=True, verbose_name='Valor Novo')),
                ('quantidade_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade Anterior')),
                ('quantidade_nova', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade Nova')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_almoxarifado', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='militares.itemalmoxarifado', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Histórico de Almoxarifado',
                'verbose_name_plural': 'Históricos de Almoxarifado',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='EntradaAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrada', models.CharField(choices=[('COMPRA', 'Compra'), ('DOACAO', 'Doação'), ('DEVOLUCAO', 'Devolução'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE', 'Ajuste de Estoque'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Entrada')),
                ('data_entrada', models.DateField(verbose_name='Data da Entrada')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Unitário (R$)')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total (R$)')),
                ('fornecedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fornecedor')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_almoxarifado_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('grande_comando_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_almoxarifado_origem', to='militares.grandecomando', verbose_name='Grande Comando de Origem')),
                ('orgao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_almoxarifado_origem', to='militares.orgao', verbose_name='Órgão de Origem')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_almoxarifado_responsavel', to='militares.militar', verbose_name='Responsável')),
                ('sub_unidade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_almoxarifado_origem', to='militares.subunidade', verbose_name='Sub-Unidade de Origem')),
                ('unidade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_almoxarifado_origem', to='militares.unidade', verbose_name='Unidade de Origem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='militares.itemalmoxarifado', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Entrada de Almoxarifado',
                'verbose_name_plural': 'Entradas de Almoxarifado',
                'ordering': ['-data_entrada', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SaidaAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_saida', models.CharField(choices=[('REQUISICAO', 'Requisição'), ('CONSUMO', 'Consumo'), ('TRANSFERENCIA', 'Transferência'), ('BAIXA', 'Baixa'), ('AJUSTE', 'Ajuste de Estoque'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Saída')),
                ('data_saida', models.DateField(verbose_name='Data da Saída')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantidade')),
                ('numero_requisicao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Requisição')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_almoxarifado_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('grande_comando_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_almoxarifado_destino', to='militares.grandecomando', verbose_name='Grande Comando de Destino')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='militares.itemalmoxarifado', verbose_name='Item')),
                ('orgao_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_almoxarifado_destino', to='militares.orgao', verbose_name='Órgão de Destino')),
                ('requisitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_almoxarifado_requisitante', to='militares.militar', verbose_name='Requisitante')),
                ('responsavel_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_almoxarifado_responsavel_entrega', to='militares.militar', verbose_name='Responsável pela Entrega')),
                ('sub_unidade_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_almoxarifado_destino', to='militares.subunidade', verbose_name='Sub-Unidade de Destino')),
                ('unidade_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_almoxarifado_destino', to='militares.unidade', verbose_name='Unidade de Destino')),
            ],
            options={
                'verbose_name': 'Saída de Almoxarifado',
                'verbose_name_plural': 'Saídas de Almoxarifado',
                'ordering': ['-data_saida', '-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='itemalmoxarifado',
            index=models.Index(fields=['codigo'], name='militares_i_codigo_a5f55d_idx'),
        ),
        migrations.AddIndex(
            model_name='itemalmoxarifado',
            index=models.Index(fields=['categoria'], name='militares_i_categor_f3510e_idx'),
        ),
        migrations.AddIndex(
            model_name='itemalmoxarifado',
            index=models.Index(fields=['ativo'], name='militares_i_ativo_9e7d87_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoalmoxarifado',
            index=models.Index(fields=['item', '-data_alteracao'], name='militares_h_item_id_92a708_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoalmoxarifado',
            index=models.Index(fields=['-data_alteracao'], name='militares_h_data_al_d3b1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='entradaalmoxarifado',
            index=models.Index(fields=['item', '-data_entrada'], name='militares_e_item_id_23fdb4_idx'),
        ),
        migrations.AddIndex(
            model_name='entradaalmoxarifado',
            index=models.Index(fields=['tipo_entrada', '-data_entrada'], name='militares_e_tipo_en_d9e098_idx'),
        ),
        migrations.AddIndex(
            model_name='entradaalmoxarifado',
            index=models.Index(fields=['-data_entrada'], name='militares_e_data_en_ead06d_idx'),
        ),
        migrations.AddIndex(
            model_name='saidaalmoxarifado',
            index=models.Index(fields=['item', '-data_saida'], name='militares_s_item_id_08732e_idx'),
        ),
        migrations.AddIndex(
            model_name='saidaalmoxarifado',
            index=models.Index(fields=['tipo_saida', '-data_saida'], name='militares_s_tipo_sa_ed54d7_idx'),
        ),
        migrations.AddIndex(
            model_name='saidaalmoxarifado',
            index=models.Index(fields=['-data_saida'], name='militares_s_data_sa_4ff521_idx'),
        ),
    ]
