# Generated by Django 5.2.3 on 2025-11-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0343_funcaomenuconfig_show_almoxarifado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemalmoxarifado',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras do item (gerado automaticamente baseado no código)', max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
    ]
