# Generated by Django 5.2.3 on 2025-11-09 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0344_add_codigo_barras_item_almoxarifado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número único de identificação do processo', max_length=50, unique=True, verbose_name='Número do Processo')),
                ('tipo', models.CharField(choices=[('PROCESSO_ADMINISTRATIVO', 'Processo Administrativo'), ('PROCEDIMENTO_ADMINISTRATIVO', 'Procedimento Administrativo'), ('INQUERITO', 'Inquérito'), ('SINDICANCIA', 'Sindicância'), ('REPRESENTACAO', 'Representação'), ('OUTROS', 'Outros')], max_length=30, verbose_name='Tipo de Processo')),
                ('assunto', models.CharField(help_text='Assunto ou título do processo', max_length=500, verbose_name='Assunto')),
                ('descricao', models.TextField(help_text='Descrição detalhada do processo', verbose_name='Descrição')),
                ('status', models.CharField(choices=[('EM_ABERTURA', 'Em Abertura'), ('EM_ANDAMENTO', 'Em Andamento'), ('EM_ANALISE', 'Em Análise'), ('AGUARDANDO_DECISAO', 'Aguardando Decisão'), ('DECIDIDO', 'Decidido'), ('ARQUIVADO', 'Arquivado'), ('CANCELADO', 'Cancelado')], default='EM_ABERTURA', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridade')),
                ('data_abertura', models.DateField(verbose_name='Data de Abertura')),
                ('data_prazo', models.DateField(blank=True, help_text='Prazo para conclusão do processo', null=True, verbose_name='Data de Prazo')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('data_arquivamento', models.DateField(blank=True, null=True, verbose_name='Data de Arquivamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_administrativos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('escrivaos', models.ManyToManyField(blank=True, help_text='Militares que atuam como escribãos no processo', related_name='processos_como_escriva', to='militares.militar', verbose_name='Escribãos')),
                ('grande_comando', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_administrativos', to='militares.grandecomando', verbose_name='Grande Comando')),
                ('militares_encarregados', models.ManyToManyField(blank=True, help_text='Militares responsáveis pelo processo', related_name='processos_como_encarregado', to='militares.militar', verbose_name='Militares Encarregados')),
                ('militares_envolvidos', models.ManyToManyField(blank=True, help_text='Militares que são parte do processo', related_name='processos_como_envolvido', to='militares.militar', verbose_name='Militares Envolvidos')),
                ('orgao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_administrativos', to='militares.orgao', verbose_name='Órgão')),
                ('sub_unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_administrativos', to='militares.subunidade', verbose_name='Sub-Unidade')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_administrativos', to='militares.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Processo Administrativo',
                'verbose_name_plural': 'Processos Administrativos',
                'ordering': ['-data_abertura', '-data_criacao'],
                'indexes': [models.Index(fields=['numero'], name='militares_p_numero_fbd750_idx'), models.Index(fields=['tipo'], name='militares_p_tipo_8d06ad_idx'), models.Index(fields=['status'], name='militares_p_status_7e67ea_idx'), models.Index(fields=['data_abertura'], name='militares_p_data_ab_bf25d0_idx')],
            },
        ),
    ]
