# Generated by Django 5.2.3 on 2025-11-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0346_add_show_processos_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoadministrativo',
            name='tipo',
            field=models.CharField(choices=[('SINDICANCIA', 'Sindicância'), ('INQUERITO_POLICIAL', 'Inquérito Policial'), ('INQUERITO_POLICIAL_MILITAR', 'Inquérito Policial Militar'), ('INQUERITO_TECNICO', 'Inquérito Técnico'), ('PROCESSO_ADMINISTRATIVO_DISCIPLINAR_SUMARIO', 'Processo Administrativo Disciplinar Sumário'), ('PROCESSO_ADMINISTRATIVO_DISCIPLINAR_ORDINARIO', 'Processo Administrativo Disciplinar Ordinário'), ('PROCESSO_CRIMINAL', 'Processo Criminal'), ('PROCESSO_ADMINISTRATIVO', 'Processo Administrativo'), ('PROCEDIMENTO_ADMINISTRATIVO', 'Procedimento Administrativo'), ('REPRESENTACAO', 'Representação'), ('OUTROS', 'Outros')], max_length=50, verbose_name='Tipo de Processo'),
        ),
    ]
