# Generated by Django 5.0.2 on 2025-11-10 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0347_update_tipo_processo_choices"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE militares_escalaservico DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="processoadministrativo",
            name="processo_origem",
            field=models.ForeignKey(
                blank=True,
                help_text="Processo que deu origem a este processo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processos_derivados",
                to="militares.processoadministrativo",
                verbose_name="Processo de Origem",
            ),
        ),
        migrations.AddField(
            model_name="processoadministrativo",
            name="processo_procedimento",
            field=models.ForeignKey(
                blank=True,
                help_text="Processo no qual foi realizado o procedimento relacionado",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processos_que_realizaram_procedimento",
                to="militares.processoadministrativo",
                verbose_name="Processo que Realizou o Procedimento",
            ),
        ),
        migrations.AlterField(
            model_name="processoadministrativo",
            name="escrivaos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Militares que atuam como escribões no processo",
                related_name="processos_como_escriva",
                to="militares.militar",
                verbose_name="Escribões",
            ),
        ),
    ]
