# Generated by Django 5.0.2 on 2025-11-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0348_add_processo_origem_procedimento"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE militares_escalaservico DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="processoadministrativo",
            name="processo_origem",
            field=models.CharField(
                blank=True,
                help_text="Número do processo que deu origem a este processo",
                max_length=100,
                null=True,
                verbose_name="Processo de Origem",
            ),
        ),
        migrations.AlterField(
            model_name="processoadministrativo",
            name="processo_procedimento",
            field=models.CharField(
                blank=True,
                help_text="Número do processo no qual foi realizado o procedimento relacionado",
                max_length=100,
                null=True,
                verbose_name="Processo que Realizou o Procedimento",
            ),
        ),
    ]
