# Generated by Django 5.2.3 on 2025-11-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0349_change_processo_origem_procedimento_to_text'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE militares_escalaservico DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Adicionar colunas apenas se não existirem
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_criar_ficha_conceito_oficial') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_criar_ficha_conceito_oficial BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_criar_ficha_conceito_praca') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_criar_ficha_conceito_praca BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_grandes_comandos') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_grandes_comandos BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_minha_ficha_cadastro') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_minha_ficha_cadastro BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_minha_ficha_conceito_oficial') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_minha_ficha_conceito_oficial BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_minha_ficha_conceito_praca') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_minha_ficha_conceito_praca BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_minhas_informacoes') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_minhas_informacoes BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_organograma') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_organograma BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_orgaos') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_orgaos BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_pessoal') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_pessoal BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_gerais') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_gerais BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_medalhas') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_medalhas BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_militares') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_militares BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_promocoes') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_promocoes BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_publicacoes') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_publicacoes BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_sub_unidades') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_sub_unidades BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_unidades') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_unidades BOOLEAN DEFAULT FALSE;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='funcaomenuconfig',
            name='show_escalas_configuracao',
            field=models.BooleanField(default=False, verbose_name='Configurações de Escalas'),
        ),
        migrations.AlterField(
            model_name='funcaomenuconfig',
            name='show_escalas_dashboard',
            field=models.BooleanField(default=False, verbose_name='Dashboard de Escalas'),
        ),
        migrations.AlterField(
            model_name='funcaomenuconfig',
            name='show_escalas_operacoes',
            field=models.BooleanField(default=False, verbose_name='Operações de Escalas'),
        ),
        migrations.AlterField(
            model_name='itemalmoxarifado',
            name='categoria',
            field=models.CharField(choices=[('EQUIPAMENTOS_OPERACIONAIS', 'Equipamentos Operacionais'), ('EPI', 'Equipamentos de Proteção Individual'), ('EQUIPAMENTOS_VIATURAS', 'Equipamentos e Materiais para Viaturas'), ('ENGENHARIA_LOGISTICA', 'Equipamentos de Engenharia e Logística'), ('SAUDE', 'Materiais e Equipamentos de Saúde'), ('MANUTENCAO_ALMOXARIFADO', 'Materiais de Manutenção e Almoxarifado'), ('DIDATICO_TREINAMENTO', 'Materiais Didáticos e de Treinamento'), ('INFRAESTRUTURA_CONSTRUCAO', 'Materiais de Infraestrutura e Construção'), ('INFORMATICA', 'Materiais e Equipamentos de Informática'), ('ADMINISTRATIVO', 'Materiais Administrativos e de Escritório'), ('DEFESA_CIVIL', 'Materiais para Defesa Civil e Ações Humanitárias'), ('PATRIMONIO', 'Materiais Permanentes e de Patrimônio')], max_length=50, verbose_name='Categoria'),
        ),
    ]
