# Generated by Django 5.2.3 on 2025-11-10 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0350_atualizar_categorias_almoxarifado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Subcategoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.RenameIndex(
            model_name='itemalmoxarifado',
            new_name='militares_i_categor_25221b_idx',
            old_name='militares_i_categor_f3510e_idx',
        ),
        migrations.AddField(
            model_name='itemalmoxarifado',
            name='categoria_antiga',
            field=models.CharField(blank=True, choices=[('EQUIPAMENTOS_OPERACIONAIS', 'Equipamentos Operacionais'), ('EPI', 'Equipamentos de Proteção Individual'), ('EQUIPAMENTOS_VIATURAS', 'Equipamentos e Materiais para Viaturas'), ('ENGENHARIA_LOGISTICA', 'Equipamentos de Engenharia e Logística'), ('SAUDE', 'Materiais e Equipamentos de Saúde'), ('MANUTENCAO_ALMOXARIFADO', 'Materiais de Manutenção e Almoxarifado'), ('DIDATICO_TREINAMENTO', 'Materiais Didáticos e de Treinamento'), ('INFRAESTRUTURA_CONSTRUCAO', 'Materiais de Infraestrutura e Construção'), ('INFORMATICA', 'Materiais e Equipamentos de Informática'), ('ADMINISTRATIVO', 'Materiais Administrativos e de Escritório'), ('DEFESA_CIVIL', 'Materiais para Defesa Civil e Ações Humanitárias'), ('PATRIMONIO', 'Materiais Permanentes e de Patrimônio')], help_text='Categoria antiga (mantida para compatibilidade)', max_length=50, null=True, verbose_name='Categoria (Antiga)'),
        ),
        migrations.AlterField(
            model_name='itemalmoxarifado',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_almoxarifado', to='militares.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='militares.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='itemalmoxarifado',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_almoxarifado', to='militares.subcategoria', verbose_name='Subcategoria'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('categoria', 'nome')},
        ),
    ]
