# Generated by Django 5.2.3 on 2025-11-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0351_adicionar_categoria_subcategoria_almoxarifado'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE militares_escalaservico DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # NOTA: Os campos show_* de FuncaoMenuConfig já foram adicionados na migração 0350
        # Adicionar coluna imagem apenas se não existir (usando SeparateDatabaseAndState)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$ 
                        BEGIN
                            IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                           WHERE table_name='militares_itemalmoxarifado' 
                                           AND column_name='imagem') THEN
                                ALTER TABLE militares_itemalmoxarifado 
                                ADD COLUMN imagem VARCHAR(100);
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='itemalmoxarifado',
                    name='imagem',
                    field=models.ImageField(blank=True, help_text='Imagem do item do almoxarifado', null=True, upload_to='almoxarifado/itens/', verbose_name='Imagem do Item'),
                ),
            ],
        ),
    ]
