# Generated by Django 5.2.3 on 2025-11-10 22:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0352_adicionar_imagem_item_almoxarifado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantidade')),
                ('data_requisicao', models.DateField(auto_now_add=True, verbose_name='Data da Requisição')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('NEGADA', 'Negada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('motivo_negacao', models.TextField(blank=True, null=True, verbose_name='Motivo da Negação')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação/Negação')),
                ('data_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atendimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Requisição de Almoxarifado',
                'verbose_name_plural': 'Requisições de Almoxarifado',
                'ordering': ['-data_requisicao', '-data_criacao'],
            },
        ),
        # migrations.RemoveConstraint(
        #     model_name='escalaservico',
        #     name='unique_escala_data_org_tipo',
        #         ),
        # Campos já existem no banco, comentados para evitar erro
        # migrations.AddField(...) - todos os campos show_* já existem
        migrations.AlterField(
            model_name='permissaofuncao',
            name='modulo',
            field=models.CharField(choices=[('MENU_DASHBOARD', 'Dashboard'), ('MENU_EFETIVO', 'Efetivo'), ('MENU_AFASTAMENTOS', 'Afastamentos'), ('MENU_FERIAS', 'Férias'), ('MENU_VIATURAS', 'Viaturas'), ('MENU_SECAO_PROMOCOES', 'Seção de Promoções'), ('MENU_MEDALHAS', 'Medalhas'), ('MENU_PUBLICACOES', 'Publicações'), ('MENU_ESCALAS', 'Escalas de Serviço'), ('MENU_PLANEJADAS', 'Operações Planejadas'), ('MENU_CONFIGURACOES', 'Configurações'), ('MENU_RELATORIOS', 'Relatórios'), ('MENU_PESSOAL', 'Pessoal'), ('MENU_BENS_MOVEIS', 'Bens Móveis'), ('MENU_ALMOXARIFADO', 'Almoxarifado'), ('MENU_PROCESSOS', 'Processos Administrativos'), ('SUBMENU_MINHAS_INFORMACOES', 'Minhas Informações'), ('SUBMENU_MINHA_FICHA_CADASTRO', 'Minha Ficha de Cadastro'), ('SUBMENU_MINHA_FICHA_CONCEITO_OFICIAL', 'Minha Ficha de Conceito (Oficial)'), ('SUBMENU_MINHA_FICHA_CONCEITO_PRACA', 'Minha Ficha de Conceito (Praça)'), ('SUBMENU_CRIAR_FICHA_CONCEITO_OFICIAL', 'Criar Ficha de Conceito (Oficial)'), ('SUBMENU_CRIAR_FICHA_CONCEITO_PRACA', 'Criar Ficha de Conceito (Praça)'), ('SUBMENU_ATIVOS', 'Militares Ativos'), ('SUBMENU_INATIVOS', 'Militares Inativos'), ('SUBMENU_LOTACOES', 'Lotações'), ('SUBMENU_AFASTAMENTOS', 'Afastamentos'), ('SUBMENU_FICHAS_OFICIAIS', 'Fichas de Conceito (Oficiais)'), ('SUBMENU_FICHAS_PRACAS', 'Fichas de Conceito (Praças)'), ('SUBMENU_QUADROS_ACESSO', 'Quadros de Acesso'), ('SUBMENU_QUADROS_FIXACAO', 'Quadros de Fixação de Vagas'), ('SUBMENU_CALENDARIOS', 'Calendários de Promoções'), ('SUBMENU_COMISSOES', 'Comissões de Promoções'), ('SUBMENU_MEUS_VOTOS', 'Meus Votos'), ('SUBMENU_PROMOCOES', 'Promoções'), ('SUBMENU_ALMANAQUES', 'Almanaques'), ('SUBMENU_INTERSTICIOS', 'Interstícios'), ('SUBMENU_GERENCIAR_INTERSTICIOS', 'Gerenciar Interstícios'), ('SUBMENU_GERENCIAR_PREVISAO', 'Gerenciar Previsão'), ('SUBMENU_MEDALHAS_CONCESSOES', 'Concessões de Medalhas'), ('SUBMENU_MEDALHAS_PROPOSTAS', 'Propostas de Medalhas'), ('SUBMENU_ELEGIVEIS', 'Elegíveis'), ('SUBMENU_PROPOSTAS', 'Propostas'), ('SUBMENU_CONCEDER_MEDALHA', 'Conceder Medalha'), ('SUBMENU_PUBLICACOES', 'Publicações'), ('SUBMENU_NOTAS', 'Notas'), ('SUBMENU_NOTAS_RESERVADAS', 'Notas Reservadas'), ('SUBMENU_BOLETINS_OSTENSIVOS', 'Boletins Ostensivos'), ('SUBMENU_BOLETINS_RESERVADOS', 'Boletins Reservados'), ('SUBMENU_BOLETINS_ESPECIAIS', 'Boletins Especiais'), ('SUBMENU_AVISOS', 'Avisos'), ('SUBMENU_ORDENS_SERVICO', 'Ordens de Serviço'), ('SUBMENU_ESCALAS_DASHBOARD', 'Dashboard de Escalas'), ('SUBMENU_ESCALAS_LISTA', 'Lista de Escalas'), ('SUBMENU_ESCALAS_CONFIGURACAO', 'Configurações de Escalas'), ('SUBMENU_ESCALAS_BANCO_HORAS', 'Banco de Horas'), ('SUBMENU_ESCALAS_OPERACOES', 'Operações de Escalas'), ('SUBMENU_ALMOXARIFADO_ITENS', 'Itens do Almoxarifado'), ('SUBMENU_ALMOXARIFADO_ENTRADAS', 'Entradas do Almoxarifado'), ('SUBMENU_ALMOXARIFADO_SAIDAS', 'Saídas do Almoxarifado'), ('SUBMENU_USUARIOS', 'Gerenciar Usuários'), ('SUBMENU_PERMISSOES', 'Funções Militares'), ('SUBMENU_ORGAOS', 'Órgãos'), ('SUBMENU_ORGANOGRAMA', 'Organograma'), ('SUBMENU_LOGS', 'Logs do Sistema'), ('SUBMENU_TITULOS_PUBLICACAO', 'Títulos de Publicações'), ('SUBMENU_ADMINISTRACAO', 'Administração'), ('SUBMENU_GRANDES_COMANDOS', 'Grandes Comandos'), ('SUBMENU_UNIDADES', 'Unidades'), ('SUBMENU_SUB_UNIDADES', 'Sub-Unidades'), ('SUBMENU_RELATORIOS_MILITARES', 'Relatórios de Militares'), ('SUBMENU_RELATORIOS_PROMOCOES', 'Relatórios de Promoções'), ('SUBMENU_RELATORIOS_MEDALHAS', 'Relatórios de Medalhas'), ('SUBMENU_RELATORIOS_PUBLICACOES', 'Relatórios de Publicações'), ('SUBMENU_RELATORIOS_GERAIS', 'Relatórios Gerais'), ('ATIVOS_VISUALIZAR', 'Visualizar Militares Ativos'), ('ATIVOS_CRIAR', 'Criar Militares Ativos'), ('ATIVOS_EDITAR', 'Editar Militares Ativos'), ('ATIVOS_EXCLUIR', 'Excluir Militares Ativos'), ('ATIVOS_TRANSFERIR', 'Transferir Militares Ativos'), ('ATIVOS_PROMOVER', 'Promover Militares Ativos'), ('ATIVOS_INATIVAR', 'Inativar Militares Ativos'), ('ATIVOS_FICHA_CONCEITO', 'Gerenciar Fichas de Conceito'), ('ATIVOS_EXPORTAR', 'Exportar Militares Ativos'), ('ATIVOS_DASHBOARD', 'Dashboard Militares Ativos'), ('ATIVOS_REORDENAR', 'Reordenar Militares Ativos'), ('INATIVOS_VISUALIZAR', 'Visualizar Militares Inativos'), ('INATIVOS_EDITAR', 'Editar Militares Inativos'), ('INATIVOS_EXPORTAR', 'Exportar Militares Inativos'), ('LOTACOES_VISUALIZAR', 'Visualizar Lotações'), ('LOTACOES_CRIAR', 'Criar Lotações'), ('LOTACOES_EDITAR', 'Editar Lotações'), ('LOTACOES_EXCLUIR', 'Excluir Lotações'), ('INATIVOS_EDITAR', 'Editar Militares Inativos'), ('INATIVOS_EXCLUIR', 'Excluir Militares Inativos'), ('INATIVOS_REATIVAR', 'Reativar Militares Inativos'), ('LOTACOES_VISUALIZAR', 'Visualizar Lotações'), ('LOTACOES_CRIAR', 'Criar Lotações'), ('LOTACOES_EDITAR', 'Editar Lotações'), ('LOTACOES_EXCLUIR', 'Excluir Lotações'), ('DETAIL_FICHAS_CONCEITO', 'Visualizar Fichas de Conceito'), ('DETAIL_PUNICOES', 'Visualizar Punições e Elogios'), ('DETAIL_MEDALHAS', 'Visualizar Medalhas'), ('DETAIL_CONTATO', 'Visualizar Contato'), ('QUADROS_FIXACAO_VISUALIZAR', 'Visualizar Quadros de Fixação'), ('QUADROS_FIXACAO_CRIAR', 'Criar Quadros de Fixação'), ('QUADROS_FIXACAO_EDITAR', 'Editar Quadros de Fixação'), ('QUADROS_FIXACAO_EXCLUIR', 'Excluir Quadros de Fixação'), ('QUADROS_ACESSO_VISUALIZAR', 'Visualizar Quadros de Acesso'), ('QUADROS_ACESSO_CRIAR', 'Criar Quadros de Acesso'), ('QUADROS_ACESSO_EDITAR', 'Editar Quadros de Acesso'), ('QUADROS_ACESSO_EXCLUIR', 'Excluir Quadros de Acesso'), ('COMISSOES_OFICIAIS_VISUALIZAR', 'Visualizar Comissões de Oficiais'), ('COMISSOES_OFICIAIS_CRIAR', 'Criar Comissões de Oficiais'), ('COMISSOES_OFICIAIS_EDITAR', 'Editar Comissões de Oficiais'), ('COMISSOES_OFICIAIS_EXCLUIR', 'Excluir Comissões de Oficiais'), ('COMISSOES_PRACAS_VISUALIZAR', 'Visualizar Comissões de Praças'), ('COMISSOES_PRACAS_CRIAR', 'Criar Comissões de Praças'), ('COMISSOES_PRACAS_EDITAR', 'Editar Comissões de Praças'), ('COMISSOES_PRACAS_EXCLUIR', 'Excluir Comissões de Praças'), ('QUADROS_ACESSO_ASSINAR', 'Assinar Quadros de Acesso'), ('QUADROS_ACESSO_HOMOLOGAR', 'Homologar Quadros de Acesso'), ('QUADROS_ACESSO_DESHOMOLOGAR', 'Deshomologar Quadros de Acesso'), ('QUADROS_ACESSO_ELABORAR', 'Elaborar Quadros de Acesso'), ('QUADROS_ACESSO_REGENERAR', 'Regenerar Quadros de Acesso'), ('QUADROS_ACESSO_GERAR_PDF', 'Gerar PDF de Quadros de Acesso'), ('SUBMENU_MEDALHAS_CONCESSOES', 'Concessões de Medalhas'), ('SUBMENU_MEDALHAS_PROPOSTAS', 'Propostas de Medalhas'), ('SUBMENU_ELEGIVEIS', 'Elegíveis'), ('SUBMENU_PROPOSTAS', 'Propostas'), ('SUBMENU_NOTAS_LISTA', 'Lista de Notas'), ('SUBMENU_PUBLICACOES', 'Publicações'), ('SUBMENU_NOTAS', 'Notas'), ('NOTAS_VISUALIZAR', 'Visualizar Notas'), ('NOTAS_CRIAR', 'Criar Notas'), ('NOTAS_EDITAR', 'Editar Notas'), ('NOTAS_EXCLUIR', 'Excluir Notas'), ('NOTAS_REVISAR', 'Revisar Notas'), ('NOTAS_APROVAR', 'Aprovar Notas'), ('NOTAS_PUBLICAR', 'Publicar Notas'), ('NOTAS_ADMINISTRAR', 'Administrar Notas'), ('PUBLICACOES_VISUALIZAR', 'Visualizar Publicações'), ('PUBLICACOES_CRIAR', 'Criar Publicações'), ('PUBLICACOES_EDITAR', 'Editar Publicações'), ('PUBLICACOES_EXCLUIR', 'Excluir Publicações'), ('PUBLICACOES_PUBLICAR', 'Publicar Publicações'), ('SUBMENU_INTERSTICIOS', 'Interstícios'), ('SUBMENU_GERENCIAR_INTERSTICIOS', 'Gerenciar Interstícios'), ('SUBMENU_GERENCIAR_PREVISAO', 'Gerenciar Previsão'), ('SUBMENU_USUARIOS', 'Usuários'), ('SUBMENU_PERMISSOES', 'Permissões'), ('SUBMENU_LOGS', 'Logs'), ('SUBMENU_ADMINISTRACAO', 'Administração'), ('SUBMENU_PLANEJADAS', 'Operações Planejadas'), ('SUBMENU_OPERADOR_PLANEJADAS', 'Operador de Planejadas'), ('SUBMENU_FISCAL_PLANEJADAS', 'Fiscal de Planejadas'), ('SUBMENU_LIQUIDACAO', 'Liquidação'), ('PLANEJADAS_VISUALIZAR', 'Visualizar Planejadas'), ('PLANEJADAS_CRIAR', 'Criar Planejadas'), ('PLANEJADAS_EDITAR', 'Editar Planejadas'), ('PLANEJADAS_EXCLUIR', 'Excluir Planejadas'), ('PLANEJADAS_ADICIONAR_MILITAR', 'Adicionar Militar à Planejada'), ('PLANEJADAS_REMOVER_MILITAR', 'Remover Militar da Planejada'), ('PLANEJADAS_ASSINAR_OPERADOR', 'Assinar como Operador'), ('PLANEJADAS_ASSINAR_FISCAL', 'Assinar como Fiscal'), ('ORCAMENTOS_PLANEJADAS_VISUALIZAR', 'Visualizar Orçamentos de Planejadas'), ('ORCAMENTOS_PLANEJADAS_CRIAR', 'Criar Orçamentos de Planejadas'), ('ORCAMENTOS_PLANEJADAS_EDITAR', 'Editar Orçamentos de Planejadas'), ('ORCAMENTOS_PLANEJADAS_EXCLUIR', 'Excluir Orçamentos de Planejadas'), ('ORCAMENTOS_PLANEJADAS_DISTRIBUIR', 'Distribuir Orçamentos'), ('ORCAMENTOS_PLANEJADAS_APROVAR', 'Aprovar Orçamentos'), ('VIATURAS', 'Viaturas'), ('ARMAS', 'Armas'), ('PUBLICACOES', 'Publicações'), ('ELOGIOS', 'Elogios'), ('PUNICOES', 'Punições'), ('FICHAS_CONCEITO', 'Fichas de Conceito'), ('QUADROS_FIXACAO', 'Quadros de Fixação'), ('QUADROS_ACESSO', 'Quadros de Acesso'), ('COMISSOES', 'Comissões'), ('ESCALAS', 'Escalas de Serviço'), ('NOTAS', 'Notas'), ('BOLETINS_OSTENSIVOS', 'Boletins Ostensivos'), ('BOLETINS_RESERVADOS', 'Boletins Reservados'), ('BOLETINS_ESPECIAIS', 'Boletins Especiais'), ('AVISOS', 'Avisos'), ('ORDENS_SERVICO', 'Ordens de Serviço'), ('MEDALHAS', 'Medalhas'), ('USUARIOS', 'Usuários'), ('RELATORIOS', 'Relatórios'), ('PLANEJADAS', 'Operações Planejadas'), ('ORCAMENTOS_PLANEJADAS', 'Orçamentos de Planejadas'), ('AFASTAMENTOS', 'Afastamentos'), ('MILITARES', 'Militares'), ('ATIVOS', 'Militares Ativos'), ('INATIVOS', 'Militares Inativos'), ('LOTACOES', 'Lotações'), ('ALMOXARIFADO', 'Almoxarifado'), ('SUBMENU_ALMOXARIFADO_ITENS', 'Itens do Almoxarifado'), ('SUBMENU_ALMOXARIFADO_ENTRADAS', 'Entradas do Almoxarifado'), ('SUBMENU_ALMOXARIFADO_SAIDAS', 'Saídas do Almoxarifado')], max_length=50, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='saidaalmoxarifado',
            name='tipo_saida',
            field=models.CharField(choices=[('CONSUMO', 'Consumo'), ('TRANSFERENCIA', 'Transferência'), ('BAIXA', 'Baixa'), ('AJUSTE', 'Ajuste de Estoque'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Saída'),
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifado',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_almoxarifado_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifado',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_almoxarifado_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifado',
            name='grande_comando_requisitada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_almoxarifado_requisitada', to='militares.grandecomando', verbose_name='Grande Comando Requisitada'),
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifado',
            name='grande_comando_requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_almoxarifado_requisitante', to='militares.grandecomando', verbose_name='Grande Comando Requisitante'),
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifado',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='militares.itemalmoxarifado', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifado',
            name='orgao_requisitada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_almoxarifado_requisitada', to='militares.orgao', verbose_name='Órgão Requisitada'),
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifado',
            name='orgao_requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_almoxarifado_requisitante', to='militares.orgao', verbose_name='Órgão Requisitante'),
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifado',
            name='sub_unidade_requisitada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_almoxarifado_requisitada', to='militares.subunidade', verbose_name='Subunidade Requisitada'),
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifado',
            name='sub_unidade_requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_almoxarifado_requisitante', to='militares.subunidade', verbose_name='Subunidade Requisitante'),
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifado',
            name='transferencia_criada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicao_origem', to='militares.saidaalmoxarifado', verbose_name='Transferência Criada'),
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifado',
            name='unidade_requisitada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_almoxarifado_requisitada', to='militares.unidade', verbose_name='Unidade Requisitada'),
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifado',
            name='unidade_requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_almoxarifado_requisitante', to='militares.unidade', verbose_name='Unidade Requisitante'),
        ),
        migrations.AddIndex(
            model_name='requisicaoalmoxarifado',
            index=models.Index(fields=['status', '-data_requisicao'], name='militares_r_status_c3070b_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaoalmoxarifado',
            index=models.Index(fields=['unidade_requisitante', 'status'], name='militares_r_unidade_b71ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicaoalmoxarifado',
            index=models.Index(fields=['unidade_requisitada', 'status'], name='militares_r_unidade_005c64_idx'),
        ),
    ]
