# Generated by Django 5.2.3 on 2025-11-10 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0354_remove_escalaservico_unique_escala_data_org_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaRequisicaoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assinatura', models.DateTimeField(auto_now_add=True, verbose_name='Data da Assinatura')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações da Assinatura')),
                ('tipo_assinatura', models.CharField(choices=[('SOLICITANTE', 'Solicitante'), ('APROVACAO', 'Aprovação'), ('NEGACAO', 'Negação'), ('OUTROS', 'Outros')], default='SOLICITANTE', max_length=20, verbose_name='Tipo de Assinatura')),
                ('funcao_assinatura', models.CharField(blank=True, help_text='Função/cargo do usuário no momento da assinatura', max_length=200, null=True, verbose_name='Função no momento da assinatura')),
            ],
            options={
                'verbose_name': 'Assinatura de Requisição de Almoxarifado',
                'verbose_name_plural': 'Assinaturas de Requisições de Almoxarifado',
                'ordering': ['-data_assinatura'],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE militares_escalaservico DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Adicionar colunas apenas se não existirem (já podem ter sido adicionadas na migração 0350)
        migrations.RunSQL(
            sql=""" 
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_criar_ficha_conceito_oficial') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_criar_ficha_conceito_oficial BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_criar_ficha_conceito_praca') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_criar_ficha_conceito_praca BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_grandes_comandos') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_grandes_comandos BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_minha_ficha_cadastro') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_minha_ficha_cadastro BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_minha_ficha_conceito_oficial') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_minha_ficha_conceito_oficial BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_minha_ficha_conceito_praca') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_minha_ficha_conceito_praca BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_minhas_informacoes') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_minhas_informacoes BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_organograma') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_organograma BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_orgaos') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_orgaos BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_pessoal') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_pessoal BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_gerais') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_gerais BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_medalhas') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_medalhas BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_militares') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_militares BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_promocoes') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_promocoes BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_publicacoes') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_publicacoes BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_sub_unidades') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_sub_unidades BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_unidades') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_unidades BOOLEAN DEFAULT FALSE;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='assinaturarequisicaoalmoxarifado',
            name='assinado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Assinado por'),
        ),
        migrations.AddField(
            model_name='assinaturarequisicaoalmoxarifado',
            name='militar',
            field=models.ForeignKey(blank=True, help_text='Militar que assina a requisição', null=True, on_delete=django.db.models.deletion.SET_NULL, to='militares.militar', verbose_name='Militar'),
        ),
        migrations.AddField(
            model_name='assinaturarequisicaoalmoxarifado',
            name='requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='militares.requisicaoalmoxarifado', verbose_name='Requisição de Almoxarifado'),
        ),
        migrations.AlterUniqueTogether(
            name='assinaturarequisicaoalmoxarifado',
            unique_together={('requisicao', 'tipo_assinatura')},
        ),
    ]
