# Generated by Django 5.2.3 on 2025-11-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0356_assinaturaentradaalmoxarifado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemalmoxarifado',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='itens_almoxarifado', to='militares.orgao', verbose_name='Órgão'),
        ),
        migrations.AddField(
            model_name='itemalmoxarifado',
            name='grande_comando',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='itens_almoxarifado', to='militares.grandecomando', verbose_name='Grande Comando'),
        ),
        migrations.AddField(
            model_name='itemalmoxarifado',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='itens_almoxarifado', to='militares.unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='itemalmoxarifado',
            name='sub_unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='itens_almoxarifado', to='militares.subunidade', verbose_name='Sub-Unidade'),
        ),
    ]
