# Generated by Django 5.0.2 on 2025-11-11 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0357_adicionar_om_item_almoxarifado"),
    ]

    operations = [
        migrations.AddField(
            model_name="entradaalmoxarifado",
            name="grande_comando_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entradas_almoxarifado_destino",
                to="militares.grandecomando",
                verbose_name="Grande Comando de Destino",
            ),
        ),
        migrations.AddField(
            model_name="entradaalmoxarifado",
            name="orgao_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entradas_almoxarifado_destino",
                to="militares.orgao",
                verbose_name="Órgão de Destino",
            ),
        ),
        migrations.AddField(
            model_name="entradaalmoxarifado",
            name="sub_unidade_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entradas_almoxarifado_destino",
                to="militares.subunidade",
                verbose_name="Sub-Unidade de Destino",
            ),
        ),
        migrations.AddField(
            model_name="entradaalmoxarifado",
            name="unidade_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entradas_almoxarifado_destino",
                to="militares.unidade",
                verbose_name="Unidade de Destino",
            ),
        ),
        migrations.AddField(
            model_name="saidaalmoxarifado",
            name="grande_comando_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saidas_almoxarifado_origem",
                to="militares.grandecomando",
                verbose_name="Grande Comando de Origem",
            ),
        ),
        migrations.AddField(
            model_name="saidaalmoxarifado",
            name="orgao_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saidas_almoxarifado_origem",
                to="militares.orgao",
                verbose_name="Órgão de Origem",
            ),
        ),
        migrations.AddField(
            model_name="saidaalmoxarifado",
            name="sub_unidade_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saidas_almoxarifado_origem",
                to="militares.subunidade",
                verbose_name="Sub-Unidade de Origem",
            ),
        ),
        migrations.AddField(
            model_name="saidaalmoxarifado",
            name="unidade_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saidas_almoxarifado_origem",
                to="militares.unidade",
                verbose_name="Unidade de Origem",
            ),
        ),
    ]
