# Generated by Django 5.0.2 on 2025-11-11 11:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0358_adicionar_om_origem_destino_almoxarifado"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemAlmoxarifadoTamanho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        help_text="Ex: 35, 36, 37, P, M, G, GG, etc.",
                        max_length=20,
                        verbose_name="Tamanho",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tamanhos",
                        to="militares.itemalmoxarifado",
                        verbose_name="Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tamanho do Item",
                "verbose_name_plural": "Tamanhos dos Itens",
                "ordering": ["item", "tamanho"],
                "unique_together": {("item", "tamanho")},
            },
        ),
    ]
