# Generated by Django 5.0.2 on 2025-11-11 12:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0360_adicionar_tamanhos_requisicao"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntradaAlmoxarifadoTamanho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        help_text="Ex: 35, 36, 37, P, M, G, GG, etc.",
                        max_length=20,
                        verbose_name="Tamanho",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tamanhos",
                        to="militares.entradaalmoxarifado",
                        verbose_name="Entrada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tamanho da Entrada",
                "verbose_name_plural": "Tamanhos das Entradas",
                "ordering": ["entrada", "tamanho"],
            },
        ),
        migrations.CreateModel(
            name="SaidaAlmoxarifadoTamanho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        help_text="Ex: 35, 36, 37, P, M, G, GG, etc.",
                        max_length=20,
                        verbose_name="Tamanho",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "saida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tamanhos",
                        to="militares.saidaalmoxarifado",
                        verbose_name="Saída",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tamanho da Saída",
                "verbose_name_plural": "Tamanhos das Saídas",
                "ordering": ["saida", "tamanho"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="entradaalmoxarifadotamanho",
            unique_together={("entrada", "tamanho")},
        ),
        migrations.AlterUniqueTogether(
            name="saidaalmoxarifadotamanho",
            unique_together={("saida", "tamanho")},
        ),
    ]
