# Generated by Django 5.0.2 on 2025-11-11 12:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def remove_constraint_if_exists(apps, schema_editor):
    """Remove uma constraint apenas se ela existir"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT constraint_name 
            FROM information_schema.table_constraints 
            WHERE table_name = 'militares_escalaservico' 
            AND constraint_name = 'unique_escala_data_org_tipo'
            AND constraint_type IN ('UNIQUE', 'PRIMARY KEY', 'FOREIGN KEY', 'CHECK')
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE militares_escalaservico DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;")


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0361_adicionar_tamanhos_entrada_saida"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntradaAlmoxarifadoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Unitário (R$)",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Total (R$)",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Entrada",
                "verbose_name_plural": "Itens da Entrada",
                "ordering": ["entrada", "item"],
            },
        ),
        migrations.CreateModel(
            name="RequisicaoAlmoxarifadoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Requisição",
                "verbose_name_plural": "Itens da Requisição",
                "ordering": ["requisicao", "item"],
            },
        ),
        migrations.CreateModel(
            name="SaidaAlmoxarifadoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Saída",
                "verbose_name_plural": "Itens da Saída",
                "ordering": ["saida", "item"],
            },
        ),
        migrations.AlterModelOptions(
            name="entradaalmoxarifadotamanho",
            options={
                "ordering": ["entrada_item", "tamanho"],
                "verbose_name": "Tamanho da Entrada",
                "verbose_name_plural": "Tamanhos das Entradas",
            },
        ),
        migrations.AlterModelOptions(
            name="requisicaoalmoxarifadotamanho",
            options={
                "ordering": ["requisicao_item", "tamanho"],
                "verbose_name": "Tamanho da Requisição",
                "verbose_name_plural": "Tamanhos das Requisições",
            },
        ),
        migrations.AlterModelOptions(
            name="saidaalmoxarifadotamanho",
            options={
                "ordering": ["saida_item", "tamanho"],
                "verbose_name": "Tamanho da Saída",
                "verbose_name_plural": "Tamanhos das Saídas",
            },
        ),
        migrations.RunPython(
            remove_constraint_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),
        # Adicionar colunas apenas se não existirem (já podem ter sido adicionadas em migrações anteriores)
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_criar_ficha_conceito_oficial') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_criar_ficha_conceito_oficial BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_criar_ficha_conceito_praca') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_criar_ficha_conceito_praca BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_grandes_comandos') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_grandes_comandos BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_minha_ficha_cadastro') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_minha_ficha_cadastro BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_minha_ficha_conceito_oficial') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_minha_ficha_conceito_oficial BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_minha_ficha_conceito_praca') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_minha_ficha_conceito_praca BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_minhas_informacoes') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_minhas_informacoes BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_organograma') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_organograma BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_orgaos') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_orgaos BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_pessoal') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_pessoal BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_gerais') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_gerais BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_medalhas') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_medalhas BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_militares') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_militares BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_promocoes') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_promocoes BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_relatorios_publicacoes') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_relatorios_publicacoes BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_sub_unidades') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_sub_unidades BOOLEAN DEFAULT FALSE;
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' 
                                   AND column_name='show_unidades') THEN
                        ALTER TABLE militares_funcaomenuconfig 
                        ADD COLUMN show_unidades BOOLEAN DEFAULT FALSE;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="entradaalmoxarifado",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entradas",
                to="militares.itemalmoxarifado",
                verbose_name="Item (Legado)",
            ),
        ),
        migrations.AlterField(
            model_name="entradaalmoxarifado",
            name="quantidade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Quantidade (Legado)",
            ),
        ),
        migrations.AlterField(
            model_name="requisicaoalmoxarifado",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requisicoes",
                to="militares.itemalmoxarifado",
                verbose_name="Item (Legado)",
            ),
        ),
        migrations.AlterField(
            model_name="requisicaoalmoxarifado",
            name="quantidade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Quantidade (Legado)",
            ),
        ),
        migrations.AlterField(
            model_name="saidaalmoxarifado",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saidas",
                to="militares.itemalmoxarifado",
                verbose_name="Item (Legado)",
            ),
        ),
        migrations.AlterField(
            model_name="saidaalmoxarifado",
            name="quantidade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Quantidade (Legado)",
            ),
        ),
        migrations.AddField(
            model_name="entradaalmoxarifadoitem",
            name="entrada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens_entrada",
                to="militares.entradaalmoxarifado",
                verbose_name="Entrada",
            ),
        ),
        migrations.AddField(
            model_name="entradaalmoxarifadoitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entradas_itens",
                to="militares.itemalmoxarifado",
                verbose_name="Item",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entradaalmoxarifadotamanho",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="entradaalmoxarifadotamanho",
            name="entrada_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tamanhos",
                to="militares.entradaalmoxarifadoitem",
                verbose_name="Item da Entrada",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entradaalmoxarifadotamanho",
            unique_together={("entrada_item", "tamanho")},
        ),
        migrations.AddField(
            model_name="requisicaoalmoxarifadoitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisicoes_itens",
                to="militares.itemalmoxarifado",
                verbose_name="Item",
            ),
        ),
        migrations.AddField(
            model_name="requisicaoalmoxarifadoitem",
            name="requisicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens_requisicao",
                to="militares.requisicaoalmoxarifado",
                verbose_name="Requisição",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requisicaoalmoxarifadotamanho",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="requisicaoalmoxarifadotamanho",
            name="requisicao_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tamanhos",
                to="militares.requisicaoalmoxarifadoitem",
                verbose_name="Item da Requisição",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requisicaoalmoxarifadotamanho",
            unique_together={("requisicao_item", "tamanho")},
        ),
        migrations.AddField(
            model_name="saidaalmoxarifadoitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saidas_itens",
                to="militares.itemalmoxarifado",
                verbose_name="Item",
            ),
        ),
        migrations.AddField(
            model_name="saidaalmoxarifadoitem",
            name="saida",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens_saida",
                to="militares.saidaalmoxarifado",
                verbose_name="Saída",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="saidaalmoxarifadotamanho",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="saidaalmoxarifadotamanho",
            name="saida_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tamanhos",
                to="militares.saidaalmoxarifadoitem",
                verbose_name="Item da Saída",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="saidaalmoxarifadotamanho",
            unique_together={("saida_item", "tamanho")},
        ),
        migrations.AlterUniqueTogether(
            name="entradaalmoxarifadoitem",
            unique_together={("entrada", "item")},
        ),
        migrations.RemoveField(
            model_name="entradaalmoxarifadotamanho",
            name="entrada",
        ),
        migrations.AlterUniqueTogether(
            name="requisicaoalmoxarifadoitem",
            unique_together={("requisicao", "item")},
        ),
        migrations.RemoveField(
            model_name="requisicaoalmoxarifadotamanho",
            name="requisicao",
        ),
        migrations.AlterUniqueTogether(
            name="saidaalmoxarifadoitem",
            unique_together={("saida", "item")},
        ),
        migrations.RemoveField(
            model_name="saidaalmoxarifadotamanho",
            name="saida",
        ),
    ]
