# Generated by Django 5.0.2 on 2025-11-11 14:48

from django.db import migrations


def remove_constraint_if_exists(apps, schema_editor):
    """Remove a constraint apenas se ela existir"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT constraint_name 
            FROM information_schema.table_constraints 
            WHERE table_name = 'militares_escalaservico' 
            AND constraint_name = 'unique_escala_data_org_tipo'
        """)
        if cursor.fetchone():
            cursor.execute("""
                ALTER TABLE militares_escalaservico 
                DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo
            """)


def reverse_remove_constraint(apps, schema_editor):
    """Reverter a remoção da constraint (não faz nada pois não sabemos os detalhes originais)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "militares",
            "0362_entradaalmoxarifadoitem_requisicaoalmoxarifadoitem_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            remove_constraint_if_exists,
            reverse_remove_constraint
        ),
    ]
