# Generated by Django 5.0.2 on 2025-11-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0363_alterar_quantidade_requisicao_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisicaoalmoxarifado",
            name="quantidade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Quantidade (Legado)",
            ),
        ),
    ]
