# Generated by Django 5.0.2 on 2025-11-11 15:02

from django.db import migrations


def alterar_quantidade_para_null(apps, schema_editor):
    """Altera o campo quantidade para permitir NULL no banco de dados"""
    with schema_editor.connection.cursor() as cursor:
        # Verificar se a coluna já permite NULL
        cursor.execute("""
            SELECT is_nullable 
            FROM information_schema.columns 
            WHERE table_name = 'militares_requisicaoalmoxarifado' 
            AND column_name = 'quantidade'
        """)
        result = cursor.fetchone()
        
        # Se a coluna não permite NULL, alterar
        if result and result[0] == 'NO':
            cursor.execute("""
                ALTER TABLE militares_requisicaoalmoxarifado 
                ALTER COLUMN quantidade DROP NOT NULL
            """)


def reverse_alterar_quantidade(apps, schema_editor):
    """Reverter a alteração"""
    with schema_editor.connection.cursor() as cursor:
        # Primeiro, atualizar todos os NULL para 0
        cursor.execute("""
            UPDATE militares_requisicaoalmoxarifado 
            SET quantidade = 0 
            WHERE quantidade IS NULL
        """)
        # Depois, adicionar NOT NULL
        cursor.execute("""
            ALTER TABLE militares_requisicaoalmoxarifado 
            ALTER COLUMN quantidade SET NOT NULL
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0365_corrigir_quantidade_null"),
    ]

    operations = [
        migrations.RunPython(
            alterar_quantidade_para_null,
            reverse_alterar_quantidade
        ),
    ]
