# Generated by Django 5.0.2 on 2025-11-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0366_corrigir_quantidade_null_requisicao"),
    ]

    operations = [
        migrations.AddField(
            model_name='itemalmoxarifado',
            name='tamanho',
            field=models.CharField(
                blank=True,
                help_text='Tamanho ou numeração do item (ex: 35, 36, 37, P, M, G, GG, etc.). Cada tamanho diferente é um item individual no estoque.',
                max_length=20,
                null=True,
                verbose_name='Tamanho/Numeração'
            ),
        ),
    ]

