# Generated by Django 5.2.3 on 2025-11-11 20:30

from django.db import migrations, models


def add_quantidade_inicial_if_not_exists(apps, schema_editor):
    """Adiciona o campo quantidade_inicial apenas se ele não existir"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Verificar se a coluna já existe
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'militares_itemalmoxarifado' 
            AND column_name = 'quantidade_inicial'
        """)
        if not cursor.fetchone():
            # Se não existe, adicionar a coluna
            cursor.execute("""
                ALTER TABLE militares_itemalmoxarifado 
                ADD COLUMN quantidade_inicial NUMERIC(10, 2) DEFAULT 0 NOT NULL;
            """)


def remove_quantidade_inicial_if_exists(apps, schema_editor):
    """Remove o campo quantidade_inicial se ele existir (para rollback)"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Verificar se a coluna existe
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'militares_itemalmoxarifado' 
            AND column_name = 'quantidade_inicial'
        """)
        if cursor.fetchone():
            # Se existe, remover a coluna
            cursor.execute("""
                ALTER TABLE militares_itemalmoxarifado 
                DROP COLUMN IF EXISTS quantidade_inicial;
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0367_adicionar_campo_tamanho_item_almoxarifado'),
    ]

    operations = [
        migrations.RunPython(
            add_quantidade_inicial_if_not_exists,
            reverse_code=remove_quantidade_inicial_if_exists,
        ),
        # AlterField apenas atualiza o help_text no modelo, não altera o banco
        migrations.AlterField(
            model_name='itemalmoxarifado',
            name='quantidade_atual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantidade atual em estoque (calculada automaticamente: inicial + entradas - saídas)', max_digits=10, verbose_name='Quantidade Atual'),
        ),
    ]
