# Generated by Django 5.2.3 on 2025-11-11 20:35

from django.db import migrations


def remove_constraint_if_exists(apps, schema_editor):
    """Remove a constraint apenas se ela existir"""
    with schema_editor.connection.cursor() as cursor:
        # Verificar se a constraint existe
        cursor.execute("""
            SELECT constraint_name 
            FROM information_schema.table_constraints 
            WHERE table_name = 'militares_escalaservico' 
            AND constraint_name = 'unique_escala_data_org_tipo'
            AND constraint_type IN ('UNIQUE', 'PRIMARY KEY', 'FOREIGN KEY', 'CHECK')
        """)
        if cursor.fetchone():
            # Se existe, remover a constraint
            cursor.execute("""
                ALTER TABLE militares_escalaservico 
                DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;
            """)


def add_constraint_if_not_exists(apps, schema_editor):
    """Adiciona a constraint de volta se não existir (para rollback)"""
    # Esta função pode ser implementada se necessário para rollback
    # Por enquanto, deixamos vazia pois não precisamos do rollback
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0368_adicionar_quantidade_inicial_item_almoxarifado'),
    ]

    operations = [
        migrations.RunPython(
            remove_constraint_if_exists,
            reverse_code=add_constraint_if_not_exists,
        ),
    ]
