# Generated by Django 5.2.3 on 2025-11-11 22:57

from django.db import migrations, models


def remove_constraint_safely(apps, schema_editor):
    """Remove a constraint apenas se ela existir"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT constraint_name 
            FROM information_schema.table_constraints 
            WHERE table_name = 'militares_escalaservico' 
            AND constraint_name = 'unique_escala_data_org_tipo'
            AND constraint_type IN ('UNIQUE', 'PRIMARY KEY', 'FOREIGN KEY', 'CHECK')
        """)
        if cursor.fetchone():
            cursor.execute("""
                ALTER TABLE militares_escalaservico 
                DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;
            """)


def add_field_if_not_exists(apps, schema_editor):
    """Adiciona campos apenas se não existirem"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Verificar e adicionar campos de funcaomenuconfig se não existirem
        campos_funcao = [
            'show_criar_ficha_conceito_oficial',
            'show_criar_ficha_conceito_praca',
            'show_grandes_comandos',
            'show_minha_ficha_cadastro',
            'show_minha_ficha_conceito_oficial',
            'show_minha_ficha_conceito_praca',
            'show_minhas_informacoes',
            'show_organograma',
            'show_orgaos',
            'show_pessoal',
            'show_relatorios',
            'show_relatorios_gerais',
            'show_relatorios_medalhas',
            'show_relatorios_militares',
            'show_relatorios_promocoes',
            'show_relatorios_publicacoes',
            'show_sub_unidades',
            'show_unidades',
        ]
        
        for campo in campos_funcao:
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = 'militares_funcaomenuconfig' 
                AND column_name = %s
            """, [campo])
            if not cursor.fetchone():
                # Usar SQL parametrizado de forma segura
                cursor.execute("""
                    ALTER TABLE militares_funcaomenuconfig 
                    ADD COLUMN {} BOOLEAN NOT NULL DEFAULT FALSE;
                """.format(campo))
        
        # Verificar e adicionar quantidade_inicial em itemalmoxarifado se não existir
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'militares_itemalmoxarifado' 
            AND column_name = 'quantidade_inicial'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE militares_itemalmoxarifado 
                ADD COLUMN quantidade_inicial NUMERIC(10, 2) NOT NULL DEFAULT 0;
            """)
        
        # Verificar e adicionar campos de entradaalmoxarifado se não existirem
        campos_entrada = [
            ('cnpj_fornecedor', 'VARCHAR(18)'),
            ('endereco_fornecedor', 'TEXT'),
            ('numero_convenio', 'VARCHAR(100)'),
            ('numero_processo', 'VARCHAR(100)'),
        ]
        
        for campo, tipo in campos_entrada:
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = 'militares_entradaalmoxarifado' 
                AND column_name = %s
            """, [campo])
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE militares_entradaalmoxarifado 
                    ADD COLUMN {} {} NULL;
                """.format(campo, tipo))


def reverse_add_field(apps, schema_editor):
    """Função reversa"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0369_remove_escalaservico_unique_escala_data_org_tipo'),
    ]

    operations = [
        # Remover constraint de forma segura ANTES de qualquer operação automática do Django
        migrations.RunPython(
            remove_constraint_safely,
            reverse_code=migrations.RunPython.noop,
        ),
        # Forçar o Django a atualizar o estado do modelo EscalaServico
        # Isso evita que o Django tente remover a constraint automaticamente
        migrations.AlterModelOptions(
            name='escalaservico',
            options={'verbose_name': 'Escala de Serviço', 'verbose_name_plural': 'Escalas de Serviço', 'ordering': ['-data', 'organizacao', 'hora_inicio']},
        ),
        # Adicionar campos de funcaomenuconfig de forma segura
        migrations.RunPython(
            add_field_if_not_exists,
            reverse_code=reverse_add_field,
        ),
        migrations.AlterUniqueTogether(
            name='entradaalmoxarifadotamanho',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='entradaalmoxarifadotamanho',
            name='entrada_item',
        ),
        migrations.AlterUniqueTogether(
            name='itemalmoxarifadotamanho',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itemalmoxarifadotamanho',
            name='item',
        ),
        migrations.AlterUniqueTogether(
            name='requisicaoalmoxarifadotamanho',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='requisicaoalmoxarifadotamanho',
            name='requisicao_item',
        ),
        migrations.AlterUniqueTogether(
            name='saidaalmoxarifadotamanho',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='saidaalmoxarifadotamanho',
            name='saida_item',
        ),
        migrations.RemoveField(
            model_name='entradaalmoxarifado',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='entradaalmoxarifado',
            name='valor_unitario',
        ),
        migrations.RemoveField(
            model_name='entradaalmoxarifadoitem',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='entradaalmoxarifadoitem',
            name='valor_unitario',
        ),
        # Campos de entradaalmoxarifado são adicionados pela função add_field_if_not_exists acima
        # Campos de funcaomenuconfig e quantidade_inicial são adicionados pela função add_field_if_not_exists acima
        migrations.DeleteModel(
            name='EntradaAlmoxarifadoTamanho',
        ),
        migrations.DeleteModel(
            name='ItemAlmoxarifadoTamanho',
        ),
        migrations.DeleteModel(
            name='RequisicaoAlmoxarifadoTamanho',
        ),
        migrations.DeleteModel(
            name='SaidaAlmoxarifadoTamanho',
        ),
    ]
