# Generated by Django 5.2.3 on 2025-11-12 00:18

import django.db.models.deletion
import militares.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0370_adicionar_campos_fornecedor_doacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEntradaAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOTA_FISCAL', 'Nota Fiscal'), ('CONTRATO', 'Contrato'), ('CONVENIO', 'Convênio'), ('PROCESSO', 'Processo'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Documento')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Documento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to=militares.models.documento_entrada_almoxarifado_upload_path, verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
            ],
            options={
                'verbose_name': 'Documento da Entrada',
                'verbose_name_plural': 'Documentos da Entrada',
                'ordering': ['-data_upload', 'tipo'],
            },
        ),
        migrations.AddField(
            model_name='documentoentradaalmoxarifado',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='militares.entradaalmoxarifado', verbose_name='Entrada'),
        ),
        migrations.AddField(
            model_name='documentoentradaalmoxarifado',
            name='upload_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Upload por'),
        ),
    ]
