# Generated by Django 5.2.3 on 2025-11-12 00:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0371_adicionar_documento_entrada_almoxarifado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único do equipamento', max_length=50, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('BOMBA', 'Bomba de Incêndio'), ('MOTOBOMBA', 'Motobomba'), ('GERADOR', 'Gerador'), ('COMPRESSOR', 'Compressor de Ar'), ('SOLDADURA', 'Equipamento de Soldadura'), ('CORTE', 'Equipamento de Corte'), ('RESGATE', 'Equipamento de Resgate'), ('COMUNICACAO', 'Equipamento de Comunicação'), ('ILUMINACAO', 'Equipamento de Iluminação'), ('VENTILACAO', 'Equipamento de Ventilação'), ('DETECCAO', 'Equipamento de Detecção'), ('PROTECAO', 'Equipamento de Proteção'), ('FERRAMENTA', 'Ferramenta Especializada'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Equipamento')),
                ('marca', models.CharField(help_text='Ex: Honda, Yamaha, Briggs & Stratton', max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Ex: GX390, GX200, etc.', max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série')),
                ('ano_fabricacao', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano de Fabricação')),
                ('horas_uso', models.DecimalField(decimal_places=2, default=0, help_text='Total de horas de uso do equipamento', max_digits=10, verbose_name='Horas de Uso')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em Uso'), ('MANUTENCAO', 'Em Manutenção'), ('BAIXA', 'Dado de Baixa')], default='DISPONIVEL', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor de Aquisição (R$)')),
                ('fornecedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fornecedor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Equipamento Operacional',
                'verbose_name_plural': 'Equipamentos Operacionais',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAlteracaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('campo_alterado', models.CharField(max_length=100, verbose_name='Campo Alterado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_novo', models.TextField(blank=True, null=True, verbose_name='Valor Novo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Histórico de Alteração de Equipamento',
                'verbose_name_plural': 'Históricos de Alterações de Equipamentos',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='TempoUsoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('hora_inicio', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Hora de Fim')),
                ('horas_inicial', models.DecimalField(decimal_places=2, help_text='Horas de uso do equipamento no início', max_digits=10, verbose_name='Horas Inicial')),
                ('horas_final', models.DecimalField(blank=True, decimal_places=2, help_text='Horas de uso do equipamento no fim', max_digits=10, null=True, verbose_name='Horas Final')),
                ('horas_usadas', models.DecimalField(decimal_places=2, default=0, help_text='Calculado automaticamente', max_digits=10, verbose_name='Horas Usadas')),
                ('objetivo', models.CharField(choices=[('OPERACAO', 'Operação'), ('TREINAMENTO', 'Treinamento'), ('MANUTENCAO', 'Manutenção'), ('TESTE', 'Teste'), ('DEMONSTRACAO', 'Demonstração'), ('OUTROS', 'Outros')], default='OPERACAO', max_length=20, verbose_name='Objetivo')),
                ('local_uso', models.CharField(blank=True, help_text='Local onde o equipamento foi utilizado', max_length=200, null=True, verbose_name='Local de Uso')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Tempo de Uso de Equipamento',
                'verbose_name_plural': 'Tempos de Uso de Equipamentos',
                'ordering': ['-data_inicio', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transferencia', models.DateTimeField(auto_now_add=True, verbose_name='Data da Transferência')),
                ('justificativa', models.TextField(help_text='Motivo da transferência', verbose_name='Justificativa')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Transferência de Equipamento',
                'verbose_name_plural': 'Transferências de Equipamentos',
                'ordering': ['-data_transferencia'],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE militares_escalaservico DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Campos de entradaalmoxarifado, funcaomenuconfig e itemalmoxarifado já foram adicionados na migration 0370
        # Não adicionar novamente para evitar erro de coluna duplicada
        migrations.AddField(
            model_name='equipamentooperacional',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_operacionais_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='equipamentooperacional',
            name='grande_comando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='militares.grandecomando', verbose_name='Grande Comando'),
        ),
        migrations.AddField(
            model_name='equipamentooperacional',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='militares.orgao', verbose_name='Órgão'),
        ),
        migrations.AddField(
            model_name='equipamentooperacional',
            name='sub_unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='militares.subunidade', verbose_name='Sub-Unidade'),
        ),
        migrations.AddField(
            model_name='equipamentooperacional',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='militares.unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='historicoalteracaoequipamento',
            name='alterado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_equipamentos', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='historicoalteracaoequipamento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_alteracoes', to='militares.equipamentooperacional', verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='tempousoequipamento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tempos_uso_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='tempousoequipamento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempos_uso', to='militares.equipamentooperacional', verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='tempousoequipamento',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tempos_uso_operador', to='militares.militar', verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='transferenciaequipamento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='militares.equipamentooperacional', verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='transferenciaequipamento',
            name='grande_comando_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_equipamentos_destino', to='militares.grandecomando', verbose_name='Grande Comando de Destino'),
        ),
        migrations.AddField(
            model_name='transferenciaequipamento',
            name='grande_comando_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_equipamentos_origem', to='militares.grandecomando', verbose_name='Grande Comando de Origem'),
        ),
        migrations.AddField(
            model_name='transferenciaequipamento',
            name='orgao_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_equipamentos_destino', to='militares.orgao', verbose_name='Órgão de Destino'),
        ),
        migrations.AddField(
            model_name='transferenciaequipamento',
            name='orgao_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_equipamentos_origem', to='militares.orgao', verbose_name='Órgão de Origem'),
        ),
        migrations.AddField(
            model_name='transferenciaequipamento',
            name='sub_unidade_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_equipamentos_destino', to='militares.subunidade', verbose_name='Sub-Unidade de Destino'),
        ),
        migrations.AddField(
            model_name='transferenciaequipamento',
            name='sub_unidade_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_equipamentos_origem', to='militares.subunidade', verbose_name='Sub-Unidade de Origem'),
        ),
        migrations.AddField(
            model_name='transferenciaequipamento',
            name='transferido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_equipamentos', to=settings.AUTH_USER_MODEL, verbose_name='Transferido por'),
        ),
        migrations.AddField(
            model_name='transferenciaequipamento',
            name='unidade_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_equipamentos_destino', to='militares.unidade', verbose_name='Unidade de Destino'),
        ),
        migrations.AddField(
            model_name='transferenciaequipamento',
            name='unidade_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_equipamentos_origem', to='militares.unidade', verbose_name='Unidade de Origem'),
        ),
        migrations.AddIndex(
            model_name='equipamentooperacional',
            index=models.Index(fields=['codigo'], name='militares_e_codigo_3cb627_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamentooperacional',
            index=models.Index(fields=['status'], name='militares_e_status_d6e9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamentooperacional',
            index=models.Index(fields=['tipo'], name='militares_e_tipo_8080a1_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoalteracaoequipamento',
            index=models.Index(fields=['equipamento', '-data_alteracao'], name='militares_h_equipam_c308e9_idx'),
        ),
        migrations.AddIndex(
            model_name='tempousoequipamento',
            index=models.Index(fields=['equipamento', '-data_inicio'], name='militares_t_equipam_97d2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='tempousoequipamento',
            index=models.Index(fields=['data_inicio'], name='militares_t_data_in_0ff765_idx'),
        ),
        migrations.AddIndex(
            model_name='tempousoequipamento',
            index=models.Index(fields=['status'], name='militares_t_status_a201b1_idx'),
        ),
        migrations.AddIndex(
            model_name='tempousoequipamento',
            index=models.Index(fields=['operador'], name='militares_t_operado_d59618_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciaequipamento',
            index=models.Index(fields=['equipamento', '-data_transferencia'], name='militares_t_equipam_df52a4_idx'),
        ),
    ]
