# Generated by Django 5.2.3 on 2025-11-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0372_equipamentooperacional_historicoalteracaoequipamento_and_more'),
    ]

    operations = [
        # Remover unique_together do estado do Django
        # A constraint já foi removida do banco de dados em migrations anteriores
        # Esta operação apenas atualiza o estado do Django para refletir a remoção
        migrations.AlterUniqueTogether(
            name='escalaservico',
            unique_together=set(),
        ),
        # Garantir que a constraint não existe no banco (operação segura)
        migrations.RunSQL(
            sql="ALTER TABLE militares_escalaservico DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
