# Generated by Django 5.2.3 on 2025-11-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0374_remove_escalaservico_unique_escala_data_org_tipo'),
    ]

    operations = [
        # Constraint já foi removida em migrations anteriores
        # Usar RunSQL com IF EXISTS para garantir que não cause erro se não existir
        migrations.RunSQL(
            sql="ALTER TABLE militares_escalaservico DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Campos de entradaalmoxarifado já foram adicionados na migration 0370
        # Não adicionar novamente para evitar erro de coluna duplicada
        # Campos de funcaomenuconfig (exceto show_equipamentos_operacionais) já foram adicionados na migration 0370
        # Adicionar apenas o campo show_equipamentos_operacionais que não foi incluído na 0370
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_equipamentos_operacionais',
            field=models.BooleanField(default=False, verbose_name='Equipamentos Operacionais'),
        ),
        # Campo quantidade_inicial já foi adicionado na migration 0370
        # Não adicionar novamente para evitar erro de coluna duplicada
    ]
