# Generated by Django 5.2.3 on 2025-11-12 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0377_permitir_mesmo_codigo_em_oms_diferentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remover constraint apenas se existir (já foi removida em migrations anteriores)
        migrations.RunSQL(
            sql="ALTER TABLE militares_escalaservico DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Adicionar campos apenas se não existirem (podem já ter sido criados em migrations anteriores)
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_entradaalmoxarifado' AND column_name='cnpj_fornecedor') THEN
                        ALTER TABLE militares_entradaalmoxarifado ADD COLUMN cnpj_fornecedor VARCHAR(18);
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_entradaalmoxarifado' AND column_name='endereco_fornecedor') THEN
                        ALTER TABLE militares_entradaalmoxarifado ADD COLUMN endereco_fornecedor TEXT;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_entradaalmoxarifado' AND column_name='numero_convenio') THEN
                        ALTER TABLE militares_entradaalmoxarifado ADD COLUMN numero_convenio VARCHAR(100);
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_entradaalmoxarifado' AND column_name='numero_processo') THEN
                        ALTER TABLE militares_entradaalmoxarifado ADD COLUMN numero_processo VARCHAR(100);
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Adicionar campos de FuncaoMenuConfig apenas se não existirem
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_criar_ficha_conceito_oficial') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_criar_ficha_conceito_oficial BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_criar_ficha_conceito_praca') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_criar_ficha_conceito_praca BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_equipamentos_operacionais_combustivel') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_equipamentos_operacionais_combustivel BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_equipamentos_operacionais_manutencoes') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_equipamentos_operacionais_manutencoes BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_equipamentos_operacionais_tempos_uso') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_equipamentos_operacionais_tempos_uso BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_equipamentos_operacionais_trocas_oleo') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_equipamentos_operacionais_trocas_oleo BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_grandes_comandos') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_grandes_comandos BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_minha_ficha_cadastro') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_minha_ficha_cadastro BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_minha_ficha_conceito_oficial') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_minha_ficha_conceito_oficial BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_minha_ficha_conceito_praca') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_minha_ficha_conceito_praca BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_minhas_informacoes') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_minhas_informacoes BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_organograma') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_organograma BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_orgaos') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_orgaos BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_pessoal') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_pessoal BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_relatorios') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_relatorios BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_relatorios_gerais') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_relatorios_gerais BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_relatorios_medalhas') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_relatorios_medalhas BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_relatorios_militares') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_relatorios_militares BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_relatorios_promocoes') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_relatorios_promocoes BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_relatorios_publicacoes') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_relatorios_publicacoes BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_sub_unidades') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_sub_unidades BOOLEAN DEFAULT FALSE;
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_funcaomenuconfig' AND column_name='show_unidades') THEN
                        ALTER TABLE militares_funcaomenuconfig ADD COLUMN show_unidades BOOLEAN DEFAULT FALSE;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Adicionar quantidade_inicial apenas se não existir
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='militares_itemalmoxarifado' AND column_name='quantidade_inicial') THEN
                        ALTER TABLE militares_itemalmoxarifado ADD COLUMN quantidade_inicial NUMERIC(10, 2) DEFAULT 0;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Remover constraint unique do codigo se existir (já foi feito na migration anterior, mas garantindo)
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF EXISTS (SELECT 1 FROM pg_constraint 
                               WHERE conname = 'militares_itemalmoxarifado_codigo_key') THEN
                        ALTER TABLE militares_itemalmoxarifado DROP CONSTRAINT militares_itemalmoxarifado_codigo_key;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Adicionar unique_together apenas se não existir (já foi feito na migration anterior, mas garantindo)
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint 
                                   WHERE conname = 'militares_itemalmoxarifado_codigo_orgao_grande_comando_unidade_sub_unidade_uniq') THEN
                        ALTER TABLE militares_itemalmoxarifado 
                        ADD CONSTRAINT militares_itemalmoxarifado_codigo_orgao_grande_comando_unidade_sub_unidade_uniq 
                        UNIQUE (codigo, orgao_id, grande_comando_id, unidade_id, sub_unidade_id);
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Adicionar índice apenas se não existir (já foi feito na migration anterior, mas garantindo)
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes 
                                   WHERE indexname = 'militares_i_orgao_i_3cb343_idx') THEN
                        CREATE INDEX militares_i_orgao_i_3cb343_idx 
                        ON militares_itemalmoxarifado (orgao_id, grande_comando_id, unidade_id, sub_unidade_id);
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
