# Generated by Django 5.2.3 on 2025-11-12 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0378_remove_escalaservico_unique_escala_data_org_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Esta migration é uma garantia - todas as operações já foram feitas nas migrations anteriores
        # Usamos RunSQL para garantir que não há erros se algo já foi aplicado
        migrations.RunSQL(
            sql="SELECT 1;",  # Operação vazia, apenas para marcar a migration como aplicada
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
