# Generated by Django 5.2.3 on 2025-11-12 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0380_remove_escalaservico_unique_escala_data_org_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remover constraint apenas se existir (já foi removida em migrations anteriores)
        migrations.RunSQL(
            sql="ALTER TABLE militares_escalaservico DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Campos já foram adicionados na migração 0378, apenas atualizar o estado do Django
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Não modificar o banco, campos já existem
            state_operations=[
                migrations.AddField(
                    model_name='entradaalmoxarifado',
                    name='cnpj_fornecedor',
                    field=models.CharField(blank=True, help_text='CNPJ do fornecedor (formato: XX.XXX.XXX/XXXX-XX)', max_length=18, null=True, verbose_name='CNPJ do Fornecedor'),
                ),
                migrations.AddField(
                    model_name='entradaalmoxarifado',
                    name='endereco_fornecedor',
                    field=models.TextField(blank=True, help_text='Endereço completo do fornecedor', null=True, verbose_name='Endereço do Fornecedor'),
                ),
                migrations.AddField(
                    model_name='entradaalmoxarifado',
                    name='numero_convenio',
                    field=models.CharField(blank=True, help_text='Número do convênio (obrigatório para doações)', max_length=100, null=True, verbose_name='Número do Convênio'),
                ),
                migrations.AddField(
                    model_name='entradaalmoxarifado',
                    name='numero_processo',
                    field=models.CharField(blank=True, help_text='Número do processo (obrigatório para doações)', max_length=100, null=True, verbose_name='Número do Processo'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_criar_ficha_conceito_oficial',
                    field=models.BooleanField(default=False, verbose_name='Criar Ficha de Conceito (Oficial)'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_criar_ficha_conceito_praca',
                    field=models.BooleanField(default=False, verbose_name='Criar Ficha de Conceito (Praça)'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_equipamentos_operacionais_combustivel',
                    field=models.BooleanField(default=False, verbose_name='Controle de Combustível (Equipamentos)'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_equipamentos_operacionais_manutencoes',
                    field=models.BooleanField(default=False, verbose_name='Manutenções (Equipamentos)'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_equipamentos_operacionais_tempos_uso',
                    field=models.BooleanField(default=False, verbose_name='Controle de Uso por Horas'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_equipamentos_operacionais_trocas_oleo',
                    field=models.BooleanField(default=False, verbose_name='Trocas de Óleo (Equipamentos)'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_grandes_comandos',
                    field=models.BooleanField(default=False, verbose_name='Grandes Comandos'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_minha_ficha_cadastro',
                    field=models.BooleanField(default=False, verbose_name='Minha Ficha de Cadastro'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_minha_ficha_conceito_oficial',
                    field=models.BooleanField(default=False, verbose_name='Minha Ficha de Conceito (Oficial)'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_minha_ficha_conceito_praca',
                    field=models.BooleanField(default=False, verbose_name='Minha Ficha de Conceito (Praça)'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_minhas_informacoes',
                    field=models.BooleanField(default=False, verbose_name='Minhas Informações'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_organograma',
                    field=models.BooleanField(default=False, verbose_name='Organograma'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_orgaos',
                    field=models.BooleanField(default=False, verbose_name='Órgãos'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_pessoal',
                    field=models.BooleanField(default=False, verbose_name='Pessoal'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_relatorios',
                    field=models.BooleanField(default=False, verbose_name='Relatórios'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_relatorios_gerais',
                    field=models.BooleanField(default=False, verbose_name='Relatórios Gerais'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_relatorios_medalhas',
                    field=models.BooleanField(default=False, verbose_name='Relatórios de Medalhas'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_relatorios_militares',
                    field=models.BooleanField(default=False, verbose_name='Relatórios de Militares'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_relatorios_promocoes',
                    field=models.BooleanField(default=False, verbose_name='Relatórios de Promoções'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_relatorios_publicacoes',
                    field=models.BooleanField(default=False, verbose_name='Relatórios de Publicações'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_sub_unidades',
                    field=models.BooleanField(default=False, verbose_name='Sub-Unidades'),
                ),
                migrations.AddField(
                    model_name='funcaomenuconfig',
                    name='show_unidades',
                    field=models.BooleanField(default=False, verbose_name='Unidades'),
                ),
                migrations.AddField(
                    model_name='itemalmoxarifado',
                    name='quantidade_inicial',
                    field=models.DecimalField(decimal_places=2, default=0, help_text='Quantidade inicial em estoque (estoque inicial definido quando o item foi criado)', max_digits=10, verbose_name='Quantidade Inicial'),
                ),
            ],
        ),
        # Alterações de unique_together e índice já foram feitas na migração 0378, apenas atualizar o estado do Django
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Não modificar o banco, operações já foram feitas
            state_operations=[
                migrations.AlterField(
                    model_name='itemalmoxarifado',
                    name='codigo',
                    field=models.CharField(help_text='Código de identificação do item (pode ser repetido em OMs diferentes)', max_length=50, verbose_name='Código do Item'),
                ),
                migrations.AlterUniqueTogether(
                    name='itemalmoxarifado',
                    unique_together={('codigo', 'orgao', 'grande_comando', 'unidade', 'sub_unidade')},
                ),
                migrations.AddIndex(
                    model_name='itemalmoxarifado',
                    index=models.Index(fields=['orgao', 'grande_comando', 'unidade', 'sub_unidade'], name='militares_i_orgao_i_3cb343_idx'),
                ),
            ],
        ),
    ]
