# Generated by Django 5.2.3 on 2025-11-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0381_remove_escalaservico_unique_escala_data_org_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='itemalmoxarifado',
            name='militares_i_orgao_i_3cb343_idx',
        ),
        # Remover constraint unique_together e adicionar unique no codigo via SQL
        migrations.RunSQL(
            sql="""
                DO $$ 
                DECLARE
                    constraint_name TEXT;
                BEGIN
                    -- Buscar e remover constraint unique_together se existir
                    SELECT conname INTO constraint_name
                    FROM pg_constraint
                    WHERE conrelid = 'militares_itemalmoxarifado'::regclass
                    AND contype = 'u'
                    AND array_length(conkey, 1) = 5
                    LIMIT 1;
                    
                    IF constraint_name IS NOT NULL THEN
                        EXECUTE format('ALTER TABLE militares_itemalmoxarifado DROP CONSTRAINT IF EXISTS %I', constraint_name);
                    END IF;
                    
                    -- Adicionar unique no codigo se não existir
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conrelid = 'militares_itemalmoxarifado'::regclass 
                        AND contype = 'u'
                        AND array_length(conkey, 1) = 1
                        AND conkey[1] = (SELECT attnum FROM pg_attribute WHERE attrelid = 'militares_itemalmoxarifado'::regclass AND attname = 'codigo')
                    ) THEN
                        ALTER TABLE militares_itemalmoxarifado ADD CONSTRAINT militares_itemalmoxarifado_codigo_key UNIQUE (codigo);
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Atualizar o estado do modelo (banco já foi alterado via SQL acima)
        # Não usar AlterField pois o campo já foi alterado via SQL
        # Apenas atualizar o estado do modelo para refletir as mudanças
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='itemalmoxarifado',
                    name='codigo',
                    field=models.CharField(help_text='Código de identificação único do item (produto único como supermercado)', max_length=50, unique=True, verbose_name='Código do Item'),
                ),
            ],
        ),
    ]
