# Generated by Django 5.2.3 on 2025-11-13 03:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0382_sistema_supermercado_produto_unico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaAlmoxarifadoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantidade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Produto da Entrada',
                'verbose_name_plural': 'Produtos da Entrada',
                'ordering': ['entrada', 'produto'],
            },
        ),
        # ProdutoAlmoxarifado já existe (tabela militares_itemalmoxarifado)
        # Não criar novamente, apenas adicionar campos faltantes depois
        migrations.CreateModel(
            name='ProdutoAlmoxarifadoLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(blank=True, help_text='Localização física do produto no almoxarifado desta OM', max_length=200, null=True, verbose_name='Localização')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Localização do Produto por OM',
                'verbose_name_plural': 'Localizações dos Produtos por OM',
            },
        ),
        migrations.CreateModel(
            name='RequisicaoAlmoxarifadoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantidade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Produto da Requisição',
                'verbose_name_plural': 'Produtos da Requisição',
                'ordering': ['requisicao', 'produto'],
            },
        ),
        migrations.CreateModel(
            name='SaidaAlmoxarifadoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantidade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Produto da Saída',
                'verbose_name_plural': 'Produtos da Saída',
                'ordering': ['saida', 'produto'],
            },
        ),
        # Remover unique_together apenas se existir (pode já ter sido removido ou tabela não existir)
        migrations.RunSQL(
            sql="""
                DO $$ 
                DECLARE
                    constraint_name TEXT;
                    table_exists BOOLEAN;
                BEGIN
                    -- Verificar se a tabela existe
                    SELECT EXISTS (
                        SELECT FROM information_schema.tables 
                        WHERE table_schema = 'public' 
                        AND table_name = 'militares_entradaalmoxarifadoitem'
                    ) INTO table_exists;
                    
                    IF table_exists THEN
                        -- Buscar e remover constraint unique_together se existir
                        SELECT conname INTO constraint_name
                        FROM pg_constraint
                        WHERE conrelid = 'militares_entradaalmoxarifadoitem'::regclass
                        AND contype = 'u'
                        AND array_length(conkey, 1) = 2
                        LIMIT 1;
                        
                        IF constraint_name IS NOT NULL THEN
                            EXECUTE format('ALTER TABLE militares_entradaalmoxarifadoitem DROP CONSTRAINT IF EXISTS %I', constraint_name);
                        END IF;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Atualizar apenas o estado do Django
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='entradaalmoxarifadoitem',
                    unique_together=None,
                ),
            ],
        ),
        # Tabela será deletada no final, apenas atualizar estado do Django
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='entradaalmoxarifadoitem',
                    name='entrada',
                ),
                migrations.RemoveField(
                    model_name='entradaalmoxarifadoitem',
                    name='item',
                ),
            ],
        ),
        # Remover unique_together apenas se existir (já foi removido na migração 0382, mas garantindo)
        migrations.RunSQL(
            sql="""
                DO $$ 
                DECLARE
                    constraint_name TEXT;
                BEGIN
                    -- Buscar e remover constraint unique_together se existir
                    SELECT conname INTO constraint_name
                    FROM pg_constraint
                    WHERE conrelid = 'militares_itemalmoxarifado'::regclass
                    AND contype = 'u'
                    AND array_length(conkey, 1) = 5
                    LIMIT 1;
                    
                    IF constraint_name IS NOT NULL THEN
                        EXECUTE format('ALTER TABLE militares_itemalmoxarifado DROP CONSTRAINT IF EXISTS %I', constraint_name);
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='itemalmoxarifado',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='itemalmoxarifado',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='itemalmoxarifado',
            name='grande_comando',
        ),
        migrations.RemoveField(
            model_name='itemalmoxarifado',
            name='orgao',
        ),
        migrations.RemoveField(
            model_name='itemalmoxarifado',
            name='sub_unidade',
        ),
        migrations.RemoveField(
            model_name='itemalmoxarifado',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='itemalmoxarifado',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='entradaalmoxarifado',
            name='item',
        ),
        migrations.RemoveField(
            model_name='historicoalmoxarifado',
            name='item',
        ),
        migrations.RemoveField(
            model_name='requisicaoalmoxarifadoitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='saidaalmoxarifado',
            name='item',
        ),
        migrations.RemoveField(
            model_name='saidaalmoxarifadoitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='requisicaoalmoxarifado',
            name='item',
        ),
        # Remover unique_together apenas se existir (pode já ter sido removido ou tabela não existir)
        migrations.RunSQL(
            sql="""
                DO $$ 
                DECLARE
                    constraint_name TEXT;
                    table_exists BOOLEAN;
                BEGIN
                    -- Verificar se a tabela existe
                    SELECT EXISTS (
                        SELECT FROM information_schema.tables 
                        WHERE table_schema = 'public' 
                        AND table_name = 'militares_requisicaoalmoxarifadoitem'
                    ) INTO table_exists;
                    
                    IF table_exists THEN
                        -- Buscar e remover constraint unique_together se existir
                        SELECT conname INTO constraint_name
                        FROM pg_constraint
                        WHERE conrelid = 'militares_requisicaoalmoxarifadoitem'::regclass
                        AND contype = 'u'
                        AND array_length(conkey, 1) = 2
                        LIMIT 1;
                        
                        IF constraint_name IS NOT NULL THEN
                            EXECUTE format('ALTER TABLE militares_requisicaoalmoxarifadoitem DROP CONSTRAINT IF EXISTS %I', constraint_name);
                        END IF;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Atualizar apenas o estado do Django
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='requisicaoalmoxarifadoitem',
                    unique_together=None,
                ),
            ],
        ),
        # Tabela será deletada no final, apenas atualizar estado do Django
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='requisicaoalmoxarifadoitem',
                    name='requisicao',
                ),
            ],
        ),
        # Remover unique_together apenas se existir (pode já ter sido removido ou tabela não existir)
        migrations.RunSQL(
            sql="""
                DO $$ 
                DECLARE
                    constraint_name TEXT;
                    table_exists BOOLEAN;
                BEGIN
                    -- Verificar se a tabela existe
                    SELECT EXISTS (
                        SELECT FROM information_schema.tables 
                        WHERE table_schema = 'public' 
                        AND table_name = 'militares_saidaalmoxarifadoitem'
                    ) INTO table_exists;
                    
                    IF table_exists THEN
                        -- Buscar e remover constraint unique_together se existir
                        SELECT conname INTO constraint_name
                        FROM pg_constraint
                        WHERE conrelid = 'militares_saidaalmoxarifadoitem'::regclass
                        AND contype = 'u'
                        AND array_length(conkey, 1) = 2
                        LIMIT 1;
                        
                        IF constraint_name IS NOT NULL THEN
                            EXECUTE format('ALTER TABLE militares_saidaalmoxarifadoitem DROP CONSTRAINT IF EXISTS %I', constraint_name);
                        END IF;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Atualizar apenas o estado do Django
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='saidaalmoxarifadoitem',
                    unique_together=None,
                ),
            ],
        ),
        # Tabela será deletada no final, apenas atualizar estado do Django
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='saidaalmoxarifadoitem',
                    name='saida',
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name='entradaalmoxarifado',
            name='militares_e_item_id_23fdb4_idx',
        ),
        migrations.RemoveIndex(
            model_name='historicoalmoxarifado',
            name='militares_h_item_id_92a708_idx',
        ),
        migrations.RemoveIndex(
            model_name='saidaalmoxarifado',
            name='militares_s_item_id_08732e_idx',
        ),
        migrations.AddField(
            model_name='entradaalmoxarifadoproduto',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_entrada', to='militares.entradaalmoxarifado', verbose_name='Entrada'),
        ),
        # Renomear ItemAlmoxarifado para ProdutoAlmoxarifado no estado do Django
        # A tabela no banco já existe como militares_itemalmoxarifado, será renomeada depois
        migrations.RenameModel(
            old_name='ItemAlmoxarifado',
            new_name='ProdutoAlmoxarifado',
        ),
        migrations.AddField(
            model_name='produtoalmoxarifado',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_almoxarifado', to='militares.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='produtoalmoxarifado',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_almoxarifado_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='produtoalmoxarifado',
            name='grande_comando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_almoxarifado', to='militares.grandecomando', verbose_name='Grande Comando'),
        ),
        migrations.AddField(
            model_name='produtoalmoxarifado',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_almoxarifado', to='militares.orgao', verbose_name='Órgão'),
        ),
        migrations.AddField(
            model_name='produtoalmoxarifado',
            name='sub_unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_almoxarifado', to='militares.subunidade', verbose_name='Sub-Unidade'),
        ),
        migrations.AddField(
            model_name='produtoalmoxarifado',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_almoxarifado', to='militares.subcategoria', verbose_name='Subcategoria'),
        ),
        migrations.AddField(
            model_name='produtoalmoxarifado',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_almoxarifado', to='militares.unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='entradaalmoxarifadoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_produtos', to='militares.produtoalmoxarifado', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='entradaalmoxarifado',
            name='produto',
            field=models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='militares.produtoalmoxarifado', verbose_name='Produto (Legado)'),
        ),
        migrations.AddField(
            model_name='historicoalmoxarifado',
            name='produto',
            field=models.ForeignKey(db_column='item_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='militares.produtoalmoxarifado', verbose_name='Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifado',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes', to='militares.produtoalmoxarifado', verbose_name='Produto (Legado)'),
        ),
        migrations.AddField(
            model_name='saidaalmoxarifado',
            name='produto',
            field=models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas', to='militares.produtoalmoxarifado', verbose_name='Produto (Legado)'),
        ),
        # Adicionar índices apenas se não existirem (após os campos serem adicionados)
        # Nota: entradaalmoxarifado, historicoalmoxarifado e saidaalmoxarifado usam db_column='item_id'
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    -- Para entradaalmoxarifado: usa item_id (db_column)
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'militares_entradaalmoxarifado' 
                        AND column_name = 'item_id'
                    ) THEN
                        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'militares_e_item_id_23fdb4_idx') THEN
                            CREATE INDEX militares_e_item_id_23fdb4_idx ON militares_entradaalmoxarifado (item_id, data_entrada DESC);
                        END IF;
                    END IF;
                    
                    -- Para historicoalmoxarifado: usa item_id (db_column)
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'militares_historicoalmoxarifado' 
                        AND column_name = 'item_id'
                    ) THEN
                        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'militares_h_item_id_92a708_idx') THEN
                            CREATE INDEX militares_h_item_id_92a708_idx ON militares_historicoalmoxarifado (item_id, data_alteracao DESC);
                        END IF;
                    END IF;
                    
                    -- Para saidaalmoxarifado: usa item_id (db_column)
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'militares_saidaalmoxarifado' 
                        AND column_name = 'item_id'
                    ) THEN
                        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'militares_s_item_id_08732e_idx') THEN
                            CREATE INDEX militares_s_item_id_08732e_idx ON militares_saidaalmoxarifado (item_id, data_saida DESC);
                        END IF;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Atualizar apenas o estado do Django
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='entradaalmoxarifado',
                    index=models.Index(fields=['produto', '-data_entrada'], name='militares_e_item_id_23fdb4_idx'),
                ),
                migrations.AddIndex(
                    model_name='historicoalmoxarifado',
                    index=models.Index(fields=['produto', '-data_alteracao'], name='militares_h_item_id_92a708_idx'),
                ),
                migrations.AddIndex(
                    model_name='saidaalmoxarifado',
                    index=models.Index(fields=['produto', '-data_saida'], name='militares_s_item_id_08732e_idx'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='produtoalmoxarifadolocalizacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizacoes_produtos_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='produtoalmoxarifadolocalizacao',
            name='grande_comando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes_produtos', to='militares.grandecomando', verbose_name='Grande Comando'),
        ),
        migrations.AddField(
            model_name='produtoalmoxarifadolocalizacao',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes_produtos', to='militares.orgao', verbose_name='Órgão'),
        ),
        migrations.AddField(
            model_name='produtoalmoxarifadolocalizacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes_om', to='militares.produtoalmoxarifado', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='produtoalmoxarifadolocalizacao',
            name='sub_unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes_produtos', to='militares.subunidade', verbose_name='Sub-Unidade'),
        ),
        migrations.AddField(
            model_name='produtoalmoxarifadolocalizacao',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes_produtos', to='militares.unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifadoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_produtos', to='militares.produtoalmoxarifado', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='requisicaoalmoxarifadoproduto',
            name='requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_requisicao', to='militares.requisicaoalmoxarifado', verbose_name='Requisição'),
        ),
        migrations.AddField(
            model_name='saidaalmoxarifadoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas_produtos', to='militares.produtoalmoxarifado', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='saidaalmoxarifadoproduto',
            name='saida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_saida', to='militares.saidaalmoxarifado', verbose_name='Saída'),
        ),
        # Deletar tabelas apenas se existirem (ItemAlmoxarifado será renomeado, não deletado)
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    DROP TABLE IF EXISTS militares_entradaalmoxarifadoitem CASCADE;
                    DROP TABLE IF EXISTS militares_requisicaoalmoxarifadoitem CASCADE;
                    DROP TABLE IF EXISTS militares_saidaalmoxarifadoitem CASCADE;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Atualizar apenas o estado do Django
        # ItemAlmoxarifado já foi renomeado para ProdutoAlmoxarifado, não precisa deletar
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='EntradaAlmoxarifadoItem',
                ),
                migrations.DeleteModel(
                    name='RequisicaoAlmoxarifadoItem',
                ),
                migrations.DeleteModel(
                    name='SaidaAlmoxarifadoItem',
                ),
            ],
        ),
        # Adicionar índices apenas se não existirem
        # A tabela pode estar como militares_itemalmoxarifado ou militares_produtoalmoxarifado
        migrations.RunSQL(
            sql="""
                DO $$ 
                DECLARE
                    tbl_name TEXT;
                BEGIN
                    -- Verificar qual tabela existe
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'militares_produtoalmoxarifado') THEN
                        tbl_name := 'militares_produtoalmoxarifado';
                    ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'militares_itemalmoxarifado') THEN
                        tbl_name := 'militares_itemalmoxarifado';
                    ELSE
                        RETURN; -- Tabela não existe, não criar índices
                    END IF;
                    
                    -- Criar índices na tabela correta
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'militares_i_codigo_a5f55d_idx') THEN
                        EXECUTE format('CREATE INDEX militares_i_codigo_a5f55d_idx ON %I (codigo)', tbl_name);
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'militares_i_categor_25221b_idx') THEN
                        EXECUTE format('CREATE INDEX militares_i_categor_25221b_idx ON %I (categoria_id)', tbl_name);
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'militares_i_ativo_9e7d87_idx') THEN
                        EXECUTE format('CREATE INDEX militares_i_ativo_9e7d87_idx ON %I (ativo)', tbl_name);
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Atualizar apenas o estado do Django
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='produtoalmoxarifado',
                    index=models.Index(fields=['codigo'], name='militares_i_codigo_a5f55d_idx'),
                ),
                migrations.AddIndex(
                    model_name='produtoalmoxarifado',
                    index=models.Index(fields=['categoria'], name='militares_i_categor_25221b_idx'),
                ),
                migrations.AddIndex(
                    model_name='produtoalmoxarifado',
                    index=models.Index(fields=['ativo'], name='militares_i_ativo_9e7d87_idx'),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='entradaalmoxarifadoproduto',
            unique_together={('entrada', 'produto')},
        ),
        # Adicionar índice apenas se não existir
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'militares_p_produto_45df49_idx') THEN
                        CREATE INDEX militares_p_produto_45df49_idx ON militares_produtoalmoxarifadolocalizacao (produto_id, orgao_id, grande_comando_id, unidade_id, sub_unidade_id);
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Atualizar apenas o estado do Django
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='produtoalmoxarifadolocalizacao',
                    index=models.Index(fields=['produto', 'orgao', 'grande_comando', 'unidade', 'sub_unidade'], name='militares_p_produto_45df49_idx'),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='produtoalmoxarifadolocalizacao',
            unique_together={('produto', 'orgao', 'grande_comando', 'unidade', 'sub_unidade')},
        ),
        migrations.AlterUniqueTogether(
            name='requisicaoalmoxarifadoproduto',
            unique_together={('requisicao', 'produto')},
        ),
        migrations.AlterUniqueTogether(
            name='saidaalmoxarifadoproduto',
            unique_together={('saida', 'produto')},
        ),
    ]
