# Generated by Django 5.0.2 on 2025-11-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0384_criar_tabela_produto_almoxarifado_localizacao"),
    ]

    operations = [
        # Migration vazia - não alterar o banco
        # A quantidade é obrigatória e será calculada a partir dos produtos_entrada na view
        # O campo quantidade armazena a soma total das quantidades dos produtos
    ]
