# Generated by Django 5.0.2 on 2025-11-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0385_alterar_quantidade_entrada_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="entradaalmoxarifadoproduto",
            name="valor_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor total do produto (quantidade × valor unitário)",
                max_digits=12,
                null=True,
                verbose_name="Valor Total (R$)",
            ),
        ),
        migrations.AddField(
            model_name="entradaalmoxarifadoproduto",
            name="valor_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor unitário do produto nesta entrada",
                max_digits=12,
                null=True,
                verbose_name="Valor Unitário (R$)",
            ),
        ),
    ]
