# Generated by Django 5.2.3 on 2025-11-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0386_adicionar_valores_entrada_almoxarifado_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoalmoxarifado',
            options={'ordering': ['codigo'], 'verbose_name': 'Produto do Almoxarifado', 'verbose_name_plural': 'Produtos do Almoxarifado'},
        ),
        # Constraint já foi removida em migrations anteriores (0375)
        # Usar RunSQL com IF EXISTS para garantir que não cause erro se não existir
        migrations.RunSQL(
            sql="ALTER TABLE militares_escalaservico DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Renomear índices apenas se existirem no banco de dados
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    -- Renomear índice codigo se existir
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'militares_i_codigo_a5f55d_idx' AND tablename = 'militares_produtoalmoxarifado') THEN
                        ALTER INDEX militares_i_codigo_a5f55d_idx RENAME TO militares_p_codigo_ed7b0b_idx;
                    END IF;
                    
                    -- Renomear índice categoria se existir
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'militares_i_categor_25221b_idx' AND tablename = 'militares_produtoalmoxarifado') THEN
                        ALTER INDEX militares_i_categor_25221b_idx RENAME TO militares_p_categor_352c6e_idx;
                    END IF;
                    
                    -- Renomear índice ativo se existir
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'militares_i_ativo_9e7d87_idx' AND tablename = 'militares_produtoalmoxarifado') THEN
                        ALTER INDEX militares_i_ativo_9e7d87_idx RENAME TO militares_p_ativo_eb25b4_idx;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Atualizar o estado do Django para refletir os novos nomes dos índices
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='produtoalmoxarifado',
                    name='militares_i_codigo_a5f55d_idx',
                ),
                migrations.RemoveIndex(
                    model_name='produtoalmoxarifado',
                    name='militares_i_categor_25221b_idx',
                ),
                migrations.RemoveIndex(
                    model_name='produtoalmoxarifado',
                    name='militares_i_ativo_9e7d87_idx',
                ),
                migrations.AddIndex(
                    model_name='produtoalmoxarifado',
                    index=models.Index(fields=['codigo'], name='militares_p_codigo_ed7b0b_idx'),
                ),
                migrations.AddIndex(
                    model_name='produtoalmoxarifado',
                    index=models.Index(fields=['categoria'], name='militares_p_categor_352c6e_idx'),
                ),
                migrations.AddIndex(
                    model_name='produtoalmoxarifado',
                    index=models.Index(fields=['ativo'], name='militares_p_ativo_eb25b4_idx'),
                ),
            ],
        ),
        # unique_together já foi removido em migrations anteriores (0382)
        # Apenas atualizar o estado do Django sem modificar o banco
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Não modificar o banco, constraint já foi removida
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='produtoalmoxarifado',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='codigo',
            field=models.CharField(help_text='Código de identificação único do produto (produto único como supermercado)', max_length=50, unique=True, verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras do produto (gerado automaticamente baseado no código)', max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='descricao',
            field=models.CharField(help_text='Descrição detalhada do produto', max_length=500, verbose_name='Descrição do Produto'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem do produto do almoxarifado', null=True, upload_to='almoxarifado/produtos/', verbose_name='Imagem do Produto'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Localização física do produto no almoxarifado', max_length=200, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='quantidade_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantidade inicial em estoque (estoque inicial definido quando o produto foi criado)', max_digits=10, verbose_name='Quantidade Inicial'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='tamanho',
            field=models.CharField(blank=True, help_text='Tamanho ou numeração do produto (ex: 35, 36, 37, P, M, G, GG, etc.). Cada tamanho diferente é um produto individual no estoque.', max_length=20, null=True, verbose_name='Tamanho/Numeração'),
        ),
        migrations.AlterField(
            model_name='produtoalmoxarifado',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor unitário médio do produto', max_digits=12, null=True, verbose_name='Valor Unitário (R$)'),
        ),
        migrations.AlterModelTable(
            name='produtoalmoxarifado',
            table='militares_produtoalmoxarifado',
        ),
    ]
