# Generated by Django 5.2.3 on 2025-11-14 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0388_adicionar_campos_confirmacao_recebimento_requisicao'),
    ]

    operations = [
        # Constraint já foi removida em migrations anteriores (0375, 0387)
        # Usar RunSQL com IF EXISTS para garantir que não cause erro se não existir
        migrations.RunSQL(
            sql="ALTER TABLE militares_escalaservico DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
