# Generated by Django 5.2.3 on 2025-11-14 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0389_remove_escalaservico_unique_escala_data_org_tipo'),
    ]

    operations = [
        # Primeiro, garantir que a constraint não existe no banco (operação segura)
        migrations.RunSQL(
            sql="ALTER TABLE militares_escalaservico DROP CONSTRAINT IF EXISTS unique_escala_data_org_tipo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Depois, atualizar o estado do Django removendo a constraint do estado
        # Usamos SeparateDatabaseAndState para atualizar apenas o estado, sem tocar no banco
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Não fazer nada no banco, a constraint já foi removida
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='escalaservico',
                    name='unique_escala_data_org_tipo',
                ),
            ],
        ),
    ]
