# Generated by Django 5.0.2 on 2025-11-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0390_remove_escalaservico_unique_escala_data_org_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="permitir_flexibilizacao_validacoes",
            field=models.BooleanField(
                default=False,
                help_text="Quando ativado, permite que militares sejam adicionados em planejadas mesmo que não atendam todas as validações do sistema (qualificações, intervalos, limites mensais, etc.). Use com cautela!",
                verbose_name="Permitir Flexibilização de Validações",
            ),
        ),
    ]
