# Generated by Django 5.0.2 on 2025-11-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0391_add_permitir_flexibilizacao_validacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="permitir_flexibilizacao_p1",
            field=models.BooleanField(
                default=False,
                help_text="Quando ativado, permite que militares sejam adicionados em planejadas P1 mesmo que não atendam todas as validações do sistema (qualificações, intervalos, limites mensais, etc.). Use com cautela!",
                verbose_name="Permitir Flexibilização P1",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="permitir_flexibilizacao_p2",
            field=models.BooleanField(
                default=False,
                help_text="Quando ativado, permite que militares sejam adicionados em planejadas P2 mesmo que não atendam todas as validações do sistema (qualificações, intervalos, limites mensais, etc.). Use com cautela!",
                verbose_name="Permitir Flexibilização P2",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="permitir_flexibilizacao_p3",
            field=models.BooleanField(
                default=False,
                help_text="Quando ativado, permite que militares sejam adicionados em planejadas P3 mesmo que não atendam todas as validações do sistema (qualificações, intervalos, limites mensais, etc.). Use com cautela!",
                verbose_name="Permitir Flexibilização P3",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoplanejadas",
            name="permitir_flexibilizacao_p4",
            field=models.BooleanField(
                default=False,
                help_text="Quando ativado, permite que militares sejam adicionados em planejadas P4 mesmo que não atendam todas as validações do sistema (qualificações, intervalos, limites mensais, etc.). Use com cautela!",
                verbose_name="Permitir Flexibilização P4",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaoplanejadas",
            name="permitir_flexibilizacao_validacoes",
            field=models.BooleanField(
                default=False,
                help_text="DEPRECATED: Use os campos específicos por tipo (P1, P2, P3, P4). Este campo será removido em versões futuras.",
                verbose_name="Permitir Flexibilização de Validações (Legado)",
            ),
        ),
    ]
