# Generated by Django 5.2.3 on 2025-11-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0393_adicionar_situacao_anterior_afastamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='data_ultima_inativacao',
            field=models.DateField(blank=True, help_text='Data em que o militar foi inativado pela última vez', null=True, verbose_name='Data da Última Inativação'),
        ),
        migrations.AddField(
            model_name='militar',
            name='data_ultima_reativacao',
            field=models.DateField(blank=True, help_text='Data em que o militar foi reativado pela última vez', null=True, verbose_name='Data da Última Reativação'),
        ),
        migrations.AddField(
            model_name='militar',
            name='tempo_servico_acumulado_dias',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Total de dias de serviço acumulados antes de ser transferido para inativo', null=True, verbose_name='Tempo de Serviço Acumulado (dias)'),
        ),
    ]
