# Generated by Django 5.2.3 on 2025-11-15 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0394_add_tempo_servico_controle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemInstantanea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GERAL', 'Geral - Todos os usuários'), ('ESPECIFICO', 'Usuário Específico'), ('GRUPO', 'Grupo de Usuários')], default='GERAL', max_length=20, verbose_name='Tipo de Mensagem')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('prioridade', models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANTE', 'Importante'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20, verbose_name='Prioridade')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('destinatarios_ids', models.JSONField(blank=True, default=list, verbose_name='IDs dos Destinatários')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Mensagem Instantânea',
                'verbose_name_plural': 'Mensagens Instantâneas',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['destinatario', 'lida', 'ativa'], name='militares_m_destina_41c15a_idx'), models.Index(fields=['tipo', 'data_criacao'], name='militares_m_tipo_7184b0_idx'), models.Index(fields=['prioridade', 'data_criacao'], name='militares_m_priorid_f38d9c_idx')],
            },
        ),
    ]
