# Generated by Django 5.2.3 on 2025-11-15 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0395_mensageminstantanea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('participante1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_participante1', to=settings.AUTH_USER_MODEL, verbose_name='Participante 1')),
                ('participante2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_participante2', to=settings.AUTH_USER_MODEL, verbose_name='Participante 2')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['-ultima_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='militares.chat', verbose_name='Chat')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Mensagem de Chat',
                'verbose_name_plural': 'Mensagens de Chat',
                'ordering': ['data_envio'],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['participante1', 'ativo'], name='militares_c_partici_7f080c_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['participante2', 'ativo'], name='militares_c_partici_b34f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['ultima_atualizacao'], name='militares_c_ultima__d2ac1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('participante1', 'participante2')},
        ),
        migrations.AddIndex(
            model_name='mensagemchat',
            index=models.Index(fields=['chat', 'data_envio'], name='militares_m_chat_id_4cdc7e_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagemchat',
            index=models.Index(fields=['remetente', 'lida'], name='militares_m_remeten_3c7ea3_idx'),
        ),
    ]
