# Generated by Django 5.2.3 on 2025-11-15 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0396_chat_mensagemchat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VOZ', 'Chamada de Voz'), ('VIDEO', 'Chamada de Vídeo')], default='VOZ', max_length=10, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('INICIANDO', 'Iniciando'), ('CHAMANDO', 'Chamando'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADA', 'Finalizada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='INICIANDO', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('duracao_segundos', models.IntegerField(blank=True, null=True, verbose_name='Duração (segundos)')),
                ('oferta_sdp', models.TextField(blank=True, null=True, verbose_name='Oferta SDP')),
                ('resposta_sdp', models.TextField(blank=True, null=True, verbose_name='Resposta SDP')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='militares.chat', verbose_name='Chat')),
                ('iniciador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas_iniciadas', to=settings.AUTH_USER_MODEL, verbose_name='Iniciador')),
            ],
            options={
                'verbose_name': 'Chamada',
                'verbose_name_plural': 'Chamadas',
                'ordering': ['-data_inicio'],
                'indexes': [models.Index(fields=['chat', 'status'], name='militares_c_chat_id_d68b38_idx'), models.Index(fields=['iniciador', 'status'], name='militares_c_iniciad_831fb5_idx')],
            },
        ),
    ]
