# Generated by Django 5.2.3 on 2025-11-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0397_chamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemchat',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_audios/%Y/%m/', verbose_name='Áudio'),
        ),
        migrations.AddField(
            model_name='mensagemchat',
            name='duracao_audio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duração do Áudio (segundos)'),
        ),
        migrations.AlterField(
            model_name='mensagemchat',
            name='mensagem',
            field=models.TextField(blank=True, verbose_name='Mensagem'),
        ),
    ]
