# Generated by Django 5.2.3 on 2025-11-15 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0398_mensagemchat_audio_mensagemchat_duracao_audio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoRequisicaoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('APROVACAO', 'Aprovação'), ('NEGACAO', 'Negação'), ('ATENDIMENTO', 'Atendimento'), ('CANCELAMENTO', 'Cancelamento'), ('CONFIRMACAO_RECEBIMENTO', 'Confirmação de Recebimento')], max_length=30, verbose_name='Tipo de Ação')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('campo_alterado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo Alterado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_novo', models.TextField(blank=True, null=True, verbose_name='Valor Novo')),
                ('quantidade_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade Anterior')),
                ('quantidade_nova', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade Nova')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_requisicoes_almoxarifado', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_requisicoes', to='militares.produtoalmoxarifado', verbose_name='Produto')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='militares.requisicaoalmoxarifado', verbose_name='Requisição')),
            ],
            options={
                'verbose_name': 'Histórico de Requisição de Almoxarifado',
                'verbose_name_plural': 'Históricos de Requisições de Almoxarifado',
                'ordering': ['-data_alteracao'],
                'indexes': [models.Index(fields=['requisicao', '-data_alteracao'], name='militares_h_requisi_97fec8_idx')],
            },
        ),
    ]
