# Generated by Django 5.2.3 on 2025-11-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0399_adicionar_historico_requisicao_almoxarifado'),
    ]

    operations = [
        migrations.AddField(
            model_name='armaparticular',
            name='alma_raiada',
            field=models.BooleanField(default=False, help_text='Se a arma possui alma raiada', verbose_name='Alma Raiada'),
        ),
        migrations.AddField(
            model_name='armaparticular',
            name='direcao_raias',
            field=models.CharField(blank=True, choices=[('DIREITA', 'Direita'), ('ESQUERDA', 'Esquerda')], help_text='Direção das raias (apenas se alma raiada)', max_length=10, null=True, verbose_name='Direção das Raias'),
        ),
        migrations.AddField(
            model_name='armaparticular',
            name='quantidade_raias',
            field=models.PositiveIntegerField(blank=True, help_text='Número de raias (apenas se alma raiada)', null=True, verbose_name='Quantidade de Raias'),
        ),
        migrations.AlterField(
            model_name='arma',
            name='numero_registro_policia',
            field=models.CharField(blank=True, help_text='Número do registro SIGMA', max_length=100, null=True, verbose_name='Nº Registro SIGMA'),
        ),
        migrations.AlterField(
            model_name='armaparticular',
            name='numero_registro_policia',
            field=models.CharField(help_text='Número do registro SIGMA', max_length=100, verbose_name='Nº Registro SIGMA'),
        ),
    ]
