# Generated by Django 5.2.3 on 2025-11-17 22:44

import django.db.models.deletion
import militares.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0400_adicionar_campos_raias_arma_particular'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoMunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem da munição', null=True, upload_to=militares.models.municao_imagem_upload_path, verbose_name='Imagem da Munição')),
                ('calibre', models.CharField(choices=[('380', '.380'), ('9MM', '9mm'), ('40', '.40'), ('45', '.45'), ('556', '5.56mm'), ('762', '7.62mm'), ('12', '12 Gauge'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Calibre')),
                ('tipo_municao', models.CharField(choices=[('FMJ', 'FMJ (Full Metal Jacket)'), ('HP', 'HP (Hollow Point)'), ('JHP', 'JHP (Jacketed Hollow Point)'), ('SP', 'SP (Soft Point)'), ('BT', 'BT (Boat Tail)'), ('TRACER', 'Tracer (Rastreadora)'), ('INCENDIARIA', 'Incendiária'), ('PERFURANTE', 'Perfurante'), ('FRANGIVEL', 'Frangível'), ('OUTROS', 'Outros')], help_text='Tipo de projétil', max_length=20, verbose_name='Tipo de Munição')),
                ('marca', models.CharField(help_text='Ex: CBC, Magtech, Federal', max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Ex: FMJ 115gr, HP 124gr', max_length=100, verbose_name='Modelo/Tipo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição adicional da munição', null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Configuração de Munição',
                'verbose_name_plural': 'Configurações de Munições',
                'ordering': ['calibre', 'marca', 'modelo'],
            },
        ),
        migrations.RemoveIndex(
            model_name='municao',
            name='militares_m_calibre_247a17_idx',
        ),
        migrations.RemoveIndex(
            model_name='municao',
            name='militares_m_orgao_i_677f2b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='municao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='configuracaomunicao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_municao_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddIndex(
            model_name='configuracaomunicao',
            index=models.Index(fields=['calibre', 'tipo_municao'], name='militares_c_calibre_607f00_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracaomunicao',
            index=models.Index(fields=['marca', 'modelo'], name='militares_c_marca_251045_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracaomunicao',
            index=models.Index(fields=['ativo'], name='militares_c_ativo_3ca713_idx'),
        ),
        migrations.AddConstraint(
            model_name='configuracaomunicao',
            constraint=models.UniqueConstraint(fields=('calibre', 'tipo_municao', 'marca', 'modelo'), name='unique_configuracao_municao'),
        ),
    ]
