# Generated by Django 5.2.3 on 2025-11-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0401_configuracaomunicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='tipo',
            field=models.CharField(choices=[('PISTOLA', 'Pistola'), ('REVOLVER', 'Revólver'), ('GARRUCHA', 'Garrucha'), ('CARABINA', 'Carabina'), ('RIFLE', 'Rifle'), ('FUZIL', 'Fuzil'), ('CARABINA_TATICA_PCC', 'Carabina Tática (PCC)'), ('ESPINGARDA_ALMA_LISA', 'Espingarda (alma lisa)'), ('ESCOPETA_PUMP', 'Escopeta Pump'), ('ESPINGARDA_SEMIAUTOMATICA', 'Espingarda Semiautomática'), ('SUBMETRALHADORA', 'Submetralhadora'), ('METRALHADORA_LEVE', 'Metralhadora Leve'), ('METRALHADORA_MEDIA', 'Metralhadora Média'), ('METRALHADORA_PESADA', 'Metralhadora Pesada'), ('RIFLE_PRECISAO_SNIPER', 'Rifle de Precisão (Sniper)'), ('FUZIL_ANTIMATERIAL_50', 'Fuzil Antimaterial (.50)'), ('LANCADOR_GRANADAS_37_38', 'Lançador de Granadas 37/38 mm'), ('LANCADOR_GRANADAS_40', 'Lançador de Granadas 40 mm'), ('ARMA_ELASTOMERO', 'Arma de Elastômero (menos letal)'), ('PISTOLA_CHOQUE_TASER', 'Pistola de Choque (Taser)'), ('ARMA_PRESSAO_AIRGUN', 'Arma de Pressão (airgun)'), ('ARMA_AIRSOFT', 'Arma de Airsoft'), ('ARMA_COMBINADA', 'Arma Combinada (duas almas)'), ('ARMA_HISTORICA_COLECIONAVEL', 'Arma Histórica / Colecionável'), ('FACA', 'Faca'), ('BAIONETA', 'Baioneta'), ('OUTROS', 'Outros')], max_length=30, verbose_name='Tipo de Arma'),
        ),
        migrations.AlterField(
            model_name='armaparticular',
            name='tipo',
            field=models.CharField(choices=[('PISTOLA', 'Pistola'), ('REVOLVER', 'Revólver'), ('GARRUCHA', 'Garrucha'), ('CARABINA', 'Carabina'), ('RIFLE', 'Rifle'), ('FUZIL', 'Fuzil'), ('CARABINA_TATICA_PCC', 'Carabina Tática (PCC)'), ('ESPINGARDA_ALMA_LISA', 'Espingarda (alma lisa)'), ('ESCOPETA_PUMP', 'Escopeta Pump'), ('ESPINGARDA_SEMIAUTOMATICA', 'Espingarda Semiautomática'), ('SUBMETRALHADORA', 'Submetralhadora'), ('METRALHADORA_LEVE', 'Metralhadora Leve'), ('METRALHADORA_MEDIA', 'Metralhadora Média'), ('METRALHADORA_PESADA', 'Metralhadora Pesada'), ('RIFLE_PRECISAO_SNIPER', 'Rifle de Precisão (Sniper)'), ('FUZIL_ANTIMATERIAL_50', 'Fuzil Antimaterial (.50)'), ('LANCADOR_GRANADAS_37_38', 'Lançador de Granadas 37/38 mm'), ('LANCADOR_GRANADAS_40', 'Lançador de Granadas 40 mm'), ('ARMA_ELASTOMERO', 'Arma de Elastômero (menos letal)'), ('PISTOLA_CHOQUE_TASER', 'Pistola de Choque (Taser)'), ('ARMA_PRESSAO_AIRGUN', 'Arma de Pressão (airgun)'), ('ARMA_AIRSOFT', 'Arma de Airsoft'), ('ARMA_COMBINADA', 'Arma Combinada (duas almas)'), ('ARMA_HISTORICA_COLECIONAVEL', 'Arma Histórica / Colecionável'), ('FACA', 'Faca'), ('OUTROS', 'Outros')], max_length=30, verbose_name='Tipo de Arma'),
        ),
        migrations.AlterField(
            model_name='configuracaoarma',
            name='tipo',
            field=models.CharField(choices=[('PISTOLA', 'Pistola'), ('REVOLVER', 'Revólver'), ('GARRUCHA', 'Garrucha'), ('CARABINA', 'Carabina'), ('RIFLE', 'Rifle'), ('FUZIL', 'Fuzil'), ('CARABINA_TATICA_PCC', 'Carabina Tática (PCC)'), ('ESPINGARDA_ALMA_LISA', 'Espingarda (alma lisa)'), ('ESCOPETA_PUMP', 'Escopeta Pump'), ('ESPINGARDA_SEMIAUTOMATICA', 'Espingarda Semiautomática'), ('SUBMETRALHADORA', 'Submetralhadora'), ('METRALHADORA_LEVE', 'Metralhadora Leve'), ('METRALHADORA_MEDIA', 'Metralhadora Média'), ('METRALHADORA_PESADA', 'Metralhadora Pesada'), ('RIFLE_PRECISAO_SNIPER', 'Rifle de Precisão (Sniper)'), ('FUZIL_ANTIMATERIAL_50', 'Fuzil Antimaterial (.50)'), ('LANCADOR_GRANADAS_37_38', 'Lançador de Granadas 37/38 mm'), ('LANCADOR_GRANADAS_40', 'Lançador de Granadas 40 mm'), ('ARMA_ELASTOMERO', 'Arma de Elastômero (menos letal)'), ('PISTOLA_CHOQUE_TASER', 'Pistola de Choque (Taser)'), ('ARMA_PRESSAO_AIRGUN', 'Arma de Pressão (airgun)'), ('ARMA_AIRSOFT', 'Arma de Airsoft'), ('ARMA_COMBINADA', 'Arma Combinada (duas almas)'), ('ARMA_HISTORICA_COLECIONAVEL', 'Arma Histórica / Colecionável'), ('ACESSORIO', 'Acessório'), ('OUTROS', 'Outros')], max_length=30, verbose_name='Tipo de Arma'),
        ),
    ]
