# Generated by Django 5.0.2 on 2025-11-18 15:35

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import militares.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0403_atualizar_calibres_municoes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialEscolar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Material"),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EPI", "EPI - Equipamento de Proteção Individual"),
                            ("UNIFORME", "Uniforme"),
                            ("MATERIAL_ESCRITA", "Material de Escrita"),
                            ("LIVRO", "Livro"),
                            ("APOSTILA", "Apostila"),
                            ("EQUIPAMENTO", "Equipamento"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Material",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "quantidade_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade Total"
                    ),
                ),
                (
                    "quantidade_disponivel",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade Disponível"
                    ),
                ),
                (
                    "unidade_medida",
                    models.CharField(
                        default="UN", max_length=20, verbose_name="Unidade de Medida"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Escolar",
                "verbose_name_plural": "Materiais Escolares",
                "ordering": ["tipo", "nome"],
            },
        ),
        migrations.RemoveField(
            model_name="funcaomenuconfig",
            name="show_avisos",
        ),
        migrations.RemoveField(
            model_name="funcaomenuconfig",
            name="show_ordens_servico",
        ),
        migrations.AlterField(
            model_name="armaparticular",
            name="autorizado_uso_servico",
            field=models.BooleanField(
                default=False,
                help_text="Se o militar está autorizado a portar a arma",
                verbose_name="Autorizado a Portar a Arma",
            ),
        ),
        migrations.AlterField(
            model_name="permissaofuncao",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("MENU_DASHBOARD", "Dashboard"),
                    ("MENU_EFETIVO", "Efetivo"),
                    ("MENU_AFASTAMENTOS", "Afastamentos"),
                    ("MENU_FERIAS", "Férias"),
                    ("MENU_VIATURAS", "Viaturas"),
                    ("MENU_FROTA", "Frota"),
                    ("MENU_EQUIPAMENTOS_OPERACIONAIS", "Equipamentos Operacionais"),
                    ("MENU_SECAO_PROMOCOES", "Seção de Promoções"),
                    ("MENU_MEDALHAS", "Medalhas"),
                    ("MENU_PUBLICACOES", "Publicações"),
                    ("MENU_ESCALAS", "Escalas de Serviço"),
                    ("MENU_PLANEJADAS", "Operações Planejadas"),
                    ("MENU_CONFIGURACOES", "Configurações"),
                    ("MENU_RELATORIOS", "Relatórios"),
                    ("MENU_PESSOAL", "Pessoal"),
                    ("MENU_BENS_MOVEIS", "Bens Móveis"),
                    ("MENU_ALMOXARIFADO", "Almoxarifado"),
                    ("MENU_PROCESSOS", "Processos Administrativos"),
                    ("SUBMENU_MINHAS_INFORMACOES", "Minhas Informações"),
                    ("SUBMENU_MINHA_FICHA_CADASTRO", "Minha Ficha de Cadastro"),
                    (
                        "SUBMENU_MINHA_FICHA_CONCEITO_OFICIAL",
                        "Minha Ficha de Conceito (Oficial)",
                    ),
                    (
                        "SUBMENU_MINHA_FICHA_CONCEITO_PRACA",
                        "Minha Ficha de Conceito (Praça)",
                    ),
                    (
                        "SUBMENU_CRIAR_FICHA_CONCEITO_OFICIAL",
                        "Criar Ficha de Conceito (Oficial)",
                    ),
                    (
                        "SUBMENU_CRIAR_FICHA_CONCEITO_PRACA",
                        "Criar Ficha de Conceito (Praça)",
                    ),
                    ("SUBMENU_ATIVOS", "Militares Ativos"),
                    ("SUBMENU_INATIVOS", "Militares Inativos"),
                    ("SUBMENU_LOTACOES", "Lotações"),
                    ("SUBMENU_AFASTAMENTOS", "Afastamentos"),
                    ("SUBMENU_FICHAS_OFICIAIS", "Fichas de Conceito (Oficiais)"),
                    ("SUBMENU_FICHAS_PRACAS", "Fichas de Conceito (Praças)"),
                    ("SUBMENU_QUADROS_ACESSO", "Quadros de Acesso"),
                    ("SUBMENU_QUADROS_FIXACAO", "Quadros de Fixação de Vagas"),
                    ("SUBMENU_CALENDARIOS", "Calendários de Promoções"),
                    ("SUBMENU_COMISSOES", "Comissões de Promoções"),
                    ("SUBMENU_MEUS_VOTOS", "Meus Votos"),
                    ("SUBMENU_PROMOCOES", "Promoções"),
                    ("SUBMENU_ALMANAQUES", "Almanaques"),
                    ("SUBMENU_INTERSTICIOS", "Interstícios"),
                    ("SUBMENU_GERENCIAR_INTERSTICIOS", "Gerenciar Interstícios"),
                    ("SUBMENU_GERENCIAR_PREVISAO", "Gerenciar Previsão"),
                    ("SUBMENU_MEDALHAS_CONCESSOES", "Concessões de Medalhas"),
                    ("SUBMENU_MEDALHAS_PROPOSTAS", "Propostas de Medalhas"),
                    ("SUBMENU_ELEGIVEIS", "Elegíveis"),
                    ("SUBMENU_PROPOSTAS", "Propostas"),
                    ("SUBMENU_CONCEDER_MEDALHA", "Conceder Medalha"),
                    ("SUBMENU_PUBLICACOES", "Publicações"),
                    ("SUBMENU_NOTAS", "Notas"),
                    ("SUBMENU_NOTAS_RESERVADAS", "Notas Reservadas"),
                    ("SUBMENU_BOLETINS_OSTENSIVOS", "Boletins Ostensivos"),
                    ("SUBMENU_BOLETINS_RESERVADOS", "Boletins Reservados"),
                    ("SUBMENU_BOLETINS_ESPECIAIS", "Boletins Especiais"),
                    ("SUBMENU_ESCALAS_DASHBOARD", "Dashboard de Escalas"),
                    ("SUBMENU_ESCALAS_LISTA", "Lista de Escalas"),
                    ("SUBMENU_ESCALAS_CONFIGURACAO", "Configurações de Escalas"),
                    ("SUBMENU_ESCALAS_BANCO_HORAS", "Banco de Horas"),
                    ("SUBMENU_ESCALAS_OPERACOES", "Operações de Escalas"),
                    ("SUBMENU_VIATURAS", "Viaturas"),
                    ("SUBMENU_CONTROLE_COMBUSTIVEL", "Controle de Combustível"),
                    ("SUBMENU_MANUTENCOES", "Manutenções"),
                    ("SUBMENU_TROCAS_OLEO", "Trocas de Óleo"),
                    ("SUBMENU_LICENCIAMENTOS", "Licenciamentos"),
                    ("SUBMENU_RODAGENS", "Rodagens"),
                    ("SUBMENU_PAINEL_GUARDA", "Painel de Guarda"),
                    ("SUBMENU_EQUIPAMENTOS_OPERACIONAIS", "Equipamentos Operacionais"),
                    (
                        "SUBMENU_EQUIPAMENTOS_OPERACIONAIS_COMBUSTIVEL",
                        "Controle de Combustível (Equipamentos)",
                    ),
                    (
                        "SUBMENU_EQUIPAMENTOS_OPERACIONAIS_MANUTENCOES",
                        "Manutenções (Equipamentos)",
                    ),
                    (
                        "SUBMENU_EQUIPAMENTOS_OPERACIONAIS_TROCAS_OLEO",
                        "Trocas de Óleo (Equipamentos)",
                    ),
                    (
                        "SUBMENU_EQUIPAMENTOS_OPERACIONAIS_TEMPOS_USO",
                        "Controle de Uso por Horas",
                    ),
                    ("SUBMENU_ALMOXARIFADO_ITENS", "Itens do Almoxarifado"),
                    ("SUBMENU_ALMOXARIFADO_ENTRADAS", "Entradas do Almoxarifado"),
                    ("SUBMENU_ALMOXARIFADO_SAIDAS", "Saídas do Almoxarifado"),
                    ("SUBMENU_ALMOXARIFADO_REQUISICOES", "Requisições do Almoxarifado"),
                    ("SUBMENU_USUARIOS", "Gerenciar Usuários"),
                    ("SUBMENU_PERMISSOES", "Funções Militares"),
                    ("SUBMENU_ORGAOS", "Órgãos"),
                    ("SUBMENU_ORGANOGRAMA", "Organograma"),
                    ("SUBMENU_LOGS", "Logs do Sistema"),
                    ("SUBMENU_TITULOS_PUBLICACAO", "Títulos de Publicações"),
                    ("SUBMENU_ADMINISTRACAO", "Administração"),
                    ("SUBMENU_GRANDES_COMANDOS", "Grandes Comandos"),
                    ("SUBMENU_UNIDADES", "Unidades"),
                    ("SUBMENU_SUB_UNIDADES", "Sub-Unidades"),
                    ("SUBMENU_RELATORIOS_MILITARES", "Relatórios de Militares"),
                    ("SUBMENU_RELATORIOS_PROMOCOES", "Relatórios de Promoções"),
                    ("SUBMENU_RELATORIOS_MEDALHAS", "Relatórios de Medalhas"),
                    ("SUBMENU_RELATORIOS_PUBLICACOES", "Relatórios de Publicações"),
                    ("SUBMENU_RELATORIOS_GERAIS", "Relatórios Gerais"),
                    ("ATIVOS_VISUALIZAR", "Visualizar Militares Ativos"),
                    ("ATIVOS_CRIAR", "Criar Militares Ativos"),
                    ("ATIVOS_EDITAR", "Editar Militares Ativos"),
                    ("ATIVOS_EXCLUIR", "Excluir Militares Ativos"),
                    ("ATIVOS_TRANSFERIR", "Transferir Militares Ativos"),
                    ("ATIVOS_PROMOVER", "Promover Militares Ativos"),
                    ("ATIVOS_INATIVAR", "Inativar Militares Ativos"),
                    ("ATIVOS_FICHA_CONCEITO", "Gerenciar Fichas de Conceito"),
                    ("ATIVOS_EXPORTAR", "Exportar Militares Ativos"),
                    ("ATIVOS_DASHBOARD", "Dashboard Militares Ativos"),
                    ("ATIVOS_REORDENAR", "Reordenar Militares Ativos"),
                    ("INATIVOS_VISUALIZAR", "Visualizar Militares Inativos"),
                    ("INATIVOS_EDITAR", "Editar Militares Inativos"),
                    ("INATIVOS_EXPORTAR", "Exportar Militares Inativos"),
                    ("LOTACOES_VISUALIZAR", "Visualizar Lotações"),
                    ("LOTACOES_CRIAR", "Criar Lotações"),
                    ("LOTACOES_EDITAR", "Editar Lotações"),
                    ("LOTACOES_EXCLUIR", "Excluir Lotações"),
                    ("INATIVOS_EDITAR", "Editar Militares Inativos"),
                    ("INATIVOS_EXCLUIR", "Excluir Militares Inativos"),
                    ("INATIVOS_REATIVAR", "Reativar Militares Inativos"),
                    ("LOTACOES_VISUALIZAR", "Visualizar Lotações"),
                    ("LOTACOES_CRIAR", "Criar Lotações"),
                    ("LOTACOES_EDITAR", "Editar Lotações"),
                    ("LOTACOES_EXCLUIR", "Excluir Lotações"),
                    ("DETAIL_FICHAS_CONCEITO", "Visualizar Fichas de Conceito"),
                    ("DETAIL_PUNICOES", "Visualizar Punições e Elogios"),
                    ("DETAIL_MEDALHAS", "Visualizar Medalhas"),
                    ("DETAIL_CONTATO", "Visualizar Contato"),
                    ("QUADROS_FIXACAO_VISUALIZAR", "Visualizar Quadros de Fixação"),
                    ("QUADROS_FIXACAO_CRIAR", "Criar Quadros de Fixação"),
                    ("QUADROS_FIXACAO_EDITAR", "Editar Quadros de Fixação"),
                    ("QUADROS_FIXACAO_EXCLUIR", "Excluir Quadros de Fixação"),
                    ("QUADROS_ACESSO_VISUALIZAR", "Visualizar Quadros de Acesso"),
                    ("QUADROS_ACESSO_CRIAR", "Criar Quadros de Acesso"),
                    ("QUADROS_ACESSO_EDITAR", "Editar Quadros de Acesso"),
                    ("QUADROS_ACESSO_EXCLUIR", "Excluir Quadros de Acesso"),
                    (
                        "COMISSOES_OFICIAIS_VISUALIZAR",
                        "Visualizar Comissões de Oficiais",
                    ),
                    ("COMISSOES_OFICIAIS_CRIAR", "Criar Comissões de Oficiais"),
                    ("COMISSOES_OFICIAIS_EDITAR", "Editar Comissões de Oficiais"),
                    ("COMISSOES_OFICIAIS_EXCLUIR", "Excluir Comissões de Oficiais"),
                    ("COMISSOES_PRACAS_VISUALIZAR", "Visualizar Comissões de Praças"),
                    ("COMISSOES_PRACAS_CRIAR", "Criar Comissões de Praças"),
                    ("COMISSOES_PRACAS_EDITAR", "Editar Comissões de Praças"),
                    ("COMISSOES_PRACAS_EXCLUIR", "Excluir Comissões de Praças"),
                    ("QUADROS_ACESSO_ASSINAR", "Assinar Quadros de Acesso"),
                    ("QUADROS_ACESSO_HOMOLOGAR", "Homologar Quadros de Acesso"),
                    ("QUADROS_ACESSO_DESHOMOLOGAR", "Deshomologar Quadros de Acesso"),
                    ("QUADROS_ACESSO_ELABORAR", "Elaborar Quadros de Acesso"),
                    ("QUADROS_ACESSO_REGENERAR", "Regenerar Quadros de Acesso"),
                    ("QUADROS_ACESSO_GERAR_PDF", "Gerar PDF de Quadros de Acesso"),
                    ("SUBMENU_MEDALHAS_CONCESSOES", "Concessões de Medalhas"),
                    ("SUBMENU_MEDALHAS_PROPOSTAS", "Propostas de Medalhas"),
                    ("SUBMENU_ELEGIVEIS", "Elegíveis"),
                    ("SUBMENU_PROPOSTAS", "Propostas"),
                    ("SUBMENU_NOTAS_LISTA", "Lista de Notas"),
                    ("SUBMENU_PUBLICACOES", "Publicações"),
                    ("SUBMENU_NOTAS", "Notas"),
                    ("NOTAS_VISUALIZAR", "Visualizar Notas"),
                    ("NOTAS_CRIAR", "Criar Notas"),
                    ("NOTAS_EDITAR", "Editar Notas"),
                    ("NOTAS_EXCLUIR", "Excluir Notas"),
                    ("NOTAS_REVISAR", "Revisar Notas"),
                    ("NOTAS_APROVAR", "Aprovar Notas"),
                    ("NOTAS_PUBLICAR", "Publicar Notas"),
                    ("NOTAS_ADMINISTRAR", "Administrar Notas"),
                    ("PUBLICACOES_VISUALIZAR", "Visualizar Publicações"),
                    ("PUBLICACOES_CRIAR", "Criar Publicações"),
                    ("PUBLICACOES_EDITAR", "Editar Publicações"),
                    ("PUBLICACOES_EXCLUIR", "Excluir Publicações"),
                    ("PUBLICACOES_PUBLICAR", "Publicar Publicações"),
                    ("SUBMENU_INTERSTICIOS", "Interstícios"),
                    ("SUBMENU_GERENCIAR_INTERSTICIOS", "Gerenciar Interstícios"),
                    ("SUBMENU_GERENCIAR_PREVISAO", "Gerenciar Previsão"),
                    ("SUBMENU_USUARIOS", "Usuários"),
                    ("SUBMENU_PERMISSOES", "Permissões"),
                    ("SUBMENU_LOGS", "Logs"),
                    ("SUBMENU_ADMINISTRACAO", "Administração"),
                    ("SUBMENU_PLANEJADAS", "Operações Planejadas"),
                    ("SUBMENU_OPERADOR_PLANEJADAS", "Operador de Planejadas"),
                    ("SUBMENU_FISCAL_PLANEJADAS", "Fiscal de Planejadas"),
                    ("SUBMENU_LIQUIDACAO", "Liquidação"),
                    ("PLANEJADAS_VISUALIZAR", "Visualizar Planejadas"),
                    ("PLANEJADAS_CRIAR", "Criar Planejadas"),
                    ("PLANEJADAS_EDITAR", "Editar Planejadas"),
                    ("PLANEJADAS_EXCLUIR", "Excluir Planejadas"),
                    ("PLANEJADAS_ADICIONAR_MILITAR", "Adicionar Militar à Planejada"),
                    ("PLANEJADAS_REMOVER_MILITAR", "Remover Militar da Planejada"),
                    ("PLANEJADAS_ASSINAR_OPERADOR", "Assinar como Operador"),
                    ("PLANEJADAS_ASSINAR_FISCAL", "Assinar como Fiscal"),
                    (
                        "ORCAMENTOS_PLANEJADAS_VISUALIZAR",
                        "Visualizar Orçamentos de Planejadas",
                    ),
                    ("ORCAMENTOS_PLANEJADAS_CRIAR", "Criar Orçamentos de Planejadas"),
                    ("ORCAMENTOS_PLANEJADAS_EDITAR", "Editar Orçamentos de Planejadas"),
                    (
                        "ORCAMENTOS_PLANEJADAS_EXCLUIR",
                        "Excluir Orçamentos de Planejadas",
                    ),
                    ("ORCAMENTOS_PLANEJADAS_DISTRIBUIR", "Distribuir Orçamentos"),
                    ("ORCAMENTOS_PLANEJADAS_APROVAR", "Aprovar Orçamentos"),
                    ("VIATURAS", "Viaturas"),
                    ("EQUIPAMENTOS_OPERACIONAIS", "Equipamentos Operacionais"),
                    ("ARMAS", "Armas"),
                    ("MUNICOES", "Munições"),
                    ("BENS_MOVEIS", "Bens Móveis"),
                    ("PUBLICACOES", "Publicações"),
                    ("ELOGIOS", "Elogios"),
                    ("PUNICOES", "Punições"),
                    ("FICHAS_CONCEITO", "Fichas de Conceito"),
                    ("QUADROS_FIXACAO", "Quadros de Fixação"),
                    ("QUADROS_ACESSO", "Quadros de Acesso"),
                    ("COMISSOES", "Comissões"),
                    ("ESCALAS", "Escalas de Serviço"),
                    ("NOTAS", "Notas"),
                    ("BOLETINS_OSTENSIVOS", "Boletins Ostensivos"),
                    ("BOLETINS_RESERVADOS", "Boletins Reservados"),
                    ("BOLETINS_ESPECIAIS", "Boletins Especiais"),
                    ("AVISOS", "Avisos"),
                    ("ORDENS_SERVICO", "Ordens de Serviço"),
                    ("MEDALHAS", "Medalhas"),
                    ("USUARIOS", "Usuários"),
                    ("RELATORIOS", "Relatórios"),
                    ("PLANEJADAS", "Operações Planejadas"),
                    ("ORCAMENTOS_PLANEJADAS", "Orçamentos de Planejadas"),
                    ("AFASTAMENTOS", "Afastamentos"),
                    ("MILITARES", "Militares"),
                    ("ATIVOS", "Militares Ativos"),
                    ("INATIVOS", "Militares Inativos"),
                    ("LOTACOES", "Lotações"),
                    ("ALMOXARIFADO", "Almoxarifado"),
                    ("SUBMENU_ALMOXARIFADO_ITENS", "Itens do Almoxarifado"),
                    ("SUBMENU_ALMOXARIFADO_ENTRADAS", "Entradas do Almoxarifado"),
                    ("SUBMENU_ALMOXARIFADO_SAIDAS", "Saídas do Almoxarifado"),
                ],
                max_length=50,
                verbose_name="Módulo",
            ),
        ),
        migrations.CreateModel(
            name="AlunoEnsino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Matrícula do Aluno"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=militares.models.foto_aluno_upload_path,
                        verbose_name="Foto",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("DESLIGADO", "Desligado"),
                            ("TRANSFERIDO", "Transferido"),
                            ("CONCLUIDO", "Concluído"),
                            ("JUBILADO", "Jubilado"),
                            ("EXCLUIDO", "Excluído"),
                        ],
                        default="ATIVO",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "data_matricula",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Matrícula"
                    ),
                ),
                (
                    "data_desligamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Desligamento"
                    ),
                ),
                (
                    "motivo_desligamento",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo do Desligamento"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aluno_ensino",
                        to="militares.militar",
                        verbose_name="Militar/Civil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
                "ordering": ["matricula"],
            },
        ),
        migrations.CreateModel(
            name="DisciplinaEnsino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Disciplina"),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "carga_horaria",
                    models.PositiveIntegerField(verbose_name="Carga Horária (horas)"),
                ),
                ("ementa", models.TextField(verbose_name="Ementa")),
                (
                    "conteudo_programatico",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Conteúdo Programático"
                    ),
                ),
                (
                    "metodos_avaliacao",
                    models.TextField(verbose_name="Métodos de Avaliação"),
                ),
                (
                    "frequencia_minima",
                    models.DecimalField(
                        decimal_places=2,
                        default=75.0,
                        help_text="Percentual mínimo de frequência para aprovação",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Frequência Mínima (%)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "instrutor_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disciplinas_responsaveis",
                        to="militares.militar",
                        verbose_name="Instrutor Responsável",
                    ),
                ),
                (
                    "monitores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="disciplinas_monitoradas",
                        to="militares.militar",
                        verbose_name="Monitores",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="CursoEnsino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Curso"),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único do curso",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("finalidade", models.TextField(verbose_name="Finalidade")),
                (
                    "publico_alvo",
                    models.CharField(
                        choices=[
                            ("PRACAS", "Praças"),
                            ("OFICIAIS", "Oficiais"),
                            ("CIVIS", "Civis"),
                            ("MISTO", "Misto"),
                        ],
                        max_length=20,
                        verbose_name="Público-Alvo",
                    ),
                ),
                (
                    "carga_horaria",
                    models.PositiveIntegerField(
                        verbose_name="Carga Horária Total (horas)"
                    ),
                ),
                (
                    "pre_requisitos",
                    models.TextField(
                        blank=True, null=True, verbose_name="Pré-requisitos"
                    ),
                ),
                (
                    "legislacao",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Legislação e Normas Internas",
                    ),
                ),
                (
                    "ementa",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ensino/cursos/ementas/",
                        verbose_name="Ementa",
                    ),
                ),
                (
                    "plano_curso",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ensino/cursos/planos/",
                        verbose_name="Plano de Curso",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "coordenador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cursos_coordenados",
                        to="militares.militar",
                        verbose_name="Coordenador do Curso",
                    ),
                ),
                (
                    "disciplinas_complementares",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cursos_complementares",
                        to="militares.disciplinaensino",
                        verbose_name="Disciplinas Complementares",
                    ),
                ),
                (
                    "disciplinas_obrigatorias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cursos_obrigatorios",
                        to="militares.disciplinaensino",
                        verbose_name="Disciplinas Obrigatórias",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso de Ensino",
                "verbose_name_plural": "Cursos de Ensino",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ATESTADO", "Atestado Médico"),
                            ("LAUDO", "Laudo"),
                            ("AUTORIZACAO", "Autorização"),
                            ("DECLARACAO", "Declaração"),
                            ("HISTORICO", "Histórico Escolar"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Documento"),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=militares.models.documento_ensino_upload_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Emissão"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Vencimento"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Upload"
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="militares.alunoensino",
                        verbose_name="Aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento do Aluno",
                "verbose_name_plural": "Documentos dos Alunos",
                "ordering": ["-data_upload"],
            },
        ),
        migrations.CreateModel(
            name="InstrutorEnsino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "especialidades",
                    models.TextField(
                        blank=True, null=True, verbose_name="Especialidades"
                    ),
                ),
                (
                    "assinatura_digital",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ensino/instrutores/assinaturas/",
                        verbose_name="Assinatura Digital",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrutor_ensino",
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrutor",
                "verbose_name_plural": "Instrutores",
                "ordering": ["militar__nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="CautelaMaterialEscolar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(verbose_name="Quantidade")),
                (
                    "data_emprestimo",
                    models.DateField(verbose_name="Data de Empréstimo"),
                ),
                (
                    "data_devolucao_prevista",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Devolução Prevista"
                    ),
                ),
                (
                    "data_devolucao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Devolução"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EMPRESTADO", "Emprestado"),
                            ("DEVOLVIDO", "Devolvido"),
                            ("DANIFICADO", "Danificado"),
                            ("EXTRAVIADO", "Extraviado"),
                        ],
                        default="EMPRESTADO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Registro"
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cautelas_material",
                        to="militares.alunoensino",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "responsavel_emprestimo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_emprestadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável pelo Empréstimo",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cautelas",
                        to="militares.materialescolar",
                        verbose_name="Material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cautela de Material Escolar",
                "verbose_name_plural": "Cautelas de Material Escolar",
                "ordering": ["-data_emprestimo"],
            },
        ),
        migrations.CreateModel(
            name="TurmaEnsino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificacao",
                    models.CharField(
                        help_text="Ex: Curso X – Turma Alfa 2025",
                        max_length=200,
                        verbose_name="Identificação",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_fim", models.DateField(verbose_name="Data de Término")),
                (
                    "ativa",
                    models.BooleanField(default=True, verbose_name="Turma Ativa"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "coordenador_turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turmas_coordenadas",
                        to="militares.militar",
                        verbose_name="Coordenador de Turma",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turmas",
                        to="militares.cursoensino",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "instrutor_chefe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turmas_chefiadas",
                        to="militares.militar",
                        verbose_name="Instrutor-Chefe",
                    ),
                ),
                (
                    "monitores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="turmas_monitoradas",
                        to="militares.militar",
                        verbose_name="Monitores",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "ordering": ["-data_inicio", "identificacao"],
            },
        ),
        migrations.CreateModel(
            name="OcorrenciaDisciplinar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("APRESENTACAO", "Apresentação"),
                            ("ATRASO", "Atraso"),
                            ("FALTA", "Falta"),
                            ("PUNICAO", "Punição"),
                            ("ADVERTENCIA", "Advertência"),
                            ("SUSPENSAO", "Suspensão"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Ocorrência",
                    ),
                ),
                (
                    "gravidade",
                    models.CharField(
                        choices=[
                            ("LEVE", "Leve"),
                            ("MEDIA", "Média"),
                            ("GRAVE", "Grave"),
                            ("GRAVISSIMA", "Gravíssima"),
                        ],
                        default="LEVE",
                        max_length=20,
                        verbose_name="Gravidade",
                    ),
                ),
                (
                    "data_ocorrencia",
                    models.DateField(verbose_name="Data da Ocorrência"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "medidas_adotadas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Medidas Adotadas"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Registro"
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="militares.alunoensino",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "responsavel_registro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocorrencias_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável pelo Registro",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="militares.turmaensino",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência Disciplinar",
                "verbose_name_plural": "Ocorrências Disciplinares",
                "ordering": ["-data_ocorrencia"],
            },
        ),
        migrations.CreateModel(
            name="EscalaInstrucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_escala", models.DateField(verbose_name="Data da Escala")),
                ("hora_inicio", models.TimeField(verbose_name="Hora de Início")),
                ("hora_fim", models.TimeField(verbose_name="Hora de Término")),
                ("local", models.CharField(max_length=100, verbose_name="Local")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalas",
                        to="militares.disciplinaensino",
                        verbose_name="Disciplina",
                    ),
                ),
                (
                    "instrutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalas_instrucao",
                        to="militares.militar",
                        verbose_name="Instrutor",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalas",
                        to="militares.turmaensino",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escala de Instrução",
                "verbose_name_plural": "Escalas de Instrução",
                "ordering": ["data_escala", "hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="CertificadoEnsino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Número do Certificado",
                    ),
                ),
                ("data_conclusao", models.DateField(verbose_name="Data de Conclusão")),
                (
                    "carga_horaria_total",
                    models.PositiveIntegerField(verbose_name="Carga Horária Total"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("GERADO", "Gerado"),
                            ("ASSINADO", "Assinado"),
                            ("ENTREGUE", "Entregue"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "arquivo_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ensino/certificados/",
                        verbose_name="Arquivo PDF",
                    ),
                ),
                (
                    "data_assinatura_comandante",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Assinatura (Comandante)",
                    ),
                ),
                (
                    "data_assinatura_diretor",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Assinatura (Diretor)",
                    ),
                ),
                (
                    "data_entrega",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Entrega"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to="militares.alunoensino",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "assinado_por_comandante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificados_assinados_comandante",
                        to="militares.militar",
                        verbose_name="Assinado por (Comandante)",
                    ),
                ),
                (
                    "assinado_por_diretor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificados_assinados_diretor",
                        to="militares.militar",
                        verbose_name="Assinado por (Diretor de Ensino)",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to="militares.cursoensino",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to="militares.turmaensino",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "ordering": ["-data_conclusao", "numero"],
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoEnsino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TEORICA", "Avaliação Teórica"),
                            ("PRATICA", "Avaliação Prática"),
                            ("TESTE_FISICO", "Teste Físico"),
                            ("PROVA_MILITAR", "Prova Militar"),
                            ("ORDEM_FORMA", "Ordem e Forma"),
                            ("MARCHA", "Marcha"),
                            ("ARMAMENTO", "Armamento"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Avaliação",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Avaliação"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("data_avaliacao", models.DateField(verbose_name="Data da Avaliação")),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Peso da avaliação no cálculo da nota final",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Peso",
                    ),
                ),
                (
                    "nota_maxima",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Nota Máxima",
                    ),
                ),
                (
                    "criterios_aprovacao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Critérios de Aprovação"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="militares.disciplinaensino",
                        verbose_name="Disciplina",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="militares.turmaensino",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "ordering": ["-data_avaliacao", "disciplina"],
            },
        ),
        migrations.CreateModel(
            name="AulaEnsino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_aula", models.DateField(verbose_name="Data da Aula")),
                ("hora_inicio", models.TimeField(verbose_name="Hora de Início")),
                ("hora_fim", models.TimeField(verbose_name="Hora de Término")),
                ("local", models.CharField(max_length=100, verbose_name="Local")),
                (
                    "tipo_local",
                    models.CharField(
                        choices=[
                            ("SALA", "Sala de Aula"),
                            ("AUDITORIO", "Auditório"),
                            ("CAMPO", "Campo"),
                            ("PISTA", "Pista"),
                            ("LABORATORIO", "Laboratório"),
                            ("OUTROS", "Outros"),
                        ],
                        default="SALA",
                        max_length=20,
                        verbose_name="Tipo de Local",
                    ),
                ),
                (
                    "conteudo_ministrado",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Conteúdo Ministrado"
                    ),
                ),
                (
                    "assinatura_instrutor",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ensino/aulas/assinaturas/",
                        verbose_name="Assinatura do Instrutor",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ensino/aulas/qrcodes/",
                        verbose_name="QR Code para Chamada",
                    ),
                ),
                (
                    "registro_fotografico",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ensino/aulas/fotos/",
                        verbose_name="Registro Fotográfico",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "instrutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aulas_ministradas",
                        to="militares.militar",
                        verbose_name="Instrutor",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="militares.disciplinaensino",
                        verbose_name="Disciplina",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="militares.turmaensino",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "ordering": ["-data_aula", "-hora_inicio"],
            },
        ),
        migrations.AddField(
            model_name="alunoensino",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alunos",
                to="militares.turmaensino",
                verbose_name="Turma",
            ),
        ),
        migrations.CreateModel(
            name="FrequenciaAula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "presenca",
                    models.CharField(
                        choices=[
                            ("PRESENTE", "Presente"),
                            ("FALTA", "Falta"),
                            ("FALTA_JUSTIFICADA", "Falta Justificada"),
                            ("ATRASO", "Atraso"),
                            ("SAIDA_ANTECIPADA", "Saída Antecipada"),
                        ],
                        default="PRESENTE",
                        max_length=20,
                        verbose_name="Presença",
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(
                        blank=True, null=True, verbose_name="Justificativa"
                    ),
                ),
                (
                    "hora_entrada",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Entrada"
                    ),
                ),
                (
                    "hora_saida",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Saída"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Registro"
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="militares.alunoensino",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="militares.aulaensino",
                        verbose_name="Aula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frequência",
                "verbose_name_plural": "Frequências",
                "ordering": ["aula", "aluno"],
                "unique_together": {("aula", "aluno")},
            },
        ),
        migrations.CreateModel(
            name="NotaAvaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Nota",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_lancamento",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Lançamento"
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="militares.alunoensino",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="militares.avaliacaoensino",
                        verbose_name="Avaliação",
                    ),
                ),
                (
                    "lancado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_lancadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Lançado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Avaliação",
                "verbose_name_plural": "Notas de Avaliação",
                "ordering": ["avaliacao", "aluno"],
                "unique_together": {("avaliacao", "aluno")},
            },
        ),
        migrations.CreateModel(
            name="HistoricoEscolar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequencia_percentual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Frequência (%)",
                    ),
                ),
                (
                    "nota_final",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Nota Final",
                    ),
                ),
                (
                    "aprovado",
                    models.BooleanField(default=False, verbose_name="Aprovado"),
                ),
                (
                    "carga_horaria_cursada",
                    models.PositiveIntegerField(verbose_name="Carga Horária Cursada"),
                ),
                (
                    "data_conclusao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Registro"
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicos",
                        to="militares.alunoensino",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicos",
                        to="militares.cursoensino",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicos",
                        to="militares.disciplinaensino",
                        verbose_name="Disciplina",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicos",
                        to="militares.turmaensino",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico Escolar",
                "verbose_name_plural": "Históricos Escolares",
                "ordering": ["aluno", "curso", "disciplina"],
                "unique_together": {("aluno", "curso", "turma", "disciplina")},
            },
        ),
        migrations.CreateModel(
            name="AproveitamentoDisciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequencia_percentual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Frequência (%)",
                    ),
                ),
                (
                    "nota_final",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Nota Final",
                    ),
                ),
                (
                    "aprovado",
                    models.BooleanField(default=False, verbose_name="Aprovado"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aproveitamentos",
                        to="militares.alunoensino",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aproveitamentos",
                        to="militares.disciplinaensino",
                        verbose_name="Disciplina",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aproveitamentos",
                        to="militares.turmaensino",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aproveitamento",
                "verbose_name_plural": "Aproveitamentos",
                "ordering": ["aluno", "disciplina"],
                "unique_together": {("aluno", "disciplina", "turma")},
            },
        ),
    ]
