# Generated by Django 5.0.2 on 2025-11-18 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "militares",
            "0404_materialescolar_remove_funcaomenuconfig_show_avisos_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitorEnsino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atribuicoes",
                    models.TextField(
                        blank=True,
                        help_text="Principais atribuições e responsabilidades do monitor",
                        null=True,
                        verbose_name="Atribuições",
                    ),
                ),
                (
                    "areas_atuacao",
                    models.TextField(
                        blank=True,
                        help_text="Áreas em que o monitor atua",
                        null=True,
                        verbose_name="Áreas de Atuação",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "instrutor_vinculado",
                    models.ForeignKey(
                        blank=True,
                        help_text="Instrutor ao qual o monitor está vinculado",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitores_vinculados",
                        to="militares.militar",
                        verbose_name="Instrutor Vinculado",
                    ),
                ),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor_ensino",
                        to="militares.militar",
                        verbose_name="Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitor",
                "verbose_name_plural": "Monitores",
                "ordering": ["militar__nome_completo"],
            },
        ),
    ]
