# Generated by Django 5.2.3 on 2025-11-18 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0405_monitorensino'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrutorensino',
            options={'verbose_name': 'Instrutor', 'verbose_name_plural': 'Instrutores'},
        ),
        migrations.AlterModelOptions(
            name='monitorensino',
            options={'verbose_name': 'Monitor', 'verbose_name_plural': 'Monitores'},
        ),
        migrations.RemoveField(
            model_name='cursoensino',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='cursoensino',
            name='disciplinas_complementares',
        ),
        migrations.RemoveField(
            model_name='cursoensino',
            name='disciplinas_obrigatorias',
        ),
        migrations.RemoveField(
            model_name='disciplinaensino',
            name='instrutor_responsavel',
        ),
        migrations.RemoveField(
            model_name='disciplinaensino',
            name='monitores',
        ),
        migrations.RemoveField(
            model_name='monitorensino',
            name='instrutor_vinculado',
        ),
        migrations.RemoveField(
            model_name='turmaensino',
            name='coordenador_turma',
        ),
        migrations.RemoveField(
            model_name='turmaensino',
            name='instrutor_chefe',
        ),
        migrations.RemoveField(
            model_name='turmaensino',
            name='monitores',
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='coordenador_militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_coordenados_militar', to='militares.militar', verbose_name='Coordenador Militar'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='instrutores_curso',
            field=models.ManyToManyField(blank=True, help_text='Instrutores que atuam neste curso', related_name='cursos_instrutores', to='militares.instrutorensino', verbose_name='Instrutores do Curso'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='monitores_curso',
            field=models.ManyToManyField(blank=True, help_text='Monitores que atuam neste curso', related_name='cursos_monitores', to='militares.monitorensino', verbose_name='Monitores do Curso'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='instrutor_responsavel_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas_responsaveis_externo', to='militares.instrutorensino', verbose_name='Instrutor Responsável (Externo)'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='instrutor_responsavel_militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas_responsaveis_militar', to='militares.militar', verbose_name='Instrutor Responsável (Militar)'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='monitores_externos',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_monitoradas_externo', to='militares.monitorensino', verbose_name='Monitores Externos'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='monitores_militares',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_monitoradas_militar', to='militares.militar', verbose_name='Monitores Militares'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='instrutor_vinculado_externo',
            field=models.ForeignKey(blank=True, help_text='Instrutor externo ao qual o monitor está vinculado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitores_vinculados_externo', to='militares.instrutorensino', verbose_name='Instrutor Vinculado (Externo)'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='instrutor_vinculado_militar',
            field=models.ForeignKey(blank=True, help_text='Instrutor militar ao qual o monitor está vinculado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitores_vinculados_militar', to='militares.militar', verbose_name='Instrutor Vinculado (Militar)'),
        ),
        migrations.AddField(
            model_name='turmaensino',
            name='coordenador_turma_militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_coordenadas_militar', to='militares.militar', verbose_name='Coordenador de Turma (Militar)'),
        ),
        migrations.AddField(
            model_name='turmaensino',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, help_text='Disciplinas que serão ministradas nesta turma', related_name='turmas_disciplinas', to='militares.disciplinaensino', verbose_name='Disciplinas da Turma'),
        ),
        migrations.AddField(
            model_name='turmaensino',
            name='instrutor_chefe_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_chefiadas_externo', to='militares.instrutorensino', verbose_name='Instrutor-Chefe (Externo)'),
        ),
        migrations.AddField(
            model_name='turmaensino',
            name='instrutor_chefe_militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_chefiadas_militar', to='militares.militar', verbose_name='Instrutor-Chefe (Militar)'),
        ),
        migrations.AddField(
            model_name='turmaensino',
            name='monitores_externos',
            field=models.ManyToManyField(blank=True, related_name='turmas_monitoradas_externo', to='militares.monitorensino', verbose_name='Monitores Externos'),
        ),
        migrations.AddField(
            model_name='turmaensino',
            name='monitores_militares',
            field=models.ManyToManyField(blank=True, related_name='turmas_monitoradas_militar', to='militares.militar', verbose_name='Monitores Militares'),
        ),
        migrations.AlterField(
            model_name='alunoensino',
            name='militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_ensino', to='militares.militar', verbose_name='Militar'),
        ),
        migrations.AlterField(
            model_name='instrutorensino',
            name='militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrutor_ensino', to='militares.militar', verbose_name='Militar'),
        ),
        migrations.AlterField(
            model_name='monitorensino',
            name='militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_ensino', to='militares.militar', verbose_name='Militar'),
        ),
        migrations.CreateModel(
            name='DisciplinaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OBRIGATORIA', 'Obrigatória'), ('COMPLEMENTAR', 'Complementar'), ('OPTATIVA', 'Optativa')], default='OBRIGATORIA', max_length=20, verbose_name='Tipo')),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem de apresentação da disciplina no curso', verbose_name='Ordem')),
                ('carga_horaria_curso', models.PositiveIntegerField(blank=True, help_text='Carga horária específica desta disciplina neste curso (opcional)', null=True, verbose_name='Carga Horária no Curso')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='militares.cursoensino', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='militares.disciplinaensino', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina do Curso',
                'verbose_name_plural': 'Disciplinas dos Cursos',
                'ordering': ['curso', 'ordem', 'disciplina'],
            },
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='disciplinas',
            field=models.ManyToManyField(help_text='Disciplinas que compõem este curso', related_name='cursos', through='militares.DisciplinaCurso', to='militares.disciplinaensino', verbose_name='Disciplinas do Curso'),
        ),
        migrations.CreateModel(
            name='PessoaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(help_text='Apenas números', max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('tipo_pessoa', models.CharField(choices=[('ALUNO', 'Aluno'), ('INSTRUTOR', 'Instrutor'), ('MONITOR', 'Monitor'), ('ALUNO_INSTRUTOR', 'Aluno e Instrutor'), ('ALUNO_MONITOR', 'Aluno e Monitor'), ('INSTRUTOR_MONITOR', 'Instrutor e Monitor'), ('TODOS', 'Todos os Perfis')], default='ALUNO', help_text='Define o perfil desta pessoa no sistema de ensino', max_length=20, verbose_name='Tipo de Pessoa')),
                ('instituicao_origem', models.CharField(blank=True, help_text='Instituição de onde a pessoa vem (ex: PM, CBM, Civil, etc)', max_length=200, null=True, verbose_name='Instituição de Origem')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ensino/pessoas_externas/fotos/', verbose_name='Foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Pessoa Externa',
                'verbose_name_plural': 'Pessoas Externas',
                'ordering': ['nome_completo'],
                'indexes': [models.Index(fields=['cpf'], name='militares_p_cpf_fce9da_idx'), models.Index(fields=['nome_completo'], name='militares_p_nome_co_e39acf_idx')],
            },
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='pessoa_externa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_ensino', to='militares.pessoaexterna', verbose_name='Pessoa Externa'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='coordenador_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_coordenados_externo', to='militares.pessoaexterna', verbose_name='Coordenador Externo'),
        ),
        migrations.AddField(
            model_name='instrutorensino',
            name='pessoa_externa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrutor_ensino', to='militares.pessoaexterna', verbose_name='Pessoa Externa'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='pessoa_externa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_ensino', to='militares.pessoaexterna', verbose_name='Pessoa Externa'),
        ),
        migrations.AddField(
            model_name='turmaensino',
            name='coordenador_turma_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_coordenadas_externo', to='militares.pessoaexterna', verbose_name='Coordenador de Turma (Externo)'),
        ),
        migrations.AddConstraint(
            model_name='alunoensino',
            constraint=models.CheckConstraint(check=models.Q(militar__isnull=False) | models.Q(pessoa_externa__isnull=False), name='aluno_deve_ter_militar_ou_externo'),
        ),
        migrations.AddConstraint(
            model_name='instrutorensino',
            constraint=models.CheckConstraint(check=models.Q(militar__isnull=False) | models.Q(pessoa_externa__isnull=False), name='instrutor_deve_ter_militar_ou_externo'),
        ),
        migrations.AddConstraint(
            model_name='monitorensino',
            constraint=models.CheckConstraint(check=models.Q(militar__isnull=False) | models.Q(pessoa_externa__isnull=False), name='monitor_deve_ter_militar_ou_externo'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinacurso',
            unique_together={('curso', 'disciplina')},
        ),
    ]
