# Generated by Django 5.2.3 on 2025-11-18 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0406_alter_instrutorensino_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaensino',
            name='ano_vigencia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Vigência'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='arquivos_complementares',
            field=models.FileField(blank=True, null=True, upload_to='disciplinas_arquivos/', verbose_name='Arquivos Complementares'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='carga_horaria_maxima_dia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária Máxima Permitida por Dia'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='carga_horaria_pratica',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária Prática (horas)'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='carga_horaria_teorica',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária Teórica (horas)'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='categoria',
            field=models.CharField(blank=True, choices=[('OPERACIONAL', 'Operacional'), ('ADMINISTRATIVO', 'Administrativo'), ('CONDUTA_MILITAR', 'Conduta Militar'), ('PRE_HOSPITALAR', 'Pré-Hospitalar'), ('SALVAMENTO', 'Salvamento'), ('INCENDIO', 'Incêndio'), ('ENSINO_CIVICO', 'Ensino Cívico'), ('OUTROS', 'Outros')], max_length=50, null=True, verbose_name='Categoria / Área de Conhecimento'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='competencias_desenvolvidas',
            field=models.TextField(blank=True, null=True, verbose_name='Competências Desenvolvidas'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='criterios_avaliacao',
            field=models.TextField(blank=True, null=True, verbose_name='Critérios de Avaliação'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='cronograma_sugerido',
            field=models.TextField(blank=True, null=True, verbose_name='Cronograma Sugerido'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='descricao_geral',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Geral'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='disciplina_substituivel',
            field=models.BooleanField(default=False, verbose_name='Disciplina Substituível por Equivalente?'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='epis_obrigatorios',
            field=models.TextField(blank=True, null=True, verbose_name='EPIs Obrigatórios'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='equipamentos_necessarios',
            field=models.TextField(blank=True, null=True, verbose_name='Equipamentos Necessários'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='forma_registro_frequencia',
            field=models.CharField(blank=True, choices=[('POR_AULA', 'Por Aula'), ('POR_ATIVIDADE', 'Por Atividade Prática'), ('POR_MODULO', 'Por Módulo')], default='POR_AULA', max_length=50, null=True, verbose_name='Forma de Registro de Frequência'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='links_uteis',
            field=models.URLField(blank=True, null=True, verbose_name='Links Úteis'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='materiais_obrigatorios',
            field=models.TextField(blank=True, null=True, verbose_name='Materiais Obrigatórios'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='materiais_utilizados',
            field=models.TextField(blank=True, null=True, verbose_name='Materiais Utilizados em Aula'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='media_minima_aprovacao',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='Nota mínima para aprovação (0-10)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Média Mínima para Aprovação'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='metodologia_ensino',
            field=models.TextField(blank=True, null=True, verbose_name='Metodologia de Ensino'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='normas_seguranca',
            field=models.TextField(blank=True, null=True, verbose_name='Normas de Segurança Aplicáveis'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='numero_encontros',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Encontros/Aulas'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='objetivos',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivos da Disciplina'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='observacoes_administrativas',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Administrativas'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='plano_ensino',
            field=models.FileField(blank=True, null=True, upload_to='planos_ensino/', verbose_name='Plano de Ensino (Upload)'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='pre_requisitos_disciplinas',
            field=models.ManyToManyField(blank=True, related_name='disciplinas_que_requerem', to='militares.disciplinaensino', verbose_name='Pré-requisitos de Disciplinas'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='procedimentos_emergencia',
            field=models.TextField(blank=True, null=True, verbose_name='Procedimentos em Caso de Incidente/Emergência'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='requisitos_infraestrutura',
            field=models.TextField(blank=True, null=True, verbose_name='Requisitos de Infraestrutura'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='requisitos_matricula',
            field=models.TextField(blank=True, null=True, verbose_name='Requisitos de Matrícula'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='riscos_envolvidos',
            field=models.TextField(blank=True, null=True, verbose_name='Riscos Envolvidos'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='semestre_vigencia',
            field=models.CharField(blank=True, choices=[('1', '1º Semestre'), ('2', '2º Semestre'), ('ANUAL', 'Anual')], max_length=20, null=True, verbose_name='Semestre de Vigência'),
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='versao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Versão da Disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplinaensino',
            name='carga_horaria',
            field=models.PositiveIntegerField(verbose_name='Carga Horária Total (horas)'),
        ),
    ]
