# Generated by Django 5.2.3 on 2025-11-18 20:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0407_disciplinaensino_ano_vigencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nome'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='pontuacao',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='tipo',
        ),
        migrations.AddField(
            model_name='curso',
            name='carga_horaria_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária Total'),
        ),
        migrations.AddField(
            model_name='curso',
            name='objetivo',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='publico_alvo',
            field=models.TextField(blank=True, null=True, verbose_name='Público-Alvo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='requisitos',
            field=models.TextField(blank=True, null=True, verbose_name='Requisitos'),
        ),
        migrations.AddField(
            model_name='curso',
            name='sigla',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='acompanhamento_individual',
            field=models.BooleanField(default=False, verbose_name='Acompanhamento Individual dos Alunos'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='apostilas_pdfs',
            field=models.FileField(blank=True, null=True, upload_to='ensino/cursos/apostilas/', verbose_name='Apostilas / PDFs'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='atestado_medico_obrigatorio',
            field=models.BooleanField(default=False, verbose_name='Atestado Médico Obrigatório'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='autorizacao_responsaveis',
            field=models.BooleanField(default=False, verbose_name='Autorização dos Responsáveis (se menor)'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='calendario_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Calendário de Início'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='calendario_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Calendário de Término'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='carga_horaria_certificada',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária Certificada'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='carga_horaria_minima_aprovacao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária Mínima para Aprovação'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='carga_horaria_por_instrutor',
            field=models.TextField(blank=True, null=True, verbose_name='Carga Horária por Instrutor'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='checklist_equipamentos_aluno',
            field=models.TextField(blank=True, null=True, verbose_name='Checklist de Equipamentos por Aluno'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='competencias_habilidades',
            field=models.TextField(blank=True, null=True, verbose_name='Competências e Habilidades Desenvolvidas'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='controle_vagas_reservadas',
            field=models.BooleanField(default=False, verbose_name='Controle de Vagas Reservadas'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='criterios_gerais_avaliacao',
            field=models.TextField(blank=True, null=True, verbose_name='Critérios Gerais de Avaliação'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='descricao_resumida',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Resumida'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='documentos_obrigatorios',
            field=models.TextField(blank=True, null=True, verbose_name='Documentos Obrigatórios'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='duracao_prevista_dias',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração Prevista (dias)'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='duracao_prevista_meses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração Prevista (meses)'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='duracao_prevista_semanas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração Prevista (semanas)'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='epis_necessarios',
            field=models.TextField(blank=True, null=True, verbose_name='EPIs Necessários'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='equipamentos_necessarios',
            field=models.TextField(blank=True, null=True, verbose_name='Equipamentos Necessários'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='escolaridade_requerida',
            field=models.TextField(blank=True, null=True, verbose_name='Escolaridade Requerida'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='formacao_notas',
            field=models.TextField(blank=True, null=True, verbose_name='Formação de Notas (peso por disciplina ou atividades)'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='formas_avaliacao',
            field=models.TextField(blank=True, null=True, verbose_name='Formas de Avaliação'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='historico_versoes',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico de Versões'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='horas_complementares',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas Complementares'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='horas_praticas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas Práticas'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='horas_teoricas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas Teóricas'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='idade_minima',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade Mínima'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='integracao_financeiro',
            field=models.BooleanField(default=False, verbose_name='Integração com Módulo Financeiro'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='local_realizacao',
            field=models.TextField(blank=True, null=True, verbose_name='Local de Realização'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='manuais',
            field=models.FileField(blank=True, null=True, upload_to='ensino/cursos/manuais/', verbose_name='Manuais'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='matriz_curricular',
            field=models.FileField(blank=True, null=True, upload_to='ensino/cursos/matrizes/', verbose_name='Matriz Curricular (PDF)'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='media_minima_aprovacao',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='Nota mínima para aprovação (0-10)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Média Mínima para Aprovação'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='modalidade',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('SEMI_PRESENCIAL', 'Semi-presencial'), ('EAD', 'EAD'), ('MISTO', 'Misto')], default='PRESENCIAL', max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='modelo_certificado',
            field=models.FileField(blank=True, null=True, upload_to='ensino/cursos/certificados/', verbose_name='Modelo do Certificado (Upload ou Template)'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='normas_seguranca',
            field=models.TextField(blank=True, null=True, verbose_name='Normas de Segurança Aplicáveis ao Curso'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='numero_maximo_alunos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número Máximo de Alunos'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='numero_minimo_alunos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número Mínimo de Alunos'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='objetivos_especificos',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivos Específicos'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='observacoes_internas',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Internas'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='pagamentos_mensais',
            field=models.BooleanField(default=False, verbose_name='Pagamentos Mensais'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='percentual_frequencia_minima',
            field=models.DecimalField(decimal_places=2, default=75.0, help_text='Percentual mínimo de frequência para aprovação', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual Mínimo de Frequência'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='plano_pedagogico',
            field=models.FileField(blank=True, null=True, upload_to='ensino/cursos/planos_pedagogicos/', verbose_name='Plano Pedagógico Completo'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='planos_contingencia',
            field=models.TextField(blank=True, null=True, verbose_name='Planos de Contingência'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='possibilidade_equivalencia',
            field=models.BooleanField(default=False, verbose_name='Possibilidade de Equivalência entre Disciplinas'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='posto_graduacao_requerido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Posto/Graduação Requerido'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='procedimentos_emergencia',
            field=models.TextField(blank=True, null=True, verbose_name='Procedimentos de Emergência'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='regime_matricula',
            field=models.CharField(choices=[('UNICA', 'Única'), ('CONTINUA', 'Contínua'), ('TURMAS_ANUAIS', 'Turmas Anuais')], default='UNICA', max_length=20, verbose_name='Regime de Matrícula'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='registro_ocorrencias',
            field=models.BooleanField(default=False, verbose_name='Registro de Ocorrências'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='requisitos_ingresso',
            field=models.TextField(blank=True, null=True, verbose_name='Requisitos de Ingresso'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='riscos_envolvidos',
            field=models.TextField(blank=True, null=True, verbose_name='Riscos Envolvidos'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='sequencia_recomendada',
            field=models.TextField(blank=True, null=True, verbose_name='Sequência Recomendada das Disciplinas'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('EM_REVISAO', 'Em Revisão')], default='ATIVO', max_length=20, verbose_name='Status do Curso'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='taxa_material',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa de Material'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='taxa_matricula',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa de Matrícula'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='teste_fisico_obrigatorio',
            field=models.BooleanField(default=False, verbose_name='Teste Físico (TAF) Obrigatório'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='tipo_certificado',
            field=models.CharField(blank=True, choices=[('PARTICIPACAO', 'Participação'), ('CONCLUSAO', 'Conclusão'), ('HABILITACAO', 'Habilitação'), ('ESPECIALIZACAO', 'Especialização')], max_length=20, null=True, verbose_name='Tipo de Certificado'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='tipo_curso',
            field=models.CharField(blank=True, choices=[('FORMACAO', 'Formação'), ('CAPACITACAO', 'Capacitação'), ('ESPECIALIZACAO', 'Especialização'), ('HABILITACAO', 'Habilitação'), ('ATUALIZACAO', 'Atualização')], max_length=20, null=True, verbose_name='Tipo de Curso'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='unidade_responsavel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unidade Responsável pelo Curso'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='uniformes_equipamentos',
            field=models.TextField(blank=True, null=True, verbose_name='Uniformes e Equipamentos Necessários'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='versao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Versão / Ano Letivo'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='videos_instrucionais',
            field=models.URLField(blank=True, null=True, verbose_name='Vídeos Instrucionais (Link)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='codigo',
            field=models.CharField(help_text='Ex: CBM-OP-2025', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='coordenador_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_coordenados_externo', to='militares.pessoaexterna', verbose_name='Coordenador Geral (Externo)'),
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='coordenador_militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_coordenados_militar', to='militares.militar', verbose_name='Coordenador Geral (Militar)'),
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='finalidade',
            field=models.TextField(verbose_name='Objetivo Geral / Finalidade'),
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='instrutores_curso',
            field=models.ManyToManyField(blank=True, help_text='Instrutores que atuam neste curso', related_name='cursos_instrutores', to='militares.instrutorensino', verbose_name='Instrutores Principais'),
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='monitores_curso',
            field=models.ManyToManyField(blank=True, help_text='Monitores que atuam neste curso', related_name='cursos_monitores', to='militares.monitorensino', verbose_name='Monitores'),
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='publico_alvo',
            field=models.CharField(choices=[('PRACAS', 'Praças'), ('OFICIAIS', 'Oficiais'), ('CIVIS', 'Civis'), ('MISTO', 'Misto'), ('CRIANCAS', 'Crianças'), ('COMUNIDADE', 'Comunidade')], max_length=20, verbose_name='Público-Alvo'),
        ),
    ]
