# Generated by Django 5.2.3 on 2025-11-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0408_atualizar_modelo_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, max_length=30, null=True, verbose_name='Sigla')),
                ('ementa', models.TextField(blank=True, null=True, verbose_name='Ementa')),
                ('objetivo', models.TextField(blank=True, null=True, verbose_name='Objetivo')),
                ('conteudo_programatico', models.TextField(blank=True, null=True, verbose_name='Conteúdo Programático')),
                ('carga_horaria_padrao', models.PositiveIntegerField(verbose_name='Carga Horária Padrão')),
                ('tipo', models.CharField(choices=[('teorica', 'Teórica'), ('pratica', 'Prática'), ('mista', 'Teórico-Prática')], max_length=30, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='cursoensino',
            name='autorizacao_responsaveis',
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='atestado_medico_obrigatorio',
            field=models.BooleanField(default=False, verbose_name='Inspeção de Saúde Obrigatória'),
        ),
    ]
