# Generated by Django 5.2.3 on 2025-11-18 21:42

import django.db.models.deletion
from django.db import migrations, models


def copiar_especialidades_para_habilitacoes(apps, schema_editor):
    """Copia dados de especialidades para habilitacoes antes de remover o campo"""
    InstrutorEnsino = apps.get_model('militares', 'InstrutorEnsino')
    for instrutor in InstrutorEnsino.objects.all():
        # Verificar se o campo especialidades existe e tem valor
        if hasattr(instrutor, 'especialidades') and instrutor.especialidades:
            if not instrutor.habilitacoes:
                instrutor.habilitacoes = instrutor.especialidades
                instrutor.save()


def remover_instrutores_sem_militar(apps, schema_editor):
    """Remove instrutores que não têm militar (não podem existir mais)"""
    InstrutorEnsino = apps.get_model('militares', 'InstrutorEnsino')
    InstrutorEnsino.objects.filter(militar__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0409_disciplina_and_more'),
    ]

    operations = [
        # Primeiro, adicionar campo habilitacoes se não existir (pode já existir)
        migrations.AddField(
            model_name='instrutorensino',
            name='habilitacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Habilitações'),
        ),
        # Copiar dados de especialidades para habilitacoes (se especialidades existir)
        migrations.RunPython(copiar_especialidades_para_habilitacoes, migrations.RunPython.noop),
        # Remover instrutores sem militar antes de tornar o campo obrigatório
        migrations.RunPython(remover_instrutores_sem_militar, migrations.RunPython.noop),
        # Remover campos antigos
        migrations.RemoveField(
            model_name='instrutorensino',
            name='pessoa_externa',
        ),
        migrations.RemoveField(
            model_name='instrutorensino',
            name='especialidades',
        ),
        migrations.RemoveField(
            model_name='instrutorensino',
            name='assinatura_digital',
        ),
        migrations.RemoveField(
            model_name='instrutorensino',
            name='observacoes',
        ),
        # Remover constraint antiga antes de alterar os campos (se existir)
        # A constraint pode não existir se já foi removida anteriormente
        migrations.RunSQL(
            sql="ALTER TABLE militares_instrutorensino DROP CONSTRAINT IF EXISTS instrutor_deve_ter_militar_ou_externo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Tornar militar obrigatório
        migrations.AlterField(
            model_name='instrutorensino',
            name='militar',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='instrutor_ensino',
                to='militares.militar',
                verbose_name='Militar'
            ),
        ),
        # Adicionar unique_together para garantir que um militar só pode ser instrutor uma vez
        migrations.AlterUniqueTogether(
            name='instrutorensino',
            unique_together={('militar',)},
        ),
    ]
