# Generated by Django 5.2.3 on 2025-11-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0411_adicionar_tipo_instrutor_campos'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE militares_instrutorensino DROP CONSTRAINT IF EXISTS instrutor_deve_ter_militar_ou_externo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='instrutorensino',
            name='cep_bombeiro',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP (Instrutor)'),
        ),
        migrations.AddField(
            model_name='instrutorensino',
            name='cep_outra_forca',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='instrutorensino',
            name='cidade_bombeiro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade (Instrutor)'),
        ),
        migrations.AddField(
            model_name='instrutorensino',
            name='cidade_outra_forca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='instrutorensino',
            name='email_bombeiro',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail (Instrutor)'),
        ),
        migrations.AddField(
            model_name='instrutorensino',
            name='endereco_bombeiro',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço (Instrutor)'),
        ),
        migrations.AddField(
            model_name='instrutorensino',
            name='endereco_outra_forca',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='instrutorensino',
            name='telefone_bombeiro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone (Instrutor)'),
        ),
        migrations.AddField(
            model_name='instrutorensino',
            name='uf_bombeiro',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF (Instrutor)'),
        ),
        migrations.AddField(
            model_name='instrutorensino',
            name='uf_outra_forca',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF'),
        ),
    ]
