# Generated by Django 5.2.3 on 2025-11-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0412_adicionar_endereco_contatos_instrutor'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE militares_instrutorensino DROP CONSTRAINT IF EXISTS instrutor_deve_ter_militar_ou_externo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='militar',
            name='cep',
            field=models.CharField(blank=True, help_text='Formato: 00000-000', max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='militar',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='militar',
            name='endereco',
            field=models.TextField(blank=True, help_text='Logradouro, número, complemento, bairro', null=True, verbose_name='Endereço Completo'),
        ),
        migrations.AddField(
            model_name='militar',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF'),
        ),
    ]
