# Generated by Django 5.2.3 on 2025-11-18 23:21

import django.db.models.deletion
import militares.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0413_adicionar_endereco_militar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE militares_instrutorensino DROP CONSTRAINT IF EXISTS instrutor_deve_ter_militar_ou_externo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='DocumentoInstrutorEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CERTIFICADO', 'Certificado'), ('DIPLOMA', 'Diploma'), ('HABILITACAO', 'Habilitação'), ('COMPROVANTE', 'Comprovante'), ('CONTRATO', 'Contrato'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Tipo de Documento')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Documento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to=militares.models.documento_instrutor_upload_path, verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
            ],
            options={
                'verbose_name': 'Documento do Instrutor',
                'verbose_name_plural': 'Documentos do Instrutor',
                'ordering': ['-data_upload', 'tipo'],
            },
        ),
        migrations.AddField(
            model_name='instrutorensino',
            name='foto_outra_forca',
            field=models.ImageField(blank=True, null=True, upload_to='ensino/instrutores/fotos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='documentoinstrutorensino',
            name='instrutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='militares.instrutorensino', verbose_name='Instrutor'),
        ),
        migrations.AddField(
            model_name='documentoinstrutorensino',
            name='upload_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Upload por'),
        ),
    ]
