# Generated by Django 5.2.3 on 2025-11-19 00:04

import django.db.models.deletion
import militares.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0414_adicionar_foto_outra_forca_documentos_instrutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoMonitorEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CERTIFICADO', 'Certificado'), ('DIPLOMA', 'Diploma'), ('HABILITACAO', 'Habilitação'), ('COMPROVANTE', 'Comprovante'), ('CONTRATO', 'Contrato'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Tipo de Documento')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Documento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to=militares.models.documento_monitor_upload_path, verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
            ],
            options={
                'verbose_name': 'Documento do Monitor',
                'verbose_name_plural': 'Documentos do Monitor',
                'ordering': ['-data_upload', 'tipo'],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE militares_instrutorensino DROP CONSTRAINT IF EXISTS instrutor_deve_ter_militar_ou_externo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE militares_monitorensino DROP CONSTRAINT IF EXISTS monitor_deve_ter_militar_ou_externo;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='monitorensino',
            name='areas_atuacao',
        ),
        migrations.RemoveField(
            model_name='monitorensino',
            name='atribuicoes',
        ),
        migrations.RemoveField(
            model_name='monitorensino',
            name='instrutor_vinculado_externo',
        ),
        migrations.RemoveField(
            model_name='monitorensino',
            name='instrutor_vinculado_militar',
        ),
        migrations.RemoveField(
            model_name='monitorensino',
            name='pessoa_externa',
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='cep_bombeiro',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP (Monitor)'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='cep_civil',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='cep_outra_forca',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='cidade_bombeiro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade (Monitor)'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='cidade_civil',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='cidade_outra_forca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='cpf_civil',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='cpf_outra_forca',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='cursos_complementares',
            field=models.TextField(blank=True, null=True, verbose_name='Cursos Complementares'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='data_nascimento_civil',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='email_bombeiro',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail (Monitor)'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='email_civil',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='email_outra_forca',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='endereco_bombeiro',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço (Monitor)'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='endereco_civil',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='endereco_outra_forca',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='especialidades',
            field=models.TextField(blank=True, null=True, verbose_name='Especialidades'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='experiencia_profissional',
            field=models.TextField(blank=True, null=True, verbose_name='Experiência Profissional'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='forca_armada',
            field=models.CharField(blank=True, choices=[('EB', 'Exército Brasileiro'), ('MB', 'Marinha do Brasil'), ('FAB', 'Força Aérea Brasileira'), ('PM', 'Polícia Militar'), ('PC', 'Polícia Civil'), ('PRF', 'Polícia Rodoviária Federal'), ('PF', 'Polícia Federal'), ('OUTRA', 'Outra')], max_length=20, null=True, verbose_name='Força Armada/Polícia'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='formacao_civil',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Formação Acadêmica'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ensino/monitores/fotos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='foto_outra_forca',
            field=models.ImageField(blank=True, null=True, upload_to='ensino/monitores/fotos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='habilitacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Habilitações'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='instituicao_civil',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição de Ensino'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='instituicao_outra_forca',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição/Órgão'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='matricula_outra_forca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula/Identificação'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='nome_civil',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='nome_outra_forca',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='posto_outra_forca',
            field=models.CharField(blank=True, choices=[('CEL', 'Coronel'), ('TEN CEL', 'Tenente-Coronel'), ('MAJ', 'Major'), ('CAP', 'Capitão'), ('1TEN', '1º Tenente'), ('2TEN', '2º Tenente'), ('SUBTEN', 'Subtenente'), ('1SGT', '1º Sargento'), ('2SGT', '2º Sargento'), ('3SGT', '3º Sargento'), ('CB', 'Cabo'), ('SD', 'Soldado')], max_length=20, null=True, verbose_name='Posto/Graduação'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='rg_civil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='telefone_bombeiro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone (Monitor)'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='telefone_civil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='telefone_outra_forca',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='tipo_monitor',
            field=models.CharField(choices=[('BOMBEIRO', 'Bombeiro Militar'), ('OUTRA_FORCA', 'Militar de Outra Força'), ('CIVIL', 'Civil')], default='BOMBEIRO', max_length=20, verbose_name='Tipo de Monitor'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='uf_bombeiro',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF (Monitor)'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='uf_civil',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='monitorensino',
            name='uf_outra_forca',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='monitorensino',
            name='militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_ensino', to='militares.militar', verbose_name='Militar Bombeiro'),
        ),
        migrations.AddField(
            model_name='documentomonitorensino',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='militares.monitorensino', verbose_name='Monitor'),
        ),
        migrations.AddField(
            model_name='documentomonitorensino',
            name='upload_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Upload por'),
        ),
    ]
