# Generated by Django 5.2.3 on 2025-11-19 00:56

import django.db.models.deletion
import militares.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0415_adaptar_monitor_ensino_estrutura_instrutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCursoEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CERTIFICADO', 'Certificado'), ('DIPLOMA', 'Diploma'), ('HABILITACAO', 'Habilitação'), ('COMPROVANTE', 'Comprovante'), ('CONTRATO', 'Contrato'), ('PORTARIA', 'Portaria'), ('DECRETO', 'Decreto'), ('LEGISLACAO', 'Legislação'), ('PLANO_CURSO', 'Plano de Curso'), ('EMENTA', 'Ementa'), ('PLANO_PEDAGOGICO', 'Plano Pedagógico'), ('MATERIAL_DIDATICO', 'Material Didático'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Tipo de Documento')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Documento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to=militares.models.documento_curso_upload_path, verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
            ],
            options={
                'verbose_name': 'Documento do Curso',
                'verbose_name_plural': 'Documentos do Curso',
                'ordering': ['-data_upload', 'tipo'],
            },
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='carga_horaria',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária Total (horas)'),
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='codigo',
            field=models.CharField(blank=True, help_text='Ex: CBM-OP-2025', max_length=50, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='finalidade',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo Geral / Finalidade'),
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='publico_alvo',
            field=models.CharField(blank=True, choices=[('PRACAS', 'Praças'), ('OFICIAIS', 'Oficiais'), ('CIVIS', 'Civis'), ('MISTO', 'Misto'), ('CRIANCAS', 'Crianças'), ('COMUNIDADE', 'Comunidade')], max_length=20, null=True, verbose_name='Público-Alvo'),
        ),
        migrations.AddField(
            model_name='documentocursoensino',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='militares.cursoensino', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='documentocursoensino',
            name='upload_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Upload por'),
        ),
    ]
