# Generated by Django 5.2.3 on 2025-11-19 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0416_tornar_campos_curso_opcionais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTrocaInstrutorDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_anterior', models.DateField(blank=True, null=True, verbose_name='Data de Início do Instrutor Anterior')),
                ('data_fim_anterior', models.DateField(verbose_name='Data de Fim do Instrutor Anterior')),
                ('data_inicio_novo', models.DateField(verbose_name='Data de Início do Instrutor Novo')),
                ('motivo_troca', models.TextField(verbose_name='Motivo da Troca')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Histórico de Troca de Instrutor',
                'verbose_name_plural': 'Históricos de Troca de Instrutor',
                'ordering': ['-data_fim_anterior', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoTrocaMonitorDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_anterior', models.DateField(blank=True, null=True, verbose_name='Data de Início do Monitor Anterior')),
                ('data_fim_anterior', models.DateField(verbose_name='Data de Fim do Monitor Anterior')),
                ('data_inicio_novo', models.DateField(verbose_name='Data de Início do Monitor Novo')),
                ('motivo_troca', models.TextField(verbose_name='Motivo da Troca')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Histórico de Troca de Monitor',
                'verbose_name_plural': 'Históricos de Troca de Monitor',
                'ordering': ['-data_fim_anterior', '-data_criacao'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='instrutorensino',
            name='instrutor_deve_ter_militar_ou_externo',
        ),
        migrations.RemoveConstraint(
            model_name='monitorensino',
            name='monitor_deve_ter_militar_ou_externo',
        ),
        migrations.AddField(
            model_name='historicotrocainstrutordisciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_troca_instrutor', to='militares.disciplinaensino', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='historicotrocainstrutordisciplina',
            name='instrutor_anterior_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_troca_instrutor_anterior', to='militares.instrutorensino', verbose_name='Instrutor Anterior (Externo)'),
        ),
        migrations.AddField(
            model_name='historicotrocainstrutordisciplina',
            name='instrutor_anterior_militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_troca_instrutor_anterior', to='militares.militar', verbose_name='Instrutor Anterior (Militar)'),
        ),
        migrations.AddField(
            model_name='historicotrocainstrutordisciplina',
            name='instrutor_novo_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_troca_instrutor_novo', to='militares.instrutorensino', verbose_name='Instrutor Novo (Externo)'),
        ),
        migrations.AddField(
            model_name='historicotrocainstrutordisciplina',
            name='instrutor_novo_militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_troca_instrutor_novo', to='militares.militar', verbose_name='Instrutor Novo (Militar)'),
        ),
        migrations.AddField(
            model_name='historicotrocainstrutordisciplina',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_troca_instrutor', to='militares.turmaensino', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='historicotrocainstrutordisciplina',
            name='usuario_que_trocou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_troca_instrutor_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Realizou a Troca'),
        ),
        migrations.AddField(
            model_name='historicotrocamonitordisciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_troca_monitor', to='militares.disciplinaensino', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='historicotrocamonitordisciplina',
            name='monitor_anterior_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_troca_monitor_anterior', to='militares.monitorensino', verbose_name='Monitor Anterior (Externo)'),
        ),
        migrations.AddField(
            model_name='historicotrocamonitordisciplina',
            name='monitor_anterior_militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_troca_monitor_anterior', to='militares.militar', verbose_name='Monitor Anterior (Militar)'),
        ),
        migrations.AddField(
            model_name='historicotrocamonitordisciplina',
            name='monitor_novo_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_troca_monitor_novo', to='militares.monitorensino', verbose_name='Monitor Novo (Externo)'),
        ),
        migrations.AddField(
            model_name='historicotrocamonitordisciplina',
            name='monitor_novo_militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_troca_monitor_novo', to='militares.militar', verbose_name='Monitor Novo (Militar)'),
        ),
        migrations.AddField(
            model_name='historicotrocamonitordisciplina',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_troca_monitor', to='militares.turmaensino', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='historicotrocamonitordisciplina',
            name='usuario_que_trocou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_troca_monitor_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Realizou a Troca'),
        ),
    ]
