# Generated by Django 5.2.3 on 2025-11-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0417_historicotrocainstrutordisciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoaluno',
            name='tipo',
            field=models.CharField(choices=[('PROCESSO_DISCIPLINAR', 'Processo Disciplinar'), ('TERMO_DESLIGAMENTO', 'Termo de Desligamento'), ('NOTIFICACAO', 'Notificação'), ('ADVERTENCIA', 'Advertência'), ('SUSPENSAO', 'Suspensão'), ('RELATORIO', 'Relatório'), ('PARECER', 'Parecer'), ('DECISAO', 'Decisão'), ('PORTARIA', 'Portaria'), ('OFICIO', 'Ofício'), ('ATA', 'Ata'), ('ATESTADO', 'Atestado Médico'), ('LAUDO', 'Laudo'), ('AUTORIZACAO', 'Autorização'), ('DECLARACAO', 'Declaração'), ('HISTORICO', 'Histórico Escolar'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Documento'),
        ),
    ]
