# Generated by Django 5.2.3 on 2025-11-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0418_adicionar_tipos_documento_desligamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoensino',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matrícula do Aluno'),
        ),
    ]
