# Generated by Django 5.2.3 on 2025-11-20 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0419_tornar_matricula_aluno_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunoensino',
            name='cep_civil',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='cep_outra_forca',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='cidade_civil',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='cidade_outra_forca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='cpf_civil',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='cpf_outra_forca',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='data_nascimento_civil',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='data_nascimento_outra_forca',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='email_civil',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='email_outra_forca',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='endereco_civil',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='endereco_outra_forca',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='forca_armada',
            field=models.CharField(blank=True, choices=[('EB', 'Exército Brasileiro'), ('MB', 'Marinha do Brasil'), ('FAB', 'Força Aérea Brasileira'), ('PM', 'Polícia Militar'), ('PC', 'Polícia Civil'), ('PF', 'Polícia Federal'), ('PRF', 'Polícia Rodoviária Federal'), ('OUTRA', 'Outra')], max_length=20, null=True, verbose_name='Força Armada/Polícia'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='formacao_civil',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Formação Acadêmica'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='instituicao_civil',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição de Ensino'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='instituicao_outra_forca',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição/Órgão'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='matricula_outra_forca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula/Identificação'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='nome_civil',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='nome_outra_forca',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='posto_outra_forca',
            field=models.CharField(blank=True, choices=[('CEL', 'Coronel'), ('TEN CEL', 'Tenente-Coronel'), ('MAJ', 'Major'), ('CAP', 'Capitão'), ('1º TEN', '1º Tenente'), ('2º TEN', '2º Tenente'), ('SUBTEN', 'Subtenente'), ('1º SGT', '1º Sargento'), ('2º SGT', '2º Sargento'), ('3º SGT', '3º Sargento'), ('CB', 'Cabo'), ('SD', 'Soldado')], max_length=20, null=True, verbose_name='Posto/Graduação'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='rg_civil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='rg_outra_forca',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='telefone_civil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='telefone_outra_forca',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='tipo_aluno',
            field=models.CharField(choices=[('BOMBEIRO', 'Bombeiro Militar'), ('OUTRA_FORCA', 'Militar de Outra Força'), ('CIVIL', 'Civil')], default='BOMBEIRO', max_length=20, verbose_name='Tipo de Aluno'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='uf_civil',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='uf_outra_forca',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='alunoensino',
            name='militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_ensino', to='militares.militar', verbose_name='Militar Bombeiro'),
        ),
        migrations.AlterField(
            model_name='alunoensino',
            name='pessoa_externa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_ensino', to='militares.pessoaexterna', verbose_name='Pessoa Externa (Deprecated)'),
        ),
    ]
