# Generated by Django 5.2.3 on 2025-11-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0420_adicionar_campos_completos_aluno'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alunoensino',
            name='aluno_deve_ter_militar_ou_externo',
        ),
    ]
