# Generated by Django 5.2.3 on 2025-11-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0421_remover_constraint_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaensino',
            name='categoria',
            field=models.CharField(blank=True, choices=[('AREA_TEMATICA_I', 'ÁREA TEMÁTICA I - SISTEMAS, INSTITUIÇÕES E GESTÃO INTEGRADA EM SEGURANÇA PÚBLICA'), ('AREA_TEMATICA_II', 'ÁREA TEMÁTICA II - VIOLÊNCIA, CRIME E CONTROLE SOCIAL'), ('AREA_TEMATICA_III', 'ÁREA TEMÁTICA III - CONHECIMENTOS JURÍDICOS'), ('AREA_TEMATICA_IV', 'ÁREA TEMÁTICA IV - MODALIDADES DE GESTÃO DE CONFLITOS E EVENTOS CRÍTICOS'), ('AREA_TEMATICA_V', 'ÁREA TEMÁTICA V - VALORIZAÇÃO PROFISSIONAL E SAÚDE DO TRABALHADOR'), ('AREA_TEMATICA_VI', 'ÁREA TEMÁTICA VI - COMUNICAÇÃO, INFORMAÇÃO E TECNOLOGIAS EM SEGURANÇA PÚBLICA'), ('AREA_TEMATICA_VII', 'ÁREA TEMÁTICA VII - CULTURA, COTIDIANO E PRÁTICA REFLEXIVA'), ('AREA_TEMATICA_VIII', 'ÁREA TEMÁTICA VIII - FUNÇÕES, TÉCNICAS E PROCEDIMENTOS EM SEGURANÇA PÚBLICA')], max_length=100, null=True, verbose_name='Categoria / Área de Conhecimento'),
        ),
    ]
