# Generated by Django 5.2.3 on 2025-11-20 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0422_alter_disciplinaensino_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocursoensino',
            name='tipo',
            field=models.CharField(choices=[('CERTIFICADO', 'Certificado'), ('DIPLOMA', 'Diploma'), ('HABILITACAO', 'Habilitação'), ('COMPROVANTE', 'Comprovante'), ('CONTRATO', 'Contrato'), ('PORTARIA', 'Portaria'), ('DECRETO', 'Decreto'), ('LEGISLACAO', 'Legislação'), ('PLANO_CURSO', 'Plano de Curso'), ('EMENTA', 'Ementa'), ('PLANO_PEDAGOGICO', 'Plano Pedagógico'), ('MATERIAL_DIDATICO', 'Material Didático'), ('ARQUIVO_COMPLEMENTAR', 'Arquivo Complementar'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.CreateModel(
            name='LinkUtilCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Link')),
                ('url', models.URLField(verbose_name='URL')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_uteis', to='militares.cursoensino', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Link Útil do Curso',
                'verbose_name_plural': 'Links Úteis do Curso',
                'ordering': ['-data_criacao', 'titulo'],
            },
        ),
    ]
