# Generated by Django 5.2.3 on 2025-11-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0423_alter_documentocursoensino_tipo_linkutilcurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaensino',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código'),
        ),
    ]
