# Generated by Django 5.2.3 on 2025-11-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0424_alter_disciplinaensino_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaensino',
            name='conteudo_programatico',
            field=models.TextField(verbose_name='Conteúdo Programático'),
        ),
    ]
