# Generated by Django 5.2.3 on 2025-11-20 19:47

import django.db.models.deletion
import militares.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0425_alter_disciplinaensino_conteudo_programatico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinaensino',
            name='arquivos_complementares',
        ),
        migrations.RemoveField(
            model_name='disciplinaensino',
            name='links_uteis',
        ),
        migrations.CreateModel(
            name='DocumentoDisciplinaEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ARQUIVO_COMPLEMENTAR', 'Arquivo Complementar'), ('APOSTILA', 'Apostila'), ('SLIDE', 'Slide'), ('MANUAL', 'Manual'), ('PLANO_AULA', 'Plano de Aula'), ('MATERIAL_DIDATICO', 'Material Didático'), ('OUTROS', 'Outros')], default='ARQUIVO_COMPLEMENTAR', max_length=20, verbose_name='Tipo de Documento')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Documento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to=militares.models.documento_disciplina_upload_path, verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='militares.disciplinaensino', verbose_name='Disciplina')),
                ('upload_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Upload por')),
            ],
            options={
                'verbose_name': 'Documento da Disciplina',
                'verbose_name_plural': 'Documentos da Disciplina',
                'ordering': ['-data_upload', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='LinkUtilDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Link')),
                ('url', models.URLField(verbose_name='URL')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_uteis', to='militares.disciplinaensino', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Link Útil da Disciplina',
                'verbose_name_plural': 'Links Úteis da Disciplina',
                'ordering': ['-data_criacao', 'titulo'],
            },
        ),
    ]
