# Generated by Django 5.2.3 on 2025-11-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0426_remove_disciplinaensino_arquivos_complementares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrutorensino',
            name='link_lattes',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Currículo Lattes'),
        ),
        migrations.AlterField(
            model_name='avaliacaoensino',
            name='tipo',
            field=models.CharField(choices=[('TEORICA', 'Avaliação Teórica'), ('PRATICA', 'Avaliação Prática'), ('TESTE_FISICO', 'Teste Físico'), ('PROVA_MILITAR', 'Prova Militar'), ('ORDEM_FORMA', 'Ordem e Forma'), ('MARCHA', 'Marcha'), ('ARMAMENTO', 'Armamento'), ('RECUPERACAO', 'Recuperação'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Avaliação'),
        ),
    ]
