# Generated by Django 5.2.3 on 2025-11-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0427_add_link_lattes_instrutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutorensino',
            name='link_lattes',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Currículo Lattes'),
        ),
    ]
