# Generated by Django 5.2.3 on 2025-11-22 20:00

import django.db.models.deletion
from django.db import migrations, models


def remover_indices_orfaos(apps, schema_editor):
    """Remove índices órfãos que podem existir sem as colunas"""
    with schema_editor.connection.cursor() as cursor:
        # Remover índice órfão se existir
        cursor.execute("""
            DROP INDEX IF EXISTS militares_turmaensino_instrutor_chefe_militar_id_56ff902a;
        """)


def reverter_remocao_indices(apps, schema_editor):
    """Não faz nada na reversão"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0428_alter_instrutorensino_link_lattes'),
    ]

    operations = [
        migrations.RunPython(remover_indices_orfaos, reverter_remocao_indices),
        migrations.AddField(
            model_name='turmaensino',
            name='instrutor_chefe_externo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='turmas_chefiadas_externo',
                to='militares.instrutorensino',
                verbose_name='Instrutor-Chefe (Externo)'
            ),
        ),
        migrations.AddField(
            model_name='turmaensino',
            name='instrutor_chefe_militar',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='turmas_chefiadas_militar',
                to='militares.militar',
                verbose_name='Instrutor-Chefe (Militar)'
            ),
        ),
    ]
