# Generated by Django 5.2.3 on 2025-11-22 20:28

import django.db.models.deletion
from django.db import migrations, models


def remover_campos_se_existirem(apps, schema_editor):
    """Remove campos órfãos que podem existir sem definição no modelo"""
    with schema_editor.connection.cursor() as cursor:
        # Remover índices órfãos se existirem
        cursor.execute("""
            DROP INDEX IF EXISTS militares_turmaensino_coordenador_curso_externo_id_abc123;
            DROP INDEX IF EXISTS militares_turmaensino_coordenador_curso_militar_id_def456;
            DROP INDEX IF EXISTS militares_turmaensino_supervisor_curso_externo_id_ghi789;
            DROP INDEX IF EXISTS militares_turmaensino_supervisor_curso_militar_id_jkl012;
        """)


def reverter_remocao(apps, schema_editor):
    """Não faz nada na reversão"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0429_adicionar_campos_instrutor_chefe_turma'),
    ]

    operations = [
        migrations.RunPython(remover_campos_se_existirem, reverter_remocao),
        migrations.AddField(
            model_name='turmaensino',
            name='coordenador_curso_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_coordenador_curso_externo', to='militares.pessoaexterna', verbose_name='Coordenador do Curso (Externo)'),
        ),
        migrations.AddField(
            model_name='turmaensino',
            name='coordenador_curso_militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_coordenador_curso_militar', to='militares.militar', verbose_name='Coordenador do Curso (Militar)'),
        ),
        migrations.AddField(
            model_name='turmaensino',
            name='supervisor_curso_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_supervisor_curso_externo', to='militares.pessoaexterna', verbose_name='Supervisor do Curso (Externo)'),
        ),
        migrations.AddField(
            model_name='turmaensino',
            name='supervisor_curso_militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_supervisor_curso_militar', to='militares.militar', verbose_name='Supervisor do Curso (Militar)'),
        ),
        migrations.AddField(
            model_name='turmaensino',
            name='supervisor_turma_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_supervisionadas_externo', to='militares.pessoaexterna', verbose_name='Supervisor de Turma (Externo)'),
        ),
        migrations.AddField(
            model_name='turmaensino',
            name='supervisor_turma_militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_supervisionadas_militar', to='militares.militar', verbose_name='Supervisor de Turma (Militar)'),
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='modalidade',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('SEMIPRESENCIAL', 'Semipresencial (Híbrida)'), ('EAD', 'EAD (Online)'), ('ONLINE_AO_VIVO', 'Online ao Vivo'), ('AUTOINSTRUCIONAL', 'Autoinstrucional'), ('INTENSIVA', 'Intensiva'), ('MODULAR', 'Modular'), ('CONTINUADA', 'Continuada'), ('PRATICA_OPERACIONAL', 'Prática/Operacional'), ('TEORICA', 'Teórica')], default='PRESENCIAL', max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='cursoensino',
            name='tipo_curso',
            field=models.CharField(blank=True, choices=[('FORMACAO', 'Formação'), ('HABILITACAO', 'Habilitação'), ('APERFEICOAMENTO', 'Aperfeiçoamento'), ('ESPECIALIZACAO', 'Especialização'), ('EXTENSAO', 'Extensão'), ('CAPACITACAO', 'Capacitação'), ('ATUALIZACAO', 'Atualização'), ('QUALIFICACAO', 'Qualificação'), ('TECNICO', 'Técnico'), ('PERMANENTE', 'Permanente'), ('REGULAR', 'Regular'), ('INTENSIVO', 'Intensivo'), ('MODULAR', 'Modular'), ('LIVRE', 'Livre'), ('POS_GRADUACAO', 'Pós-graduação'), ('NIVELAMENTO', 'Nivelamento')], max_length=20, null=True, verbose_name='Tipo de Curso'),
        ),
    ]
