# Generated by Django 5.2.3 on 2025-11-22 20:30

import django.db.models.deletion
from django.db import migrations, models


def remover_indices_orfaos(apps, schema_editor):
    """Remove índices órfãos se existirem"""
    with schema_editor.connection.cursor() as cursor:
        # Buscar todos os índices relacionados
        cursor.execute("""
            SELECT indexname 
            FROM pg_indexes 
            WHERE tablename='militares_turmaensino'
            AND (indexname LIKE '%supervisor_curso%')
        """)
        indices = [row[0] for row in cursor.fetchall()]
        for idx in indices:
            cursor.execute(f"DROP INDEX IF EXISTS {idx};")


def reverter_remocao(apps, schema_editor):
    """Não faz nada na reversão"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0430_adicionar_supervisor_coordenador_turma'),
    ]

    operations = [
        migrations.RunPython(remover_indices_orfaos, reverter_remocao),
        migrations.AddField(
            model_name='turmaensino',
            name='supervisor_curso_externo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='turmas_supervisor_curso_externo',
                to='militares.pessoaexterna',
                verbose_name='Supervisor do Curso (Externo)'
            ),
        ),
        migrations.AddField(
            model_name='turmaensino',
            name='supervisor_curso_militar',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='turmas_supervisor_curso_militar',
                to='militares.militar',
                verbose_name='Supervisor do Curso (Militar)'
            ),
        ),
    ]
