# Generated by Django 5.2.3 on 2025-11-22 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0431_adicionar_supervisor_curso_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmaensino',
            name='coordenador_curso_externo',
        ),
        migrations.RemoveField(
            model_name='turmaensino',
            name='coordenador_turma_externo',
        ),
        migrations.RemoveField(
            model_name='turmaensino',
            name='supervisor_curso_externo',
        ),
        migrations.RemoveField(
            model_name='turmaensino',
            name='supervisor_turma_externo',
        ),
        migrations.RenameField(
            model_name='turmaensino',
            old_name='coordenador_curso_militar',
            new_name='coordenador_curso',
        ),
        migrations.RenameField(
            model_name='turmaensino',
            old_name='coordenador_turma_militar',
            new_name='coordenador_turma',
        ),
        migrations.RenameField(
            model_name='turmaensino',
            old_name='supervisor_curso_militar',
            new_name='supervisor_curso',
        ),
        migrations.RenameField(
            model_name='turmaensino',
            old_name='supervisor_turma_militar',
            new_name='supervisor_turma',
        ),
    ]
