# Generated by Django 5.2.3 on 2025-11-22 23:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0432_remover_campos_externos_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoensino',
            name='posto_outra_forca',
            field=models.CharField(blank=True, choices=[('CEL', 'Coronel'), ('TEN CEL', 'Tenente-Coronel'), ('MAJ', 'Major'), ('CAP', 'Capitão'), ('1º TEN', '1º Tenente'), ('2º TEN', '2º Tenente'), ('SUBTEN', 'Subtenente'), ('1º SGT', '1º Sargento'), ('2º SGT', '2º Sargento'), ('3º SGT', '3º Sargento'), ('CB', 'Cabo'), ('SD', 'Soldado'), ('ALS', 'Aluno-Soldado')], max_length=20, null=True, verbose_name='Posto/Graduação'),
        ),
        migrations.AlterField(
            model_name='instrutorensino',
            name='posto_outra_forca',
            field=models.CharField(blank=True, choices=[('CEL', 'Coronel'), ('TEN CEL', 'Tenente-Coronel'), ('MAJ', 'Major'), ('CAP', 'Capitão'), ('1TEN', '1º Tenente'), ('2TEN', '2º Tenente'), ('SUBTEN', 'Subtenente'), ('1SGT', '1º Sargento'), ('2SGT', '2º Sargento'), ('3SGT', '3º Sargento'), ('CB', 'Cabo'), ('SD', 'Soldado'), ('ALS', 'Aluno-Soldado')], max_length=20, null=True, verbose_name='Posto/Graduação'),
        ),
        migrations.AlterField(
            model_name='intersticio',
            name='posto',
            field=models.CharField(choices=[('CB', 'Coronel'), ('TC', 'Tenente Coronel'), ('MJ', 'Major'), ('CP', 'Capitão'), ('1T', '1º Tenente'), ('2T', '2º Tenente'), ('AS', 'Aspirante a Oficial'), ('AA', 'Aluno de Adaptação'), ('ST', 'Subtenente'), ('1S', '1º Sargento'), ('2S', '2º Sargento'), ('3S', '3º Sargento'), ('CAB', 'Cabo'), ('SD', 'Soldado'), ('ALS', 'Aluno-Soldado')], max_length=4, verbose_name='Posto'),
        ),
        migrations.AlterField(
            model_name='militar',
            name='posto_graduacao',
            field=models.CharField(choices=[('CB', 'Coronel'), ('TC', 'Tenente Coronel'), ('MJ', 'Major'), ('CP', 'Capitão'), ('1T', '1º Tenente'), ('2T', '2º Tenente'), ('AS', 'Aspirante a Oficial'), ('AA', 'Aluno de Adaptação'), ('ST', 'Subtenente'), ('1S', '1º Sargento'), ('2S', '2º Sargento'), ('3S', '3º Sargento'), ('CAB', 'Cabo'), ('SD', 'Soldado'), ('ALS', 'Aluno-Soldado')], max_length=4, verbose_name='Posto/Graduação'),
        ),
        migrations.AlterField(
            model_name='militarfuncao',
            name='posto_final',
            field=models.CharField(blank=True, choices=[('CB', 'Coronel'), ('TC', 'Tenente Coronel'), ('MJ', 'Major'), ('CP', 'Capitão'), ('1T', '1º Tenente'), ('2T', '2º Tenente'), ('AS', 'Aspirante a Oficial'), ('AA', 'Aluno de Adaptação'), ('ST', 'Subtenente'), ('1S', '1º Sargento'), ('2S', '2º Sargento'), ('3S', '3º Sargento'), ('CAB', 'Cabo'), ('SD', 'Soldado'), ('ALS', 'Aluno-Soldado')], help_text='Posto do militar no fim da função', max_length=4, null=True, verbose_name='Posto Final'),
        ),
        migrations.AlterField(
            model_name='militarfuncao',
            name='posto_inicial',
            field=models.CharField(blank=True, choices=[('CB', 'Coronel'), ('TC', 'Tenente Coronel'), ('MJ', 'Major'), ('CP', 'Capitão'), ('1T', '1º Tenente'), ('2T', '2º Tenente'), ('AS', 'Aspirante a Oficial'), ('AA', 'Aluno de Adaptação'), ('ST', 'Subtenente'), ('1S', '1º Sargento'), ('2S', '2º Sargento'), ('3S', '3º Sargento'), ('CAB', 'Cabo'), ('SD', 'Soldado'), ('ALS', 'Aluno-Soldado')], help_text='Posto do militar no início da função', max_length=4, null=True, verbose_name='Posto Inicial'),
        ),
        migrations.AlterField(
            model_name='monitorensino',
            name='posto_outra_forca',
            field=models.CharField(blank=True, choices=[('CEL', 'Coronel'), ('TEN CEL', 'Tenente-Coronel'), ('MAJ', 'Major'), ('CAP', 'Capitão'), ('1TEN', '1º Tenente'), ('2TEN', '2º Tenente'), ('SUBTEN', 'Subtenente'), ('1SGT', '1º Sargento'), ('2SGT', '2º Sargento'), ('3SGT', '3º Sargento'), ('CB', 'Cabo'), ('SD', 'Soldado'), ('ALS', 'Aluno-Soldado')], max_length=20, null=True, verbose_name='Posto/Graduação'),
        ),
        migrations.AlterField(
            model_name='previsaovaga',
            name='posto',
            field=models.CharField(choices=[('CB', 'Coronel'), ('TC', 'Tenente Coronel'), ('MJ', 'Major'), ('CP', 'Capitão'), ('1T', '1º Tenente'), ('2T', '2º Tenente'), ('AS', 'Aspirante a Oficial'), ('AA', 'Aluno de Adaptação'), ('ST', 'Subtenente'), ('1S', '1º Sargento'), ('2S', '2º Sargento'), ('3S', '3º Sargento'), ('CAB', 'Cabo'), ('SD', 'Soldado'), ('ALS', 'Aluno-Soldado')], max_length=4, verbose_name='Posto'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='posto_anterior',
            field=models.CharField(choices=[('CB', 'Coronel'), ('TC', 'Tenente Coronel'), ('MJ', 'Major'), ('CP', 'Capitão'), ('1T', '1º Tenente'), ('2T', '2º Tenente'), ('AS', 'Aspirante a Oficial'), ('AA', 'Aluno de Adaptação'), ('ST', 'Subtenente'), ('1S', '1º Sargento'), ('2S', '2º Sargento'), ('3S', '3º Sargento'), ('CAB', 'Cabo'), ('SD', 'Soldado'), ('ALS', 'Aluno-Soldado')], max_length=4, verbose_name='Posto Anterior'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='posto_novo',
            field=models.CharField(choices=[('CB', 'Coronel'), ('TC', 'Tenente Coronel'), ('MJ', 'Major'), ('CP', 'Capitão'), ('1T', '1º Tenente'), ('2T', '2º Tenente'), ('AS', 'Aspirante a Oficial'), ('AA', 'Aluno de Adaptação'), ('ST', 'Subtenente'), ('1S', '1º Sargento'), ('2S', '2º Sargento'), ('3S', '3º Sargento'), ('CAB', 'Cabo'), ('SD', 'Soldado'), ('ALS', 'Aluno-Soldado')], max_length=4, verbose_name='Novo Posto'),
        ),
        migrations.AlterField(
            model_name='turmaensino',
            name='coordenador_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_coordenador_curso', to='militares.militar', verbose_name='Coordenador do Curso'),
        ),
        migrations.AlterField(
            model_name='turmaensino',
            name='coordenador_turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_coordenadas', to='militares.militar', verbose_name='Coordenador de Turma'),
        ),
        migrations.AlterField(
            model_name='turmaensino',
            name='supervisor_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_supervisor_curso', to='militares.militar', verbose_name='Supervisor do Curso'),
        ),
        migrations.AlterField(
            model_name='turmaensino',
            name='supervisor_turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_supervisionadas', to='militares.militar', verbose_name='Supervisor de Turma'),
        ),
        migrations.AddField(
            model_name='cursoensino',
            name='media_minima_recuperacao',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Nota mínima na recuperação para aprovação (0-10)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Média Mínima para Recuperação'),
        ),
    ]
