# Generated by Django 5.2.3 on 2025-11-22 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0433_adicionar_media_minima_recuperacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursoensino',
            name='media_minima_recuperacao',
        ),
        migrations.AddField(
            model_name='disciplinaensino',
            name='media_minima_recuperacao',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Nota mínima na recuperação para aprovação (0-10)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Média Mínima para Recuperação'),
        ),
    ]
