# Generated by Django 5.2.3 on 2025-11-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0434_mover_media_recuperacao_para_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursoensino',
            name='media_minima_aprovacao',
        ),
    ]
