# Generated by Django 5.2.3 on 2025-11-23 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0436_alterar_padrao_media_recuperacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocoDisciplinaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bloco', models.PositiveIntegerField(help_text='Número sequencial do bloco (1, 2, 3, ...). Alunos devem ser aprovados em todas as disciplinas de um bloco para avançar ao próximo.', verbose_name='Número do Bloco')),
                ('ordem_disciplina', models.PositiveIntegerField(default=1, help_text='Ordem da disciplina dentro do bloco (para organização visual)', verbose_name='Ordem da Disciplina no Bloco')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos_turmas', to='militares.disciplinaensino', verbose_name='Disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos_disciplinas', to='militares.turmaensino', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Bloco de Disciplina da Turma',
                'verbose_name_plural': 'Blocos de Disciplinas das Turmas',
                'ordering': ['turma', 'numero_bloco', 'ordem_disciplina'],
                'indexes': [models.Index(fields=['turma', 'numero_bloco'], name='militares_b_turma_i_bdc97c_idx')],
                'unique_together': {('turma', 'disciplina')},
            },
        ),
    ]
