# Generated by Django 5.2.3 on 2025-11-23 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0437_adicionar_blocos_disciplinas_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadroTrabalhoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_semana', models.DateField(help_text='Data de referência da semana (geralmente segunda-feira)', verbose_name='Data da Semana')),
                ('dia_semana', models.CharField(choices=[('SEGUNDA', 'Segunda-feira'), ('TERCA', 'Terça-feira'), ('QUARTA', 'Quarta-feira'), ('QUINTA', 'Quinta-feira'), ('SEXTA', 'Sexta-feira'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=10, verbose_name='Dia da Semana')),
                ('data', models.DateField(help_text='Data específica da aula', verbose_name='Data Específica')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Término')),
                ('horas_aula', models.DecimalField(decimal_places=2, help_text='Quantidade de horas/aula (calculado automaticamente ou informado manualmente)', max_digits=5, verbose_name='Horas/Aula')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadros_trabalho_semanal', to='militares.disciplinaensino', verbose_name='Disciplina')),
                ('instrutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quadros_trabalho_semanal', to='militares.militar', verbose_name='Instrutor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadros_trabalho_semanal', to='militares.turmaensino', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Quadro de Trabalho Semanal',
                'verbose_name_plural': 'Quadros de Trabalho Semanal',
                'ordering': ['data_semana', 'dia_semana', 'hora_inicio'],
                'indexes': [models.Index(fields=['turma', 'data_semana'], name='militares_q_turma_i_b944c7_idx'), models.Index(fields=['data'], name='militares_q_data_717e57_idx')],
            },
        ),
    ]
