# Generated by Django 5.2.3 on 2025-11-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0441_adicionar_instrutor_militar_externo_aula_quadro'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino',
            field=models.BooleanField(default=False, verbose_name='Ensino'),
        ),
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_dashboard',
            field=models.BooleanField(default=False, verbose_name='Dashboard de Ensino'),
        ),
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_cursos',
            field=models.BooleanField(default=False, verbose_name='Cursos'),
        ),
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_turmas',
            field=models.BooleanField(default=False, verbose_name='Turmas'),
        ),
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_disciplinas',
            field=models.BooleanField(default=False, verbose_name='Disciplinas'),
        ),
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_alunos',
            field=models.BooleanField(default=False, verbose_name='Alunos'),
        ),
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_instrutores',
            field=models.BooleanField(default=False, verbose_name='Instrutores'),
        ),
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_monitores',
            field=models.BooleanField(default=False, verbose_name='Monitores'),
        ),
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_aulas',
            field=models.BooleanField(default=False, verbose_name='Aulas'),
        ),
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_frequencias',
            field=models.BooleanField(default=False, verbose_name='Frequências'),
        ),
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_avaliacoes',
            field=models.BooleanField(default=False, verbose_name='Avaliações'),
        ),
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_certificados',
            field=models.BooleanField(default=False, verbose_name='Certificados'),
        ),
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_quadros_trabalho_semanal',
            field=models.BooleanField(default=False, verbose_name='Quadros de Trabalho Semanal'),
        ),
    ]
