# Generated by Django 5.2.3 on 2025-11-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0442_adicionar_campos_ensino_funcao_menu_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_dashboard',
            field=models.BooleanField(default=False, verbose_name='Dashboard de Ensino'),
        ),
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_frequencias',
            field=models.BooleanField(default=False, verbose_name='Frequências'),
        ),
        migrations.AddField(
            model_name='funcaomenuconfig',
            name='show_ensino_quadros_trabalho_semanal',
            field=models.BooleanField(default=False, verbose_name='Quadros de Trabalho Semanal'),
        ),
    ]
