# Generated by Django 5.2.3 on 2025-11-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0445_adicionar_modelos_ite_ensino'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunoensino',
            name='capacidade_fisica_geral',
            field=models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('NAO_AVALIADO', 'Não Avaliado')], default='NAO_AVALIADO', help_text='Avaliação geral da capacidade física do aluno', max_length=20, verbose_name='Capacidade Física Geral'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='data_ultima_avaliacao_fisica',
            field=models.DateField(blank=True, help_text='Data da última avaliação física realizada', null=True, verbose_name='Data da Última Avaliação Física'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='observacoes_capacitacao_fisica',
            field=models.TextField(blank=True, help_text='Observações gerais sobre a capacitação física do aluno', null=True, verbose_name='Observações sobre Capacitação Física'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='pcf_aprovado',
            field=models.BooleanField(default=False, help_text='Indica se o aluno foi aprovado na Prova de Capacitação Física', verbose_name='Aprovado na PCF'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='pcf_data_realizacao',
            field=models.DateField(blank=True, help_text='Data em que o aluno realizou a Prova de Capacitação Física', null=True, verbose_name='Data de Realização da PCF'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='pcf_nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota final obtida na Prova de Capacitação Física (0 a 100)', max_digits=5, null=True, verbose_name='Nota Final da PCF'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='pcf_observacoes',
            field=models.TextField(blank=True, help_text='Observações sobre o desempenho na PCF', null=True, verbose_name='Observações da PCF'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='taf_aprovado',
            field=models.BooleanField(default=False, help_text='Indica se o aluno foi aprovado no Teste de Aptidão Física', verbose_name='Aprovado no TAF'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='taf_data_realizacao',
            field=models.DateField(blank=True, help_text='Data em que o aluno realizou o Teste de Aptidão Física', null=True, verbose_name='Data de Realização do TAF'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='taf_nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota final obtida no Teste de Aptidão Física (0 a 100)', max_digits=5, null=True, verbose_name='Nota Final do TAF'),
        ),
        migrations.AddField(
            model_name='alunoensino',
            name='taf_observacoes',
            field=models.TextField(blank=True, help_text='Observações sobre o desempenho no TAF', null=True, verbose_name='Observações do TAF'),
        ),
    ]
