# Generated by Django 5.2.3 on 2025-11-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0446_alunoensino_capacidade_fisica_geral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacaofinalcurso',
            name='total_disciplinas_reprovadas',
            field=models.PositiveIntegerField(default=0, help_text='Número de disciplinas em que o aluno foi reprovado', verbose_name='Total de Disciplinas Reprovadas'),
        ),
    ]
