# Generated by Django 5.2.3 on 2025-11-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0447_classificacaofinalcurso_total_disciplinas_reprovadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoensino',
            name='tipo',
            field=models.CharField(choices=[('PROVA_ESCRITA', 'Prova Escrita'), ('PROVA_ORAL', 'Prova Oral'), ('PROVA_GRAFICA', 'Prova Gráfica'), ('PROVA_PRATICA', 'Prova Prática'), ('TRABALHO_TECNICO_PROFISSIONAL', 'Trabalho Técnico-Profissional'), ('RECUPERACAO', 'Recuperação')], max_length=30, verbose_name='Tipo de Avaliação'),
        ),
    ]
