# Generated by Django 5.2.3 on 2025-11-24 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0448_alter_avaliacaoensino_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoensino',
            name='percentual_questoes_dificeis',
            field=models.DecimalField(blank=True, decimal_places=2, default=20.0, help_text='20% de questões difíceis (ITE 15.15.6.3)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Questões Difíceis'),
        ),
        migrations.AlterField(
            model_name='avaliacaoensino',
            name='percentual_questoes_faceis',
            field=models.DecimalField(blank=True, decimal_places=2, default=20.0, help_text='20% de questões fáceis (ITE 15.15.6.1)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Questões Fáceis'),
        ),
        migrations.AlterField(
            model_name='avaliacaoensino',
            name='percentual_questoes_medias',
            field=models.DecimalField(blank=True, decimal_places=2, default=60.0, help_text='60% de questões médias (ITE 15.15.6.2)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Questões Médias'),
        ),
    ]
