# Generated by Django 5.2.3 on 2025-11-25 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0449_tornar_percentuais_questoes_opcionais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaQTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assinatura', models.DateTimeField(auto_now_add=True, verbose_name='Data da Assinatura')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações da Assinatura')),
                ('tipo_assinatura', models.CharField(choices=[('REVISAO', 'Revisão'), ('APROVACAO', 'Aprovação')], default='APROVACAO', max_length=15, verbose_name='Tipo de Assinatura')),
                ('funcao_assinatura', models.CharField(blank=True, help_text='Função/cargo do usuário no momento da assinatura', max_length=100, null=True, verbose_name='Função no momento da assinatura')),
                ('tipo_midia', models.CharField(choices=[('FISICA', 'Física'), ('ELETRONICA', 'Eletrônica')], default='FISICA', max_length=10, verbose_name='Tipo de Mídia')),
                ('hash_documento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hash do Documento')),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Timestamp da Assinatura')),
                ('assinatura_digital', models.TextField(blank=True, null=True, verbose_name='Assinatura Digital')),
                ('certificado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Certificado Digital')),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da Assinatura')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('assinado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Assinado por')),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='militares.quadrotrabalhosemanal', verbose_name='Quadro de Trabalho Semanal')),
            ],
            options={
                'verbose_name': 'Assinatura do Quadro de Trabalho Semanal',
                'verbose_name_plural': 'Assinaturas dos Quadros de Trabalho Semanal',
                'ordering': ['-data_assinatura'],
                'unique_together': {('quadro', 'assinado_por', 'tipo_assinatura')},
            },
        ),
    ]
