# Generated by Django 5.2.3 on 2025-11-25 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0450_assinaturaqts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quadrotrabalhosemanal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quadrotrabalhosemanal',
            name='numero_aditamento',
            field=models.CharField(blank=True, help_text='Número do aditamento (A01, A02, A03, etc.)', max_length=10, null=True, verbose_name='Número do Aditamento'),
        ),
        migrations.AddField(
            model_name='quadrotrabalhosemanal',
            name='quadro_original',
            field=models.ForeignKey(blank=True, help_text='QTS original do qual este é um aditamento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aditamentos', to='militares.quadrotrabalhosemanal', verbose_name='Quadro Original'),
        ),
    ]
