# Generated by Django 5.0.2 on 2025-11-26 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0451_adicionar_campos_aditamento_qts"),
    ]

    operations = [
        migrations.CreateModel(
            name="EdicaoCurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_edicao",
                    models.IntegerField(
                        help_text="Ex: 1, 2, 3...", verbose_name="Número da Edição"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: 1ª Edição 2025",
                        max_length=200,
                        verbose_name="Nome da Edição",
                    ),
                ),
                ("ano", models.IntegerField(verbose_name="Ano da Edição")),
                (
                    "data_inicio",
                    models.DateField(verbose_name="Data de Início da Edição"),
                ),
                (
                    "data_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Término da Edição"
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(default=True, verbose_name="Edição Ativa"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edicoes",
                        to="militares.cursoensino",
                        verbose_name="Curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Edição de Curso",
                "verbose_name_plural": "Edições de Curso",
                "ordering": ["curso", "-ano", "-numero_edicao"],
                "unique_together": {("curso", "numero_edicao", "ano")},
            },
        ),
        migrations.AddField(
            model_name="turmaensino",
            name="edicao",
            field=models.ForeignKey(
                blank=True,
                help_text="Edição do curso (para cursos permanentes)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turmas",
                to="militares.edicaocurso",
                verbose_name="Edição",
            ),
        ),
    ]
