# Generated by Django 5.2.3 on 2025-11-26 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0455_legislacaogeral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoRevisaoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('EM_ANALISE_COORDENADOR', 'Em análise pelo Coordenador'), ('ENCAMINHADA_INSTRUTOR', 'Encaminhada ao Instrutor'), ('DECISAO_INSTRUTOR', 'Decisão do Instrutor'), ('EM_RECURSO_COMISSAO', 'Recurso à Comissão'), ('DECISAO_FINAL', 'Decisão Final'), ('INDEFERIDA', 'Indeferida')], default='SOLICITADA', max_length=30, verbose_name='Status')),
                ('fundamentacao', models.TextField(blank=True, verbose_name='Fundamentação')),
                ('nova_nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nova Nota')),
                ('justificativa_instrutor', models.TextField(blank=True, null=True, verbose_name='Justificativa do Instrutor')),
                ('parecer_comissao', models.TextField(blank=True, null=True, verbose_name='Parecer da Comissão')),
                ('decisao_final', models.TextField(blank=True, null=True, verbose_name='Decisão Final')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data da Atualização')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='militares.alunoensino', verbose_name='Aluno')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes_coordenador', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador')),
                ('instrutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes_instrutor', to=settings.AUTH_USER_MODEL, verbose_name='Instrutor')),
                ('nota_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='militares.notaavaliacao', verbose_name='Nota Avaliação')),
            ],
            options={
                'verbose_name': 'Pedido de Revisão de Prova',
                'verbose_name_plural': 'Pedidos de Revisão de Prova',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='PedidoRevisaoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Mensagem')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='revisoes_arquivos/%Y/%m/', verbose_name='Arquivo')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisao_mensagens', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
                ('revisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='militares.pedidorevisaoprova', verbose_name='Revisão')),
            ],
            options={
                'verbose_name': 'Mensagem de Revisão',
                'verbose_name_plural': 'Mensagens de Revisão',
                'ordering': ['data_envio'],
            },
        ),
    ]
