# Generated by Django 5.2.3 on 2025-11-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0456_pedidorevisaoprova_pedidorevisaomensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidorevisaoprova',
            name='comissao_nomeada',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comissão Nomeada'),
        ),
    ]
