# Generated by Django 5.2.3 on 2025-11-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0457_pedidorevisaoprova_comissao_nomeada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidorevisaoprova',
            name='numero',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Número do Pedido'),
        ),
    ]
