# Generated by Django 5.2.3 on 2025-11-26 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0458_pedidorevisaoprova_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidorevisaoprova',
            name='pedido_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='militares.pedidorevisaoprova'),
        ),
    ]
