# Generated by Django 5.2.3 on 2025-11-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0460_webpushsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidorevisaomensagem',
            name='remetente',
        ),
        migrations.RemoveField(
            model_name='pedidorevisaomensagem',
            name='revisao',
        ),
        migrations.RemoveField(
            model_name='pedidorevisaoprova',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='pedidorevisaoprova',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='pedidorevisaoprova',
            name='instrutor',
        ),
        migrations.RemoveField(
            model_name='pedidorevisaoprova',
            name='nota_avaliacao',
        ),
        migrations.RemoveField(
            model_name='pedidorevisaoprova',
            name='pedido_original',
        ),
        migrations.RemoveField(
            model_name='webpushsubscription',
            name='user',
        ),
        migrations.AlterField(
            model_name='alunoensino',
            name='cpf_civil',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='alunoensino',
            name='cpf_outra_forca',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='instrutorensino',
            name='cpf_civil',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='instrutorensino',
            name='cpf_outra_forca',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='monitorensino',
            name='cpf_civil',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='monitorensino',
            name='cpf_outra_forca',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.DeleteModel(
            name='LegislacaoGeral',
        ),
        migrations.DeleteModel(
            name='PedidoRevisaoMensagem',
        ),
        migrations.DeleteModel(
            name='PedidoRevisaoProva',
        ),
        migrations.DeleteModel(
            name='WebPushSubscription',
        ),
    ]
