# Generated by Django 5.2.3 on 2025-11-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0461_remove_pedidorevisaomensagem_remetente_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alunoensino',
            index=models.Index(fields=['situacao', 'matricula'], name='militares_a_situaca_f5a748_idx'),
        ),
        migrations.AddIndex(
            model_name='alunoensino',
            index=models.Index(fields=['situacao', 'cpf_outra_forca'], name='militares_a_situaca_ef92ec_idx'),
        ),
        migrations.AddIndex(
            model_name='alunoensino',
            index=models.Index(fields=['situacao', 'cpf_civil'], name='militares_a_situaca_bb3496_idx'),
        ),
        migrations.AddIndex(
            model_name='instrutorensino',
            index=models.Index(fields=['ativo', 'cpf_outra_forca'], name='militares_i_ativo_b0b189_idx'),
        ),
        migrations.AddIndex(
            model_name='instrutorensino',
            index=models.Index(fields=['ativo', 'cpf_civil'], name='militares_i_ativo_a92cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='instrutorensino',
            index=models.Index(fields=['ativo', 'militar'], name='militares_i_ativo_69645d_idx'),
        ),
        migrations.AddIndex(
            model_name='monitorensino',
            index=models.Index(fields=['ativo', 'cpf_outra_forca'], name='militares_m_ativo_d00f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='monitorensino',
            index=models.Index(fields=['ativo', 'cpf_civil'], name='militares_m_ativo_9f5d78_idx'),
        ),
        migrations.AddIndex(
            model_name='monitorensino',
            index=models.Index(fields=['ativo', 'militar'], name='militares_m_ativo_c9515a_idx'),
        ),
    ]
