# Generated by Django 5.2.3 on 2025-11-30 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0462_alunoensino_militares_a_situaca_f5a748_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoRevisaoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('EM_ANALISE', 'Em análise'), ('DEFERIDA', 'Deferida'), ('INDEFERIDA', 'Indeferida')], default='SOLICITADA', max_length=20, verbose_name='Status')),
                ('fundamentacao', models.TextField(blank=True, verbose_name='Fundamentação')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data da Atualização')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_revisao', to='militares.alunoensino', verbose_name='Aluno')),
                ('nota_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_revisao', to='militares.notaavaliacao', verbose_name='Nota Avaliação')),
            ],
            options={
                'verbose_name': 'Pedido de Revisão de Prova',
                'verbose_name_plural': 'Pedidos de Revisão de Prova',
                'ordering': ['-data_solicitacao'],
                'unique_together': {('nota_avaliacao', 'aluno')},
            },
        ),
    ]
