# Generated by Django 5.2.3 on 2025-11-30 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0463_pedidorevisaoprova'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidorevisaoprova',
            name='etapa',
            field=models.CharField(choices=[('ALUNO_SOLICITOU', 'Aluno solicitou'), ('DESPACHADA_INSTRUTOR', 'Despachada ao instrutor'), ('PARECER_INSTRUTOR', 'Parecer do instrutor'), ('RECURSO_DIRETORIA', 'Recurso à diretoria'), ('PARECER_FINAL', 'Parecer final')], default='ALUNO_SOLICITOU', max_length=30, verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='pedidorevisaoprova',
            name='instrutor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_revisao', to='militares.instrutorensino', verbose_name='Instrutor Responsável'),
        ),
        migrations.AddField(
            model_name='pedidorevisaoprova',
            name='parecer_final_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Parecer Final - Texto'),
        ),
        migrations.AddField(
            model_name='pedidorevisaoprova',
            name='parecer_instrutor',
            field=models.CharField(blank=True, choices=[('FAVORAVEL', 'Favorável'), ('DESFAVORAVEL', 'Desfavorável')], max_length=20, null=True, verbose_name='Parecer do Instrutor'),
        ),
        migrations.AddField(
            model_name='pedidorevisaoprova',
            name='parecer_instrutor_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Parecer do Instrutor - Texto'),
        ),
    ]
