# Generated by Django 5.2.3 on 2025-11-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0464_pedidorevisaoprova_etapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacaofinalcurso',
            name='comissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_revisao_ensino', to='militares.comissaopromocao', verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='pedidorevisaoprova',
            name='etapa',
            field=models.CharField(choices=[('ALUNO_SOLICITOU', 'Aluno solicitou'), ('DESPACHADA_INSTRUTOR', 'Despachada ao instrutor'), ('PARECER_INSTRUTOR', 'Parecer do instrutor'), ('RECURSO_DIRETORIA', 'Recurso à diretoria'), ('COMISSAO_NOMEADA', 'Comissão nomeada'), ('PARECER_FINAL', 'Parecer final')], default='ALUNO_SOLICITOU', max_length=30, verbose_name='Etapa'),
        ),
    ]
