# Generated by Django 5.2.3 on 2025-11-30 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0465_classificacaofinalcurso_comissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidorevisaoprova',
            name='comissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_revisao_comissao', to='militares.comissaopromocao', verbose_name='Comissão'),
        ),
    ]
