# Generated by Django 5.2.3 on 2025-11-30 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0466_pedidorevisaoprova_comissao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidorevisaoprova',
            name='despacho_envio_instrutor_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do despacho ao instrutor'),
        ),
        migrations.AddField(
            model_name='pedidorevisaoprova',
            name='despacho_envio_instrutor_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_revisao_despacho_instrutor', to=settings.AUTH_USER_MODEL, verbose_name='Despachado por'),
        ),
        migrations.AddField(
            model_name='pedidorevisaoprova',
            name='despacho_envio_instrutor_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Despacho de envio ao instrutor'),
        ),
    ]
