# Generated by Django 5.0.2 on 2025-12-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0467_pedidorevisaoprova_despacho_envio_instrutor_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidorevisaoprova",
            name="data_conhecimento_oficial",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Data de Conhecimento Oficial da Nota",
            ),
        ),
        migrations.AddField(
            model_name="pedidorevisaoprova",
            name="itens_solicitados",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Itens Solicitados (limitados à revisão)",
            ),
        ),
        migrations.AddField(
            model_name="pedidorevisaoprova",
            name="nova_nota_final",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Nova Nota (Final)",
            ),
        ),
        migrations.AddField(
            model_name="pedidorevisaoprova",
            name="nova_nota_instrutor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Nova Nota (Instrutor)",
            ),
        ),
        migrations.AddField(
            model_name="pedidorevisaoprova",
            name="prazo_limite_comissao",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Prazo Limite da Comissão (8 dias úteis)",
            ),
        ),
        migrations.AddField(
            model_name="pedidorevisaoprova",
            name="prazo_limite_instrutor",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Prazo Limite do Instrutor (3 dias úteis)",
            ),
        ),
        migrations.AddField(
            model_name="pedidorevisaoprova",
            name="prazo_limite_solicitacao",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Prazo Limite para Solicitação (2 dias úteis)",
            ),
        ),
    ]
